### ISSUE TITLE
Use another image tag than og:image

### ISSUE THREAD

**Issue by gcomte** [getAlby/lightning-browser-extension#1011]
Imo the meta-tag `property="og:image"` isn't really fitting to display the 'avatar' in the get alby browser-extension.

The reason for this is, that the og:image is often used as some kind of background image or something, a rather big image that isn't necessarily recognizable when used as an avatar picture.

I'd propose one of the following options:
- Use another tag for the avatar
- Use your own tag
- Use a high resolution version of the favicon

What to do with the `og:image`:
- Use as a fallback for the avatar
- In case another avatar picture is provided, use it as a background (replacing the part where you now put an individual color)

**Comment by bumi** [comment]
Alby now picks up an `alby:image` meta tag, so websites can define this specifically. 

https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/content-script/originData.ts#L500-L528
