### ISSUE TITLE
Allowances: Edit budget should use DualCurrencyField instead of TextField with `type=number`

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1016]
### Is your feature request related to a problem?

#1000 will add [a new Input-type](https://github.com/getAlby/lightning-browser-extension/pull/1000/files#diff-e341c06a28185f14a891bdb91afc6aa3ecaffb6f2f78dea6afb5e4b7d891d2c7) for sats which also displays the fiat value while typing.  

When editing an allowance (budget) this isn't being used yet:  

![image](https://user-images.githubusercontent.com/1016218/172776936-d7e74739-3b1d-4afb-ab23-8994c299d873.png)
 
### Describe the solution you'd like

The new field should be used there as well.  
An example how to use it can be found on the "Receive" view  :
![image](https://user-images.githubusercontent.com/1016218/172777343-8ae9e630-b1a0-47ec-82f6-9598d7d469d5.png)

### Additional context

Maybe have a look through the code if other fields need to be updated as well.  
If yes you could create issues for these and create PRs if you want to.

### Are you working on this?

No

**Comment by secondl1ght** [comment]
This is completed with #1089
