### ISSUE TITLE
Format displayed SATS amounts with seperators

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1022]
### Is your feature request related to a problem?

Long numbers are hard to read, i.e.: `123456789`  

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/1016218/172995800-e1b78de7-a624-4365-b1a0-702b4d86eaf8.png)

Would be nice to format in a localized way, i.e. `123,456,789`
Possible solution: [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat#basic_usage)

### Describe alternatives you've considered

none

### Additional context

Related to: #1000 

### Are you working on this?

No

**Comment by secondl1ght** [comment]
Is this still blocked?

**Comment by escapedcat** [comment]
No, tried to indicate it by removing the "later" label. Made this more clear now.
