### ISSUE TITLE
Rename AuthProvider to AccountProvider to reflect actual usage

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1040]
### Is your feature request related to a problem? Please describe

We currently use a `AuthProvider` for most main-views, defined here:  
https://github.com/getAlby/lightning-browser-extension/blob/feat/597_currency-support/src/app/context/AuthContext.tsx

### Describe the solution you'd like

We should rename this to `AccountProvider`/`AccountContext` because it's mainly handling the current used account.

### Describe alternatives you've considered

none

### Additional context

Blocked by #1000 

### Are you working on this?

No

**Comment by iamziike** [comment]
@escapedcat can I take this up?

**Comment by escapedcat** [comment]
@iamziike currently it's blocked (that's why the `later` tag is added) by #1000 but once it's merged, we're happy if you wanna do this.

**Comment by escapedcat** [comment]
@iamziike it's merged, give it a go if you like

**Comment by iamziike** [comment]
@escapedcat yeah sure
