### ISSUE TITLE
Add new Bitcoin Beach Wallet logo to connector 

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1043]
### Describe the bug

Bitcoin Beach changed the logo. 

### Screenshots (If Any)

![image](https://user-images.githubusercontent.com/13707997/173625304-eeaa6fb0-d6f0-4d64-8da9-12391cceea1a.png)

### Expected behavior
The connector shows the new logo, which is available here: https://drive.google.com/drive/folders/1PL8WdTh80YmocCD1H60UHRu88YGdVqMU

### Are you working on this issue?

No

**Comment by secondl1ght** [comment]
> Can I work upon this?

There is already a PR in for this, but thanks for the offer!

**Comment by secondl1ght** [comment]
Completed
