### ISSUE TITLE
Alby does not pickup LN address from Github when entered in location

### ISSUE THREAD

**Issue by prusnak** [getAlby/lightning-browser-extension#1056]
Alby does pickup LN address from Twitter when it is entered in location - see https://twitter.com/pavolrusnak as an example

The same is not true for Github where Alby only checks the bio field - see https://github.com/prusnak as an example

It would be nice if Alby would scan also other fields not just the bio

The Twitter location scan was added in https://github.com/getAlby/lightning-browser-extension/pull/816

As can be seen here, on Github Alby only scans the bio text (and the main article):

https://github.com/getAlby/lightning-browser-extension/blob/0d71999d03e02d7ab920b7b4e8474a6662f7d636/src/extension/content-script/batteries/GitHub.ts#L34-L36

**Comment by escapedcat** [comment]
I think some of this is being covered by #1028
