### ISSUE TITLE
Namespace and type extension "utils" calls

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1065]
### Is your feature request related to a problem? 

We currently use normal string to call actions within the extension i.e.:
```ts
    await utils.call("editAccount", {
      name,
      id,
    });
```

- https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Accounts/index.tsx#L43
- https://github.com/getAlby/lightning-browser-extension/blob/master/src/common/lib/utils.ts#L13
- https://github.com/getAlby/lightning-browser-extension/blob/master/src/types.ts#L102
- 
### Describe the solution you'd like

- Instead of just use strings try to use types
- Instead of just writing `editAccount` namespace these types, i.e. `account/add`

### Describe alternatives you've considered

none

### Additional context

We should do this for all bigger action-groups
- [ ] account
- [ ] allowance
- [ ] [blocklist](https://github.com/getAlby/lightning-browser-extension/pull/825)
- [ ] think about ho to namespace non-groped actions if needed

### Are you working on this?

No

**Comment by bumi** [comment]
I think for this we now have that `api` wrapper?

**Comment by escapedcat** [comment]
The api wrapper already existed when this issue was created.  
This is one of the "let's improve typing" tickets. It's a reminder.

**Comment by bumi** [comment]
utils.call is a function that accepts pretty much anything. the api can be typed specifically. e.g. api.getSettings() that function knows what is returned. utils.call('getSettings') on the other hand not really. 

that's how I understand it.

**Comment by reneaaron** [comment]
Closing as not actionable.
