### ISSUE TITLE
Design a "Blocked List" management flow in the pop-up and the extension web.

### ISSUE THREAD

**Issue by dvoroneca** [getAlby/lightning-browser-extension#1067]
Some websites request confirmation upon every interaction and sometimes even without any actions. 
Other times the user may want to use an extension other than Alby, and therefore has to be able to block Alby for a given website in order to use another service.

We have to allow the user to block the service and unblock it when needed.
The user has to be able to review the list. He has to enter blocked application settings via the "manage your blocked applications" link from the Extension pop-up and from the List of applications that his wallet is connected. 

---------------

**Comment by reneaaron** [comment]
Closing as not relevant currently, users can remove blocks by visiting the website and opening the extension popup.
