### ISSUE TITLE
Be more consistent with primary color usage

### ISSUE THREAD

**Issue by Bosch-0** [getAlby/lightning-browser-extension#1069]
## Tasks

- [ ] Change colors from Bitcoin Orange to Alby Yellow
- [ ] Keep buttons consistent and change the border-radius accordingly.

---
## Originally Posted

Alby's mascot and website uses a primary yellow colour of `#FFDF6F` (.bg-albyYellow-300 in CSS) but throughout the browser extension the primary colour used is `#EE871B` (.bg-orange-bitcoin in CSS).

For visual consistency I would stick with the yellow `#FFDF6F` (.bg-albyYellow-300) throughout. 

Example below. The site uses the yellow but the extension uses the orange

![image](https://user-images.githubusercontent.com/55287964/174946899-f21eeb47-664f-4f96-af8d-8718c1b390fa.png)

**Comment by dvoroneca** [comment]
Thank you @Bosch-0 for your attention to detail and to use of Alby brand assets. 

You are absolutely correct, we do use Alby Yellow on the website and Bitcoin Orange on the extension pop-up. At the moment we are using the components in this configuration. It is likely that in the future our UI will change.

**Comment by stackingsaunter** [comment]
Closing as solved with new gradient primary color
