### ISSUE TITLE
add tests for allowance action

### ISSUE THREAD

**Issue by im-adithya** [getAlby/lightning-browser-extension#1076]
### Is your feature request related to a problem? Please describe

The allowance actions lack tests currently, it would be nice to add them, especially as we are working to migrate them to TS so as to ensure we don't break any functionality.

### Additional context

- [ ]  add.js
- [ ]  delete.js
- [ ]  enable.js
- [ ]  get.js
- [ ]  getById.js
- [ ]  list.ts
- [ ]  update.js

### Are you working on this?

Yes

**Comment by escapedcat** [comment]
Hm, I feel like with every switch to TS we should add a test. For accounts that was the only way we could actually "tests" the types

**Comment by im-adithya** [comment]
I was thinking to add them before but yeah that makes more sense as we have to use the same action type made in each PR.
Closing this!
