### ISSUE TITLE
List of test users for Alby Chrome extension

### ISSUE THREAD

**Issue by dvoroneca** [getAlby/lightning-browser-extension#1115]
Make an email campaign for those who signed up for Alby newsletter and User signups to invite them to take part in our User Tests. 

- [ ] Make an email invite
- [ ] Make a Typeform to learn about their profiles 
- [ ] Invite them to different User tests with Alby Products
- [ ] Invite to take part in surveys

--------------

### Email

We need to make an email that will tell our users about the Alby UX Testing program.

_Dear Alby subscribers, as you know we are working hard on building the best way to pay with Bitcoin on the web. We would use your help to test our ideas and our designs. If you have some free time to participate in our tests, please fill out the form and we will invite you to our testing sessions._

_Link to the Typeform_

--------------

### Typeform

We will send an email invitation to our UX testing program. When someone wants to participate, he will be asked to fill out a form where we will find out if he is an Alby user. 

- How often he’s using Alby. 
- How are they using Alby. P2p transaction or to pay services
- If for services, then what services they use Alby to pay
- Is he a web 3 newb/middlevel user/ or a professional web 3 user
- How often do they use other browser extension weekly/monthly/never
- What are they using? Metamask/ phantom/ other
- Background (technical or humanitarian
- Name and email
- Lightning wallet address

--------------

Send out the prototypes and the task, and ask to record their screens. After the testing, ask questions and collect feedback.

--------------

Analise responses and make a report.

--------------

Iterate the designs in accordance with the report results.

**Comment by taiwodada230** [comment]
I already created an email template on figma.

Below is the link to the file:

https://www.figma.com/file/TfENO0hA9XZ2IZf2syBTZ4/Alby.?node-id=0%3A1

**Comment by reneaaron** [comment]
Closing as not relevant anymore, if you want to take part in some user testing sessions feel free to reach out on telegram, nostr or our discord channel (see README.md).
