### ISSUE TITLE
Create a list of test cases

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1116]
### Is your feature request related to a problem? Please describe

We have greatly improved with automated tests in the recent weeks.
To make it easier for people to manually test Alby functionality (and potentially also to automate more of those test workflows) we should document the major test cases. 

The test case should include what a user needs to do and what the expected outcome is. 

I've created a wiki page for this: 
https://github.com/getAlby/lightning-browser-extension/wiki/Extension-Manual-Test-Cases

**Comment by AnastasiaVolk** [comment]
Together with @dvoroneca we created a list of scenarios
If somebody has something to add, please do

SCENARIOS

As a new user I want to know what is Alby?
As a new user I want  to start using Alby (onboarding)
As existing logged-in user I want to continue using Alby
As existing logged-out user I want to continue using Alby
As user I want to add funds to my Alby account As user I want to send funds to service (3 different types of connection)
As user I want to receive payment
As user I want to review my past transactions As user I need help with Alby
As a user I want to change the app theme
As a user I want to enable tipping 
As a user I want to change language (doesn’t work)
As a user I want to send funds to QR code 
As a user of old wallet I want to recoup my funds 
As a user i want to allow Alby to charge me without additional confirmation
As an advanced user I want to connect node
(Alby Portal)
As an advanced user I want to get API Token
As a user I want to change my account passward
As a podcaster I want to give my listner an opportunity to donate as they listen
As a user I want to connect another wallet
As a user I want to update my email
As a user I want to update my password
As a user I want to log out
As a user I want to send additional data (my name and email) with my payment
As a node creater I want to connect node with existing wallet
As contant creator I want to recieve contributions on my own website
As a user a want to give a feedback
As a user I want to switch account
As a user I want to add new account
As a user I want to hide my wallet (lock)

**Comment by GBKS** [comment]
Great list. A possible next step could be to prioritize them (percentage of users that do this) and group them by phase of the [usage life cycle](https://bitcoin.design/guide/designing-products/usage-life-cycle/). That makes it then easier to match it against design and what to work on.

**Comment by AnastasiaVolk** [comment]
Exactly! We have already started to create scripts for the most prioritized ones here: [
](https://github.com/getAlby/lightning-browser-extension/wiki/Extension-Manual-Test-Cases)
Planning to create block schemes on them afterwards
As well we gonna have a list of prioritized bugs to be fixed[  ](https://github.com/orgs/getAlby/projects/11/views/1?visibleFields=%5B%22Title%22%2C9499599%2C9499458%2C%22Assignees%22%2C9499392%2C%22Status%22%5D)

**Comment by AnastasiaVolk** [comment]
https://github.com/orgs/getAlby/projects/11/views/1?visibleFields=%5B%22Title%22%2C9499599%2C9499458%2C%22Assignees%22%2C9499392%2C%22Status%22%5D

**Comment by escapedcat** [comment]
When can this issue be closed? What's the expected further outcome if any?

**Comment by AnastasiaVolk** [comment]
@escapedcat I'm working on the Wiki to create scripts for test cases that we'll test later. But the issue itself may be closed as I can see I'm the only one editing it anyways, so it not really needed

**Comment by escapedcat** [comment]
No, that's cool. Paste the wiki page here when it's done and then we'll close it.

**Comment by AnastasiaVolk** [comment]
https://github.com/getAlby/lightning-browser-extension/wiki/Extension-Manual-Test-Cases
