### ISSUE TITLE
Bug: No password requirements on screen "Your password" in Onboarding

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1121]
### Bug description 

For the password it is possible to use only one character to proceed

### Screenshots 

<img width="1363" alt="• power of lightning in your" src="https://user-images.githubusercontent.com/108762093/177803490-b6f5a21d-f52f-4f1f-b90e-662becd50d55.png">

<img width="1321" alt="Do you have a lightning wallet" src="https://user-images.githubusercontent.com/108762093/177803986-dfdc35a7-35bd-4fd6-b73c-ae77fbfe66cc.png">

### To Reproduce

1. Visit to getalby.com
2. Click on "Install Alby"
3. Click "Add extension to Chrome"
4. Click "Get started"
5. Input a password with 1 character only

### Expected behavior

A requirement of password 6 characters and more 

### Alby information

- Alby Version: [v1.11.2]
- Alby installed through Google Chrome

### Device information [optional]:

- OS: [masOS Monterey 12.0.1 ]
- Browser [chrome, safari]
- Browser Version [Safari Version 15.1, Chrome Version 103.0.5060.114]

### Additional context

Password requirements component already exists in Account Password Input 
Consider adding the same behaviour to Extension Password Input
![Screenshot 2022-07-07 at 19 42 07](https://user-images.githubusercontent.com/108762093/177826746-e90b02d6-6c09-42a5-8b66-245f4a88c6e0.png)

### Are you working on this issue?

No

￼

__

**Comment by escapedcat** [comment]
@bumi what requirements would be good for the password here?

**Comment by bumi** [comment]
was this closed intentionally? 

regarding the password: 

the first password is used to store the account data locally encrypted with that password. (there I'd keep the requirements low because always typing complex, long passwords is annoying and the data is only stored locally)

the second password is for the account on getalby.com

**Comment by AnastasiaVolk** [comment]
yes , I closed this one as I converted the same issue from the table.I thought of moving all the bugs there, so we have all of them at one place.

**Comment by bumi** [comment]
ok.
