### ISSUE TITLE
LNURL-auth with BlueWallet

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1127]
### Describe the bug

Using LNURL-auth currently leads to different identities when you import your Alby account into BlueWallet.

### To Reproduce

1. Go to lightninglogin.live (or any other site with LNURL-auth support)
2. Login with your Alby extension and remember the generated identity
3. Logout
4. Import your Alby account into BlueWallet
5. Try to login again by scanning the QR-Code with BlueWallet
6. The identities do not match 

### Expected behavior

The identities generated from step 2 and step 5 should be the same. 

### Are you working on this issue?

_No._

**Comment by bumi** [comment]
this is known and fixed in https://github.com/getAlby/lightning-browser-extension/pull/968

We had updated the key generation to follow the scheme with bluewallet (because with custodial wallets the key is derived from the login/password).
But we still did use an invalid hash. 

the problem with this is: how to best roll it out. because it would break the login for existing users.

**Comment by reneaaron** [comment]
Ahh, okay. Isn't that somehow the same as with the legacy signing option we already have in Alby? Can we maybe even change the signing key based on this setting, too? 

![image](https://user-images.githubusercontent.com/100827540/178024922-c8a1b61f-5c91-4a83-b2b8-2e49d5ab72f2.png)

The sooner we switch the less people are impacted by this change, right?

**Comment by bumi** [comment]
that legacy singing was when we changed the way we generate keys to be compatible with bluewallet. 
It is related, but not the same. 

Yes, the sooner the better.

**Comment by reneaaron** [comment]
I see. How about adding another setting and putting them in some separate section of the settings page that is a little less prominent than the current one and remove them in some months?

That way we would offer a migration path for existing users but don't overwhelm new users with those settings.

**Comment by reneaaron** [comment]
Closing as out of date.
