### ISSUE TITLE
LNURL-auth with Zeus mobile app

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1128]
### Describe the bug

Scanning a lnurl-auth QR-Code with the Alby account added to a Zeus wallet currently leads to an error: 

`Invalid attempt to descrtucture non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method`, followed by another error:

`LnurlAuth not supported by your node implementation`

### To Reproduce

1. Import your Alby account into Zeus wallet
2. Scan a LNURL-auth QR-Code 

### Are you working on this issue?

_No._

**Comment by bumi** [comment]
I think Zeus does not support LNURL-auth, they would need to implement that. 
Afaik this is nothing that we can do.

**Comment by reneaaron** [comment]
They do support LNURL-auth. Login works using my own node, but not for the Alby account via LNDHub. 🤔

**Comment by bumi** [comment]
they support it for LND but not LNDHub.

**Comment by reneaaron** [comment]
Okay, got it. Would it make sense to raise this issue in the Zeus repo?

**Comment by bumi** [comment]
imo, yes. they would need to implment lnurl-auth for their lndhub connections and derive the key the same way as Alby and bluewallet do it from the user credentials.

**Comment by reneaaron** [comment]
Awesome, I'll open one. Thanks for your feedback.
