### ISSUE TITLE
Add new setting: disable fiat amounts

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1141]
### Is your feature request related to a problem? Please describe

We recently introduced support to show fiat amounts. But maybe I do not want to use fiat amounts and thus it should be possible to disable the fiat amounts

### Describe the solution you'd like

We should have a setting to choose if fiat amounts should be shown and then (if fiat amounts should be shown) the fiat currency can be choosen.

**Comment by bumi** [comment]
#1125

**Comment by lisabaut** [comment]
@dvoroneca 

As discussed see here the current status of the new toggle which shows/hides the settings "currency" and "exchange":


| Setting enabled  | Setting disabled  |
|---|---|
|![Bildschirmfoto 2022-07-25 um 13 27 26](https://user-images.githubusercontent.com/11243967/180769767-3e4df8d2-e8d3-4bea-83e2-4ff9a2a6b6f0.png)| ![Bildschirmfoto 2022-07-25 um 13 41 10](https://user-images.githubusercontent.com/11243967/180769985-247518d8-5e4b-4cf9-8851-2fec601d99a4.png) |

Happy about some design feedback for better text and maybe new Headers etc 🙂

**Comment by lisabaut** [comment]
I created a follow-up ticket fot the design https://github.com/getAlby/lightning-browser-extension/issues/1224
