### ISSUE TITLE
Disable allowance - should be able to disable Alby from a service inside Alby without delete it

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1142]
### Is your feature request related to a problem?

> I see that now we have green Alby icon when connected to a service. I think could be great to be able to disconnect from the service inside Alby.  

As a user I want to be able to "disable" an allowance/budget to stop auto-payment for a webpage if I want to.
Without resetting or deleting the budget.

### Describe the solution you'd like

Can disable/enable budgets via the settings-cog icon

### Describe alternatives you've considered

none

### Additional context

none

### Are you working on this?

No

**Comment by bumi** [comment]
thanks for the feedback. 

Right now we only have "deleting" which would remove it also from the websites list. 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/318/179310495-21f4e593-0059-41f0-ae21-22e0b40f9966.png">

**Comment by bitcoinuser** [comment]
What is confusing to me is: 

I enabled on alby for example (https://pro.kollider.xyz/) , so I see the Alby green icon even without being disconnected (not logged) on Kollider.

I thought that the green alby icon represented that I was logged on a site that support lightning login.

So enabled on Alby means what? that the alby can do actions on the site?

**Comment by bitcoinuser** [comment]
> thanks for the feedback.
> 
> Right now we only have "deleting" which would remove it also from the websites list. <img alt="image" width="362" src="https://user-images.githubusercontent.com/318/179310495-21f4e593-0059-41f0-ae21-22e0b40f9966.png">

Now I understand that connected means. Yes, make sense do disable or disconnect without removing. I opened the issue for one thing but was useful for other thing, haha.

**Comment by bitcoinuser** [comment]
Closing it because I was confused about some things when I opened it. I think now doesn't make sense have this option.
