### ISSUE TITLE
(data-)Migration strategy for future updates

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1146]
### Is your feature request related to a problem?

Currently we have no way to migrate data if a new version comes out.  
In this case we would always need to check within the code what exists and handle it and with this support old code/data-structures.  

### Describe the solution you'd like

We would need a migration strategy for things involving data stored in the users browser. I.e.

- DexieDB
  https://dexie.org/docs/Version/Version.upgrade()
- Settings
- ...

### Describe alternatives you've considered

Nothing. Currently we just have minor workarounds within the codes to i.e. handle `string` and `number`-types while this mostly should be only one of these.

### Additional context

None

### Are you working on this?

No

**Comment by qqqzhch** [comment]
To back up this data, should  back up account-related information or transaction-related information ？

**Comment by reneaaron** [comment]
Closing as migrations are possible by now.
