### ISSUE TITLE
Show an option to connect on site that supports Lightning login

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1148]
Hi,

When I enter on staker.news site I need to do three steps to login using lightning. I think when the user enter on Stacker news site, Alby should detect that the site support lightning login and automatically popup a window like:
We detected that Stacker News support lightning login. Do you want to login with Alby? Yes or NO and do not show this popup again.

**Comment by bitcoinuser** [comment]
Related to: https://github.com/getAlby/lightning-browser-extension/issues/833

**Comment by stackingsaunter** [comment]
This would need to be a call from stacker.news side, am I right? @escapedcat

**Comment by reneaaron** [comment]
We don't know beforehand if a website supports lnurl-auth logins, there is currently also no effort to implement a spec for websites to signal that to extensions.

Closing this issue as there is nothing we could add on our end to support that currently. Users will be prompted as they click the "sign in with lightning" button on different websites.
