### ISSUE TITLE
Should add the website of the project on connectors

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1151]
I think should have the link of the website of the connector, like: https://umbrel.com/ on this page:

![Captura de tela de 2022-07-14 09-35-02](https://user-images.githubusercontent.com/1178856/178984177-339660d3-1b61-45fc-99cb-6156b7de5a3e.png)

**Comment by Cheapshot003** [comment]
I will try to work on this. Seems pretty straightforward. Will be my first commit to open source projects ever

**Comment by bumi** [comment]
@Cheapshot003 yeah nice! let me know if you need help getting started.
I think those screens are in here: https://github.com/getAlby/lightning-browser-extension/tree/master/src/app/screens/connectors

**Comment by Cheapshot003** [comment]
Already found them and had a look at them. My naive approach would be to just add a hyperlink to the title like this:
`title="Connect to your <a href="https://runcitadel.space/">Citadel</a> Node"`

I still need to figure out how to run this thing with my changes. Yarn says "No such file or directory "install" when I try to install the packages

**Comment by bitcoinuser** [comment]
It's added
