### ISSUE TITLE
No password requirements on screen "Your password" in Onboarding

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1155]
**Bug description**

For the password it is possible to use only one character to proceed

**Screenshots**

![Image](https://user-images.githubusercontent.com/108762093/179185462-c51a38d3-c3df-4717-bc7b-266517cbae3d.png)

![Image](https://user-images.githubusercontent.com/108762093/179185599-f0287874-65ee-4ae0-b72f-a8b27aac5c70.png)

**To Reproduce**

Visit to getalby.com
Click on "Install Alby"
Click "Add extension to Chrome"
Click "Get started"
Input a password with 1 character only

**Expected behavior**

A requirement of password 6 characters and more

**Alby information**

Alby Version: [v1.11.2]
Alby installed through Google Chrome
Device information [optional]:

OS: [masOS Monterey 12.0.1 ]
Browser [chrome, safari]
Browser Version [Safari Version 15.1, Chrome Version 103.0.5060.114]

**Additional context**

Password requirements component already exists in Account Password Input
Consider adding the same behaviour to Extension Password Input

![Image](https://user-images.githubusercontent.com/108762093/179185841-9e08ea04-422f-4168-996a-29db90f80155.png)

Are you working on this issue?

No

**Comment by bumi** [comment]
closing this as it is "only" for the local encrypted data and increasing the requirement would have potential usability problems

**Comment by AnastasiaVolk** [comment]
This needed to be explained for the user
Because the most likely he will create a regular password here, which will make it annoying to type it in every time to unlock 
Call it simple like - "unlock password" maybe add "you can use 1 symbol and more"

**Comment by escapedcat** [comment]
@kiwiidb suggested to call this "pin" and @dvoroneca suggested to only show 4 single-char input field. If this is the way to go we can create a task for this and link it here later.
