### ISSUE TITLE
Extra symbols in the notification of taken email

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1162]
**Bug description**

Extra symbols in the notification of taken email

**Screenshots**

![Image](https://user-images.githubusercontent.com/108762093/179029810-17564069-c0b1-4a26-9eb6-39787a9067ea.png)

**To Reproduce**

1. Click on the extension
2. Enter the account menu (down arrow)
3. Click “add a new account”
4. Click on the Alby Wallet button
5. Enter existing email
6. Enter new password
7. Click “Continue”
8. Notification of taken email appears

**Expected behavior**

Clear notice without any extra symbols

**Alby information:**

Alby Version: [v1.12.0]
Alby installed through Google Chrome
Device information:
OS: [macOS Monterey 12.0.1 ]  
Browser Version [Chrome Version 103.0.5060.114]

**Are you working on this issue?**
No

**Comment by bumi** [comment]
solved in #1397
