### ISSUE TITLE
Accepting the wrong email format for "Your Lightning Address" in Onboarding

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1163]
**Bug description**

System gives no error when using wrong email format for "Choose Your Lightning Address" field

**Screenshots**

![Image](https://user-images.githubusercontent.com/108762093/179565346-16f3d290-03c8-410c-836b-f00b3ad35051.png)

![Image](https://user-images.githubusercontent.com/108762093/179565350-f3382569-2edb-43e4-9f34-87887a89cc1c.png)

**To Reproduce**

Visit to getalby.com
Click on "Install Alby"
Click "Add extension to Chrome"
Click "Get started"
Input a password
Confirm a password
Click "Next"
Input new/existing email
Input correct password
Input wrong email format for "Choose Your Lightning Address" field

**Expected behavior**
A notification about wrong email format appears

**Alby information**

Alby Version: [v1.11.2]
Alby installed through Google Chrome
Device information

OS: [masOS Monterey 12.0.1 ]
Browser [chrome, safari]
Browser Version [Safari Version 15.1, Chrome Version 103.0.5060.114]

**Are you working on this issue?**

No

**Comment by AnastasiaVolk** [comment]
Collecting all the bugs in the table[  ](https://github.com/orgs/getAlby/projects/11/views/1), so we have all of them at one place and can prioritize them. These are converted issues from the table.

**Comment by AnastasiaVolk** [comment]
https://github.com/orgs/getAlby/projects/11/views/1

**Comment by bumi** [comment]
add a alphanumeric pattern requirement to the field

**Comment by bumi** [comment]
fixed in: https://github.com/getAlby/lightning-browser-extension/pull/1425
