### ISSUE TITLE
User scenarios for Alby chrome extension

### ISSUE THREAD

**Issue by dvoroneca** [getAlby/lightning-browser-extension#1165]
Work out all user scenarios, and convert those to flow charts with the screens inside Figma.

See a list of user scenarios here: https://github.com/getAlby/lightning-browser-extension/issues/1116#issuecomment-1175426932

**Comment by dvoroneca** [comment]
Starting with these:

1. The first flow to analyse and create flow charts is the Onboarding https://github.com/getAlby/lightning-browser-extension/issues/981

2.  Logging in, recovering password, installing Alby to a new browser [Figma link](https://www.figma.com/file/IJeZhqg2Cn2lpRRZQUi3oq/Password-reset?node-id=0%3A1)

3. Adding funds

4. Send funds

5. Receive payment

6. Support

7. 1-Click Payments

8. Changing settings, passwords, language, currency

9. Making payments (includes adding data to payments, configuring payments for streams)

10. Accounts

11. Connecting Multiple wallets

-------------

12. Setting up Alby for merchants/content creators/...

**Comment by escapedcat** [comment]
@dvoroneca what is the outcome of this issue? Or... when can this be closed? When all 12 points have been tackled?

**Comment by Mysttykinz** [comment]
Have anyone been assigned this task, I'll love to work on it

**Comment by reneaaron** [comment]
I think @stackingsaunter completed that some weeks ago. 🙌
