### ISSUE TITLE
The word "config" in the description of incorrect password entry does not give the user an understanding of possible further actions (ref. to 1137)

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1169]
**Bug description**
The word "config" in the description of the error doesn't give a user understanding on possible future actions

Ref #1137

**Screenshots**

![Image](https://user-images.githubusercontent.com/108762093/179764729-fec5d94d-4dbc-4ada-96b9-34e7211bfafc.png)

**To Reproduce**

1. Press Alby extension button
2. “Unlock to continue” window appears
3. Input incorrect password
4. “Invalid password (config)” noticement appears

**Expected behavior:**

A "Forgot Password" link appears as text and It is clear that it can be clicked on. It opens a modal window with an explanation, followed by a reset button.

**Suggestions:**
in the case the user lost the password:
We warn the user, then delete the user's accounts and link the user again to the onboarding.

**Comment by escapedcat** [comment]
Todos:

- Set new pw
- Create new account
- Also: delete all encrypted accounts
- Make the link visible
