### ISSUE TITLE
Possible to send an invoice with incorrect symbols (, e)

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1170]
**Bug description**

System allows to send an invoice with "," or "e" symbols instead of figures in the field "amount"

**Screenshots**

![Image](https://user-images.githubusercontent.com/108762093/179569563-1b729b70-b054-4ff9-9881-69bef37bd6a9.png)

![Image](https://user-images.githubusercontent.com/108762093/179569591-ed518d00-18f3-4e8d-b6d5-8e4d0cb9f8f3.png)

**Steps to reproduce the behaviour:**

1. Press on the extension icon
2. Press “Receive”
3. Input characters "," or "e" or both
4. Press "Create invoice"
5. "Receive" page appears with QR-code to scan

**Expected behavior**
An error message appears

**Alby information**

Alby Version: [v1.12.0]
Alby installed through Google Chrome

**Device information:**

OS: [macOS Monterey 12.0.1 ] 
Browser [chrome]  Browser Version [Chrome Version 103.0.5060.114]

**Are you working on this issue?**

No

**Comment by bumi** [comment]
related: #1070

**Comment by bumi** [comment]
this should be now fixed

**Comment by AnastasiaVolk** [comment]
fixed
![Screenshot 2022-09-13 at 15 20 52](https://user-images.githubusercontent.com/108762093/189899531-af4cfc6e-dc39-4a78-8e8a-20272b2a2f02.png)
