### ISSUE TITLE
Incorrect password entry for existing email on the "Your Alby Lightning Wallet" web page does not give an error notification

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1182]
**Bug description**

The system does not give an error notification on incorrect password entry on the "Your Alby Lightning Wallet" web page

**Screenshots**

![Image](https://user-images.githubusercontent.com/108762093/180184290-b27a71be-e899-4a6e-b226-518a17955df7.png)

**Steps to reproduce the behaviour:**

1. Visit to getalby.com
2. Click on "Install Alby"
3. Click "Add extension to Chrome"
4. Click "Get started"
5. Choose and confirm password 
6. Choose Alby Wallet 
7. Input existing email
8. Input incorrect password

**Expected behavior**

System does not give a wrong password respond

**Alby information**

Alby Version: [v1.12.0]
Alby installed through Google Chrome

**Device information:**

OS: [macOS Monterey 12.0.1 ] 
Browser [chrome]  Browser Version [Chrome Version 103.0.5060.114]

**Are you working on this issue?**

No

**Comment by bumi** [comment]
related: #1162

**Comment by AnastasiaVolk** [comment]
In version [v1.13.0] we have a notification of taken email (ref. #1162 , but no instructions on password recovery

![Image](https://user-images.githubusercontent.com/108762093/183267581-3d710779-a9d5-4dcf-9415-25a29a39c838.png)

**Comment by bumi** [comment]
solved in #1397
