### ISSUE TITLE
No notification about existing lightening address when trying to use it with new email and password in Onboarding

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1183]
**Bug description:**

Input new correct email and valid password (6 and more) , but existing lightening address doesn't lead to any notification - system gives no respond

**Screenshots:**

![Image](https://user-images.githubusercontent.com/108762093/180211207-97ebac12-7e99-427e-8758-234e9b29dfd6.png)

NOTHING HAPPENS

![Image](https://user-images.githubusercontent.com/108762093/180211271-ba9f39a5-7358-4a42-8003-f7fc1a478750.png)

![Image](https://user-images.githubusercontent.com/108762093/180211296-6715f2a3-d349-4d82-843f-8470f2d6614b.png)

**To Reproduce**

1. Visit to getalby.com
2. Click on "Install Alby"
3. Click "Add extension to Chrome"
4. Click "Get started"
5. Input a password
6. Confirm a password
7. Choose Alby Wallet
8. Input new correct email
9. Input correct password
10. Input existing lightening address 

**Expected behavior**

Notification that this lightening address is taken 

**Alby information**

Alby Version: [v1.12.0]
Alby installed through Google Chrome

**Device information:**

OS: [macOS Monterey 12.0.1 ] 
Browser [chrome]  Browser Version [Chrome Version 103.0.5060.114]

**Are you working on this issue?**

No

**Comment by bumi** [comment]
=> will be tackled with the new onboarding flow. 
#981
