### ISSUE TITLE
No notification of the wrong Alby address for an existing email and the correct password when installing Alby

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1186]
**Bug description:**

When installing Alby system gives no notification of an incorrect Alby address for an existing email and the correct password

**Screenshots:**

![Image](https://user-images.githubusercontent.com/108762093/180417953-8eb639cf-5d82-4169-9d66-37dcc1ddcbca.png)

![Image](https://user-images.githubusercontent.com/108762093/180417979-080984ec-8755-4fcf-a048-d31ba0e2070b.png)

**To Reproduce**

1. Visit to getalby.com
2. Click on "Install Alby"
3. Click "Add extension to Chrome"
4. Click "Get started"
5. Input a password
6. Confirm a password
7. Choose Alby Wallet
8. Input existing email
9. Input correct password
10. Input wrong lightening address

**Expected behavior**

Notification of incorrect lightening address appears

**Alby information**

Alby Version: [v1.12.0]
Alby installed through Google Chrome

**Device information:**

OS: [macOS Monterey 12.0.1 ] 
Browser [chrome]  Browser Version [Chrome Version 103.0.5060.114]

**Are you working on this issue?**

No

**Comment by escapedcat** [comment]
Not actually sure what happens if the Alby account and LN address already exists and you input a different LN address there. I believe this will be solved by the new design where new and existing Alby account flow is separated.

**Comment by bumi** [comment]
will be address with the work on the onboarding flow: #981

**Comment by bumi** [comment]
fixed

**Comment by escapedcat** [comment]
Can be closed?
