### ISSUE TITLE
Changing the language does not work

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1192]
**Bug description**

In the settings there is an option to change language, but it doesn't work

**Screenshots**

![Image](https://user-images.githubusercontent.com/108762093/180831201-bc43a9fa-d94c-4bb7-ac82-7a97e309ce1f.png)

**Steps to reproduce the behaviour:**

1. Click on Alby Extension Icon
2. Pop up window appears
3. Click on the "menu" button in the right
4. The menu appears
5. Click on "settings"
6. "Settings" page appears
7. In the line "Language" try to change it

**Expected behavior**

The language changes to the chosen one

**Suggestion**

Either remove the option for changing or make it work

**Alby information**

Alby Version: [v1.12.0]
Alby installed through Google Chrome

**Device information:**

OS: [macOS Monterey 12.0.1 ] 
Browser [chrome]  Browser Version [Chrome Version 103.0.5060.114]

**Are you working on this issue?**

No

**Comment by escapedcat** [comment]
Not all languages have been translated completely yet. This will happen over time [via Weblate](https://hosted.weblate.org/projects/getalby-lightning-browser-extension/getalby-lightning-browser-extension/). I think this can be closed.

**Comment by AnastasiaVolk** [comment]
Maybe it makes sense to remove this option before it's done? It gives the impression of a very raw product

**Comment by escapedcat** [comment]
True, I understand that. Doubt translations will be 100% finished soon. We kinda wanted this in so people are aware of it.

Maybe we could improve the info here:
![image](https://user-images.githubusercontent.com/1016218/180947866-4cf02e47-7ded-428a-9df8-a5b1603f7c51.png)
1. Change to "Translations are not 100% finished yet. Help us translate Alby into your language!
2. "translate Alby into your language" link this to the Weblate service we use for translations

**Comment by AnastasiaVolk** [comment]
Yes, then it turns out to be even useful! I love it!

P.S. I think translations are very important, actually. For example, most Russians don't speak English at all. Neither do Spaniards. It might even stop them from using the product.

**Comment by secondl1ght** [comment]
I agree that the current setup is not correct, we should only show a language in the selector when the entire app has been translated. It doesn't make sense to show it otherwise, so we could only show English for now and then when we have full translations add the other languages.

**Comment by escapedcat** [comment]
For the entire app to be translatable we need to switch all strings to i18n placeholders first. You up for it?

**Comment by secondl1ght** [comment]
PR #1244 is in for this issue, will now look into updating remaining strings into i18n placeholders.
