### ISSUE TITLE
1-click budget (allowance) flow

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1197]
### Is your feature request related to a problem?

Current budget flow:
1. On first payment you can "Remember and set a budget"  
       <img src="https://user-images.githubusercontent.com/1016218/181215845-4076b06a-1c52-4fc4-bedf-04c97e7f6319.png" width="200" />
1. Set budget and confirm the first payment  
        <img src="https://user-images.githubusercontent.com/1016218/181216013-d18f9b31-0f7a-4ee3-9d1d-66b79cfab085.png" width="200" />
 

### Describe the solution you'd like
- See: https://github.com/getAlby/lightning-browser-extension/issues/1090#issuecomment-1186821835
- Figma Designs (make sure to select "for Dev" in the left navigation):
  https://www.figma.com/file/HXIxAFG9OUCcr2EJMJ6JMm/1-Click-Pay?node-id=321%3A5678

#### Design Screenshots
- Design during "First payment"  
    ![image](https://user-images.githubusercontent.com/1016218/181217581-4df09f62-f590-4149-9de7-2c1bd2e21ecc.png)
- Design when "Setting a budget via 1-click pay"  
    ![image](https://user-images.githubusercontent.com/1016218/181219445-acd076f3-e8ac-4b8a-a8c8-a362d11c3d5a.png)
- Out of scope, screen with:
    - Sats/Fiat inputfield
    - Max payment
    - Cooldown
    - Notifications

#### **Important**
- Split new design and functionality when developing
- Different people might work on these things aync

### Are you working on this?

No

**Comment by escapedcat** [comment]
Removed from milestone because:
- UX is still in discussion
- UI will partly be covered by #1379

**Comment by reneaaron** [comment]
Closing this as out of date and not actionable.
