### ISSUE TITLE
Look for phpBB tags or find tipping tag in user signatures

### ISSUE THREAD

**Issue by RenegadeButcher** [getAlby/lightning-browser-extension#1207]
I may be helping to setup an old school phpBB board soon, so I've been experimenting.  I added the [ ⚡️name@address.ln ] code like you do in twitter to my signature on a test board.  Alby doesn't seem to pick it up.  Is there something else I should do to make it visible to the extension?  I'd like to enable folks to put their own code in board signatures and accept tips similar to on Twitter.

Just a random idea that could come in handy, could something be added to the Alby code to look for a bbcode?  Something like [alby][/alby] or [ln][/ln] bracketing either an ln address or LNURL?  Click and call up the extension type deal.

**Comment by escapedcat** [comment]
Currently Alby is using "batteries" to pick up LN-addresses on certain websites.
You can try to create one for your project. Have a look at [this twitter example](https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/content-script/batteries/Twitter.ts).
Let us know if you need help.

**Comment by reneaaron** [comment]
@RenegadeButcher Thanks for bringing this up. I just managed to create a phpBB shortcode for exactly that purpose! 💯

First you have to create a custom BBCode in the control panel of phpBB:

![image](https://user-images.githubusercontent.com/100827540/182220393-5e41cc8f-cb9d-49e6-a5bb-17d651e63747.png)

After that you can use this new BBcode like this:

`[lightning="example@lnaddress.me"] ⚡ Send some sats[/lightning]`

![image](https://user-images.githubusercontent.com/100827540/182220700-3390e108-a6dc-490b-83f7-e8e387e366a8.png)

Clicking the link will automatically open Alby (if it is installed) or ask you to open this request in your favorite mobile wallet on your phone. 

Please let me know if that works for you, i might wrap this up in some blog post.

**Comment by escapedcat** [comment]
Thanks @reneaaron , this makes way more sense!

**Comment by escapedcat** [comment]
We consider this solved
