### ISSUE TITLE
Replace api.getSettings with hook useSettings

### ISSUE THREAD

**Issue by lisabaut** [getAlby/lightning-browser-extension#1210]
### Refactoring of settings on Component Level

Once this PR is merged https://github.com/getAlby/lightning-browser-extension/pull/1177
which introduces a SettingsContext with the hook `useSettings`
all places where `api.getSettings` is called on **component level** can be replaced with this new hook.

For exmaple here: https://github.com/getAlby/lightning-browser-extension/blob/feat/738_openchannel/src/app/screens/LNURLPay.tsx/#L100-L109

**Comment by escapedcat** [comment]
Relates to #743 , reminder for myself
