### ISSUE TITLE
Design: Improve setting "show fiat"

### ISSUE THREAD

**Issue by lisabaut** [getAlby/lightning-browser-extension#1224]
### Description

Sinse this PR https://github.com/getAlby/lightning-browser-extension/pull/1177 a new settings toogle is integrated "Show Fiat".

See the current integration here:

| Setting enabled  | Setting disabled  |
|---|---|
|![Bildschirmfoto 2022-07-25 um 13 27 26](https://user-images.githubusercontent.com/11243967/180769767-3e4df8d2-e8d3-4bea-83e2-4ff9a2a6b6f0.png)| ![Bildschirmfoto 2022-07-25 um 13 41 10](https://user-images.githubusercontent.com/11243967/180769985-247518d8-5e4b-4cf9-8851-2fec601d99a4.png) |

### Describe the solution you'd like

As discussed with design the integration can be improved with e.g.:

- [ ] better text for the toggle (title and subline)
- [ ] maybe re-arrange the settings and divide all currency related settings including the toggle with a new header

### Are you working on this?

_(Yes/No)_

**Comment by stackingsaunter** [comment]
closing as stale
