### ISSUE TITLE
Reword blocklist-action on "enable" screen to make it more clear

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1225]
### Is your feature request related to a problem? 

![image](https://user-images.githubusercontent.com/1016218/182117995-afab1dcd-4fd8-4c1e-a571-c427fbbf003c.png)

This is s slightly confusing: "Enable" Vs. "Don't ask for this site again"?  
I know one is "allow forever" and one is "block this page" but for a new user this could sound similar. 

### Describe the solution you'd like

A more precise/clear wording.

I.e.

> Block [WEBSITE] from further requests

### Are you working on this?

No

**Comment by bumi** [comment]
<img width="409" alt="image" src="https://user-images.githubusercontent.com/318/182190241-0dd7ff12-96a3-4330-a07f-3d8ce971f4bc.png">

**Comment by im-adithya** [comment]
This can be closed ig?

Right now, we show "Block and Ignore https://pro.kollider.xyz"
