### ISSUE TITLE
Creator's scripts

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1238]
After YouTube users get the understanding how to integrate Alby (ref. getAlby/getalby.com#212) they gonna face the following scenarios:

As a YouTube user I want to see where my funds are
As a YouTube user I want to know how I can convert my funds in fiat
As a YouTube user I want to withdraw

Same scripts will relate to Twitter or Bitcoin TV users.

Also, for the creators which use different platforms (and most commonly they do) will be scripts like: 

As a creator I want to know where the funds come from (YouTube, Twitter) 

Here is a Wiki page for it, please add if you feel like adding something :

https://github.com/getAlby/lightning-browser-extension/wiki/Creator's-scripts

**Comment by reneaaron** [comment]
There are now different guides that explain those things.
