### ISSUE TITLE
Transaction list: long description for incoming txs is being cut off

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1243]
### Describe the bug

Description is currently being cut off

### Screenshots

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1016218/182990816-43163e76-6069-45f5-8d52-d993a49a8e78.png">

### To Reproduce

- Create incoming tx with long description

### Expected behavior

If full description should always be shown in the "disclosure panel" like i.e. here:
![image](https://user-images.githubusercontent.com/1016218/182991150-9d202394-c755-4386-8390-1d335ec92726.png)

### Additional context

The `+`/`-` icon in front of the tx is confusing. People tend to think this is clickable to open the panel but a possible panel is indicated by `^` (see screenshot).

If we would show mixed (incoming & outgoing) txs these icons might make sense but currently we do not mix txs afaik.
Should we get rid of these icons?

### Are you working on this issue?

No

**Comment by im-adithya** [comment]
> The +/- icon in front of the tx is confusing. People tend to think this is clickable to open the panel but a possible panel is indicated by ^ (see screenshot).

Maybe coloring them with green and red respectively can make it more evident that it signifies received/sent?

**Comment by escapedcat** [comment]
@dvoroneca and we decided to just remove them. The transaction list will be redone anyway in the mid-term.

**Comment by bumi** [comment]
is this fixed now?

**Comment by escapedcat** [comment]
Yes, fixed with #1389
