### ISSUE TITLE
Adding existing account to the account list: incorrect password input is not defined in the error description and doesn't give password recovery suggestion

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1253]
**Description:**

Adding existing account to the account list: incorrect password input doesn't identify an error of incorrect password and doesn't give password recovery suggestion

**Steps to reproduce:**

1. Go to Alby Extension
2. Click on "Add a new account"
![Image](https://user-images.githubusercontent.com/108762093/183307555-f389ade6-02cf-4a9a-9487-4bd85a16ece2.png)

3. Input correct email
4. Input incorrect password
![Image](https://user-images.githubusercontent.com/108762093/183307572-99aac6f4-1133-47f6-a7c0-0180c5426625.png)

5. only error notification of existing account appears:
![Image](https://user-images.githubusercontent.com/108762093/183307586-04b81af3-69b5-49ff-8e71-f569e6471daf.png)

**Suggestion:**

Identify an error - wrong password for existing email
Add "password recovery" link

**Alby information**

Alby Version: [v1.13.0]
Alby installed through Google Chrome

**Device information:**

OS: [macOS Monterey 12.0.1 ] 
Browser [chrome]  Browser Version [Chrome Version 103.0.5060.114]

**Are you working on this issue?**

No

**Comment by escapedcat** [comment]
Does this duplicate #1182 ?

**Comment by AnastasiaVolk** [comment]
#1182 happens when we are installing Alby and trying to log in with existing email , this one is for when Alby is already installed and we are trying to log in. And the errors are different - in #1182 is no notification at all, here it is, but not defined as incorrect email and no link for password recovery which we have now

**Comment by bumi** [comment]
this is now done, can you check it again.

**Comment by AnastasiaVolk** [comment]
@bumi yes, works fine. Closing this.
