### ISSUE TITLE
When an existing user tries to use Alby from a browser, a full-screen window called "unlock to continue" appears (to log in to the extension)

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1254]
1. Your Alby Extension Account is locked
    ![Image](https://user-images.githubusercontent.com/108762093/183286684-bd10930a-f746-4a0e-b0ae-a7aea8afa695.png)

2. Go to getalby.com
    ![Image](https://user-images.githubusercontent.com/108762093/183286713-b4b8b59e-b621-4264-a291-b52e5337a681.png)
3. Click on "Dashboard"
4. Full screen called "Unlock to continue" with  a suggestion to unlock the Extension appears
    ![Image](https://user-images.githubusercontent.com/108762093/183286767-4761bdbd-2cec-44fe-97ef-9d294c8c8551.png)

**Expected behaviour:**

1. User needs to be suggested to choose the account he wants to work with first
2. Different UI for Unlock Account Page needed so the user understands he can close it and keep on work on web

**Comment by escapedcat** [comment]
Can we split this into two issues? Can be worked on separately and with different priorities.

**Comment by AnastasiaVolk** [comment]
@escapedcat done! #205 for re-working the flow, and for Different UI for Unlock Account Page keeping it as a draft as it has no high priority
