### ISSUE TITLE
List name of the receiver (here: the podcaster) in the transaction list

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1260]
### Is your feature request related to a problem? Please describe

![image](https://user-images.githubusercontent.com/13707997/183602793-0f639f56-c4e7-4d88-963b-cf498fde7d5b.png)
all transactions display podcastindex.org but not to the actual podcaster as receiver

### Describe the solution you'd like
I would like to see the name of the podcast as receiver (for podcasting) 

### Describe alternatives you've considered

It is probably very different from use case to use case where we get the data from to display the actual recipient. 
We could keep the website (i.e. podcastindex.org) as of now and add the receiver in the details view.  Then it is not so apparent that we do not now the actual receiver for some use cases. 

### Are you working on this?

No

**Comment by bumi** [comment]
We kinda already can do this with the `alby:name` and `alby:image` metatag. 
https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/content-script/originData.ts#L197

if you add such a meta tag to the website we show it:

```
<meta property="alby:name" content="podcaster name" />
```

**Comment by MoritzKa** [comment]
how does that help on a web podcast player? The website stays the same but the podcast I listen to changes. Wouldn´t Alby need to reed the RSS feed of each podcast in order to know the recipient?

**Comment by bumi** [comment]
no, the website knows what it plays and it needs to set the meta tag accordingly. 
e.g. on https://podcastindex.org/podcast/227573 set the `alby:name` tag to "Podnews podcasting news" then payments on that page will show that name. 
Alby will still always show the host do the user to not get tricked.

**Comment by bumi** [comment]
I think we can close this, this is up to the website
