### ISSUE TITLE
Add Value 4 Value tipping support for substack

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1263]
### Is your feature request related to a problem? Please describe

As a reader I want to be able to tip a substack publisher the same way as we do it with [the other "batteries"](https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/content-script/batteries)

### Describe the solution you'd like

Alby could extract the lightning details from each article or the about page.

**Comment by lukeojones** [comment]
I'll pick this one up as an intro to the project.

**Comment by abhiShandy** [comment]
Is there anything left to do about this issue?

**Comment by lukeojones** [comment]
No. The feature is complete.

**Comment by rolznz** [comment]
Thanks @lukeojones ! I will close this issue.
