### ISSUE TITLE
i18n - Switch hardcoded strings to translations: Screens batch 1

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1283]
### Is your feature request related to a problem? Please describe

We can split this ticket. Please write your name behind the "screen" in the list or write a comment if you start working on it. And assign yourself to this issue if you can.
Just to avoid people accidentally work on the same screen.

Switch these screens and related components to be translatable:

- [x] Accounts - #1291
- [x] Enable - #1297
- [x] Home - #1298
- [x] Onboard
- [x] Options - #1300
- [x] Publishers - #1295
- [x] Send - #1290
- [x] Receive - #1290

### Describe the solution you'd like

All hardcoded English strings should be replaced by

### Additional context

- Maybe unit-tests need to be adjusted to handle i18n. [Like we did here](https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/components/TransactionsTable/index.test.tsx#L125-L127) maybe.
- Don't create one big PR. Keep them small so they are easy to review and can be merged fast and do not create big conflicts.

### Are you working on this?

No

**Comment by im-adithya** [comment]
The options screen is done already!

**Comment by im-adithya** [comment]
Same with Onboarding!
(except for a small word `sats` if we want it to be translated as well (if yes, then we can just wait till the Home screen PR gets merged as it includes `sats` in tCommon to borrow from there!))

**Comment by escapedcat** [comment]
No, all good, just wanted to double check it. I'll mark them as done. Thanks!
