### ISSUE TITLE
After trying to enter the incorrect password, when entering with the correct one, messages about incorrect entry appear (one for each try)

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1286]
**Description:**

After trying to enter the password incorrectly, when entering with the correct password, messages about incorrect entry appear (one for each try)

**Screenshots:**
![Image](https://user-images.githubusercontent.com/108762093/183482148-51f6a064-3268-49d5-b6b5-3700fcd19c8c.png)

**Steps to reproduce:**

 1. Click on the Extension icon
2. Input incorrect password
3. Input correct password
4. The extension unlocks and notification about incorrect password appears (as many as were incorrect password attempts)

**Alby information**

Alby Version: [v1.13.0]
Alby installed through Google Chrome

**Device information:**

OS: [macOS Monterey 12.0.1 ] 
Browser [chrome]  Browser Version [Chrome Version 103.0.5060.114]

**Are you working on this issue?**

No

**Comment by escapedcat** [comment]
Some background
- Toast is trggered by
    https://github.com/getAlby/lightning-browser-extension/blob/master/src/common/lib/utils.ts#L30
- Initial message comes from here
    https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/actions/accounts/unlock.ts#L26
- The unlock screen needs a message to show it here
    https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Unlock/index.tsx#L87
