### ISSUE TITLE
possible to add already logged in account again

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1296]
**Description**

In the Extension it's possible to add already logged in account again and again

**Screenshots**

![Image](https://user-images.githubusercontent.com/108762093/184657145-777eda4b-0123-4398-b40b-e7b56bc7fb8c.png)

**Steps to reproduce the behaviour:**

1. Click on the Extension icon
2. Unlock
3. Go the account list
4. Click on "add a new account"
5. Choose Alby Wallet
6. Enter email and password of already logged in account
7. Click on "Continue"
8. "Success!" page appears

**Expected behavior**

 Notification about being logged in this account appears 

**Alby information**

Alby Version: [v1.13.0]
Alby installed through Google Chrome

**Device information:**

OS: [macOS Monterey 12.0.1 ] 
Browser [chrome]  Browser Version [Chrome Version 103.0.5060.114]

Are you working on this issue?

No

**Comment by escapedcat** [comment]
This is more like an enhancement I think. Nothing is really broken here. But yes, we should tackle this in a way.

**Comment by bumi** [comment]
I kinda think this is fine. 
no code is better than no code :) and adding the same account twice is not really a problem, is it?
