### ISSUE TITLE
Error handling for LNURL-withdraw

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1302]
### Describe the bug

Withdraws can fail for various reasons. (not enough balance, no channel, etc) Currently it seems there is no error handling and all of the withdraws are confirmed with a success message:

![image](https://user-images.githubusercontent.com/100827540/185404916-0e91fd6b-3d06-46bf-b66c-a41d3a06b431.png)

### To Reproduce

1. Open the Alby extension popup, click on "Send"
2. Enter a LNURL-withdraw link that doesn't work (go to LNBits, enable LNURL-w, create a new link and do not fund the wallet)
3. See success message (but no incoming transaction as the withdraw failed)

### Expected behavior

I want to see a proper error message if the withdraw failed. (+ if possible some advanced information on what went wrong, if we have this info)

### Are you working on this issue?

No.

**Comment by bumi** [comment]
I think this is released? can you check again?
