### ISSUE TITLE
Updating paths to app tiles for allowances

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1304]
### Describe the bug

If a website ever decides to delete the preview image from their servers or change the path, Alby will not update it for available allowances. This leads to broken or outdated images being displayed in the extension.

### Screenshots (If Any)

![image](https://user-images.githubusercontent.com/100827540/185418865-a41af8e5-61b3-4f8d-baef-6d9c40ebd754.png)

### To Reproduce

1. Open a site that has WebLN capabilities
2. Allow the site to interact with Alby (`webln.enable()`)
3. An allowance has now been created with the current image of the website
4. When the website deletes the image from their servers the path of the image remains in the database and links to an image that doesn't exist anymore

### Expected behavior

Alby should update the website's thumbnails in regular intervals, at least when the user visits the site again. 

### Are you working on this issue?

No.

**Comment by escapedcat** [comment]
Fix: On enable-action if allowance exists update image-url via updateAllowance

**Comment by bumi** [comment]
https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/actions/allowances/enable.ts#L40

probably something like this: 

```js
await db.allowances.update(allowance.id, { 
  enabled: true,
  name: message.origin.name,
  imageURL: message.origin.icon,
});
```
