### ISSUE TITLE
Display fiat amount in payment confirmation

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1306]
### Is your feature request related to a problem? Please describe

Currently the fiat amount is only displayed as I create the payment. 

![image](https://user-images.githubusercontent.com/100827540/185453246-850cf1d6-4a27-49c5-a57a-56e318469947.png)

As there are other entry points (`webln.sendPayment()`, invoices, etc) it would be nice to also include the fiat amount in the payment confirmation dialog:

![image](https://user-images.githubusercontent.com/100827540/185453094-01438bb9-b51c-4037-b1a9-1e31d485856c.png)

### Are you working on this?

No.

**Comment by lexyd** [comment]
I would like to work on the design for this, is there a general design board? @reneaaron

**Comment by escapedcat** [comment]
@lexyd have a look at these links:
https://github.com/getAlby/lightning-browser-extension#designer

/cc @dvoroneca

**Comment by lexyd** [comment]
@escapedcat  I have designed and added the fiat.
Here is an image of it.

Ill need access to add it to the board

<img width="384" alt="Send Payment" src="https://user-images.githubusercontent.com/17413130/185889060-7010047e-cfac-48cd-90ac-77752bf925bd.png">
.

**Comment by escapedcat** [comment]
> @escapedcat I have designed and added the fiat. Here is an image of it.
> Ill need access to add it to the board

Thanks, @dvoroneca our designer will need to have a look first. She's off this week just fyi.
Fiat should always have a `~` in front because it's never 100% accurate. we already do that in the app, i.e.:
![image](https://user-images.githubusercontent.com/1016218/185912399-918669c1-47e0-4911-8897-96dad7191311.png)



@lisabaut we do the technically implementation first as discussed in the call.

**Comment by lexyd** [comment]
@escapedcat I will be looking forward to hearing from @dvoroneca

Meanwhile, I have added the ~ to the design. Thank you
<img width="384" alt="Send Payment" src="https://user-images.githubusercontent.com/17413130/185917065-05b167f9-3916-4786-b268-f3262d34b781.png">

**Comment by lexyd** [comment]
PS @escapedcat You can tag me to other design related issues

**Comment by escapedcat** [comment]
> PS @escapedcat You can tag me to other design related issues

@dvoroneca will on-board you once she's back.
Thanks for your interest and support!

P.s.
Sats are more important than fiat for us so we will put sats first.
