### ISSUE TITLE
Capture links in dynamic content

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1307]
### Describe the bug

If links are not present at the time the document is loaded they seem to not be captured by Alby.

### To Reproduce

I've put together a little repro: 

https://codepen.io/reneaaron/pen/RwMEvmP

### Expected behavior

Clicking the dynamic link should trigger the extension as well. 

### Are you working on this issue?

_No_

**Comment by escapedcat** [comment]
Not easy to solve because we do not know/cannot know pages will change.

Relates to #1305

**Comment by reneaaron** [comment]
Did some bughunting. Dynamic content doesn't seem to be the issue generally. (all links in the repro case work after appending elements to the DOM instead of using `document.write`.

Sites where links are currently not captured:
 - lnmarkets.com
 - widgets.twentyuno.net (you need to click on the QR-Code)

**Comment by reneaaron** [comment]
Setting the events `capture` to `true` seems to fix it for LNMarkets, but not for the widgets. 

Might be related to the widgets using `Shadow DOM` as the event target is `<lightning-widget>`, compared to `<a>` in other events.

**Comment by reneaaron** [comment]
Thanks for your feedback in the PR. I now managed to narrow down the issue:

This bug appears if a website sets `e.stopPropagation()` for any lightning link. By setting `capture` to `true` we shift our event handler to the capturing phase of a event:

- https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
- https://stackoverflow.com/questions/7398290/unable-to-understand-usecapture-parameter-in-addeventlistener

I've put together a minimal reproduction case:

https://codepen.io/reneaaron/pen/ExLYVKP?editors=1111

**Comment by bumi** [comment]
All your examples work now! \o/
