### ISSUE TITLE
Update node version to 18 to stay up-to-date

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1314]
### Is your feature request related to a problem?

We're currently using v14 which is maintenance is running out April next year.
See: https://nodejs.org/en/about/releases/

### Describe the solution you'd like

- Update node version to latest v18 in i.e. 
    - `node-version`
    - `.nvmrc`
- Install it
- Test if dev task still work
- Test if build still works

#### Unit-test setup
Looks like some unit-tests fail after an update to 16/18.
This helps partly:
- Updating runcitadel #1280
- `transformIgnorePatterns: ["node_modules/(?!(dexie))/"],`
- Update `jest` (and related)to v29
- In other cases more mocking helps, i.e.:
    ```ts
    jest.mock("~/common/lib/utils");
    jest.mock("~/common/utils/currencyConvert");
    ```

#### Failing npm deps
- https://github.com/getAlby/lightning-browser-extension/pull/1549
    Latest [wext-manifest-loader](https://github.com/abhijithvijayan/wext-manifest-loader) needs node v16.15.0 as a minimum  
    Update will be paused via depfu for now

**Comment by bumi** [comment]
can we remove those node-version and nvmrc files? 
I don't think we have really version specific code. multiple versions should be supported.
