### ISSUE TITLE
Boostagram transactions do not display in history

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#1317]
### Is your feature request related to a problem? Please describe

When sending a boost from Podverse with a connected Alby wallet, the transaction get's sent but does not show up in the Outgoing transaction history view.

### Describe the solution you'd like

Tx shows up in history so there is a record of it.

### Additional context

![image](https://user-images.githubusercontent.com/85003930/185808927-6394d755-9094-4526-b481-c720f8b07378.png)

### Are you working on this?

No

**Comment by escapedcat** [comment]
> Tx shows up in history...

Which history?

**Comment by secondl1ght** [comment]
@escapedcat see screenshot above ^

**Comment by escapedcat** [comment]
> Tx shows up in history so there is a record of it.

I mean this. 

- It's not show in up in outgoing txs: understood
- It's showing in the history: I do not understand 

Sorry :D

**Comment by secondl1ght** [comment]
> > Tx shows up in history so there is a record of it.
> 
> I mean this.
> 
> * It's not show in up in outgoing txs: understood
> * It's showing in the history: I do not understand
> 
> Sorry :D

Sorry that was under the header **Describe the solution you'd like**, so that is the expected behavior. Could have been more clear :P.

**Comment by bumi** [comment]
Problem here is: 

how do we store the information? We need to check if we have all `custom_record` information after sending the payment (or if we only pass that to the connector call)
and then the question is how do we save it to the payments table and how do we read it/show it. 

and we have to keep in mind that this is not only about boostagrams but also potential other data.

**Comment by stackingsaunter** [comment]
afaik this is done, so closing (cc: @reneaaron to double check)
