### ISSUE TITLE
Configuration Tab not initiated on Tor Browser

### ISSUE THREAD

**Issue by KoalaSat** [getAlby/lightning-browser-extension#1328]
### Describe the bug

When the extension is installed on Tor Browser, the initial configuration tab is not triggered. 
The extension icon appears but when I click on it, it displays the login popup.
Accessing to the extension's local url will displays the same login view.

### Screenshots (If Any)

![image](https://user-images.githubusercontent.com/111684255/186098046-0455ff10-0d56-4553-b55b-829a63696f82.png)
![image](https://user-images.githubusercontent.com/111684255/186098098-6e9bdcd1-98f6-486b-aa22-edc1034ee1e5.png)

### To Reproduce

1. Install the extension in Tor Browser

### Expected behavior

The user should be able to see and set the initial configuration.

### Alby information

- Alby Version: 1.13.0
- Alby installed through: Tor Browser
- Wallet connected with Alby: -

### Device information [optional]:

- OS: OSX
- Browser Tor Browser
- Browser Version 11.5.1

### Additional context

On https://github.com/Reckless-Satoshi/robosats we are working on implementing WebLN and we are using Alby for development. We ask all our users to access Robosats through the TorNet to improve privacy, so we would like to make sure it properly works with the Tor Browser.

### Are you working on this issue?

No

**Comment by Reckless-Satoshi** [comment]
As found out by @bumi, Tor Browser seems to be strict on what can be saved (uses "Private Browsing Mode" by default). Some config of Alby needs to be saved (the account), but that storage profile is not available in "Private Browsing" setting.

While not ideal if max privacy is wanted, the solution is: 
1. Go to `Settings`
2. In the search bar type `"History"` 
3. Uncheck `"Always use private browsing mode"`

Certainly not an Alby related issue. Can be closed.
