### ISSUE TITLE
WebLN: VerifyMessage

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1345]
### Describe the bug

Signing and verifying a message isn't creating valid signatures, currently they are `{ valid: false }`.

```js
await webln.enable();
var result =  await webln.signMessage(message);
console.log(result);
console.log(await webln.verifyMessage(result.signature, message));
```

➡️ [Demo](https://codepen.io/reneaaron/pen/QWmRzyg?editors=1111)
(see console output)

### Expected behavior

 - Signing and verifying should produce valid signatures. 
 - Shouldn't there be a popup that allows users to verify signatures in Alby? (users would need to see the message, signature and the result to verify the integrity)
 - What is the use case of `verifyMessage`?

**Comment by bumi** [comment]
somehow I think verifyMessage should be deprecated. I don't really know what the use case for this is and nobody uses it it seems.

**Comment by reneaaron** [comment]
I had the same thought. If we can't come up with a valid use case I'd rather throw a `NotImplementedException()` than confusing users with API methods that don't work / make no sense. 

https://youtu.be/fTzW9iJhiNg?t=1586

**Comment by reneaaron** [comment]
I would say so. I think the right way to remove this code is to to throw an exception in `webln.verifyMessage()` and tell developers that this method is not supported by Alby. (there are also other WebLN providers that don't support all methods)
