### ISSUE TITLE
Feat: Publisher - show incoming/outgoing transactions (like we do on home)

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1347]
### Is your feature request related to a problem?

Publisher transaction-list only shows outgoing txs:
<img width="200" src="https://user-images.githubusercontent.com/1016218/187016594-095bb1d1-86d8-4199-a3f1-9919b6fb2586.png">

### Describe the solution you'd like

If possible it would be good to show incoming and outgoing txs per publisher.  
Similiar to what we do on the home-screen:
<img width="200" src="https://user-images.githubusercontent.com/1016218/187016556-a298b459-8bfe-4a3e-870f-360ae24b3289.png"/>

### Describe alternatives you've considered

none

### Additional context

fyi: We do not know where the incoming ones came from

> I did a lnurl-withdraw on lnmarkets and received the funds, but then I opened Alby and I only see funds sent

<img src="https://user-images.githubusercontent.com/1178856/187004419-10d9a1e5-888d-479d-9ed8-91e794376533.jpg" width="200"/>

### Are you working on this?

No

**Comment by escapedcat** [comment]
First finding:  
The current `getuserinvoices` (LND) API call result is not showing anything related to the host:
```json
{
    "r_hash": {
        "type": "Buffer",
        "data": [
            7,
            14,
            ...
        ]
    },
    "payment_hash": "123",
    "payment_request": "lnbc123",
    "description": "Withdrawal for [USER] on SN",
    "pay_req": "lnbc123",
    "timestamp": 1661932491,
    "type": "user_invoice",
    "expire_time": 86400,
    "amt": 10,
    "ispaid": true,
    "keysend": false,
    "custom_records": null
}
```

Filtering incoming txs via a `description` sounds like a bad idea.
