### ISSUE TITLE
Alby integration for SoundCloud

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1348]
### Description

For SoundCloud it is possible to integrate https://getalby.com/yourname to the main page. The link is working and when you click on it, also the Extension activates . But if the LN address is being added in the track description (same way as it done for YouTube videos), it wouldn’t activate the Extension as it does for YouTube videos

### How would like to see it

LN address in the track description on SoundCloud activates the Extension same way it does on YouTube

### Screenshot
Here is the screenshot of SoundCloud profile, the track description page on SC and a link for it (https://soundcloud.com/monvol)

<img width="1440" alt="Screenshot 2022-08-26 at 12 56 31" src="https://user-images.githubusercontent.com/108762093/187022115-4255978c-d606-49c6-93b5-23a03588af37.png">

<img width="1307" alt="Screenshot 2022-08-27 at 11 35 23" src="https://user-images.githubusercontent.com/108762093/187022400-83ca9a4e-4a0a-4d93-bb91-14821a5254a5.png">

### Are you working on this?

No

**Comment by escapedcat** [comment]
Good idea! Same for https://www.mixcloud.com/ maybe.

**Comment by AnastasiaVolk** [comment]
Now in value4value section we need to add SoundCloud (and Mixcloud)
Aa well as in the Integration in the Account on getalby.com

**Comment by AnastasiaVolk** [comment]
It is not working for Mixcloud

**Comment by escapedcat** [comment]
We figured it out, all good
