### ISSUE TITLE
Refactor currency converter

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1351]
### Describe the bug

currently the currency converter loads the settings every time an amount is converted. 

Generally I think it might be good to move getting the rate and caching the rate to an action in the background script. 
Currently this is done in the "frontend". Which means on every page load we get the rate again.

**Comment by escapedcat** [comment]
Duplicates #1021, will be done there

**Comment by bumi** [comment]
ah thanks, missed that one. very well documented.
