### ISSUE TITLE
My Umbrel connection with Alby using Tailscale is lost from time to time

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1355]
Hi, 

From time to time my Umbrel connection with Alby using Tailscale is lost and it's annoying. Always when is disconnected, I need to do this process:

![Captura de tela de 2022-08-29 19-14-25](https://user-images.githubusercontent.com/1178856/187309152-7e1f8d96-02de-452e-9d3b-2195ce6cbe92.png)

![Captura de tela de 2022-08-29 19-14-48](https://user-images.githubusercontent.com/1178856/187309170-0492226a-fe3f-4091-8e99-189897762ea7.png)

I think should have a way to have permanent connection.

**Comment by bumi** [comment]
yeah, this is still a hard one. browsers do not like the self-signed certificate. 
Instead of adding the exception you could try to import the certificate in the browser certificate list - but I haven't tried this much myself, yet.

**Comment by reneaaron** [comment]
@bitcoinuser Does this problem still persist for you?
