### ISSUE TITLE
Show fiat rates in notifications

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1381]
### Is your feature request related to a problem? Please describe

We have now the option to show fiat amounts when we display satoshi amounts.
So far we do not do this in the notifications. we should also show the same amount information.

### Additional context

we need to convert the amount here: https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/events/notifications.js#L13-L23

Probably it would be helpful if we refactor the currency converter first to do the api call and caching in a background script action?

**Comment by escapedcat** [comment]
Should wait for #1021
