### ISSUE TITLE
Use identicons 

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1391]
### Is your feature request related to a problem? Please describe

Currently we use one fixed default image (which looks actually like an identicon).
To make that image more useful and actually something unique per website/recipient we can use an identicon. 

Identicons provide a visual identifier for the website. 

### Describe the solution you'd like

We can use this one for example and dynamically generate the image: https://www.npmjs.com/package/identicon.js

**Comment by escapedcat** [comment]
Won't do
