### ISSUE TITLE
Generalize i18n strings

### ISSUE THREAD

**Issue by im-adithya** [getAlby/lightning-browser-extension#1394]
### Is your feature request related to a problem? Please describe

Right now, we don't have a separate rule book to decide the naming of i18n strings, which resulted in using different ways (mostly revolving around indentation and underscore) like:
```JSON
{
  "blue_label": "Blue"
}
```
```JSON
{
  "blue": {
    "label": "Blue"
  }
}
```
### Describe the solution you'd like

1) We should have guidelines agreed upon by all to decide i18n string naming.
2) Ensure they are being followed throughout

### Are you working on this?

Yes

**Comment by bumi** [comment]
+1 
when changing translation keys we just have to be careful because this will likely break already translated languages
