### ISSUE TITLE
Search bar for accounts

### ISSUE THREAD

**Issue by im-adithya** [getAlby/lightning-browser-extension#1395]
### Is your feature request related to a problem? Please describe

When there are many accounts, the alignment of the extension popup gets disturbed because of the scrollbar:

![Screenshot from 2022-09-06 10-47-30](https://user-images.githubusercontent.com/64399555/188552698-7e840bf3-0b3f-4bdf-b202-869fb07a1b62.png)

### Describe the solution you'd like

We can restrict the space using max-width and have a search bar for better UX!

### Are you working on this?

Yes

**Comment by bumi** [comment]
we actually also have a limit on the amount of accounts - there is a browser storage limit. I don't know the exact number, but your screenshot should be close to it.

**Comment by reneaaron** [comment]
I don't think this is a problem regular users have, closing for now :sweat_smile:
