### ISSUE TITLE
Transaction appear as received 53 years ago

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1403]
### Describe the bug

- Transaction appear as received 53 years ago
- Node used: Umbrel

### Screenshots

<img width="250" src="https://user-images.githubusercontent.com/1178856/188985511-6a768601-6bcd-40dc-9ccd-c3ac306a6ab7.jpg"/>

**Comment by escapedcat** [comment]
Screenshot from the TG chat showing it within Umbrel:  
<img src="https://user-images.githubusercontent.com/1016218/203102641-01b438fa-c955-4aa2-bc03-257e236d467c.png" width="350" />

Bumi mentioned:

> that's probably some invoices that do not have a timestamp? and something like 1.1.1970 is used?

If the timestamp is 0 it leads to 53 years.  
What would we prefer, showing nothing at all or i.e. "No date available"?

**Comment by escapedcat** [comment]
"Same issue" with kollider:  
![image](https://user-images.githubusercontent.com/1016218/203273824-e8b401d6-af63-4138-866f-7b2e6ec5460c.png)

**Comment by escapedcat** [comment]
We need to investigate why certain incomign (even settled txs) do not have a date.

**Comment by escapedcat** [comment]
Last status regarding this:

> :+1: so that looks good and it's not hat we always show all invoices

How to proceed now? The underlying issue is unrelated to Alby.

**Comment by bumi** [comment]
Do we now know the underlaying issue? When does LND return no settled date for settled invoices?

**Comment by escapedcat** [comment]
> Hm, are these related?
> On the other hand Leo says AMP invoices do not show up at all. Also not in his Umbrel.
> 
> But in our case invoices with `settle_date: 0` do show up. So I guess it's unrelated.
> - https://github.com/lightningnetwork/lnd/issues/7071
> - https://github.com/getAlby/lightning-browser-extension/issues/1657
> 
> How to create such `settle_date: 0` invoice on purpose?
