### ISSUE TITLE
Detection of a Lightning Address on Linktree page

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1415]
### Is your feature request related to a problem? Please describe

Linktree has 12m users: https://linktr.ee/ and is a simple way to show different websites to visitors. 
one Linktree example of a Bitcoiner: https://linktr.ee/BlueeMooon

### Describe the solution you'd like

I would like that Linktree users can add a Lightning Address to their LinkTree profile, Alby detects it and allows the Alby user to send bitcoin. 

### Describe alternatives you've considered

A linktree user could add a link to the Alby donation website. But they can already do that today. If Alby can detect a Lightning Address directly on the Linktree page the Alby user does not need to leave the website. 

### Are you working on this?

No

**Comment by MoritzKa** [comment]
not urgent.

**Comment by MoritzKa** [comment]
You already have one.

**Comment by escapedcat** [comment]
Yeah, so I tested this:
![image](https://user-images.githubusercontent.com/1016218/189855419-d289cda3-5a36-426d-982f-589355ea5c0f.png)

**Comment by bitcoinuser** [comment]
Hi, this is implemented. I think can be closed, right?

**Comment by escapedcat** [comment]
Yes, the last related PR was this:
https://github.com/getAlby/lightning-browser-extension/pull/1456
