### ISSUE TITLE
Connection problem or invalid lnurl / lightning address.

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1437]
### Describe the bug

I tried to send sats to a video youtube and I see this error: Connection problem or invalid lnurl / lightning address.

### Screenshots (If Any)

![Captura de tela de 2022-09-13 11-23-39](https://user-images.githubusercontent.com/1178856/189927524-b27e7d88-b3f3-4df3-97b0-eeb53ed27284.png)

### To Reproduce

1- Go to: https://www.youtube.com/watch?v=PqNRpStZRAE
2- Go to blue alby icon from extension and try to send sats

### Expected behavior

Able to send sats

### Alby information

- Alby Version: 1.15.1

**Comment by bumi** [comment]
@im-adithya can you have a look at this. the algorithm is confused with the tipping .me URL. We need to adjust it that it does not match characters like `:` or `/`
