### ISSUE TITLE
Cannot unlock Alby on TOR browser

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1462]
### Describe the bug

I cannot start the onboarding / I cannot unlock Alby or set a un unlock PIN on the TOR browser.

### Screenshots (If Any)

![firefox_VAx9XCaF57](https://user-images.githubusercontent.com/13707997/190893494-bcf0174b-6ddc-48e4-98c7-cdd80a92bbfc.png)

### To Reproduce

I want to use Alby on Tor browser. The browser seems to run on Firefox so I downloaded the Alby extension for Firefox, installed and want to connect my Alby wallet to the extension. But I cannot unlock it.

### Expected behavior

_A clear and concise description of what you expected to happen_

### Alby information

- Alby Version: the latest
- Alby installed through Firefox Store

### Device information [optional]:

- OS: [e.g. Windows]
- Browser: TOR
- Browser Version 91

### Are you working on this issue?

No

**Comment by MoritzKa** [comment]
Alby needs persistent memory, Tor Browser disables it by default. Go to Settings, type "History" on the search bar and uncheck "Always use private browsing mode"

**Comment by nikicat** [comment]
It didn't help me

**Comment by nikicat** [comment]
![image](https://github.com/getAlby/lightning-browser-extension/assets/329262/e637f14f-8e94-45da-b052-21be5e648169)
![image](https://github.com/getAlby/lightning-browser-extension/assets/329262/9a5b494a-684c-439c-ae04-55487a64bc30)

**Comment by Cyberpunk-Hardware** [comment]
same issue
