### ISSUE TITLE
Display auto login option for publishers

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#148]
The publisher list and detail page and popup should show of auto login with lnurl-auth is enabled or not.

Similar to updating the budget it should also be possible to enable/disable the auto login from the publishers edit form.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/318/142949835-795aeee3-ceb0-4b0c-a21e-42b841f6a709.png">
<img width="726" alt="image" src="https://user-images.githubusercontent.com/318/142949892-c313b669-8c9d-4b68-a2f1-fad8587c7210.png">

**Comment by secondl1ght** [comment]
I could work on the frontend for this if someone wants to do the backend?

**Comment by bumi** [comment]
yeah, let's do it. 
I think the `lnurlAuth` attribute is already part of the allowance data.

I can then update the action that it stores the update if you add it to the form.
