### ISSUE TITLE
How do I monetize my content on YouTube with an Alby Page?

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1480]
-  Write a script

-  Record over voice 

-  Screencast steps

-  Post-production, add music, intro/outro

- Cover editing

**Comment by AnastasiaVolk** [comment]
**How do I monetize my content on YouTube with an Alby Page?**

With your Alby Page, you can receive payments from your audience directly, instantly and without additional commissions.
Let them do it with the click of a button.

Here we explain to you how it works.

1. First, you need to get your Alby Page. If you don’t know how to do that, watch our video linked in the description, or click on the link in the upper right corner that you see now (add link https://www.youtube.com/watch?v=jQOhnyNisV4 ).
2. Go to your YouTube channel.
3. Click on “Customize channel”
4. Click on “Basic Info.”
5. Scroll down to “Links”
6. Paste the address of your Alby page that you copied from your account page at [getalby.com](http://getalby.com/).
7. “Link title” is left up to you, just make sure your audience understands what it’s for.
8. Click on “Publish.”
9. You can now see it right on the main cover of your channel.

Now when your audience clicks on the icon, they are directed to your Alby page.

For those who have the Alby Browser Extension installed, it will activate once they are on your channel, and they will be able to send you sats while watching your videos - they no longer need to leave your page.

We have many more interesting features for YouTube, so stay tuned, subscribe to our channel, try out the extension yourself and let your audience know how they can support you.

**Comment by bitcoinuser** [comment]
I already saw a video with these steps on Alby channel. I think this issue can be closed, right?

**Comment by AnastasiaVolk** [comment]
yes
