### ISSUE TITLE
How do I monetize my content on SoundCloud with an Alby Page?

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1482]
How do I monetize my content on SoundCloud with an Alby Page?

With your Alby Page, you can receive payments from your audience directly, instantly and without additional commissions.
Let them do it with the click of a button.

Here we explain to you how it works.
1. First, you need to get your Alby Page. If you don’t know how to do that, watch our video linked in the description, or click on the link in the upper right corner that you see now (add link https://www.youtube.com/watch?v=jQOhnyNisV4 ).
2. Go to your SoundCloud
3. Click on “Edit”
4. In “Your Links” add your Alby Page

![Image](https://user-images.githubusercontent.com/108762093/191011094-b00c69c5-3143-4f08-9d06-d47ecef9f556.png)

5. “Link title” is left up to you, just make sure your audience understands what it’s for.
6. Click “Save changes”

You can now see it among other social links for your channel.

When your audience clicks on it, they are directed to your Alby page.

For those who have the Alby Browser Extension installed, it will activate as soon as they are on your page and they can send you sats while listening to your tracks or mixes - they no longer need to leave your page.

Do you also use YouTube or MixCloud? Both of those services now also have integration with Alby Page, so you can watch our videos via the link in the description or by clicking on the link in the top right corner you see now.

Stay tuned, subscribe to our channel, try out the extension yourself and let your audience know how they can support you.

**Comment by stackingsaunter** [comment]
@MoritzKa can we close this?

**Comment by MoritzKa** [comment]
Yes
