### ISSUE TITLE
Balance on home screen

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1490]
### Is your feature request related to a problem? Please describe

As a user I want to see the total balance on the home screen. Currently there is a PublisherCard:

![image](https://user-images.githubusercontent.com/100827540/191240947-d46b97f0-136c-4ebe-b595-5a7e9c75bb7e.png)

Replace the `PublisherCard`with the total balance of the current account on the Home Screen

Maybe we could also remove the balance from the dropdown then:

![image](https://user-images.githubusercontent.com/100827540/191241667-14fa7ecc-cfd6-451f-98ab-4e62b86a0c39.png)

### Are you working on this?

No.

**Comment by escapedcat** [comment]
@dvoroneca assigning this to you till the design is done. Hope that's ok.

**Comment by escapedcat** [comment]
Further notes:
When we talk about the design we should think about splitting `PublisherCard` (for the allwoance view) from "found lightning-address info". This tends to be highly confusing and causes misunderstandings and bugs. If we can not tackle this in this issue we can open a new one.

**Comment by reneaaron** [comment]
Closing in favor of #2236.
