### ISSUE TITLE
Send to ln-address: lightning address server is online but responses with an error alby should show an error

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1492]
### Describe the bug

I tried to send sats to a page that have a lightning address but the lightning server was offline.
When trying to send sats nothing happens.

### To Reproduce

1. Try to send sats using Alby on a page that have a lightning address but the lightning address server is offline.

### Expected behavior

I expected Alby show an error that the lightning server is offline or not working. But for now, nothing happens, I click on Send sats button and nothing happens.

### Alby information

- Alby Version: 1.15.1

**Comment by bitcoinuser** [comment]
I think that when the server is offline, it really shows an error. What I reproduced with ZBD lightningaddress I think was other problem that @fiatjaf can explain here.

**Comment by fiatjaf** [comment]
In this specific case the server was not offline, it was returning an error on the first lnurlpay call. Something like `{"status": "ERROR", "reason": "couldn't find user"}`, which is the same error format returned in all other places.
