### ISSUE TITLE
Onboarding flow improvements

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1504]
### Is your feature request related to a problem? Please describe

The onboarding flow has some flaws that we want to address with this issue.

#### Remove benefits page

 - Users might not see the "Get started" button at the very top
 - Users do not read this page

![image](https://user-images.githubusercontent.com/100827540/191741592-ca1d5b34-4602-4c2d-b326-c552b7fb5da0.png)

#### Remove progress bar
![image](https://user-images.githubusercontent.com/100827540/191741843-26cc0691-45a2-4cbc-b315-625ff1319da0.png)

#### Remove the page where we ask people to send us SATS.
 - Most of our users don't have any sats in their wallet
 - Don't ask them to spend (will add a "fund you wallet" guide later)

![image](https://user-images.githubusercontent.com/100827540/191742141-175d3c30-f73f-44c7-bf78-a1f49b2588b0.png)

#### Questions
 - Where should we send users after they have setup their account? Should we maybe open the extension startpage? 
![image](https://user-images.githubusercontent.com/100827540/191742764-43e08a56-c071-4ff1-9244-1b0183e9cddd.png)

**Comment by reneaaron** [comment]
I really like the idea of having contextual contents (top up when wallet balance is 0)! 💯

So for this issue we would at least need the designs for those buttons in the extension popup and how that should look like on the websites screen:

![image](https://user-images.githubusercontent.com/100827540/191781080-de1127f7-f631-4dbc-b495-c8200099956f.png)

 - We could remove the "Your Websites" section completely if there are none
 - Rename "Other Websites" to something more recognizable like "⚡ Lightning Apps on the web"
 - Create a new section where we educate users about how to fund their account

I'd go for the gitbook for now as we already have them and don't need to invent / build anything new on the website. I could think of a comprehensive guide here:

https://app.gitbook.com/o/uiUeRqI074apbV0PWsyf/s/Fc98arDakfIy96P4JqRN/

Contents should contain: 
 - Buy (new users)
 - Fund wallet with on-chain 
 - Fund wallet with lightning
 - Earn bitcoin (maybe a link to some other site)
 
/cc @MoritzKa

**Comment by bumi** [comment]
The idea of the [demo page](https://getalby.com/demo) was to guide the user through the functionality and allow them to use and learn it.

Johns had done some journey mapping on this before, and I think it is important to guide the user through the journey and make sure that there is no dead-end.

**Comment by reneaaron** [comment]
@bumi There should definitely be no dead end. We could take it to our extension start page ("websites") where they will see some "fund your wallet" content. (if they have no funds in it)

> The idea of the [demo page](https://getalby.com/demo) was to guide the user through the functionality and allow them to use and learn it.

The problem I see here is that it's not an interactive tutorial where they would actually work with the extension (also they have never seen the extension UI before and can't really imagine how that would work) The only action they can really try with Alby is the button at the very bottom of the page which most of the new users can't use because they have no funds. 😕

**Comment by bumi** [comment]
> The problem I see here is that it's not an interactive tutorial where they would actually work with the extension (also they have never seen the extension UI before and can't really imagine how that would work) The only action they can really try with Alby is the button at the very bottom of the page which most of the new users can't use because they have no funds.

sure, that page like it is currently is shit. I mean I made it in no time...and for sure it would be good to have something interactive. 
but here is the general problem that we have to work on: how do we ship things fast? having something tomorrow is better than having something in a month. So what is the first step to improve?

**Comment by reneaaron** [comment]
If we don't have the topup page ready we could tackle the first 2 points from the original issue (Remove benefits page and remove progress bar) and add remove the "Try now" page / add the conditional buttons in a separate step.

**Comment by bumi** [comment]
we can just create a top up page. the most simple version is a page with text...

**Comment by bumi** [comment]
https://github.com/getAlby/lightning-browser-extension/pull/1432

**Comment by escapedcat** [comment]
Tasks:

- Remove "progress bar"
- Remove "benefits page" -> So we start at "password", yes?
- Remove last page and go directly to "Websites"
- Improve content for empty "your websites"
- New headline for "Other websites"
- Banner for "topup guide"

**Comment by reneaaron** [comment]
Adding this information here for further discussion:
 - Add a "Pin extension" screen to onboarding
![image](https://user-images.githubusercontent.com/100827540/194404282-286afee4-19b9-4d11-844d-a8cd0accdbd8.png)
 - Add a link to getalby.com for getalby.com users (where they can login with the extension and can use it for the first time)
![image](https://user-images.githubusercontent.com/100827540/194404220-bf267015-8044-4d46-831d-3605b6418bd2.png)
 - The onboarding flow could continue from there (lighting address, tipping site, etc)


/cc @dvoroneca

**Comment by escapedcat** [comment]
Welcome designs can be found here: https://github.com/getAlby/getalby.com/issues/231#issuecomment-1282236973

**Comment by dvoroneca** [comment]
> Welcome designs can be found here: [getAlby/getalby.com#231 (comment)](https://github.com/getAlby/getalby.com/issues/231#issuecomment-1282236973)

Yes, thanks for redirecting.

**Comment by dulcedu** [comment]
hello, sup? 
Do you guys have any Figma doc open to the community to add suggestions? I did the onboarding today again after some time ago, and there is a lot of improvement, -Congrats- but some room for little improvements according to your needs and who is your user persona o target audience.

**Comment by reneaaron** [comment]
Hey @dulcedu! Thanks for your feedback, we're glad you like the recent changes. 

For design-related discussions it might be good to connect on the bitcoin.design slack. We're hanging out in the #lightning-browser-extension channel. Feel free to say hi there and let's discuss what we could improve further in the onboarding! Looking forward to hear from you!

**Comment by jakubszwedo** [comment]
@dulcedu [Here is a file](https://www.figma.com/file/z3uJ9ukGm6RIuTVKvKMYNw/Alby-onboarding-evaluation?node-id=106%3A5601&t=80qBOBKO5jDu3dKP-1) with onboarding designs that were implemented lately - we highly appreciate your suggestions!
