### ISSUE TITLE
Improve alert-text when deleting a website

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1505]
### Describe the bug

If I go to allowance and click on delete, appear this message: Are you sure you want to delete this website?. But I think the text can be improved to something like: If you delete this website, you will loose all history of transactions you did on it, like total of payments and sats spent. Are you sure you want to delete this website?

### Screenshots (If Any)

![Captura de tela de 2022-09-22 10-53-50](https://user-images.githubusercontent.com/1178856/191768084-7603e5f3-3ff4-404c-878b-f348fd351515.png)

### To Reproduce

See the screenshot

### Expected behavior

I think the text can be improved to something like: If you delete this website, you will loose all history of transactions you did on it, like total of payments and sats spent. Are you sure you want to delete this website?

### Alby information

- Alby Version: 1.15.1

### Are you working on this issue?

No

**Comment by bitcoinuser** [comment]
Hi,

Looks like if I delete a website than I do a payment again to the website I deleted, the previous transactions show again. Is this correct?

**Comment by bitcoinuser** [comment]
> Looks like if I delete a website than I do a payment again to the website I deleted, the previous transactions show again. Is this correct?

If yes, what is the logic of have the option to delete a website? Maybe could just have the option to ACTIVATE or DISABLE from: https://github.com/getAlby/lightning-browser-extension/pull/1494, no?

**Comment by escapedcat** [comment]
> Looks like if I delete a website than I do a payment again to the website I deleted, the previous transactions show again. Is this correct?

According to this it's not correct: #186

**Comment by bitcoinuser** [comment]
> > Looks like if I delete a website than I do a payment again to the website I deleted, the previous transactions show again. Is this correct?
> 
> According to this it's not correct: #186

You mean I'm correct, right? payments are not deleted.

**Comment by VishalNayek** [comment]
Would love to fix this @bitcoinuser . Could you please assign this to me?

**Comment by escapedcat** [comment]
@qqqzhch already tackled this via #1844
