### ISSUE TITLE
Send screen from popup should not show "Remember and set a budget" when i.e. pasting a lightning invoice (or other screens)

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1510]
### Describe the bug

If I create a ln invoice on a wallet like Phoenix and copy it and paste on Alby, Alby show the option Remember and set a budget. But doesn't make sense, because it's not a service or a page, so it's not saved.

### Screenshots

![Captura de tela de 2022-09-23 10-59-01](https://user-images.githubusercontent.com/1178856/191978498-cc2a3621-98aa-4c10-8a4b-13d5aa3ac6f3.png)

### To Reproduce

1. Generate a ln invoice on a ln wallet like Phoenix and copy the invoice.
2. Click on Alby send button, then paste the invoice and click continue button

### Expected behavior

Remember and set a budget option not be showed.

### Alby information

- Alby Version: 1.15.1

**Comment by vaibhavgarg237** [comment]
I'm working on this

**Comment by escapedcat** [comment]
> I'm working on this

Thanks! Let me know if you get stuck or need more info

**Comment by escapedcat** [comment]
Heyhey @vaibhavgarg237 , did you already start with this? Do you need any support?

**Comment by vaibhavgarg237** [comment]
> Heyhey @vaibhavgarg237 , did you already start with this? Do you need any support?

It's almost complete, I got occupied in some office work...
Although I was facing some issues related to running tests locally. So I was thinking to first run locally and then do the PR. Will create the draft PR today...

**Comment by escapedcat** [comment]
> Will create the draft PR today

Perfect, yes! No worries if it's not "ready ready" yet. Just seeing some progress is already helpful. 
Thanks for your quick reply!
