### ISSUE TITLE
Send UX: Too long input placeholder is being cut off

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1517]
### Describe the bug

Text in Portuguese is cut on send field

### Screenshots

<img width="280" src="https://user-images.githubusercontent.com/1178856/192146693-4e155976-3923-40c0-9a84-d4dfc640b6b5.jpg" />

### To Reproduce

1. Set Portuguese language on Alby and go to Send window

### Expected behavior

See all the text or on mouseover see all the text.

@escapedcat comment:

> The UX should be changed. Currently the text is an input-placeholder. This should be some sort of hint-text and not a placeholder within the input. 

[Hint can be added via input-prop](https://github.com/getAlby/lightning-browser-extension/blob/fix/i18n-20220925/src/app/components/form/TextField/index.tsx#L64-L68)

### Alby information

- Alby Version: 1.16.0

**Comment by rottingcleaner** [comment]
Alternatively we can add the `title` attribute to the input field. On mouse over the user will see a browser native tooltip with the full text of the input-placeholder. Easy to implement.

![Screenshot 2022-10-07 at 18 35 26 (1)](https://user-images.githubusercontent.com/114179325/194604075-421cdc94-b53a-4786-8672-ddc9f266891a.png)

**Comment by escapedcat** [comment]
> Alternatively we can add the title attribute to the input field. On mouse over the user will see a browser native tooltip with the full text of the input-placeholder. Easy to implement.

Yeah, but I don't think this is a common or learned UX pattern we should use. If you want to "hide" hint-texts usually people use some sort of "i"-icon with a hover, but I don't think we currently need that. A clear text below an input does the job. What do you think?

**Comment by reneaaron** [comment]
Can you post a screenshot of how that would look?

**Comment by escapedcat** [comment]
![image](https://user-images.githubusercontent.com/1016218/194750434-972bc2b8-7559-4d81-bea5-188e2f5b1aaf.png)

**Comment by vaibhavgarg237** [comment]
Just for reference
![image](https://user-images.githubusercontent.com/67408018/194919867-c8f546a8-c771-4463-a86f-d8d90735a874.png)

**Comment by vaibhavgarg237** [comment]
I feel in the case of placeholder text, we can indicate the user for action i.e. "Paste here...". Like below-attached screenshot. What do you think?

@escapedcat I opened a PR #1591, with this change

![image](https://user-images.githubusercontent.com/67408018/194920991-ca0055c0-bbb6-4718-980b-c6112f24e24e.png)

**Comment by reneaaron** [comment]
What do you think of this? 

 - Label: `Recipient`
 - Placeholder: ``
 - Helptext: `Invoice, Lightning Address or LNURL`

**Comment by vaibhavgarg237** [comment]
> What do you think of this?
> 
> * Label: `Recipient`
> * Placeholder: ``
> * Helptext: `Invoice, Lightning Address or LNURL`


TBH, the empty placeholder seems slightly odd, although this label and hint look good. Can we add "Paste here" or some similar text here?

![image](https://user-images.githubusercontent.com/67408018/195894466-b943856e-e401-4905-b90a-3b9511b7cc91.png)

**Comment by reneaaron** [comment]
I'm okay with the empty field, to me that seems fine. I don't feel like every field needs to have a placeholder.
`Paste here` feels wrong to me as you can also _type_ a lightning address.

**Comment by vaibhavgarg237** [comment]
Okay. I have updated PR #1591 with this change & test
