### ISSUE TITLE
Add a tag called LIGHTNING LOGIN in front of websites I logged in using Lightning

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1534]
### Describe the solution you'd like

For now we have the tag ACTIVE when the user specified a budget to a website. I think should have too, a tag called LIGHTNING LOGIN, when the user logged in a website using lightning login.
I think is important, because make easy to users track in which sites they used lightning to login.

**Comment by bumi** [comment]
nice, good idea to show this as a badge. 
related: https://github.com/getAlby/lightning-browser-extension/issues/148
