### ISSUE TITLE
Send satoshis window should have the back button too

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1535]
### Describe the bug

When clicking on Alby blue icon and click to send sats, I don't see the back button like there are on other Alby windows.
Back button:

![Captura de tela de 2022-09-27 11-05-39](https://user-images.githubusercontent.com/1178856/192549732-9b434d2b-26f3-45bc-a8d9-7711b278dc9a.png)

### Screenshots (If Any)

See the Send Sats window

![Captura de tela de 2022-09-27 11-05-12](https://user-images.githubusercontent.com/1178856/192549474-8b2fe09a-471d-43e6-89c1-124a03f46ca2.png)

### To Reproduce

1. Go to https://bitcoinheiros.com/
2. Click on Alby blue icon
3. Click on Send Satoshis

### Expected behavior

See the back button. 

Obs. I know on bottom exist the cancel button, but I think the back button is necessary to be consistent with the others Alby windows.

### Alby information

- Alby Version: 1.16.1

**Comment by escapedcat** [comment]
Note: We use this screen in also in the prompt. There we do not need a "back" button.

**Comment by manavdesai27** [comment]
I would like to work on this issue. @escapedcat

**Comment by manavdesai27** [comment]
@escapedcat Which screen is the prompt screen?

**Comment by escapedcat** [comment]
> @escapedcat Which screen is the prompt screen?

The individual window which prompts a payment on a website for example.  
Does this help?

**Comment by manavdesai27** [comment]
> The individual window which prompts a payment on a website for example. Does this help?

Yeah got it, thanks. I have handled that case in the PR.
