### ISSUE TITLE
Alby login button shoud be inactive with a spinner after first click on it

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1540]
### Describe the bug

If I click on login, because of delay to really login, the user tend to click on it more than one time.

### Screenshots

https://user-images.githubusercontent.com/1178856/192806375-787a91e8-a6e5-44b5-b40a-ab2a518cb295.mp4

### To Reproduce

1. Go to https://makers.bolt.fun/feed
2. click to connect
3. login

### Expected behavior

When clicking on login button on Alby, the login button should stay inactive with a spinner, so user do not click on it again. 

### Alby information

- Alby Version: 1.16.1

**Comment by escapedcat** [comment]
@reneaaron @dvoroneca  
We only wait for the success response and then close the prompt. For the rest we do not really know when the webpage will recognize this and continue, right? Would and artificial loading spinner help here? Like 1-2 second and then close the prompt for example?

**Comment by im-adithya** [comment]
@escapedcat I think it's because we don't use `loading` and `disable` props to `ConfirmOrCancel` in just these two (enable and lnurlAuth) screens (we use it in all other screens). Sending a fix!

**Comment by escapedcat** [comment]
Ah, thanks @im-adithya , I misunderstood this.
