### ISSUE TITLE
Clicking on back button should go to the previous window

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1542]
### Describe the bug

Generate an invoice and click back button, should go to previous window and not to home window.

### Screenshots

https://user-images.githubusercontent.com/1178856/192901751-4bda697f-9692-4b34-8ed9-4f3b3df08aa7.mp4

### To Reproduce

1. Click on receive button
2. Generate an invoice
3. Click on back button

### Expected behavior

Not go to home window but to the previous window

### Alby information

- Alby Version: 1.16.1

**Comment by dvoroneca** [comment]
Thank you. This is a very valid point. The back button should take users back to the previous screen. We will take this into consideration when working on creating invoice flow next.  🙌

**Comment by manavdesai27** [comment]
Is this issue still active?

**Comment by escapedcat** [comment]
> Is this issue still active?

Yes, what we see in the video is still the current status.

**Comment by manavdesai27** [comment]
We could do here something like following:

Reset `formData`
Reset `Invoice`
Reset `paid`
Reset `pollingForPayment`

**Comment by manavdesai27** [comment]
@escapedcat Could you assign me this issue?
