### ISSUE TITLE
Github bug/feature templates: Switch to forms

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1547]
### Is your feature request related to a problem?

Our issues templates sometimes lead to missing or wrongly input information.  
Would be nice to fidn a way to "guide" a user through these when filing an issue.

### Describe the solution you'd like

Currently we use simple templates for these.  
Other projects use external services.  

Zeus uses github but with a "form-generator":
 - See: https://github.com/ZeusLN/zeus/issues/new?assignees=&labels=Bug&template=bug_report.yml
 - https://raw.githubusercontent.com/ZeusLN/zeus/master/.github/ISSUE_TEMPLATE/bug_report.yml

**Comment by buneeIsSlo** [comment]
@escapedcat Hey! I want to work on this.

**Comment by escapedcat** [comment]
Thanks @buneeIsSlo ! Assigned you. Let us know if you need any further info or feedback.

**Comment by buneeIsSlo** [comment]
Hi! @escapedcat I've raised a PR, could you please take a look at it?

**Comment by escapedcat** [comment]
> Hi! @escapedcat I've raised a PR, could you please take a look at it?

Saw it, thinking about how to test it. Eventually we're just gonna merge it and will do corrections if needed. Will let you know.

**Comment by buneeIsSlo** [comment]
@escapedcat Got it! Thank you.

**Comment by escapedcat** [comment]
Thanks for you PR! I commented.
