### ISSUE TITLE
Top up with on-chain address user flow

### ISSUE THREAD

**Issue by dvoroneca** [getAlby/lightning-browser-extension#1558]

**Comment by dvoroneca** [comment]
Users want to receive funds / or top up their account. 

Design a user flow that would finish the onboarding for the users and allow them to start using Bitcoin micropayments on the web.


https://www.figma.com/file/OszHSwkAH1IiiyWI650iwE/On-chain-bitcoin-onramp?node-id=1%3A2214

**Comment by dvoroneca** [comment]
The idea for bitcoin onramps:
### 1. Chrome extension browser view welcomes the new user with a list of options to top up the account
### 2. Directs users to instructions on GitBooks with links
2.1 Hot-to-use lightning address (Alby wallet users)
2.2 How to top up with an on-chain address (Alby wallet users)
2.3 How to top up with Fiat (Alby wallet users)
2.4 Send from another lightning wallet (All users)
### 3. Get a notification about getting funds

--------------
1. Chrome extension browser view welcomes the new user with a list of options to top up the account

![Welcome for all users](https://user-images.githubusercontent.com/35034985/195126509-69c8ca80-edf0-44f3-8da2-82133052299a.png)

## [Link to Figma file](https://www.figma.com/file/7tp7ynWwA8dbXLwRjQHkhO/Onboarding?node-id=1%3A134)

**Comment by escapedcat** [comment]
Do we already have the final links?

**Comment by dvoroneca** [comment]
https://guides.getalby.com/overall-guide/alby-lightning-wallet/how-to-top-up-your-wallet-balance
 

![Image](https://user-images.githubusercontent.com/35034985/196119912-b3c356bf-093d-4c34-beb0-6e99cdd821ff.png)

What we need is:
1. Receive Bitcoin to your Bitcoin address “Fund your wallet” with on-chain BTC = From another bitcoin wallet

2. Buy Lightning Bitcoin with Fiat “Fund your wallet” with Fiat = From an exchange service

3. Receive Lightning Bitcoin to your lightning wallet “Fund your wallet” Lightning address = NO article

4.* not an option in the welcome section, but it should be fourth (Top Up with a lightning wallet) = "From another crypto wallet"

**Comment by stackingsaunter** [comment]
Closing as this is outdated. We have buy button now and will probably add a link to Alby Account onchain receive screen soon (for alby account users)
