### ISSUE TITLE
LNURLWithdraw can be received by pasting in to send. Needs UX improvement

### ISSUE THREAD

**Issue by dvoroneca** [getAlby/lightning-browser-extension#1560]
We must have an option for the user to paste the LNURL invoice when users want to receive payment from other wallets. I suggest we add a switch component.

- [ ] We have a switch component in the transactions screen. We reuse it with 1. Create an invoice and 2. Paste an invoice.

- [ ] Paste an invoice page that will consist of an input field and a Next button

- [ ] Add a success screen from https://github.com/getAlby/lightning-browser-extension/pull/1446#issuecomment-1259384465

### [Figma File](https://www.figma.com/file/u7RWBpbz3sBLx15sE6hTsO/Receive-Switch-for-creating-invoice%2Fpasting-an-invoice?node-id=6%3A1292)

As a bonus point: Can we please move our buttons to the bottom of the screen? Thanks.

**Comment by dvoroneca** [comment]
We can work on the component to make it nicer for the coming sprint.


<img width="780" alt="Screenshot 2022-10-03 at 20 41 09" src="https://user-images.githubusercontent.com/35034985/193653806-0f319991-3d43-48a2-8c12-7317f96c76e5.png">

1. We can have a simple text switch:
<img width="487" alt="Screenshot 2022-10-03 at 20 39 28" src="https://user-images.githubusercontent.com/35034985/193653486-577c82d0-f5a0-4d20-892a-005fd85782f2.png">

2. Or we can make a component with some style:

![Frame 30282](https://user-images.githubusercontent.com/35034985/193653677-37db98aa-d157-48a0-83b1-780d758cc82d.jpg)
![Frame 30282-2](https://user-images.githubusercontent.com/35034985/193653683-e7d1f6bc-dabc-4b16-b708-216656ae9f7f.jpg)
![Frame 30282-1](https://user-images.githubusercontent.com/35034985/193653689-592457f4-9673-48fc-bdc4-064560a9cf84.jpg)

 
## Check out the [Figma file here](https://www.figma.com/file/u7RWBpbz3sBLx15sE6hTsO/Untitled?node-id=0%3A1)

**Comment by bitcoinuser** [comment]
For me make much more sense use the text "redeem funds" instead of "paste an invoice"

**Comment by bitcoinuser** [comment]
And instead of "Lnurl invoice" I would use "Redeem code".

**Comment by reneaaron** [comment]
I generally agree to write copy from the user perspective, but as protocols are currently being established I feel like it is important to let the user know what is being used here. 

I wouldn't know what I am supposed to paste if an extension wants a "redeem code"  from me, probably I'd assume that would be a proprietary thing. 

But maybe there are other ways to improve the overall flow, I just summarized an idea we had here:

https://github.com/getAlby/lightning-browser-extension/issues/1564

**Comment by escapedcat** [comment]
Thanks everyone! Moving the technical implementation to [milestone 1.18](https://github.com/getAlby/lightning-browser-extension/milestone/6)

**Comment by stackingsaunter** [comment]
Issue solved
