### ISSUE TITLE
UI: update tab-style - ON HOLD

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1566]
### Feature description

Update tabs-style
![image](https://user-images.githubusercontent.com/1016218/193981295-682c57c4-852c-4e03-8215-4848ed1e0d7f.png)
![image](https://user-images.githubusercontent.com/1016218/193981263-39200ac4-3e9d-45cd-ac86-4461dd89d2fa.png)
![image](https://user-images.githubusercontent.com/1016218/193981310-c2feb0ab-89fe-416a-987c-c3a37d880a71.png)

If you start working on this please coordinate with @dvoroneca regarding which styling is preffered or i.e. easiest to implement.  
We also need to consider dark-mode.

### Describe the solution

We currently use the default tabs with an minimal adjusted style-set:
https://headlessui.com/react/tabs

We only use the tabs here currently:
- dark-mode:  
    https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Home/index.tsx/#L396-L445
![image](https://user-images.githubusercontent.com/1016218/193980978-7e5f3e61-c994-4365-b40a-3df7ef3869c9.png)
- light-mode:  
    ![image](https://user-images.githubusercontent.com/1016218/193981471-52b28769-0deb-43dc-bc43-03a693158800.png)

(If #1560 is done we will use tabs in two file screens)

### Describe alternatives

_A clear and concise description of any alternative solutions or features you've considered_

### Additional context

- This is a follow-up to #1560
- If #1560 is done, we should also move Tabs in their own component to make it more reusable (like we already do with other components). This can be done in this or in a new issue.

**Comment by escapedcat** [comment]
@Nasimmhn yes! Thanks! Let us know if you need any support or get stuck.

**Comment by escapedcat** [comment]
Hey @Nasimmhn you need any support? Did you already start?

**Comment by escapedcat** [comment]
@Nasimmhn unassining you here to give other people a chance. I guess you're busy with other things. No worries.

**Comment by whyprax** [comment]
Hello @escapedcat, is this issue still open?
If yes, can you please assign it to me?

**Comment by escapedcat** [comment]
@whyprax you got it. Let ue know if you have any issues or get stuck.

**Comment by whyprax** [comment]
Hey @escapedcat, I need your help in setting up the project.

I have followed these steps : 
    Ensure you have
    
        [Node.js](https://nodejs.org/) v14 [14.20.1] installed (We only support v14 currently)
        [Yarn](https://yarnpkg.com/) v1 or v2 installed
    
    Suppported but not required
    
        [nodenv](https://github.com/nodenv/nodenv)
        [nvm](https://github.com/nvm-sh/nvm#intro)
    
    Then run the following
    
        Install dependencies
        yarn install
        Start the development server for the extension
            yarn run dev:chrome
            yarn run dev:firefox
            yarn run dev:opera


But, I'm still not able to set it up running.

This is the error I'm getting:

    yarn run v1.22.19
    $ cross-env NODE_ENV=development TARGET_BROWSER=firefox webpack --watch
    wext-manifest-webpack-plugin: removed js/manifest.bundle.js
    (node:27328) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
    (Use `node --trace-deprecation ...` to show where the warning was created)
    (node:27328) [DEP_WEBPACK_CHUNK_ENTRY_MODULE] DeprecationWarning: Chunk.entryModule: Use new ChunkGraph API
    (node:27328) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'filter' is deprecated)
    2022-11-08 21:51:39: webpack compiled (568341dc2db6b84dd3b8)

**Comment by escapedcat** [comment]
This looks good.

```sh
2022-11-08 21:51:39: webpack compiled (568341dc2db6b84dd3b8)
```

This indicates it was build successfully. You should be able to import it into your browser, like described here: https://github.com/getAlby/lightning-browser-extension#-load-extension-into-browser

For faster assistance you can join [our slack-channel](https://github.com/getAlby/lightning-browser-extension#join-the-conversation) and contact me there.

**Comment by kkartik07** [comment]
@escapedcat is this assigned to someone, or I can work on it?

**Comment by escapedcat** [comment]
> @escapedcat is this assigned to someone, or I can work on it?

Hey @kkartik07 , assgined you now. But let's check with @reneaaron if this is still a thing we want. This issue is rather old.

**Comment by kkartik07** [comment]
> > @escapedcat is this assigned to someone, or I can work on it?
> 
> Hey @kkartik07 , assgined you now. But let's check with @reneaaron if this is still a thing we want. This issue is rather old.

Ok fine 👍

**Comment by reneaaron** [comment]
I'd probably postpone this for now until we had our designer have a look at those new tab designs again and decide how we want to go about the extension UI in general.

**Comment by stackingsaunter** [comment]
This is the tab design I proposed for onchain tabs, that could be potentially used in other places in the app. But we could use more flat ones, something like in the issue description. Which design do you guys prefer more @rolznz @reneaaron?

![image](https://user-images.githubusercontent.com/68239231/231001539-62bfd7c7-80a3-4e44-963c-49b019d8fd1f.png)

**Comment by rolznz** [comment]
@stackingsaunter I like the new design but am happy with either 👍

**Comment by reneaaron** [comment]
Closing as we already have new tab styles implemented :partying_face:
