### ISSUE TITLE
Forms: disable fom/fieldset/inputs after submit

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1572]
### Describe the bug

I'm able to type text on fields after I click on confirm button

### Screenshots of the changes [optional]

[Gravação de tela de 05-10-2022 22:52:10.webm](https://user-images.githubusercontent.com/1178856/194196838-80351ada-3f92-464d-b7cb-196a99fb4b3c.webm)

### To Reproduce

See the video

### Expected behavior

Not be able to type any information on the fields of send window when payment is processing.

### Alby information

- Alby Version: 1.17

**Comment by bitcoinuser** [comment]
I think even the cancel button should be disabled, because we can't cancel a payment that is already being processed. Right?

**Comment by vaibhavgarg237** [comment]
I'm working on this

**Comment by vaibhavgarg237** [comment]
I have disabled the Amount, Comment, Name, Email, sats Buttons, and Cancel button after tapping on confirm
