### ISSUE TITLE
Website screen logos are slightly off

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1573]
### Describe the bug

The logos of app on the "Website" screen do not fill the whole place properly.

### Screenshots of the changes [optional]

![image](https://user-images.githubusercontent.com/13707997/194333195-a2775c48-3812-4d1b-819a-0f1a9d07267e.png)

### To Reproduce

1. Visit the "Websites" screen in the Alby extension

### Expected behavior

logos fill the place properly without a white space. 

### Alby information

- Alby Version:  1.17

### Device information [optional]

- OS: Windows
- Browser Chrome

### Are you working on this issue?

No

**Comment by rottingcleaner** [comment]
The broken logo thumbnails have a transparent gap at the bottom of each SVG image. This is the reason for the incorrect display. In my screenshots you can see the spacing at the bottom. 

To display the images without visually errors, all thumbs should be **square** and **completely filled** with a (background) color.

Maybe @auwalrg8 can optimize affected thumbnails.

👎

- **Thumb 1**

![wrong 2](https://user-images.githubusercontent.com/114179325/194381484-ec1e89a3-742d-41aa-8104-6e158568fe43.png)

- **Thumb 2**

![wrong](https://user-images.githubusercontent.com/114179325/194381506-4599c3fd-289b-4afa-a63b-cff712246abd.png)

👍
![perfect](https://user-images.githubusercontent.com/114179325/194381553-f291a627-fe3d-4428-a3f6-a799b453d5fe.png)

**Comment by escapedcat** [comment]
@rottingcleaner is it possible to use a fill property via css to always fill the square? That means maybe 1-2px might be cut of but at least we solve the general issue no matter what exact icon proportions?

**Comment by rottingcleaner** [comment]
@escapedcat I don't think, it will solve the problem. But I can try it. Which color I should use to fill the squares?

From my perspective we should use prepared thumbnails without spacing around. That will increase the quality.

**Comment by escapedcat** [comment]
> @escapedcat I don't think, it will solve the problem. But I can try it. Which color I should use to fill the squares?

Um, no, I mean something like this:
https://developer.mozilla.org/en-US/docs/Web/CSS/background-size
`background-size: cover;`  
Although on this issues' case it's not a background-image.

> From my perspective we should use prepared thumbnails without spacing around. That will increase the quality.

Sure, that's the nicer solution

**Comment by rottingcleaner** [comment]
Ah, ok. I tried out but also this solution is not really an option as long the thumbnail/image itself has a transparent space.

I think we have no posibilities to fix the issue clean on the CSS side.

![Screenshot 2022-10-07 at 12 14 17](https://user-images.githubusercontent.com/114179325/194531814-297da2c4-8289-434e-ae54-4eaba6451782.png)
![Screenshot 2022-10-07 at 12 17 40](https://user-images.githubusercontent.com/114179325/194531800-4f2cbc06-90a5-4666-8c4c-9f8d20fb7646.png)

**Comment by stackingsaunter** [comment]
This seems to be resolved, right?

**Comment by MoritzKa** [comment]
Yes. That looks good if I look at the rendered ratio.

![chrome_zTqCzayD4H](https://user-images.githubusercontent.com/13707997/225572801-c1b81579-eb5b-4895-9ccb-67ae30365464.png)
