### ISSUE TITLE
Amount-input changes value on scroll (mouse/touchpad)

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1593]
### Describe the bug

Scrolling the mouse/via touchpad within an amount-input will change the value. Issue is that a user might not notice that the wheel was used and the amount was changed.

### Screenshots of the changes [optional]

![image](https://user-images.githubusercontent.com/1016218/194745576-f27bd959-cb21-4f98-b1ca-b5b7eee8505d.png)

### To Reproduce

1. Visit 'Send'
1. Input an ln-adress i.e. `bumi@getalby.com` and click 'continue"
1. Click into the amount-input (so it's focused)
1. Scroll mouse down (or up)
1. Value changes while scrolling

### Expected behavior

Value should mot change on scroll

### Additional context [optional]

These amount-fields use our [`DualCurrencyField`-component](https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/components/form/DualCurrencyField/index.tsx#L40) which is defined as a [`number`-input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number). This is helpful because it's easier for the input to deal with numbers and min/max values.  
We already [hide the special arrow-buttons via css](https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/styles/index.css/#L54-L66) but the `steps`-functionality is still supported. We should disable/remove this as well.

**Comment by g1mishra** [comment]
@escapedcat Please align with me.

**Comment by escapedcat** [comment]
Thanks for tackling this! Let us know if you get stuck or need more information.

**Comment by g1mishra** [comment]
Yes, I'm working on this. I'll update you soon.
