### ISSUE TITLE
Settings: Text very close to the "switch"-button

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1596]
### Describe the bug

Text is very near the button

### Screenshots of the changes [optional]

![Captura de tela de 2022-10-09 11-31-20](https://user-images.githubusercontent.com/1178856/194762577-ce0a97f0-11ad-4569-bbf3-e30aff6c0957.png)

### To Reproduce

1. Change language to Portuguese Brasil on settings
2. See the LNURL-Auth antigo

### Expected behavior

Text not very near the button

### Alby information

- Alby Version: 1.17

### Are you working on this issue?

No

**Comment by vaibhavgarg237** [comment]
@escapedcat We can add mr-1 [here](https://github.com/getAlby/lightning-browser-extension/blob/118ab3614240443e05ccd133194f83929c52be63/src/app/components/Setting/index.tsx#L14) in Settings component.
It will add some space in right between the toggle button and subtitle text.

Updated
![image](https://user-images.githubusercontent.com/67408018/194932661-b4fbfe9e-d8a8-46b3-a3a2-a68db42f4ae1.png)

Old image
![image](https://user-images.githubusercontent.com/67408018/194932724-81260560-64ab-4684-adf6-8c111b022da2.png)

**Comment by escapedcat** [comment]
Thanks for your suggestion @vaibhavgarg237 ! You wanna create a PR?

**Comment by vaibhavgarg237** [comment]
> Thanks for your suggestion @vaibhavgarg237 ! You wanna create a PR?

Okay, I will open a PR. You can assign it to me.

**Comment by vaibhavgarg237** [comment]
@escapedcat  I have opened a PR for this issue.
