### ISSUE TITLE
Settings: Text is displayed with HTML-tags

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1597]
### Describe the bug

Text with strange symbols like <br /> , </strong>...

### Screenshots of the changes [optional]

![Captura de tela de 2022-10-09 11-34-59](https://user-images.githubusercontent.com/1178856/194762750-dc3ba111-b2f8-45f1-afd0-d94996b28da4.png)

### To Reproduce

1. Go to Settings
2. LNURL-Auth

### Expected behavior

Text without strange symbols

### Alby information

- Alby Version: 1.17

### Are you working on this issue?

No

**Comment by vaibhavgarg237** [comment]
@escapedcat I have opened PR #1604 to fix this.

The hint text contains HTML tags that didn't parse, so it appeared as it is in the app. For this we need to use [**html-react-parser** npm package](https://www.npmjs.com/package/html-react-parser) to parse the string. Now it's showing the text as expected with the relevant Br and Strong tags.
