### ISSUE TITLE
Sometimes fiat value appear as 0 but should show none info or other kind of rendering

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1608]
### Describe the bug

Sometimes I open Alby and I look to see how much the sats I have is representing in fiat. But sometimes maybe because it take some seconds to load or maybe because the fiat quote provider service is offline, the value appear as 0.

### Screenshots of the changes [optional]

This screenshot is working ok, I couldn't take a screenshot reproducing the problem

![Captura de tela de 2022-10-11 14-05-12](https://user-images.githubusercontent.com/1178856/195156081-4fe96f11-b1c8-45b8-af55-5bc389e5f19a.png)

### To Reproduce

The problem is hard to reproduce, maybe when fiat quote provider is slow or offline

### Expected behavior

Not show 0 but instead show none information or some other kind of rendering. 

### Alby information

- Alby Version: 1.17

**Comment by vaibhavgarg237** [comment]
**I feel it shows 0 because initialState of currencyRate is set to be 0**
https://github.com/getAlby/lightning-browser-extension/blob/49705ab42ed5f9efaeb4c1d21c7832610f0d1e2e/src/app/context/SettingsContext.tsx#L30

**Initial stage of fiatBalance :**
https://github.com/getAlby/lightning-browser-extension/blob/5156710bce3f21ce543a0f2fda89f0db2e724318/src/app/context/AccountContext.tsx#L53

**Comment by escapedcat** [comment]
@bitcoinuser is the `0` usually replaced by a fiat value after some time/seconds or does it stay?  
If this just shows during loading we could i.e. just show `...` if fiat is `0` as a first fix. No need to add a spinner I think.

**Comment by bumi** [comment]
yes, esp. in slow connections this happens and is visible.

**Comment by vaibhavgarg237** [comment]
I feel we can change [this](https://github.com/getAlby/lightning-browser-extension/blob/5156710bce3f21ce543a0f2fda89f0db2e724318/src/app/components/AccountMenu/index.tsx#L95-L97) with below mentioned [changes in the image ](https://gist.github.com/vaibhavgarg237/4f5bdfe160d9cea20c9b727f9d436d9b#file-index-tsx)

Current Code:
https://github.com/getAlby/lightning-browser-extension/blob/5156710bce3f21ce543a0f2fda89f0db2e724318/src/app/components/AccountMenu/index.tsx#L95-L97

Proposed Changes:
![image](https://user-images.githubusercontent.com/67408018/195389572-a808e1f8-21da-45e2-acb3-68f9bc7f6923.png)

**Comment by escapedcat** [comment]
Hm, currency depends on the settings. So checking for i.e. `$` will not cover all cases, right?  
Play around with the currencies in "settings".  
Wanna check what solution might work better here?

**Comment by vaibhavgarg237** [comment]
> Hm, currency depends on the settings. So checking for i.e. `$` will not cover all cases, right? 

Oh I forgot that one. Will make it dynamic.

**Comment by vaibhavgarg237** [comment]
@escapedcat I have opened a PR for this issue with the proposed changes. Can assign this issue to me?
