### ISSUE TITLE
Refactor: use form onSubmit for ConfirmorCancel

### ISSUE THREAD

**Issue by vaibhavgarg237** [getAlby/lightning-browser-extension#1617]
### Description

Currently for calling Confirm from ConfirmorCancel component we use onClick as a prop, due to which user can't use Enter key to submit the form, wrapping it inside a form would be better.

### Describe the solution

Wrapping all the ConfirmorCancel components forms with forms and handling submit operation via onSubmit instead of onClick

### Describe alternatives

After merging PR #1576, onClick will be made optional after which we could wrap all occurences inside forms and handle onSubmit operation accordingly.

### Additional context [optional]

Refer PR #1576

**Comment by vaibhavgarg237** [comment]
Will open a PR for this after PR #1576 gets merged to avoid optional onClick related merge conflict

**Comment by escapedcat** [comment]
Hey @vaibhavgarg237 you still wanna do this one?

**Comment by vaibhavgarg237** [comment]
Yeah, sorry I forgot about this issue.

**Comment by bumi** [comment]
PR merged
