### ISSUE TITLE
Add HMAC signature to new wallet requests

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1622]
### Feature description

To validate the new wallet requests we should add a hmac signature.

**Comment by escapedcat** [comment]
Please elaborate

**Comment by bumi** [comment]
https://developers.cloudflare.com/firewall/recipes/require-valid-hmac-token/
https://developers.cloudflare.com/ruleset-engine/rules-language/functions/#hmac-validation
https://developers.cloudflare.com/ruleset-engine/rules-language/operators/
