### ISSUE TITLE
Send button on YouTube not active

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1630]
### Describe the bug
Send button on YouTube does not show up and Alby is not blue on different tabs in a youtube channel.

### To Reproduce

I have a Lightning Address with emoji in my YouTube channel in the About page
I also have a link to the Alby page in my profile. but it is https://getalby.com/moritz instead of https://getalby.com/p/moritz
My YouTube channel: https://www.youtube.com/channel/UCWrD1YY3oq2Ow5gTWBGc7dQ/about

with https://getalby.com/p/moritz Alby is active on any YouTube page (About, Playlists, Videos, etc.)
With https://getalby.com/moritz Alby is not active on other YouTube pages (About, Playlists, Videos, etc.)

It seems the old/ deprecated link overrules the Lightning Address in the About page.

### Expected behavior

Alby detects the Lightning Address in the About page and is active on every YouTube video and Channel tab (regardless if there is a link to the Alby page)

### Alby information

- Alby Version: the latest
- Alby installed through browser store
- Wallet connected with Alby: Alby

### Device information [optional]

- OS: Windows
- Browser Chrome

**Comment by im-adithya** [comment]
Discussed with @MoritzKa, everything seems fine
