### ISSUE TITLE
With Alby setting page opened and try to change password with Alby locked, should show an error message

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1632]
### Describe the bug

I opened Alby settings page, then I locked the Alby, then I tried to change lock password, nothing happens and no error message appear

### To Reproduce

1. Open Alby settings page
2. Lock the extension on Alby fav icon on browser top
3. Try to change Alby lock password

### Expected behavior

Alby should show a message to unlock the extension first to change the password.

### Alby information

- Alby Version: 1.17

**Comment by ShivamJhaa** [comment]
Hi I would like to work on this issue, can you please assign me?
