### ISSUE TITLE
Improve transaction lists

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1636]
### Feature description

The incoming transaction list could be decluttered quite a bit: 

![image](https://user-images.githubusercontent.com/100827540/196653548-0f4a6df3-568b-4f7e-b763-886b906af56e.png)

### Describe the solution

 - Remove obsolete icons (+) 
 - Remove obsolete texts (`Received` is repeated in every line)
 - Unfolding only makes sense if we can display additional information (currently the description is just repeated) 
![image](https://user-images.githubusercontent.com/100827540/196654179-ad96e18f-1fb4-4eb6-8304-e7804f620685.png)

**Comment by escapedcat** [comment]
> Unfolding only makes sense if we can display additional information (currently the description is just repeated)

Just some context:

- The description is used a a title if we do not have a "name"
- Currently we will always make it "unfoldable" if we have at least one of these:
    - description
    - totalFees
    - preimage
    - location
    - boostagram
