### ISSUE TITLE
Close button does close the extension website on success screen

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1638]
### Screenshots of the changes [optional]

![image](https://user-images.githubusercontent.com/100827540/196661077-fe48050e-9b0d-42ad-9a96-b838d0724ea1.png)

### To Reproduce

1. Open the extension website (click on the extension icon and open "send")
2. Send to a lightning address of your choice
3. Clicking "close" closes the tab 

### Expected behavior

In the extension popup the button "close" takes you to the send screen again.

**Comment by im-adithya** [comment]
Waiting on #1581
