### ISSUE TITLE
Text cutoff at the bottom of the connect screen (chrome)

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1639]
### Describe the bug

"Block and ignore" is currently being cut off:

![image](https://user-images.githubusercontent.com/100827540/196665453-f554cbc7-9855-4552-ac00-7e5fee0e5a56.png)

**Comment by escapedcat** [comment]
![image](https://user-images.githubusercontent.com/1016218/196696074-57e47d65-564c-484c-a52d-ef3f4fb170d6.png)
I don't have that?  
Can you still scroll down?

**Comment by reneaaron** [comment]
There are no scrollbars but I could scroll the bottom message into the view.

**Comment by bumi** [comment]
I think scrollbars are hidden by CSS.
it fits in my screen, but maybe we can remove some spacing a bit to make it a bit smaller that it fits?
