### ISSUE TITLE
Bug: get fiat value for CUC fails with 404

### ISSUE THREAD

**Issue by lisabaut** [getAlby/lightning-browser-extension#1649]
### Describe the bug

While working on this PR https://github.com/getAlby/lightning-browser-extension/pull/1645
I saw that a conversion for sats to fiat for the currency "CUC" fails.

Sidenote:
In the [PR](https://github.com/getAlby/lightning-browser-extension/pull/1645) above I added a try/catch block which was missing.

### Screenshots of the changes [optional]

From the PR mentioned above

<img width="605" alt="404" src="https://user-images.githubusercontent.com/11243967/197146363-465d5d3e-2345-40ec-9b99-82749fed7c6c.png">

### To Reproduce

1. Open the settings page
2. Change the currency to CUC
3. watch the console for the error

### Expected behavior

No error is thrown or the currency can not be selected

### Alby information

- Alby Version: current master
- Alby installed through manually
- Wallet connected with Alby 

### Device information [optional]

- OS: Mac
- Browser FF
- Browser Version 105

### Are you working on this issue?

no

**Comment by lisabaut** [comment]
As discussed:

Go over the currency list on the Settings Screen and get an overview which currency with which provider does not work / throws an error.
Remove these currencies from the list accordingly.

**Comment by bumi** [comment]
https://twitter.com/NicolasDorier/status/1602465746591928320

**Comment by mviswanathsai** [comment]
Hey! I would like to work on this, what prior knowledge do I need to contribute to Alby?

**Comment by escapedcat** [comment]
> Hey! I would like to work on this, what prior knowledge do I need to contribute to Alby?

@mviswanathsai you would need to now TS/JS mainly.  
But let us first check if removing broken ones for now is a good first iteration.  
@bumi @reneaaron wdyt? Is removing broken/unsupported ones ok for now?  
I would say yes.  
I think Nicolas' solution would also require the Alby proxy to handle different APIs internally, right? I don't think that's worth the effort currently.

**Comment by mviswanathsai** [comment]
BYN CUC MRU SSP STN VES throw 404 on Alby
CLP FKP MZN TJS YER on Coindesk
Should I remove these currencies from constants.ts?

**Comment by mviswanathsai** [comment]
I have opened a PR here #1906
