### ISSUE TITLE
Should have an option to authorize forever, for 5 minutes or just this time for nostr events on a specific service

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1652]
### Describe the bug

If I go to a nostr service like https://anigma.io/ and I enable Alby nostr on it, everytime I post a message I need to confirm signing the event on Alby

### Screenshots of the changes [optional]

![Captura de tela de 2022-10-21 21-34-53](https://user-images.githubusercontent.com/1178856/197308420-bceee44e-52fd-4576-8f63-f0e79e955abf.png)

### To Reproduce

1- Enable Nostr on Alby settings
2- Go to https://anigma.io/ and enable Alby
3- Try to send messages on Anigma

### Expected behavior

A popup with options like authorize forever, for 5 minutes or just this time, for example like the nos2x extension:

![Captura de tela de 2022-10-21 21-31-13](https://user-images.githubusercontent.com/1178856/197308505-8bafbac1-7e0b-4148-8c37-6f4816abee7b.png)

### Alby information

- Alby Version: 1.18

**Comment by bumi** [comment]
@lisabaut maybe time is something that we could add in the permissions database? what do you think about that?

**Comment by lisabaut** [comment]
@bumi 

I would add `validUntil` Date to the permission in the database.

In the UI this would be:
- authorize forever => "enabled: true"
- authorize for 5 minutes => "validUntil: Date.now + 5 min" and "enabled: false"
- authorize just this => "validUntil: null" and "enabled: false"

The request gets the permission from DB and checks [here](https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/actions/ln/request.ts):
- validUntil? => compare with Date.now if still valid
- YES => call request 
- NO => prompt
- no validUntil? => check if "enabled: true"
- YES => call request
- NO => prompt


Need to check if the DB version needs to be increased again for the new entry in the DB.

**Comment by bitcoinuser** [comment]
I think this is fixed on Alby 1.20
