### ISSUE TITLE
[BUG] Hard to see three dots on Accounts page (Dark Mode)

### ISSUE THREAD

**Issue by Cameri** [getAlby/lightning-browser-extension#1656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It's hard to see the three dots to edit an account on the Accounts page when in Dark Mode.

Please increase the contrast on the three dots so it is easier to see.

### Screenshots [optional]

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/378886/197402715-c74b1a51-60d2-497e-8c9a-216f92e8c860.png">

### Steps To Reproduce

1. Enable dark mode (browser/OS)
2. Go to settings
3. Click on Manage accounts
4. Look for the three dots

### Expected behavior

It should be easy to see that there are three dots for each account so the user can edit/remove them.

### Alby information

- Version 1.18.0
- Installed manually

### Device information

- OS: Mac OS
- Firefox Developer Edition 107.0b2 (64-bit)

### Are you working on this?

No

**Comment by bumi** [comment]
@secondl1ght any idea how to make this more prominent in dark mode?

**Comment by im-adithya** [comment]
Maybe add a border and make the dots a bit whiter?
<img width="45" alt="Screenshot 2022-10-26 at 4 18 31 PM" src="https://user-images.githubusercontent.com/64399555/198007369-e35ad25c-dbf3-4561-ba77-08746d06bfcf.png">
<img width="55" alt="Screenshot 2022-10-26 at 4 20 20 PM" src="https://user-images.githubusercontent.com/64399555/198007718-2032aac5-e9b6-4427-ae99-fccdefeef9a2.png">

**Comment by escapedcat** [comment]
> Maybe add a border and make the dots a bit whiter?

Love it! wdyt @reneaaron @dvoroneca ?

**Comment by bumi** [comment]
+1
