### ISSUE TITLE
[BUG] Transactions received without memo should appear as unknown 

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1658]
### Describe the bug

I created an invoice without memo on Zeus connected on Umbrel. Alby is too connected with the same Umbrel. So I paid this invoice with Breez wallet. I looked on received transactions on Alby and no memo info is showed.

### Screenshots [optional]

![Captura de tela de 2022-10-23 20-36-27](https://user-images.githubusercontent.com/1178856/197423862-59864952-1a02-44de-8ce5-ac991d3e1aa2.png)

### Steps To Reproduce

1.Go to Zeus wallet connected with Umbrel and create an invoice without Memo.
2. Pay the invoice with Breez or other wallet
3. Go to Alby received transactions.

### Expected behavior

See the transaction with Memo: Unknown.

### Alby information

Alby version: 1.18
Alby connected with Umbrel

**Comment by escapedcat** [comment]
@reneaaron @dvoroneca what do you think?

**Comment by reneaaron** [comment]
I don't think a list of transactions with "Unknown" makes more sense than just a list of empty transaction descriptions.
