### ISSUE TITLE
🧹 Cleanup send screen (popup, prompt, size, height)

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1662]
### Feature description

The current send screen is too long to fit into the extension popup. 

![image](https://user-images.githubusercontent.com/100827540/197572024-c7e60762-d486-4daa-9840-cec52249a819.png)

### Describe the solution

Make the send screen (especially the forms) more compact. Potential things to consider: 
 - The receiver could be a bit more compact 
![image](https://user-images.githubusercontent.com/100827540/197572982-a38aac66-9c80-41cd-8da2-eec6210e32ee.png)
 - Name + Email could initially be hidden behind a "advanced" section?
 - Do we really need the amount preselectors? Do you use them? 
![image](https://user-images.githubusercontent.com/100827540/197572570-e324edf5-cb32-47c3-bfbc-3d034b58b9c5.png)
 - See how other wallets solve it 

### Describe alternatives

-

**Comment by pavanjoshi914** [comment]
![Screenshot from 2023-02-03 12-39-49](https://user-images.githubusercontent.com/55848322/216535159-2b91d6d7-0c9d-40fa-8e9f-ee505e8cc509.png)
do we need more compact screen than this or issue is solved?

**Comment by escapedcat** [comment]
@pavanjoshi914 I believe the idea is to show it including the buttons so a user doesn't need to scroll.

**Comment by reneaaron** [comment]
Closing in favor of #2370
