### ISSUE TITLE
Extend DB with "permissions"

### ISSUE THREAD

**Issue by lisabaut** [getAlby/lightning-browser-extension#1692]
### Feature description

This is part of the meta ticket https://github.com/getAlby/meta/issues/230

In order to let WebLN pass generic methods of a connector to their API, the extension needs to check the user's permissions for this connector methods first.

### TODO

- [x] extend the DB with "permissions" with schema: `allowanceId, host, method, enabled, blocked, createdAt `(`allowanceId` and `host` are the same of the relational allowance)
- [x] extend allowance schema with "permissions" which is an array of permission `method`

### Describe alternatives

**Questions:**

Shouldn´t the permissions do have an `id` or `key` too?
What is the difference between "enabled"  and "blocked"? Shouldn't be one boolean enough to check if this permission is avtive?

### Are you working on this?

Yes

**Comment by bumi** [comment]
what would be the `id` or `key` of a permission? 

re enabled/blocked: 
if there is no permission for a call then we prompt the user.
if a permission is set and "enabled" we execute the request automatically without prompt
if a permission is set and "blocked" we reject the request, do not prompt the user and do not execute. - but we can ignore this for now. As said I just like to avoid data migrations so I thought this could be useful. (=> how can a user give a website to list invoices but reject requesting the balance? -> that would be "list invoices" enabled, but "request balance" is blocked.)

**Comment by lisabaut** [comment]
> what would be the `id` or `key` of a permission?

I meant the unique primary key within the DB table. I added this ID now.
https://dexie.org/docs/API-Reference#quick-reference

> 
> re enabled/blocked: if there is no permission for a call then we prompt the user. if a permission is set and "enabled" we execute the request automatically without prompt if a permission is set and "blocked" we reject the request, do not prompt the user and do not execute. - but we can ignore this for now. As said I just like to avoid data migrations so I thought this could be useful. (=> how can a user give a website to list invoices but reject requesting the balance? -> that would be "list invoices" enabled, but "request balance" is blocked.)

Thanks, I added this explanation to the meta ticket description https://github.com/getAlby/meta/issues/230

**Comment by bumi** [comment]
> I meant the unique primary key within the DB table. I added this ID now.

ah ja, +1 for an ID
