### ISSUE TITLE
Extend WebLN with generic request method

### ISSUE THREAD

**Issue by lisabaut** [getAlby/lightning-browser-extension#1696]
### Feature description

This is part of the meta ticket https://github.com/getAlby/meta/issues/230

To allow web apps to call other functionality on their connector which the WebLN API does not cover explicitly
the idea is to extend WebLN with a generic "request" method.

### Describe the solution

The generic method takes the two arguments ("method: string", "params?: Record<string, any>").

#### Example

```TS
await webln.enable();
const channels = await webln.request("listChannels", {channelId: string, otherKey: string}); 
```

See similar Pull Requests:
- https://github.com/getAlby/lightning-browser-extension/pull/1629
- https://github.com/getAlby/lightning-browser-extension/pull/1694

### Describe alternatives

See more information in the meta ticket:
- https://github.com/getAlby/meta/issues/230

### Are you working on this?

Yes

**Comment by bumi** [comment]
https://replit.com/@bumi17/webln-channels-demo
