### ISSUE TITLE
🧪 Explore Lightning Node Management requirements

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1717]
Generic connectors open up a whole lot of new use cases. Let's explore what requirements Lightning node management apps have and what WebLN functions we would need to provide in order for them to work as clientside apps.
 
 - Thunderhub
 - RTL
 - LNDG
 - Pool
 - amboss.space
 - lnrouter.app
 - lnnodeinsight.com

**Comment by MoritzKa** [comment]
Do you need help here?
We have contact to all of them. Shall I reach out to lnrouter.app and lnnodeinsight first?

**Comment by MoritzKa** [comment]
looks like a suitable use case: https://cold-sats.github.io/ln-charts/add-data

**Comment by reneaaron** [comment]
+1 from the concept side, however I think those charts rely on output from [BOS](https://github.com/alexbosworth/balanceofsatoshis) which would not be available via `webln`

**Comment by MoritzKa** [comment]
I will just drop it here to not forget it. I have to check it: https://lightningnetwork-analytics.com/

**Comment by reneaaron** [comment]
Resources: 
 - https://www.youtube.com/watch?v=Pux_lXcPoso
 - https://www.figma.com/file/I3cHUgMcAT7vFio8jyhIeT/LNDg-Library?node-id=3843%3A60484
