### ISSUE TITLE
[Feature] Alby page to see my Nostr profile and option to leave tips

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1785]
### Feature description

Now that Nostr is integrated on Alby, I think should have a button on Alby settings to see my Nostr profile.
What I mean by Nostr profile is something like linktree service or https://vida.page/koreacomk
For now on Alby I just can see my private key and I need to connect on any other Nostr service to view and edit my Nostr profile.

### Describe the solution

You could add an option to see the Nostr profile fields on the Alby page of the users: https://getalby.com/p/leo
So will be the first service like linktree or vidapage but with interoperability, because will use Nostr protocol

### Describe alternatives

For now on Alby I just can see my private key and I need to connect on any other Nostr service to view and edit my Nostr profile.

**Comment by stackingsaunter** [comment]
This is not related to browser extension so I am closing it, but I [added it to our feedback board](https://feedback.getalby.com/-request-a-feature/posts/add-possibility-to-include-npub-nip-to-alby-page) (which we plan to revive, promote and use extensively from now!)
