### ISSUE TITLE
No tipping possible when visiting a YouTube channel with new handles 

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1790]
### Describe the bug

YouTube introduced new URL with user handles. 
That might stop Alby from automatically detecting the lightning address and showing the publisher profile in the extension. 
The browser extension icon no longer turns blue when visiting a YouTube channel whenever the new handles are used as part of the URL.

### Steps To Reproduce

Alby recognizes [http://youtube.com/c/clubmikev](https://t.co/bFw0ajgxCC), but not [http://youtube.com/@clubmikev](https://t.co/8wuKOkdwkS).

### Expected behavior

The icon turns blue and Alby shows the YouTube publisher profile.

### Alby information

the latest version of Alby installed through the browser store. 

### Device information

Chrome

**Comment by murdawkmedia** [comment]
I think I have this same issue. 

The YouTube page in question is:
https://www.youtube.com/@murdawkmedia/about
or
https://www.youtube.com/murdawkmedia/about

The @getalby.com address is located in the 'about' section.
