### ISSUE TITLE
Prevent onboarding process from being executed multiple times

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#180]
Currently we do not check if a user already has setup an account or a password when accessing the welcome page. 
To prevent a user from inconsistent config data (e.g. by setting different passwords) we should prevent accessing the welcome page if a user is already onboarded.

**Comment by secondl1ght** [comment]
I could give this a try, could you point me to where the data is stored for if a user has already been onboarded? Is there a boolean value somewhere?

**Comment by bumi** [comment]
we have this status action: https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/actions/setup/status.js
that can be used like it is here: https://github.com/getAlby/lightning-browser-extension/blob/00c03bf895a295b90813de1b68d73f05959ea4f0/src/app/context/AuthContext.tsx#L31-L42

so if the status is completed we should redirect the user to the option page.

**Comment by secondl1ght** [comment]
Sounds like we are still waiting on some details from #375 before continuing on this?

**Comment by bumi** [comment]
seems they are a bit independent. here we should only check that we redirect to the options page if an account is already setup (if setup is configured)

**Comment by stefanwuest** [comment]
@bumi @secondl1ght 
I grabbed this as my first issue, since it's quite an easy one. Hope that's okay. One thing that I was wondering is whether people used re-doing the onboarding process as a way to change their node for example. I guess that wouldn't be possible anymore with the redirect.

**Comment by bumi** [comment]
thanks! 
users can change accounts from the options. 
They must not go through the onboarding again, because that would could change the password and thus decrypting account data would fail.
