### ISSUE TITLE
Allow users to see and delete allowance permissions

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1820]
### Feature description

Every host/allowance now can have multiple permissions.
Right now the user does not see which permission they granted to a website and there is no way to delete them.

### Describe the solution

On the allowance edit modal we can list all granted permissions and provide an option to delete those

<img width="710" alt="image" src="https://user-images.githubusercontent.com/318/205567439-1af3bf05-de37-4552-979c-c6279392412b.png">

we already have the delete action: https://github.com/getAlby/lightning-browser-extension/pull/1819/files#diff-74471d8257a5d4aee886e495b6cf7f047385054e8a3114cc2fedcc5ae1315175

We might still need to add an action to list all permissions for an allowance/host. 

### Are you working on this?

None

**Comment by reneaaron** [comment]
Summary of the discussion we just had: 
 - delete permissions at next update (migration) - delete non nostr permissions (CLN & LND)
 - add a new field to permissions (connector)
