### ISSUE TITLE
Docs: Tech stack details

### ISSUE THREAD

**Issue by hardiktheprogrammer** [getAlby/lightning-browser-extension#1829]
### Feature description

Give which tech stack you use in this project for  beginner contributor 

### Describe the solution

Give Tech Stack you use in this 
for example react .js , typescript , like this 

### Are you working on this?

None

**Comment by escapedcat** [comment]
We use react and tailwind and that we use the TS can be seen here:
![image](https://user-images.githubusercontent.com/1016218/206137492-4005d563-1c6c-40f4-91a7-5592bd0231b6.png)

What exacty we use can be seen here: https://github.com/getAlby/lightning-browser-extension/blob/master/package.json
I assume that even a beginner contributor can know `package.json`, what do you think?

**Comment by hardiktheprogrammer** [comment]
thankss
