### ISSUE TITLE
Update account wizzard to support CLN installation ons Umbrel, RaspiBlitz, etc.

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1835]
### Feature description

Some of the personal nodes also allow users to use CLN instead of LND. Our wizzard still assumes LND installations. 

We should allow the user to choose CLN there, too.

### Describe the solution

Initially we can link to the connect CLN interface, e.g. 

```
Using Core Lightning on your XXX? Do XYZ to get your details and use the "Core Lightning Connector". 
```

ToDos:

* Gather information where the user finds the CLN details
* Add the link to the UI or adjust the interface for CLN

**Comment by reneaaron** [comment]
This has been implemented a long time ago :+1:
