### ISSUE TITLE
[Feature] Add pagination on Your ⚡️ Websites list

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1839]
### Feature description

I have a long list of sites on Your ⚡️ Websites and I see take some time to load.

### Describe the solution

Show just 20 entries and add pagination

**Comment by ShivamJhaa** [comment]
@escapedcat  can I work on this issue?

**Comment by escapedcat** [comment]
Let's make sure we first define what we want here exactly.
I.e. thinking about:

- URL support (pagination reflected in URL)
- design
- ...what else?

@reneaaron @rolznz @jakubszwedo

**Comment by reneaaron** [comment]
Interesting. Thanks for this report @bitcoinuser. I also use Alby on quite some websites but never noticed any loading delays in there, even with a quite long list of websites 🤔

May I ask how many websites you have in there? Could you add a video of how that looks for you?

**Comment by bitcoinuser** [comment]
> Interesting. Thanks for this report @bitcoinuser. I also use Alby on quite some websites but never noticed any loading delays in there, even with a quite long list of websites thinking
> 
> May I ask how many websites you have in there? Could you add a video of how that looks for you?

Yes, see the video that is a little slow. Shouldn't even show the button discover sites... Maybe a loading icon would fit better.


https://user-images.githubusercontent.com/1178856/224490603-fdeccab2-0d0b-4964-96a7-315250903af4.mp4

On transaction window I see it's slow too: https://github.com/getAlby/lightning-browser-extension/issues/2197

**Comment by bitcoinuser** [comment]
> > Interesting. Thanks for this report @bitcoinuser. I also use Alby on quite some websites but never noticed any loading delays in there, even with a quite long list of websites thinking
> > May I ask how many websites you have in there? Could you add a video of how that looks for you?
> 
> Yes, see the video that is a little slow. Shouldn't even show the button discover sites... Maybe a loading icon would fit better. Obs. On transaction window I see it's slow too: #2197

As you can see in the video, even show info like: No websites yet. But then disappear and show the sites. So I think should show a loading icon.

**Comment by reneaaron** [comment]
Closing as we've added a loading indicator on this site. :heavy_check_mark:
