### ISSUE TITLE
[Feature] Add closeable tab actions on "Websites" screen

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1849]
### Feature description

- Add closable boxes if no "visited" site exists (should only show on new install)
   ![image](https://user-images.githubusercontent.com/1016218/206694806-8e1e8da6-65e2-4c28-a331-c44408d50ef7.png)

### Describe the solution

- this area (Headline, text, boxes) only shows up if list of websites is empty
- boxes can be closed
- the exact content of the boxes is TBD
    - topup-box: we only show one button to a guide for now 
       (as added here:  #1432)
    - start with basic text. icons can be added later if this is more complicated for a reason.
- the "lightning-address" box will NOT be added for now
- be aware of "out of scope" items, see #1845

**Comment by jamescharlesworth** [comment]
Can I work on this?
