### ISSUE TITLE
[Feature] Split "Your ⚡️ Websites" and "Other ⚡️ Websites" into "Discover" (Other) and "Visited" (Yours)

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1850]
### Feature description

- Split "Websites" screen into 2
     ![image](https://user-images.githubusercontent.com/1016218/206696387-9019c074-0c93-4613-840e-fd3b6d372dee.png)

### Describe the solution

- update nav-items (tab and popup view)
- split content
- not sure yet how to handle the closable boxes section now (could be removed if all boxes closed i.e.? needs to be discussed maybe)

**Comment by rolznz** [comment]
@escapedcat 

> not sure yet how to handle the closable boxes section now (could be removed if all boxes closed i.e.? needs to be discussed maybe)

I think that is a good idea. Would it be better to add these cards just on the discover view? And maybe not show the "visited" tab if you have no visited sites? Alternatively, it could have an empty state which says something like "You haven't used Alby on any sites yet. Click here to discover sites where you can use Alby"

**Comment by escapedcat** [comment]
> Alternatively, it could have an empty state which says something like "You haven't used Alby on any sites yet. Click here to discover sites where you can use Alby"

I prefer this approach to keep the navigation bar simple and clear. Wdyt @reneaaron ?

**Comment by reneaaron** [comment]
+1 for having an empty state there (instead of hiding navigation items)
