### ISSUE TITLE
[Feature] When the user click on Incoming tab take some seconds to load data. Should show instantly.

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1854]
### Feature description

For now, when the user click on Incoming tab take some seconds to load the transactions. I think Alby could cache the data of incoming transactions, so show instantly to the user when clicking on incoming tab. And a loading icon to the user know that Alby is still looking for new transactions.

### Describe the solution

I think Alby could cache the data of incoming transactions, so show instantly to the user when clicking on incoming tab. And a loading icon to the user know that Alby is still looking for new transactions.

### Are you working on this?

No

**Comment by bitcoinuser** [comment]
Related issues: 

https://github.com/getAlby/lightning-browser-extension/issues/1536
https://github.com/getAlby/lightning-browser-extension/issues/1674

**Comment by escapedcat** [comment]
We could:

1. Load incoming txs as soon as popup is being opened and cache
2. Show cached txs whn "incoming" tab is clicked, load current txs again, update view and cache these

* if account is being switched we need to behave like the popup is opened for the first time

**Comment by qqqzhch** [comment]
The incoming data is a bit of slow. Although my incoming data does not contain any data, I will be familiar with this query logic
