### ISSUE TITLE
Focus the prompt

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1856]
### Feature description

Sometimes it happens that the prompt looses focus and is hidden behind the actual browser window.

Ideally the prompt is always on top - or gets focus back after some time. 

### Describe the solution

Seems we can do `browser.window.update()` with `focused` and/or `drawAttention` in [here](https://github.com/getAlby/lightning-browser-extension/blob/master/src/common/lib/utils.ts#L77). Maybe with a setInterval?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/update

### Are you working on this?

None

**Comment by reneaaron** [comment]
Testing showed that new prompts are always focused already. 

Mentioned options like `focused` and `drawAttention` seem to only be relevant if you re-use existing windows. AFAIK we always open a new prompt for any action.

**Comment by bumi** [comment]
yeah, new prompts are always focused, but if the user looses it then it's hidden. 
To avoid this (as it seems it was reported) we can periodically put it in focus - e.g. using a setInterval and call it every 2 seconds or such.
