### ISSUE TITLE
[BUG] Unable to login to getalby.com dashboard when a non-alby hosted account is selected in the extension

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#1889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I go to getalby.com and try to login to the alby dashboard using my browser that has the alby extension, it logs in with the extension and redirects me to https://getalby.com/user/new_with_lnurl 

If I click on the login button, I immediately get a toast popup from the extension that says it has logged in, and redirects me back to the above link. I'm still logged out on the dashboard though and cannot access it.

Using a different browser that doesn't have the extension installed I can login to the dashboard fine.

### Steps To Reproduce

1. If already logged into the getalby.com dashboard, log out.
2. Install alby extension and signup
3. Add a second account that is not an Alby hosted account and make sure that one is selected
4. Go to [getalby.com/login](https://getalby.com/login)

### Expected behavior

- A non-alby account should NOT try to login (and should not have a success notification)
- Notify the user that their current account is not an alby account and allow them to switch accounts, or if they don't have an alby hosted account, then direct them sign up.

### Alby information

Alby version 1.20.1 with an alby account installed.

### Device information

Windows 11 Chrome (latest)

### Are you working on this?

None

**Comment by escapedcat** [comment]
Should this issue be moved to the website repo?

**Comment by bumi** [comment]
the issue here is that we do not save which account was used to login (lnurl-auth) into a website. 
on getalby.com we then prompt the user the create a new account - which is confusing because people have already an account but connected to another account in the extension.

**Comment by rolznz** [comment]
Would it be possible for the extension to ask you to pick which account to log in as? (And possibly have a checkbox to remember for future visits). Then in the extension settings -> websites -> getAlby.com you can edit or remove the default account.

I noticed getAlby.com does not show in my list of visited websites though, even though I logged in using the extension.

**Comment by escapedcat** [comment]
> I noticed getAlby.com does not show in my list of visited websites though, even though I logged in using the extension.

You don't get this entry?:  
![image](https://user-images.githubusercontent.com/1016218/208932248-42fb1c3e-8dfd-4e1d-97b7-2bf23f2de85b.png)

**Comment by rolznz** [comment]
> > I noticed getAlby.com does not show in my list of visited websites though, even though I logged in using the extension.
> 
> You don't get this entry?: ![image](https://user-images.githubusercontent.com/1016218/208932248-42fb1c3e-8dfd-4e1d-97b7-2bf23f2de85b.png)

@escapedcat oh I see, it is way down the list. Maybe the recently visited sites should be at the top?

**Comment by escapedcat** [comment]
> Maybe the recently visited sites should be at the top?

I guess that woudl make sense :)  
Not sure what the current order is tbh

**Comment by reneaaron** [comment]
@bumi Another reason to think about scoping allowances to accounts. 

+1 for sorting the list of websites (if easily possible)

**Comment by escapedcat** [comment]
> +1 for sorting the list of websites (if easily possible)

Current sorting is pretty random.  
Easiest would be by "created" (via `id`) or "A-Z" I guess.

**Comment by bumi** [comment]
@reneaaron this is scoping permissions to the account, not necessarily the allowance.

**Comment by reneaaron** [comment]
I know, I just said it's another reason to think about that. 

I feel like the account should be the root element of everything (except maybe for global settings). Allowances shouldn't be shared across accounts either...

**Comment by reneaaron** [comment]
Lightning Login is currently deprecated for the login, so I think this is no longer a problem.
