### ISSUE TITLE
[BUG] Update Geyser Logo

### ISSUE THREAD

**Issue by MickMorucci** [getAlby/lightning-browser-extension#1898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Current logo on Alby site:
<img width="1132" alt="Screen Shot 2022-12-20 at 10 36 45" src="https://user-images.githubusercontent.com/25527115/208647890-a89d8b3b-6af9-4919-ae10-a2da135ba136.png">

Geyser Logo has updated, please update to following:
<img width="539" alt="xxx" src="https://user-images.githubusercontent.com/25527115/208648029-2efe2a5e-f788-4b06-8918-582f7cf93cad.png">

### Steps To Reproduce

1. visit websites
2. scroll to the bottom to 'other websites'
3. see old Geyser logo

### Expected behavior

Geyser logo should be updated

### Alby information

n/a

### Are you working on this?

None

**Comment by bumi** [comment]
ping @MoritzKa can you do this?

**Comment by MoritzKa** [comment]
Done.
