### ISSUE TITLE
"Send" header: align back arrow with content and new header

### ISSUE THREAD

**Issue by jankoegel** [getAlby/lightning-browser-extension#1911]
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/100707419/209169516-51358b4d-8538-4a15-b211-e18dd8e83ad1.png">
+ move "back" arrow (top left on screenshot) further to the right, aligned with the wallet select dropdown above it (blurred out in the screenshot)

**Comment by reneaaron** [comment]
FYI: I've changed that in #1955
