### ISSUE TITLE
Update storybook screens

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#192]
Currently the "screens" in the storybooks are outdated: https://lbe-stories.netlify.app/?path=/story/screens-onboard--intro
Those need to be updated to reflect the current state of the major screen states.

**Comment by RajshreeVats** [comment]
new to open source. can I be assigned to this issue?

**Comment by secondl1ght** [comment]
If this issue is still up for grabs I can give it a try!

**Comment by bumi** [comment]
👍

**Comment by bumi** [comment]
@johnsBeharry how valuable is the storybook? it seems to me that it is hard to keep it up to date?
