### ISSUE TITLE
[Feature] Receive tab should have a copy lightning address button

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#1947]
### Feature description

Currently in the receive tab you can only create invoices. It would be great to be able to copy your lightning address so that people can send you multiple payments. 

![image](https://user-images.githubusercontent.com/33993199/211130567-52778d0f-fac7-4d20-bc36-4b12386aaf1a.png)

### Describe the solution

Maybe add a new field similar to how the getalby dashboard does it, and ask them to create a lightning address if they don't have one. Also see how this fits with https://github.com/getAlby/lightning-browser-extension/issues/1560

![image](https://user-images.githubusercontent.com/33993199/211130590-626a2cc6-0f84-46ef-b257-d5134ea0a157.png)

### Are you working on this?

None

**Comment by bumi** [comment]
keep in mind that most connectors do not have/know about a lightning address. This is specific to the Alby account and the extension currently does not differentiate between accounts (they act all the same)

**Comment by rolznz** [comment]
I think it would be cool to have additional features like this for the alby wallet, and allow users to provide their own lightning address as a setting for other accounts.

It would increase complexity but it provides a better UX IMO.

**Comment by reneaaron** [comment]
I like the idea too, I think if we strive for generic implementations (not checking for Alby specificly, but instead having e.g. `connector.getLightningAddress()` APIs) the additional complexity should be manageable.

**Comment by bumi** [comment]
will this really make such a difference? 
adding something manually sounds a bit strange. 
Maybe we can rethink what data we store for an account - we need to have something abstract there that is universal. 
and then we see how we can get that data?

**Comment by rolznz** [comment]
For some more context, I asked my friend to install the extension and then he asked me to send him some sats. He could have created an invoice but I wanted to be able to send him sats multiple times. Also, I don't think it's so obvious that the receive amount for an invoice is optional. (He wanted to copy his address because he didn't know how much I would send him)

I guess this could be expanded for other things too right, like being able to copy some other data (like a node public key for keysend)?

**Comment by HARI-124** [comment]
Is this issue open to work?

**Comment by rolznz** [comment]
I think it should be ok to work on, except we need some design guidance. @stackingsaunter could you review this ticket?

Linking this ticket also to https://github.com/getAlby/lightning-browser-extension/issues/1947

**Comment by stackingsaunter** [comment]
@rolznz @reneaaron so I guess we could display LN addresses associated with Alby Accounts, however not all Alby Accounts have LN addresses. Is will that be an issue?

Some initial design. It's a bit dense, but at least no scrolling
<img width="687" alt="Screenshot 2023-04-18 at 22 09 50" src="https://user-images.githubusercontent.com/68239231/232893642-0a6796eb-3a4e-44d0-bb6e-83e3bd6b7f19.png">

**Comment by reneaaron** [comment]
> @rolznz @reneaaron so I guess we could display LN addresses associated with Alby Accounts, however not all Alby Accounts have LN addresses. Is will that be an issue?

I don't think so, accounts with no lightning address will just not see this section. 

This feature depends on #2240 (tab component) and #1956 (API for lightning address). Might make sense to wait for those PRs to be merged before starting with this one.

**Comment by reneaaron** [comment]
We now have this button! :partying_face:
