### ISSUE TITLE
JSON in signup error message

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1967]
When entering the wrong password for your account you will see a JSON string at the end of the error message. 

![image](https://user-images.githubusercontent.com/100827540/211926725-75020286-feb1-464a-ad8d-b6850617f54a.png)

Also the error message probably is wrong (cc @bumi) because we allow both the lightning address and the email to login, right?

**Comment by jankoegel** [comment]
@reneaaron the message is as intended. We assume that `@getalby.com` addresses are lightning addresses, which we don't allow during signup. I haven't seen code in the Rails app that allows signing up with a `@getalby.com` lightning address.

Here's the check that produces the error message:
https://github.com/getAlby/getalby.com/blob/e60326d137d6f14851ee2f6650493e737f1ecdaa/app/models/user.rb#L184-L190

There's special handling for `@getalby.com` `STAFF_EMAILS`, which actually are email addresses. There we have a different email address for you. Feel free to change/extend if really necessary:
https://github.com/getAlby/getalby.com/blob/e60326d137d6f14851ee2f6650493e737f1ecdaa/config/initializers/constants.rb#L16

**Comment by jankoegel** [comment]
@reneaaron ok, just discovered that you can log in with a lightning address via the API here:
https://github.com/getAlby/getalby.com/blob/master/app/controllers/api/users_controller.rb#L36

Tried writing a fix here: https://github.com/getAlby/getalby.com/pull/332
