### ISSUE TITLE
[BUG] nostr event is invalid when passed to nostr.signEvent

### ISSUE THREAD

**Issue by ChristianChiarulli** [getAlby/lightning-browser-extension#1974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm wondering why the following event is invalid when passed to `nostr.signEvent`

```
{
  content: "asdf"
  ​created_at: 1673689168
  kind: 1
  pubkey: "220522c2c32b3bf29006b275e224b285d64bb19f79bda906991bcb3861e18cb4"
  tags: Array [ "syntax", "javascript" ]
}
```

### Screenshots [optional]

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/29136904/212467026-29094d56-83d4-44af-acdb-a58655caf185.png">

### Steps To Reproduce

pass the previous event to `nostr.signEvent`, get invalid response

### Expected behavior

I would expect this event to work

### Alby information

installed through browser

### Device information

- firefox
- brave

### Are you working on this?

None

**Comment by bumi** [comment]
I think this event misses an ID? 

but I see that this validation recently has been removed in `nostr-tools` https://github.com/nbd-wtf/nostr-tools/commit/4b36848b2d1d377e4832d9f66ecaa489240e2ba2

cc @reneaaron

**Comment by ChristianChiarulli** [comment]
I was trying to use nostr-tools to get the id with: `event.id = getEventHash(event);` but there is an incompatibility with how nostr-tools defines the tag array type leading to a serialization error.

```
Uncaught (in promise) Error: can't serialize event with wrong or missing properties
```

**Comment by bumi** [comment]
seems there was an update there but where do you get that serialize error? from nostr-tools?

**Comment by ChristianChiarulli** [comment]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/29136904/212490790-4fd9f4fa-665e-4906-b6df-8af96add2953.png">
yes

**Comment by ChristianChiarulli** [comment]
Also I don't think your object matches the validation logic for tags. The validation logic expects: `string[][]`

**Comment by bumi** [comment]
can you test this again. We now added the option that Alby automatically sets the ID when the id is not present in the event.
