### ISSUE TITLE
Add a Nostr section to the "Discover" page

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1978]
### Feature description

Add a Nostr section to the "Discover" page in addition to "Gaming", "Trading" etc. 

### Describe the solution

same as other sections
List Nostr web clients with lightning integration: 
https://astral.ninja/
https://snort.social/

### Are you working on this?

None

**Comment by reneaaron** [comment]
I'll add the images to our space later. 

 - Astral https://raw.githubusercontent.com/monlovesmango/astral/master/public/icons/favicon-256x256.png
 - Yosup https://yosup.app/icon/logo-inverted.svg
 - Hamstr.to (inline svg)
 - snort.social https://snort.social/nostrich_256.png
