### ISSUE TITLE
[Feature] Avatars for accounts

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1987]
### Feature description

Currently we completely miss account avatars in the application. Some reasons I'd like to add them:
 - Improve the recognizability of a specific when using Alby with multiple connectors (e.g. in the account dropdown)
 - Answer the question "do I use the right account" when you do payments
 - Making the experience feel more "social"

![image](https://user-images.githubusercontent.com/100827540/212700411-8f10ff8f-4889-44ab-96c0-81b7a0d6a575.png)

Adding [identicons](https://www.npmjs.com/package/react-identicons) could be a first step into that direction:

In future we could potentially open this up to connectors providing their own avatars or even allowing users to set their own avatar in the extension. 

### Describe the solution

Identicons should be added to the following components: 
 - `AccountMenu`
 - `Accounts` overview (introduced with #1964)
 - `Account` detail (introduced with #1964)

The entropy for the identicons should come from something that doesn't change but is specific to every account, possibly the `accountId` would make sense here.

**Comment by lujakob** [comment]
I'll have a look at this.

**Comment by lujakob** [comment]
@reneaaron should we merge this PR as is and add a follow up PR to add Avatar to  accounts and account once the two dependencies are merged?
