### ISSUE TITLE
[BUG] Buttons not aligned in Portuguese language

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Add new account, the buttons are not aligned in Portuguese language. In English is ok.

### Screenshots [optional]

![photo_2023-01-17_13-52-34](https://user-images.githubusercontent.com/1178856/212962074-ecf831d5-645f-4f04-ade9-eff00a3713e6.jpg)

### Steps To Reproduce

1- Change the language to Portuguese Brazilian
2- Go to Add new account

### Expected behavior

The buttons from the two columns aligned.

### Alby information

Alby: 1.24

### Are you working on this?

None

**Comment by rolznz** [comment]
How many lines is the description in Portuguese? are you able to shorten the description so it fits on just two lines like in English?

![image](https://user-images.githubusercontent.com/33993199/213089702-778975e7-8efe-40ee-810c-2609a1c9a514.png)

**Comment by bitcoinuser** [comment]
> How many lines is the description in Portuguese? are you able to shorten the description so it fits on just two lines like in English?
> 
> ![image](https://user-images.githubusercontent.com/33993199/213089702-778975e7-8efe-40ee-810c-2609a1c9a514.png)

Same two lines. Please switch to Portuguese Brazilian, so you can see it. Thanks.

**Comment by escapedcat** [comment]
fyi
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/1016218/213160836-ae1134e2-39b5-4d43-8d96-a0644da9108c.png">

**Comment by bitcoinuser** [comment]
> fyi, left is only one line, might be the issue. Maybe there's a better way to solve this with i.e. min-height <img alt="image" width="1317" src="https://user-images.githubusercontent.com/1016218/213160836-ae1134e2-39b5-4d43-8d96-a0644da9108c.png">

Ha ok, sorry. I would prefer keep the description as it is and would be better if there's another way to solve it. Thanks.

**Comment by lujakob** [comment]
I also think this a simple min-height for the description should solve it. Anyone does it or can I create a PR?

**Comment by rolznz** [comment]
@lujakob if you are happy to create a PR that would be great. Thank you!
