### ISSUE TITLE
[BUG] Lightning Address Description Hash

### ISSUE THREAD

**Issue by aaronbarnardsound** [getAlby/lightning-browser-extension#1994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am having some issues with paying to an Alby lightning address but not with other implementations of Lightning Addresses (BTC Pay Server, ZBD, Lighting TXBot) with CLN. 

The issue is that the `description_hash` in the created invoice is a hash of the stringified metadata object, but the string contains spaces between the elements in the array:

`"[[\"text/identifier\", \"user@getalby.com\"], [\"text/plain\", \"Sats for user\"]]"`

Rather than:

`"[[\"text/identifier\",\"user@getalby.com\"],[\"text/plain\",\"Sats for user\"]]"`

CLN expects the `description` parameter to be the raw object not the stringified version. So when the metadata object is sent over the wire to a CLN node it needs to be stringified first, then parsed on the other side by Commando. Then CLN will  finally convert it back to a string which has all of the spaces removed automatically and then the hashes do not match, making the invoice not payable.

Apologies if this is the wrong repo to create this issue on. Please let me know if I need to create this on one of the other Alby repos!

### Steps To Reproduce

You can reproduce this by trying to pay to a Alby Lightning Address via Commando, so you could use the commando connector within Alby I believe. I have been using [Clams](https://clams.tech) for testing.

### Expected behavior

It would be great if Alby could match other Lightning Address implementations and ensure that the `description_hash` is a hash of the stringified LNURL metadata with all spaces removed.

### Alby information

This is not specific to the Alby extension version

### Are you working on this?

No

**Comment by bumi** [comment]
Thanks for debugging this!! 
So CLN actually is aware of the JSON and does the serialization? We need to get CLN to implement that a description_hash can be passed. IMO CLN should not do the hashing. 

I review that we don't break anything and then change how we serialize that JSON to remove the space.

we should add this note to the LUD 06 description.

**Comment by aaronbarnardsound** [comment]
I am not exactly sure of the internal CLN process, I am somewhat assuming what what is happening under the hood based on what I am observing. I think it is fair that they validate the `description_hash` by hashing the passed in `description` parameter to ensure the payer is paying what they think they are paying.

> I review that we don't break anything and then change how we serialize that JSON to remove the space.
Yeah I was trying to think through if this could break other implementations or not be backwards compatible and I think it should be fine as this is the way that all other implementations work, so wallets must be handling the case of no spaces in the serialised JSON string anyways.

> we should add this note to the LUD 06 description.
Yeah I agree, this should definitely be in the spec.

**Comment by bumi** [comment]
@aaronbarnardsound 
you try to pay to a LN address? Why do you even need to do something with the description _hash on the node? don't you get an bolt11 invoice via HTTP, then you can validate the description_hash (invoice description_hash == hash(metadata) ) and pay the bolt11 through CLN. 

what am I missing?

**Comment by aaronbarnardsound** [comment]
@bumi yep we get a bolt11 to pay via http and then instruct CoreLN to pay it using the [pay](https://lightning.readthedocs.io/lightning-pay.7.html) RPC method. From the docs:

> description is only required for bolt11 invoices which do not contain a description themselves, but contain a description hash: in this case description is required. description is then checked against the hash inside the invoice before it will be paid.

We do perform an internal check that checks the hashed metadata string against the `description_hash` in the returned invoice and it all checks out client side. The problem is that we need to pass the `metadata` to CLN via the `description` parameter as a _raw object_ (not a string, so in the case of `metadata` an array) and then CLN will then stringify and hash and check against the `description_hash` which fails due to the spaces being removed before hashing. This makes the invoice unpayable with CLN.

Let me know if that clarifies!

**Comment by bumi** [comment]
sorry I still don't fully understand (it might be too late here :D)
why do you need to pass the metadata to CLN? which CLN call do you make?

**Comment by aaronbarnardsound** [comment]
No worries! We are using the [`pay`](https://lightning.readthedocs.io/lightning-pay.7.html) RPC method to pay the payment request. That method requires that a `description` parameter is also passed in if the payment request has a `description_hash`. 

From the docs for the `pay` method:
> description is only required for bolt11 invoices which do not contain a description themselves, but contain a description hash: in this case description is required. description is then checked against the hash inside the invoice before it will be paid.

This is required so that CoreLN can validate that the hash of the `description` matches the `description_hash`.

**Comment by bumi** [comment]
oohh, ok...sorry did not think of that CLN requirement. 
The issue is that when I make this change we break things for some users who have a static copy of our lnurl-pay response on their own domain. (like: https://nvk.org/alby-lnurlp )
I will try to give a bit of notice before we deploy the change.

**Comment by aaronbarnardsound** [comment]
Ah damn! Yeah I was hoping it would not be a breaking change. Is there a way that you could make it backwards compatible for the existing static lnurl pay links but make the change for all new ones?

**Comment by bumi** [comment]
@aaronbarnardsound deployed the update. can you check if this is now correct? thanks

**Comment by aaronbarnardsound** [comment]
Works perfectly @bumi thanks for updating that! 🎉

**Comment by bumi** [comment]
yay!! thanks again for reporting and the test.
