### ISSUE TITLE
[BUG] Error: Lightning Payment Request must be string

### ISSUE THREAD

**Issue by dskvr** [getAlby/lightning-browser-extension#2016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting error when testing. Upon further investigation...

```
curl 'https://getalby.com/lnurlp/sandwich/callback?amount=10000'
{"status":"OK","successAction":{"tag":"message","message":"Thanks, sats received!"},"verify":"https://getalby.com/lnurlp/sandwich/verify/eWF2ZtfMfcJVCCa5cWNRXiKQ","routes":[],"pr":null}%
```

there should be an invoice on the `pr` attribute, it is `null`.

### Screenshots [optional]

![Screen Shot 2023-01-27 at 7 14 31 PM](https://user-images.githubusercontent.com/299465/215163138-4f5ad314-5eac-4df7-92b0-7c7f4a93e33b.png)

### Steps To Reproduce

1. Run `curl 'https://getalby.com/lnurlp/sandwich/callback?amount=10000'` ... Appears valid
2. Observe response. 

### Expected behavior

`pr` is not `null` 

### Alby information

- Latest
- Chrome Store

### Are you working on this?

None

**Comment by bumi** [comment]
there have been some network errors around 7pm  which might have caused this issue, can you retry?

**Comment by dskvr** [comment]
Yes, thank you. 

I then hit another error and solved it, but it's something that doesn't appear to be implemented correctly. If `metadata` value such as `[\"text/plain\", \"some description\"]` isn't set exactly to what Alby sets it as "Sats for {USERNAME}", Alby will throw an invoice error. The description should probably either be editable through getalby.com, or otherwise alby should probably respect the "text/plain" metadata type.

https://sandwich.farm/.well-known/lnurlp/bread

I'm guessing you already know this, so consider this a +1

Thanks for your help! Closing.

**Comment by bumi** [comment]
@dskvr thanks for the update. 
The metadata issue is sadly required by the LNURL spec. Wallets validate the description_hash of the invoice to check it is the hash of the metadata. this means sadly this can not easly be changed. 
We will allow this message to be configurable. 

please note using your own domain with the static changes is not a fully supported feature, yet and we have a breaking change coming up there you will have to update the JSON file in the next days again - then it should be stable and we also have a guide for that setup.

**Comment by dskvr** [comment]
Thank you, where will I be able to find this data?

**Comment by bumi** [comment]
we will release an official guide for this. 
basically you will just have to update the JSON file to match the expected metadata again once we have pushed the update. 

related: #1994

**Comment by dskvr** [comment]
@bumi It's been happening again, but this time, the problem is unclear. Nothing has changed on my end.

**Comment by bumi** [comment]
@dskvr lnurl-pay uses millisats

do: `curl 'https://getalby.com/lnurlp/sandwich/callback?amount=1000000'`

we had to update the metadata of the lnurl last week. please update your .well-known JSON file. simply download the file from https://getalby.com/.well-known/lnurlp/sandwich 
because of CLN some whitespace had to be removed. 

We announced it as much as possible on twitter, but sadly we do not have a contact list to notify users about this. 
The custom domains will be an official and documented feature and users can subscribe and get updates in the future.

(for details/reason see: #1994 )

**Comment by dskvr** [comment]
> @dskvr lnurl-pay uses millisats

Lol, gotchya, should've figured that out myself 😉
