### ISSUE TITLE
[Feature] Receive screen: add "Receive another payment" button

### ISSUE THREAD

**Issue by lujakob** [getAlby/lightning-browser-extension#2022]
### Feature description

Problem: Currently there is no way to get back to the receive payment form after having received a payment. Would't it make sense to have a button to get back to the form? Currently only navigating to another screen and back (or a page reload for the options page) makes this possible.

<img width="749" alt="Bildschirmfoto 2023-01-28 um 07 09 31" src="https://user-images.githubusercontent.com/886152/215277008-b81442e8-9127-4aa5-ac2b-ce2bd40d685e.png">

### Describe the solution

Add orange button "Receive another payment" underneath the QR Code "Payment received" that resets the "paid" state and show the form again.

The solution is simple and I could implement it.

### Describe alternatives

Having a less prominent text link with label "Receive another payment" or "Go back" underneath the QR code?

### Are you working on this?

None

**Comment by manavdesai27** [comment]
Is there any way to get a fake payment for development purposes?

**Comment by manavdesai27** [comment]
Okay thanks!

**Comment by manavdesai27** [comment]
Okay one more thing. How do I scan this qr code? Because if I open two windows, and keep one window for receive and other for sending, one of the windows closes the alby ui, as I focus on another window.

**Comment by manavdesai27** [comment]
I would like to work on this issue.
