### ISSUE TITLE
Filter connector options for non-custodial accounts

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#2026]
### Feature description

Currently all connectors are listed on the same screen. 
To make people aware which ones are non-custodial we want to give them a filter option. 

### Describe the solution

This can be a simple filter check-box in the text here. 
which then hides the custodial ones. 

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/318/215451879-57c1fda6-c04e-47b1-926f-155fc8d2c1bc.png">

should be hidden: 
BlueWallet, LNDHub, LNBits, Bitcoin Jungle, Bitcoin Beach, Kollider

### Describe alternatives

maybe the word "custodial" is not perfect there and a better word is "full lightning nodes"

### Are you working on this?

None

**Comment by bitcoinuser** [comment]
I think wording is very important. I would like a more detailed explanation like this: https://feedback.getalby.com/-feature-request/posts/improve-add-account-window

**Comment by bitcoinuser** [comment]
I think instead of filters, when user click Connect button, on next window should ask what type of wallet/account he would like to connect, and with detail explanations, so the user choose the type and then the wallets/accounts are listed.

**Comment by bitcoinuser** [comment]
Today we have even wallets that support fiat USD, like Kollider, so maybe even give the knowledge that these wallets exist. The way works now, users that don't know that Kollider exist, will never know that they can have an account denominated in USD.

**Comment by ShivamJhaa** [comment]
@bumi I would like to work on this, can you please assign me?
Thanks!

**Comment by reneaaron** [comment]
I think we first need to clarify what we want to achieve here before we start coding. 

Wording is very important here, I agree. And also it's not quite clear how to categorize them clearly: You can also use LNBits or LNDHub (via BTCPay Server LNBank plugin or self-hosted) non-custodially for instance. 

I am wondering what problem we are trying to solve here, really? Is it really a problem that users looking for non-custodial options don't know which connector to choose? Is it then really helpful to filter by this option? The process setting up & run your own node is not something that you will do while setting up your Alby extension I guess. 

One category that could be separated quite clearly is the "home nodes" though. (so specific connectors for umbrel, citadel, start9, etc).

**Comment by bitcoinuser** [comment]
Thinking better, I like the idea of Filters. Could have filter like: Custodial, Non custodial, Fiat support like USD, EUR...
Filters like this:

![photo_2023-02-04_11-13-25](https://user-images.githubusercontent.com/1178856/216772430-23839826-8501-42cb-9629-690c709f280f.jpg)

**Comment by bitcoinuser** [comment]
And I think on each card should show tags of what kind of account is what supports, Like the Kollider card could have: USD, EUR, SATS, Custodial

**Comment by stackingsaunter** [comment]
We can do such filters, but is there really a need for this? I second Rene thoughts - people using connectors will rather know which one they have and I doubt there's a need for us to distinguish it here. It's not like they are installing those because of Alby. Also I think LNbits can be both custodial and non-custodial?
