### ISSUE TITLE
"All transactions" tab

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#2027]
### Feature description

Currently we show the transactions only per website and have a website list.
People have been asking to see all the transactions. 

### Describe the solution

Add an additional page "Transactions" in the top navigation next to "Websites" and show a chronological (latest fist) list of all transactions there. 

The UI and components can be reused from the website screen

### Are you working on this?

None

**Comment by lujakob** [comment]
@bumi I'm interested in working on this? Can you assig it to me?

**Comment by lujakob** [comment]
@bumi it would look something like this? I reused the `<TransactionsTable>` from the publisher detail page. Any comments/suggestions on this?

<img width="1071" alt="Bildschirmfoto 2023-01-30 um 22 16 00" src="https://user-images.githubusercontent.com/886152/215661635-f6817627-245c-4377-8008-a80d4dd21bdd.png">

**Comment by lujakob** [comment]
@bumi I get the data from https://github.com/lujakob/lightning-browser-extension/blob/master/src/extension/background-script/actions/payments/all.ts#L5-L5

That's correct?

**Comment by lujakob** [comment]
@bumi for the translations I created keys and translations in the `src/i18n/locales/en/translation.json` - how are translations handled in general. Is there an external tool and I only provide the keys? Or how is it done?

**Comment by reneaaron** [comment]
@lujakob Usually we just add the English keys & terms, they are then synced to Weblate where they are being translated.

**Comment by bumi** [comment]
@lujakob yes, correct. that should work. at some point we need some pagination there, but I think it's ok for now.

**Comment by lujakob** [comment]
> @lujakob yes, correct. that should work. at some point we need some pagination there, but I think it's ok for now.

I also thought about pagination, considering adding it in a further step. I tested now with 1000 payments in IndexDB and it loads quite fast on screen change, as I expected to. So I think it is ok for now to implement without Pagination.
