### ISSUE TITLE
[Feature] Enable performance improved getFormattedFiat for transforming list of payments

### ISSUE THREAD

**Issue by lujakob** [getAlby/lightning-browser-extension#2031]
### Feature description

The SettingsContext getFormattedFiat function is used to convert sats into fiat in several places of the app. The rate is fetched through messaging to the background script where an HTTP request is made. This request is cached for 10 minutes.

I found three places in the app, where this async getFormattedFiat function is called in a loop, traversing over payments. Even though the final HTTP request is cached for 10 minutes, I find it quite expensive (even though I don't have the exact number on performance costs) The three places are

https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Publisher.tsx#L54
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Home/DefaultView/index.tsx#L95
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Home/DefaultView/index.tsx#L157
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Home/AllowanceView/index.tsx#L63

### Describe the solution

As the rate is the same for all payments in the loop, I propose the get the rate before the loop and only transform the number into an object inside the loop.

Currently, fetching the rate and transforming the data in one function:
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/context/SettingsContext.tsx#L74-L84
makes sense for all of the places where a single number is converted. 

For the places above where a potentially long array of payments needs to be transformed, I propose to provide a slight refactor and expose a function in SettingsContext, where the number and rate is provided as arguments to make it sync. To improve the loops, the rate would be fetched before the loop and inside the loop the sync function is used, being provided the rate and number.

I stumbled upon this working on the "transactions page" feature. So I could do this immediately, as I can use it in this feature.

### Are you working on this?

Yes

**Comment by lujakob** [comment]
@bumi @escapedcat do you think it makes sense if I implement this?

**Comment by escapedcat** [comment]
I guess why not if the code is readable and clean. Final decision should come from bumi.

**Comment by lujakob** [comment]
@escapedcat @bumi I created a PR, as it was simple changes and not much work. If it doesn't make sense we just close it.
