### ISSUE TITLE
Build new Figma components library based on current implementation

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2044]
The goal is to adjust Figma files with current implementation, Tailswind CSS used by Alby and create a good basis for future Alby extensions design master file

**Comment by Omkar0803** [comment]
Hey @jakubszwedo  can you tell me more about this issue? I would like to work on it.

**Comment by jankoegel** [comment]
@jakubszwedo @reneaaron there's this but it looks inactive: https://github.com/react-figma/react-figma

**Comment by jakubszwedo** [comment]
@Omkar0803 this is strictly design task to do in Figma. If you still want to help let me know

**Comment by DineshGupta-droid** [comment]
@stackingsaunter can you explain me in more detail about the issue i really want to contribute to it

**Comment by stackingsaunter** [comment]
@DineshGupta-droid thanks, this is almost done and will be closed this week
