### ISSUE TITLE
[BUG] Some texts already translated to PT-BR a long time ago still appear in English on Alby UI

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some texts already translated to PT-BR a long time ago still appear in English on Alby UI

### Screenshots [optional]

The texts:

1. Read your public key.
2. Decrypt data.
3. Sign message with your key.
4. Encrypt data.

was already translated to PT-BR a long time ago but still appear in English for me.

![Captura de tela de 2023-02-04 10-58-33](https://user-images.githubusercontent.com/1178856/216771776-19226065-f47a-49db-8acb-4d71f836a8c8.png)

### Steps To Reproduce

1. Change Alby to PT-BR language
2. Go to a site with Nostr support like nostrich.com
3. Click on Alby edit permission settings.

### Expected behavior

See the texts in Portuguese Brazilian

### Alby information

Alby: 1.25.1

**Comment by escapedcat** [comment]
@im-adithya where are the permissions now? Did we lose them?

**Comment by im-adithya** [comment]
No, they are still there; it seems he(@manavdesai27) doesn't have permissions linked to an allowance yet.

> I can't seem to find edit permissions settings in Alby

You'll have to first remember the permission methods via prompts for them to appear; you can generate your Nostr Private Key in the Accounts Page and go to any website with nostr support (nostrich here, for example) to give access (permission) to your public key through an Alby prompt and check the remember box to see the enabled permissions in the modal!

**Comment by manavdesai27** [comment]
Ok @im-adithya . Let me see

**Comment by escapedcat** [comment]
Ah, right, they are (/can be) here:
![image](https://user-images.githubusercontent.com/1016218/217315737-2b16eb60-935b-426c-a678-608732f60101.png)
I got confused as well now :P
