### ISSUE TITLE
[BUG] Discover page should show (Explore the Lightning and Nostr Ecosystem)

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Discover page should show (Explore the Lightning and Nostr Ecosystem) because now we have Nostr apps listed.

### Screenshots [optional]

![Captura de tela de 2023-02-04 16-00-10](https://user-images.githubusercontent.com/1178856/216784999-9e90ff7e-ce9b-4508-af7c-de91cd96358f.png)

### Steps To Reproduce

Go to Discover page

### Expected behavior

Discover page should show (Explore the Lightning and Nostr Ecosystem) because now we have Nostr apps listed.

### Alby information

Alby 1.25.1

### Are you working on this?

No

**Comment by manavdesai27** [comment]
I would like to work on this issue.

**Comment by escapedcat** [comment]
Thanks @manavdesai27 , let's get some input from @reneaaron or @MoritzKa here first. But let's assign you already. Once we know the final text you can start.

**Comment by manavdesai27** [comment]
Sure @escapedcat .

**Comment by manavdesai27** [comment]
@escapedcat Could I get some input to start working on it?

**Comment by jakubszwedo** [comment]
All of those Nostr clients have lightning integrated, so I'd argue they are part of lightning ecosystem. They just happen to be built on nostr protocol. So I think there's no need to change. Perhaps If Nostr app space grow and we'll add more of them, not all having lightning, there will be a good reason to have 2 big sections: lightning and nostr?

**Comment by MoritzKa** [comment]
I also see Nostr clients with lightning being part of the lightning ecosystem. It is fine for me to keep it as is.

**Comment by reneaaron** [comment]
Agree, closing this issue.
