### ISSUE TITLE
[Feature] List https://blogstack.io and https://notebin.org Nostr services on Discover page

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2066]
### Feature description

[Feature] List https://blogstack.io and https://notebin.org Nostr services on Discover page

### Describe the solution

[Feature] List https://blogstack.io and https://notebin.org Nostr services on Discover page

### Are you working on this?

No

**Comment by ShivamJhaa** [comment]
@escapedcat Hi, I would like to work on this, can you please assign me?

**Comment by ShivamJhaa** [comment]
@escapedcat How I can upload logos to use them on the discover page? The link is in the format https://cdn.getalby-assets.com/alby-extension-website-screen/{logoname} .

**Comment by escapedcat** [comment]
Right, you can't. We can help with this. Can you link them here?

**Comment by ShivamJhaa** [comment]
> Right, you can't. We can help with this. Can you link them here?

![notebin](https://user-images.githubusercontent.com/86483059/217415984-addfd8e9-dc83-4812-a654-6ed032a4887c.png)
![blog_stack](https://user-images.githubusercontent.com/86483059/217416012-f45dfa9c-8203-4fa7-b8a0-f1cebc1bc3cc.png)
@escapedcat Please upload them and share the link.

**Comment by escapedcat** [comment]
- https://cdn.getalby-assets.com/alby-extension-website-screen/notebin-logo.png
- https://cdn.getalby-assets.com/alby-extension-website-screen/blockstack-logo.png

Let's see if the quality is good enough
