### ISSUE TITLE
[BUG] Change password throws error

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#2075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Changing the password currently fails with an error message in console:

![image](https://user-images.githubusercontent.com/100827540/217021517-85ff7a49-adf8-44c0-871d-c2c59a8c263a.png)

### Steps To Reproduce

1. Go to settings
2. Change unlock password
3. Enter the new password and submit
4. See the error in the console

### Expected behavior

To change the password. 🤷

### Alby information

Latest `master`

### Are you working on this?

None

**Comment by manavdesai27** [comment]
I want to work on this issue.

**Comment by manavdesai27** [comment]
The issue is that when there is no "NoStr" present in the account, it tries decrypting a null value. If I add noStr to the account, the issue gets solved. I think we need to add checks for the same.
