### ISSUE TITLE
[BUG] Change unlock password on the Settings screens does not react

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#2076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Change unlock password on the Settings screens does not react. E.g. I cannot press the button when it changed the password

### Steps To Reproduce

1. Open Alby browser extension
2. Go to 'Settings'
3. Click on 'Change unlock password'
4. type in new password

### Expected behavior

Press the button to save the password and success message.

### Alby information

latest version. 

### Device information

Windows, Chrome

### Are you working on this?

No

**Comment by manavdesai27** [comment]
Could you please share a video for the same? I can't seem to reproduce the issue.

**Comment by MoritzKa** [comment]
https://user-images.githubusercontent.com/13707997/217333452-5bf65dc2-bb90-4f05-95c3-b023f258fe8a.mp4

**Comment by manavdesai27** [comment]
@MoritzKa video doesn't seem to be working. :(

**Comment by MoritzKa** [comment]
Change unlock password on the Settings screens does not react #2076

**Comment by manavdesai27** [comment]
https://user-images.githubusercontent.com/74018438/217429970-4d6639d0-bf0e-4e11-8c98-408016ca89b0.mp4

@MoritzKa It works perfectly here.

**Comment by lujakob** [comment]
Also worked for me. I tested a local dev extension and the latest from extension store download (production)

**Comment by avikt18** [comment]
Works for me too

**Comment by MoritzKa** [comment]
Same here now. I will close this issue again.
