### ISSUE TITLE
[BUG] The text title Edit Allowance looks wrong because there are others options.

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

The text title Edit Allowance looks wrong because there are others options like Enable website login, Edit Permissions..

I think should be Edit Preferences

### Screenshots [optional]

![photo_2023-02-09_14-40-35](https://user-images.githubusercontent.com/1178856/217895253-f81cf784-fb5c-4aac-8006-99c3463fbc70.jpg)

### Steps To Reproduce

See screenshot

### Expected behavior

Instead of Edit Allowance, should be Edit Preferences.

### Alby information

Alby: 1.25.2

### Are you working on this?

No

**Comment by manavdesai27** [comment]
@MoritzKa @bumi What is your take on this? I think making it "Edit Preferences" sounds about right considering the options users can view there.

**Comment by developingright** [comment]
Hi @bitcoinuser, I would like to work on this issue.

**Comment by escapedcat** [comment]
First we need feedback here. I assume @manavdesai27 would tackle this once we have a decision.

**Comment by SiddheshKukade** [comment]
@escapedcat Sir, I would like to work on this issue. Please assign.

**Comment by stackingsaunter** [comment]
@escapedcat @manavdesai27 I think Edit Preferences is fine there. Imho this page needs general overhaul so then we will change placing of it a bit, for now Edit Preferences is good fix
