### ISSUE TITLE
Uninstall page to collect feedback why people delete it.

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#210]
When a user deletes the extension we want to ask them for feedback. 
There should be a callback to open a page on uninstall.
- https://developer.chrome.com/docs/extensions/reference/runtime/#method-setUninstallURL
- https://www.extension.ninja/blog/post/browser-extension-setuninstallurl
- https://github.com/getAlby/lightning-browser-extension/blob/refactor/_allowance-list/src/extension/background-script/index.js#L140

**Comment by secondl1ght** [comment]
Do you want me to add the new feedback website to this callback?

**Comment by escapedcat** [comment]
See other extensions for example:
![image](https://user-images.githubusercontent.com/1016218/175236967-a58d798f-7020-4684-b323-0c11f7dbef53.png)
![image](https://user-images.githubusercontent.com/1016218/175237002-4ea272b5-15e1-4dc1-8502-61a734aef878.png)

**Comment by MoritzKa** [comment]
What about this: https://form.jotform.com/221745756722057
Jotform credentials are in 1-Password.

**Comment by secondl1ght** [comment]
I can do this task unless we want to leave it open for first-time contributors?
