### ISSUE TITLE
Display the preimage in the transaction list

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#2105]
### Feature description

The preimage somehow got lost. 

### Describe the solution

we want to show the preimage if available in the transaction details

### Are you working on this?

None

**Comment by manavdesai27** [comment]
I would like to work on this issue.

**Comment by manavdesai27** [comment]
I am not able to show complete preimage in details. It gets cut because of size of the parent.

**Comment by manavdesai27** [comment]
![image](https://user-images.githubusercontent.com/74018438/218657176-acb3d6f1-0dff-4b92-b8ec-2314f3f982b9.png)

I am thinking of having it like this.
