### ISSUE TITLE
[Feature] Add extra BIG WARNING before overwriting/deleting a Nostr key

### ISSUE THREAD

**Issue by dannydeezy** [getAlby/lightning-browser-extension#2106]
### Feature description

I want to suggest adding an additional warning before overwriting or deleting an existing Nostr key. I saw there is already a warning, but I suggest having a second warning either in ALL CAPS or something where it prompts the user to type out "delete this key forever" or something extra cumbersome.

We had one user accidentally overwrite their nostr key.

### Describe the solution

Solution described above.

### Are you working on this?

None

**Comment by escapedcat** [comment]
Wdyt @jakubszwedo @reneaaron @im-adithya

**Comment by ShivamJhaa** [comment]
@escapedcat instead of showing another warning, can we just prompt the user to write something like 'confirm delete' in order to make sure this is not done by accident?

**Comment by manavdesai27** [comment]
@escapedcat  We do provide a warning prompt for Yes/No, maybe that prompt can have this text field for confirmation.

**Comment by reneaaron** [comment]
Oh no 😥 thanks for raising this issue @dannydeezy! I like the idea of having the user type something to confirm this action as it might be irreversible. 

This is how DO does it for example: 
![image](https://user-images.githubusercontent.com/100827540/218715089-638ee75f-d45e-43cc-8621-0eb795a63020.png)

We could use `window.prompt` instead of `window.confirm` for this use case maybe? 

cc @jakubszwedo

**Comment by manavdesai27** [comment]
> We could use `window.prompt` instead of `window.confirm` for this use case maybe?

Yes exactly!

**Comment by ShivamJhaa** [comment]
> How about if we display the priv key and ask user to type last 6 digits for example to cofirm? This way we make they double check what they're deleting

Sounds good to me, can I work on this?

**Comment by jakubszwedo** [comment]
I propose following flow:

If user has no keys in Alby (same as currently):

<img width="1007" alt="Screenshot 2023-02-14 at 14 42 50" src="https://user-images.githubusercontent.com/68239231/218755684-331c6e3e-c77e-4109-8d45-8194f6e72d39.png">


If user has some keys in the extensions, there's additional warning:

<img width="648" alt="Screenshot 2023-02-14 at 14 43 27" src="https://user-images.githubusercontent.com/68239231/218755822-2779a6bc-e81d-4c1a-b8a3-024d6dec12c8.png">

Then whichever option they choose (derive/generate new), modal changes to this one:

<img width="928" alt="Screenshot 2023-02-14 at 14 44 00" src="https://user-images.githubusercontent.com/68239231/218755932-49e3aa10-ef36-4039-84ff-73a511e20436.png">

They need to type 4 digits after "nsec1" to make confirmation button clickable. I think those letters are also the one which users choose to identify keys visually, at least that's what I do, but some users may use the last one.

I want to avoid stacking modal on modal, so it would be great if this modal replaces the first one (or is in-modal flow somehow).

What I also recommend here:
- Make modal width 680px, so we can see whole key and the width does not change between 2 modals"
- Ideally user shouldn't be able to copy the characters from this disabled input, so they have to type it manually. 
- Please swap buttons in the modal so the orange one is on the right if possible, like in the screenshots (currently it's on the left side)

Please review flow/copy @escapedcat @reneaaron

**Comment by reneaaron** [comment]
Looks good to me but involves quite some things that we would need to implement here. Would having a browser "prompt" window work for now as well? 

![image](https://user-images.githubusercontent.com/100827540/219224937-e0b68c1c-897c-49a3-8716-1428239f7666.png)

That would a lot easier to implement and we could potentially ship it with the next release. (and follow up with the full version after that) What do you think?

**Comment by stackingsaunter** [comment]
Sure, this is easer and faster but increases security almost as much!

**Comment by reneaaron** [comment]
@ShivamJhaa Do you want to pick this up from here?

**Comment by ShivamJhaa** [comment]
@reneaaron Yes, thank you for the clarification.
