### ISSUE TITLE
Reorder and add https://lnnodeinsight.com/ to the discover page with a new category: Node management

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#2111]
### Feature description

add channel.ninja, amboss.space and lnnodeinsight to a new category: Node Management

Jakub suggested this order: Entertainment, Shopping, Nostr, Trading, Gaming, Misc.

### Describe the solution

new project and new section on the "Discover" page. 

### Are you working on this?

None

**Comment by stackingsaunter** [comment]
Good idea. Should it be before Misc., as it's more specialistic category?

**Comment by reneaaron** [comment]
I also like the idea, however we have to consider that those things are possibly only available for users who connected their own nodes and cannot be used with connectors like Alby, LNBits, etc. 

Maybe that's okay for now though, I also don't want to maintain a list of connectors / services that work together if we can avoid that somehow.

**Comment by SiddheshKukade** [comment]
@MoritzKa Sir I would like to work on this issue. please assign. 
I'm a professional software developer and have 9 months of work experience. 

I would like to work on this re-ordering.

**Comment by SiddheshKukade** [comment]
@MoritzKa Sir,  I have a question about: `add https://lnnodeinsight.com/ to the discover page with a new category: Node management`

Are we going to add the link to `https://lnnodeinsight.com/ ` to the navbar or around the red area? 
![image](https://user-images.githubusercontent.com/65951872/225208985-1710cc9d-e47b-4306-bcaf-042319204d9a.png)

If you already have any UI blueprints on `node management` please share.
 Thanks

**Comment by escapedcat** [comment]
@SiddheshKukade I think a new category `Misc.` should be added to the list in the area you marked red.  
`https://lnnodeinsight.com/` should be added to `Misc.`

**Comment by MoritzKa** [comment]
The idea was to add channel.ninja, amboss.space and lnnodeinsight to a new category: Node Management within the red marked area. 
The order would be: Entertainment, Shopping, Nostr, Trading, Gaming, Node Management, Misc.
