### ISSUE TITLE
[docs] update project structure in SETUP.md 

### ISSUE THREAD

**Issue by avikt18** [getAlby/lightning-browser-extension#2117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current project structure has the "fixtures" and "i18n" directories missing under **src**.

### Screenshots [optional]

![image](https://user-images.githubusercontent.com/56340999/219436496-3447c02e-3ce8-4bf9-8fd6-5b6e3e0b6300.png)

### Steps To Reproduce

Visit the [SETUP.md](https://github.com/getAlby/lightning-browser-extension/blob/master/doc/SETUP.md) file

### Expected behavior

![image](https://user-images.githubusercontent.com/56340999/219437396-b0b874f2-3cb9-4a2a-97a1-3b3f413142a6.png)

### Alby information

-

### Are you working on this?

Yes

**Comment by avikt18** [comment]
Is this issue valid or the current behavior is intended @bumi @MoritzKa

**Comment by bumi** [comment]
true, yes, this needs to be updated.

**Comment by avikt18** [comment]
I will fix this 👍
