### ISSUE TITLE
[Feature] support nostr NIP-57 zaps

### ISSUE THREAD

**Issue by juestr** [getAlby/lightning-browser-extension#2120]
### Feature description

Zaps in nostr are notes with receipts of lightning payments.

The specification is here: https://github.com/nostr-protocol/nips/blob/master/57.md

### Describe the solution

When paying tips in nostr with lightning, receipts should be visible in public (possibly summed up).

### Are you working on this?

No

**Comment by lujakob** [comment]
How exactly is this going to affect the Alby extension? I understand what zaps in nostr are, but not what the changes in the alby extension are. Thanks for clarifiying.

**Comment by dskvr** [comment]
@lujakob Extra metadata is required.  The protocol is clearly explained for both the client-side and server-side in the NIP: https://github.com/nostr-protocol/nips/blob/master/57.md#protocol-flow

**Comment by juestr** [comment]
Tbh I initially thought Alby would just need to implement the zapper part, but now I am less sure. Also the Alby LN-address service NAME@getalby.com should return extra nostr data, but that's not part of the extension per se.

**Comment by reneaaron** [comment]
NIP-57 needs to implemented by your LNURL provider (getalby.com if you use your Alby account with the Extension). Thanks for your feedback though, we hear you! 👂

Closing this issue in the extension repository, but stay tuned for some updates soon. 🤞
