### ISSUE TITLE
[BUG] welcome screens are not protected by password

### ISSUE THREAD

**Issue by im-adithya** [getAlby/lightning-browser-extension#2137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We can still visit the choose-path, test-connection links without setting a password

### Screenshots [optional]

-

### Steps To Reproduce

Go to .../welcome.html#/choose-path without setting a password, it opens.

### Expected behavior

It should redirect to set password screen

### Alby information

latest

### Device information

mac os

### Are you working on this?

Yes

**Comment by reneaaron** [comment]
Won't fix for now. :sweat_smile:
