### ISSUE TITLE
[Feature] Add support for HODL invoices

### ISSUE THREAD

**Issue by LukasBahrenberg** [getAlby/lightning-browser-extension#2142]
### Feature description

Be able to create and pay HODL invoices

### Describe the solution

Add the capability to create and pay HODL invoices. Creating HODL invoices is not possible at the moment. Paying HODL invoices seems to work (pending HTLCs are added) but Alby keeps loading after paying the HODL invoice. I guess it's waiting for a response that is not coming.

### Describe alternatives

A first step to allow for the creation of HODL invoices could be to include it in the supported methods through webln.request(), e.g. AddHoldInvoice for LND.

### Are you working on this?

None

**Comment by reneaaron** [comment]
Thanks for the initiative @LukasBahrenberg 🙌

I think it's also important to know the limitations and potential drawbacks of HODL invoices. 
 - Limit of 483 concurrent HTLC payments per node 
 - Locking liquidity from routing nodes along the payment route

📖 Resources:
 - https://lightningwiki.net/index.php/HODL_Invoice
 - https://bitcoin.stackexchange.com/questions/91168/what-are-the-downsides-of-hodl-invoices
 - https://bolt.fun/guide/invoices/hodl-invoice
 - https://twitter.com/Bumi/status/1604048430464086016

That being said, let's look into the 2 problems we are trying to solve here:

### Adding HODL invoices

This could be integrated as a new method to `webln.request()` for LND: 
https://lightning.engineering/api-docs/api/lnd/invoices/add-hold-invoice

I've created a PR to enable that: 
#2151

For Core-Lightning I couldn't find a method to create HODL invoices. 

## Paying HODL invoices

The main difference between usual invoice payments and HODL invoice payments is that the invoice isn't immediately settled by the receiver. The payment dialog waits for the confirmation that could appear hours later (or never).

I think the client should know whether an invoice is supposed to be a "normal" invoice or a HODL one. So by offering a way for developers to set a timeout for those payments this could allow a better UX: (not having to ask users to close the window after X seconds)

`webln.sendPaymentAsync(pr, timeout)`

If the invoice is settled within the timeout the success screen is displayed as usual. If the timeout is reached we could display a message like "Payment in flight" and close the payment window after that?

**Comment by reneaaron** [comment]
@LukasBahrenberg Do you actually need a way to know the payment status of the paid HODL invoice as you call `webln.sendPayment()`? 

Who generates those HODL invoices? Is it purely P2P? (so one user would generate one and send it to another user who then pays it) or is there a node under your control that issues those invoices?

**Comment by reneaaron** [comment]
> I guess my service could also notify the user once it settles the invoice.

Exactly, if you are paying to your service you should already know whether an invoice has been settled or not. 

> It is actually both, the user creating and paying HODL invoices as well as my service creating and paying HODL invoices. So it is not purely P2P but the user and the service perform both tasks.

If you are creating HODL invoices on the client, who will settle them and when? Would you also need `webln.request("settleinvoice")` ([LND docs](https://lightning.engineering/api-docs/api/lnd/invoices/settle-invoice)) for that?

**Comment by LukasBahrenberg** [comment]
> If you are creating HODL invoices on the client, who will settle them and when? Would you also need `webln.request("settleinvoice")` ([LND docs](https://lightning.engineering/api-docs/api/lnd/invoices/settle-invoice)) for that?

The HODL invoice the user creates is based on a hash to which the user does not hold the preimage. In my specific application the preimage is revealed by a third party based on some external logic at some point in the future. Once the user learns the preimage, they would need to settle the invoice with the method you are quoting.

**Comment by reneaaron** [comment]
You would need to trigger the `settleinvoice` call in your app, exactly. Granting permissions for this call could get rid of the permission popup, however your app would still need to be running (and maybe polling from this external service in the background) 

So I suppose the problem here would be that you need to tell the user to come back to this page and settle certain invoices, right? 🤔

**Comment by LukasBahrenberg** [comment]
> ... Granting permissions for this call could get rid of the permission popup ...

That would make sense because the user claims funds through the settlement for themselves, which should not be to their disdvantage, unless I am overlooking something here ...

> So I suppose the problem here would be that you need to tell the user to come back to this page and settle certain invoices, right? 🤔

I think that would be fine and one solution. The disadvantage is of course that the payment might timeout if the user does not run the app again.

However, I am also looking into some other options for the user to grant permissions to an external entity to settle the invoice on their behalf. This way, the user just needs to keep their node running and does not need to run the frontend app necessarily (e.g. through [custom macaroons on LND](https://github.com/lightningnetwork/lnd/blob/master/macaroons/README.md#bakery)). This would require a user, however, to run their own node and would not work with Alby's lndhub solution, I suppose.

**Comment by reneaaron** [comment]
> That would make sense because the user claims funds through the settlement for themselves, which should not be to their disdvantage, unless I am overlooking something here ...

True. Currently all the `webln.request` methods share the same permission system (you as a user are always prompted for new API calls and can set permanent permissions via the "remember" checkbox) and we don't have method-specific handling. Something we might want to consider though. 

>Yes, it is an inconvencience but I think that could be fine and a solution. The disadvantage is of course that the payment will timeout if the user does not run the app again.

Okay, will that happen on a regular basis or is that rather the exception to the rule? What problem do you actually solve with the HODL invoice? Is it some kind of a deposit? 

> However, I am also looking into some other options for the user to grant permissions to an external entity to settle the invoice on their behalf. 

Interesting 🤔 This is then very specific to the connector and will be limited to users having an own node. LNDHub currently doesn't allow you to create / settle HODL invoices and I most of the other connectors (LNBits, etc) won't offer this functionality as well.

**Comment by LukasBahrenberg** [comment]
> Okay, will that happen on a regular basis or is that rather the exception to the rule? 

Yes, it will happen on a regular basis. The main functionality of my service is based on this.

> What problem do you actually solve with the HODL invoice? Is it some kind of a deposit?

The HODL invoice enables an atomic swap that both service and user commit to and is only settled once an external logic reveals the preimage. I am currently working on a writeup of the technical concept behind it. I am going to publish it at some point and then link it here as well.

> LNDHub currently doesn't allow you to create / settle HODL invoices and I most of the other connectors (LNBits, etc) won't offer this functionality as well.

Okay, good to know. I haven't gone through all the options yet.

**Comment by reneaaron** [comment]
>  I am currently working on a writeup of the technical concept behind it. I am going to publish it at some point and then link it here as well.

Cool 😎

So would it help you already to add the create / settle HODL invoice calls? If yes I'd try to sneak that into the next release.

**Comment by reneaaron** [comment]
Nice, thanks for the quick response. I'll finish up the the PR. 🚀

**Comment by LukasBahrenberg** [comment]
As promised, this is the [blog post](https://medium.com/@lukasbahrenberg/efficient-self-custodial-asset-exchanges-on-lightning-off-chain-swaps-and-a-central-order-book-f3ea6f9fd40b) explaining how I want to use the HODL invoices.

**Comment by LukasBahrenberg** [comment]
@reneaaron: Apologies for the very late response! Thanks again for implementing this. 

I tested the `webln.request()` methods `addholdinvoice` and `settleinvoice` when connected to LND via Alby/REST. It works except for one (minor) thing: 

I set a "remember" in Alby for `webln.sendPayment()` with a budget for my test site allowing me to make multiple payments in a row non-interactively. Now, if I try to pay multiple HODL invoices in a row, it throws me the following error and prevents me from running `webln.sendPayment()` again: 

```
inpageScriptWebLN.bundle.js:1 Uncaught (in promise) Error: window.webln call already executing
    at r (inpageScriptWebLN.bundle.js:1:357)
r @ inpageScriptWebLN.bundle.js:1
```
I suppose this has to do with getting no response for `webln.sendPayment()` in case of paying a HODL invoice. This is not too bad as e.g. a page reload solves this. I wonder, however, what happens in the background. Is Alby still waiting for a response for all the paid HODL invoices? Does this accumulate somehow?

> There is still the idea of sendPaymentAsync to prevent users from having to close the popup manually. Should we prioritize that?

There is no need to prioritize this for my sake at this point but it could solve the above mentioned problem too, right? 

Thx again, Lukas

**Comment by bumi** [comment]
@LukasBahrenberg thanks for testing and reporting. Could you open an issue for this that we do not forget it. 
Currently Alby protects the user from too many requests by the website and thus does not allow parallel requests - the hold invoice keeps the connection open, so this is a problem I guess.
