### ISSUE TITLE
[BUG] Login issue in "channel.ninja"

### ISSUE THREAD

**Issue by manavdesai27** [getAlby/lightning-browser-extension#2145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Not able to login using public key on "channel.ninja". On running `webln.getInfo`, the request gets stuck at pending and doesn't get fulfilled.

### Screenshots [optional]

https://user-images.githubusercontent.com/74018438/221371809-8557ed18-ef20-4cf6-a1b6-0f0b19fef698.mp4

### Steps To Reproduce

1. Visit `https://channel.ninja/?`
2. Click on `Get from Extension`
3. You will get alert as "Your current account does not have a public key"

### Expected behavior

Should get public key from alby account and login.

### Alby information

Installed manually using github on Google Chrome.

### Are you working on this?

None

**Comment by bumi** [comment]
for channel.ninja you need to have your own node (LND) connected. It does not work with an Alby account or similar.

**Comment by manavdesai27** [comment]
> for channel.ninja you need to have your own node (LND) connected. It does not work with an Alby account or similar.

Oh okay! Thanks for the clarification. Closing the issue.
