### ISSUE TITLE
Alby installed on the Kiwi browser does not detect QR codes or invoices from QR codes

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#2147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I cannot read out invoices from QR codes when I use Alby on the Kiwi browser

### Steps To Reproduce

1. Open Alby in the Kiwi browser
2. Click on "Send"
3. Click on Scan QR Code

### Expected behavior

Alby detects the invoice that is encoded in the QR code

### Alby information

Alby version 1.27.0

### Device information

Android, Kiwi browser.

### Are you working on this?

No

**Comment by reneaaron** [comment]
Triaged, seems to be a general problem also for Firefox / Chrome.
