### ISSUE TITLE
Enable account creation for Kollider

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#2157]
### Feature description

Kollider has opened up the registrations and allows users to signup. 
Currently users can only use existing account details we should allow users to signup from the Kollider connector form
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/connectors/ConnectKollider/index.tsx

### Describe the solution

use the Kollider API to register a new account: https://lndhubx.kollider.xyz/#/paths/~1create/post

### Are you working on this?

None

**Comment by stackingsaunter** [comment]
Proposed flow:

https://www.youtube.com/watch?v=0Oevt_2mZWs

<img width="888" alt="Screenshot 2023-03-14 at 20 40 22" src="https://user-images.githubusercontent.com/68239231/225118306-7c573ac4-4a06-4fde-a5e5-6ff2f7a748cc.png">

<img width="851" alt="Screenshot 2023-03-14 at 20 40 30" src="https://user-images.githubusercontent.com/68239231/225118335-412ad7e2-0888-44de-b43c-a6515c9dcf1d.png">

<img width="1032" alt="Screenshot 2023-03-14 at 20 40 41" src="https://user-images.githubusercontent.com/68239231/225118379-21ef8b12-6ef4-4345-9d9e-85e9656f1c1f.png">

**Comment by stackingsaunter** [comment]
Screens above are with the new layout for connectors which perhaps can be added as a seperate issue, so for now we can use older wide box with Alby: <img width="754" alt="Screenshot 2023-03-15 at 16 51 10" src="https://user-images.githubusercontent.com/68239231/225365744-98dc8b48-acd9-4f5f-8a4b-525b5efd3003.png">

However I think we can implement the first immediacy step as it is here. It is the same card box as for Alby login/signup
![image](https://user-images.githubusercontent.com/68239231/225366093-97efaabe-2746-43ae-b01b-f84a8018dd3c.png)

<img width="1120" alt="Screenshot 2023-03-15 at 16 53 29" src="https://user-images.githubusercontent.com/68239231/225366413-ae1096f2-f370-45ca-9709-b9fbc1506669.png">
