### ISSUE TITLE
[BUG] `window.nostr` not being injected in Edge browser

### ISSUE THREAD

**Issue by piraces** [getAlby/lightning-browser-extension#2158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the latest version of Microsoft Edge (actually 110.0.1587.57 64 bits), with Alby extension installed, logged in (unlocked) and using Nostr support, it cannot sucesssfully inject `nostr` into the `window` object as defined in [NIP-07](https://github.com/nostr-protocol/nips/blob/master/07.md).

This can be seen by opening the developer tools and executing `window.nostr` to see if it is `undefined` or not.

Seems like this line it's not working as expected:
https://github.com/getAlby/lightning-browser-extension/blob/a7789a92e31c1cebbeb09e9542bf9120cd7e6ee7/src/extension/inpage-script/nostr.js#L3-L5

Nevertheless, in other browsers (Chromium based) seems to be working just fine (checked in Brave v1.48.171). Maybe an Edge restriction?

### Screenshots [optional]

Working correctly in Brave browser:
![Screenshot of Brave working](https://user-images.githubusercontent.com/11027628/222207989-acf2939e-e823-40f8-bb1a-a9d33c1193ea.png)

Incorrect behaviour in same page with Edge (reproducible in any page):
![Screenshot of Edge not working](https://user-images.githubusercontent.com/11027628/222209066-35dd6c30-894d-4980-a54a-a6f635b6eb86.png)

### Steps To Reproduce

1. Download latest version of Microsoft Edge.
2. Login in the Alby extension (with Nostr support already enabled and configured).
3. Go to any page.
4. Open developer tools.
5. Inspect the window object or evaluate `window.nostr` (as [NIP-07](https://github.com/nostr-protocol/nips/blob/master/07.md) defines).
6. The object is undefined... The extension is not able to inject the object in the window.

### Expected behavior

The expected behaviour is `window.nostr` not to be undefined when the Alby extension is unlocked and configured to work with Nostr.

### Alby information

- Alby version: 1.27.0
- Alby installed with: from Chrome store.
- Wallet connected with Alby: Alby provided one (LNDHub) (name@getalby.com).

### Device information

- OS: Windows 11
- Browser: Edge (Chromium based)
- Browser version: v110.0.1587.57 64 bits

### Are you working on this?

No

**Comment by bumi** [comment]
thanks for reporting, I need to review the edge browser. 
to confirm: the nostr key is not generated by default you first have to configure the account for nostr. Did you add the key for the currently selected account?

**Comment by piraces** [comment]
My fault sorry... I changed my main browser and logged into Alby but forgot to reconfigure the account for nostr (adding the key for the currently selected account). Now working ok. Sorry for the false alarm 😞
