### ISSUE TITLE
https://www.sfcu.org/ does not open when Alby is installed. 

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#2165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://www.sfcu.org/ does not open when Alby is installed. 
The website can be reached (no error message and you can scroll) but it does not display or load content. 

### Screenshots [optional]

![slack_GDwoWdKeK0](https://user-images.githubusercontent.com/13707997/222815751-75643940-9080-429f-be78-a481ee9d5e07.png)

### Steps To Reproduce

1.) Install Alby
2.) Visit: https://www.sfcu.org/ does not open when Alby is installed. 

### Expected behavior

Website can be opened despite Alby is installed

### Alby information

Alby 

### Device information

Windows
Chrome and Firefox
Alby 1.27.0

### Are you working on this?

No

**Comment by MoritzKa** [comment]
René: The issue IS related to cookiebot:
> Cookiebot blocks scripts and trackers which set cookies on the site until the user gives appropriate consent.
Blocking cookiebot requests makes the site work again. Couldn't find out what exactly they do that causes those problems right now.

**Comment by reneaaron** [comment]
I think this should be solved by now with the new injection logic we recently added.
