### ISSUE TITLE
Success Message

### ISSUE THREAD

**Issue by sat-oshee** [getAlby/lightning-browser-extension#2171]
When a user successfully makes a payment, the feedback they get should be more visual rather than text. That will make for a good user experience. We could use a lottiefile with success checkmark animating or an illustration that signifies success, infact we could even make just the text green color just not leave it in black text. I feel like UX wise success and error messages should be more visual than texty.
![Send Payment](https://user-images.githubusercontent.com/127018181/222987143-24f01732-2cbb-4818-be21-549711d91a75.png)

**Comment by escapedcat** [comment]
@stackingsaunter is already working on animations afaik, right?

**Comment by sat-oshee** [comment]
Ok, didn't know about that.

**Comment by reneaaron** [comment]
Thanks for your feedback @sat-oshee, we will soon start to work on the new success screens! 👌

**Comment by stackingsaunter** [comment]
@sat-oshee see https://github.com/getAlby/lightning-browser-extension/issues/1960
