### ISSUE TITLE
Generate an encrypted downloadable backup 

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#2177]
### Feature description

we need to force people to make backups and for that we also need to make it easier to backup the data.

### Describe the solution

We should create an encrypted backup JSON file of the full state with all accounts that the user can download. 
The JSON file should be encrypted with the users password 

### Additional context

https://code.tutsplus.com/tutorials/how-to-save-a-file-with-javascript--cms-41105

### Are you working on this?

None

**Comment by rolznz** [comment]
Is this similar to https://github.com/getAlby/lightning-browser-extension/issues/1527 or does it only contain the minimum needed to restore access?

How useful is this if the user forgets their extension password?

**Comment by bumi** [comment]
it's similar. 

> How useful is this if the user forgets their extension password?
not sure how I should answer that question. obviously if the user does forgets the encryption pasword this is useless, but... 
isn't that the same as, if a user looses the paper on which they wrote down the backup?

**Comment by rolznz** [comment]
I think this process should also guide them to write down their password, and then prompt them again to make sure it is written down (Or maybe this should be part of the extension setup)

**Comment by im-adithya** [comment]
Closing as #2338 will fix this soon
