### ISSUE TITLE
Too hard to find on-chain deposit address

### ISSUE THREAD

**Issue by dannydeezy** [getAlby/lightning-browser-extension#2186]
It's really hard to find this. Makes it hard to get funds in!

**Comment by escapedcat** [comment]
Where did you search?  
Where would you like to see it?

**Comment by stackingsaunter** [comment]
@dannydeezy would something like this be helpful? Button would link to getalby.com Receive page, where onchain address is

<img width="437" alt="Screenshot 2023-03-10 at 18 38 04" src="https://user-images.githubusercontent.com/68239231/224384838-acaaa7f4-4816-4b53-8855-10cb66b66b5f.png">

**Comment by stackingsaunter** [comment]
Related to #2240

**Comment by bitcoinuser** [comment]
I think have two tabs is not good. Even to translate to other languages. Onchain is strange.

In my opinion should just have a message on receive window telling something like: If you want to deposit using a bitcoin address instead of a lightning address, please click here.
