### ISSUE TITLE
Remove BlueWallet connector 

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#2194]
### Feature description

BlueWallet is switching off their LNDhub in March/April. Hence the BlueWallet connector is not needed anymore. 

### Describe the solution

Remove BlueWallet connector
![chrome_ti5rygKEjW](https://user-images.githubusercontent.com/13707997/224425786-9917ed5c-b18f-44a4-bcc8-b05f1bd19437.png)

### Are you working on this?

No

**Comment by 0xZaddyy** [comment]
should i work on this?
