### ISSUE TITLE
[Feature] Add broadcstr.com on Nostr section

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2200]
### Feature description

Add https://www.broadcstr.com/ on Nostr section

### Describe the solution

Add https://www.broadcstr.com/ on Nostr section

### Are you working on this?

No

**Comment by Tejasp2003** [comment]
I would like to work on this issue

**Comment by Tejasp2003** [comment]
@escapedcat i am working on this issue
