### ISSUE TITLE
[Feature] Add websites pages loading spinner

### ISSUE THREAD

**Issue by lujakob** [getAlby/lightning-browser-extension#2210]
### Feature description

The websites page is missing a Loading spinner during data load. This got noticed for transactions page and for consistency reasons it got decided to add it to websites as well https://github.com/getAlby/lightning-browser-extension/issues/2197#issuecomment-1466952627

### Describe the solution

Add loading spinner same as on transactions page. https://github.com/getAlby/lightning-browser-extension/pull/2205

### Are you working on this?

Yes

**Comment by stackingsaunter** [comment]
Proposed pagination design here: https://github.com/getAlby/lightning-browser-extension/issues/1839#issuecomment-1464137219
