### ISSUE TITLE
Feature Request: for adding the app translation in Marathi Language

### ISSUE THREAD

**Issue by SiddheshKukade** [getAlby/lightning-browser-extension#2213]
### Feature description

To help more bitcoin and crypto adoption we have to make the UX  more friendly to the user.  Ability to use the applications in their native language will also help in this goal.
[Marathi Language](https://en.wikipedia.org/wiki/Marathi_language) is one of top 3 languages in India spoken by over 80 million people just in India. 

**Problem** : Currently  there is not translation available in marathi language for Alby App.

### Describe the solution

Adding the translation in the `i18n/locale` folder

### Are you working on this?

Yes

**Comment by SiddheshKukade** [comment]
@MoritzKa I am a native Marathi language speaker and it's my first language. Please take a look at this issue and assign me if it's valid.
Thanks

**Comment by MoritzKa** [comment]
Hi Siddhesh, sure that would be great if you help us to translate Alby to Marathi.
