### ISSUE TITLE
[Feature] (UI) Request to change button text color to black for better visiblity

### ISSUE THREAD

**Issue by soham4abc** [getAlby/lightning-browser-extension#2225]
### Feature description

Currently Alby uses  Orange buttons with white text. This causes visibility issues of the button text.
![image](https://user-images.githubusercontent.com/63705023/225642389-56998f89-35e5-42b6-a9a3-1a6a7b0b7138.png)

### Describe the solution

 Would like to change the color of the button text to black to improve the visibility. 

### Describe alternatives

Other colored text can be added as per suggestion

### Are you working on this?

Yes

**Comment by soham4abc** [comment]
> It's looking good to me as of now. May be text could be made bolder to make it more visible
How does this look?

![image](https://user-images.githubusercontent.com/63705023/225644279-baad5735-558c-4d55-88f5-ed05a8586d87.png)

**Comment by Tejasp2003** [comment]
Looks Good. But as far as I am concerned, the whole project uses the same buttons (orange background + white text).

**Comment by Tejasp2003** [comment]
Changing the buttons at all places will change the theme of the website. Also, toggles and other things are also given an orange and white color.

**Comment by stackingsaunter** [comment]
Orange is [a tricky color for buttons, text and contrasts](https://www.bounteous.com/insights/2019/03/22/orange-you-accessible-mini-case-study-color-ratio). White text on orange fails common contrast but black one doesn't really look more readable in Light theme. I agree it looks better in Dark theme so perhaps can we change it only in black theme buttons?

<img width="995" alt="Screenshot 2023-03-17 at 12 24 24" src="https://user-images.githubusercontent.com/68239231/225891474-f2dc3425-56f5-44a2-9b52-eb2c168506fc.png">

<img width="1007" alt="Screenshot 2023-03-17 at 12 25 18" src="https://user-images.githubusercontent.com/68239231/225891694-be7744b4-a2b0-418d-935a-fcdcea77dad1.png">

<img width="1022" alt="Screenshot 2023-03-17 at 12 25 30" src="https://user-images.githubusercontent.com/68239231/225891768-0fd5b735-b126-41f3-95c1-2dea27310b77.png">


But I really like the idea to increase font weight in buttons to increase readiblity. How about if we make it semi-bold (both light/dark theme). See difference:

<img width="748" alt="Screenshot 2023-03-17 at 12 26 28" src="https://user-images.githubusercontent.com/68239231/225892028-33528d4e-11c9-440c-9e9a-f60a0b4a0231.png">
<img width="734" alt="Screenshot 2023-03-17 at 12 26 37" src="https://user-images.githubusercontent.com/68239231/225892073-da0264a8-0817-4164-92f7-a85443fda5c9.png">

<img width="1165" alt="Screenshot 2023-03-17 at 12 27 24" src="https://user-images.githubusercontent.com/68239231/225892212-8900a80d-b3db-4c14-978d-2e61b42d7c94.png">

**Comment by Tejasp2003** [comment]
> Orange is [a tricky color for buttons, text and contrasts](https://www.bounteous.com/insights/2019/03/22/orange-you-accessible-mini-case-study-color-ratio). White text on orange fails common contrast but black one doesn't really look more readable in Light theme. I agree it looks better in Dark theme so perhaps can we change it only in black theme buttons?
> 
> <img alt="Screenshot 2023-03-17 at 12 24 24" width="995" src="https://user-images.githubusercontent.com/68239231/225891474-f2dc3425-56f5-44a2-9b52-eb2c168506fc.png">
> 
> <img alt="Screenshot 2023-03-17 at 12 25 18" width="1007" src="https://user-images.githubusercontent.com/68239231/225891694-be7744b4-a2b0-418d-935a-fcdcea77dad1.png">
> 
> <img alt="Screenshot 2023-03-17 at 12 25 30" width="1022" src="https://user-images.githubusercontent.com/68239231/225891768-0fd5b735-b126-41f3-95c1-2dea27310b77.png">
> 
> But I really like the idea to increase font weight in buttons to increase readiblity. How about if we make it semi-bold (both light/dark theme). See difference:
> 
> <img alt="Screenshot 2023-03-17 at 12 26 28" width="748" src="https://user-images.githubusercontent.com/68239231/225892028-33528d4e-11c9-440c-9e9a-f60a0b4a0231.png">
> 
> <img alt="Screenshot 2023-03-17 at 12 26 37" width="734" src="https://user-images.githubusercontent.com/68239231/225892073-da0264a8-0817-4164-92f7-a85443fda5c9.png">
> 
> <img alt="Screenshot 2023-03-17 at 12 27 24" width="1165" src="https://user-images.githubusercontent.com/68239231/225892212-8900a80d-b3db-4c14-978d-2e61b42d7c94.png">

Yes! exactly. Changing the font size or making the font bolder on buttons will definitely improve visibility.

**Comment by soham4abc** [comment]
Alright! I am on it!

**Comment by Tejasp2003** [comment]
> Alright! I am on it!
Okay, @soham4abc Soham. Do let me know if you need any help, or would like to contribute too. Make sure to change the font of all buttons on the website

**Comment by soham4abc** [comment]
Light Mode:
![image](https://user-images.githubusercontent.com/63705023/225897437-0dfe6649-4d79-4f63-b051-1666dee1cb13.png)
Dark Mode:
![image](https://user-images.githubusercontent.com/63705023/225897991-13ecdc61-76aa-422e-a374-04e2b1f7cc25.png)

How does it look?? @escapedcat @stackingsaunter @Tejasp2003

**Comment by soham4abc** [comment]
@escapedcat @stackingsaunter @Tejasp2003  There is an updated PR related to this you can see the changes there if you want 
#2226

**Comment by reneaaron** [comment]
Button designs completely changed, closing this as not relevant anymore.
