### ISSUE TITLE
Improvements to extension navigation

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2228]
I propose a few improvements to extension navigation:

<img width="1492" alt="Screenshot 2023-03-17 at 13 39 55" src="https://user-images.githubusercontent.com/68239231/225907063-51efa52b-5306-41df-b956-db5b3106c69f.png">

<img width="1435" alt="Screenshot 2023-03-17 at 13 52 46" src="https://user-images.githubusercontent.com/68239231/225909937-45d9d33f-1d22-4f82-8445-1eb62366fc18.png">

List of changes:
1. Changing "**Websites**" page into "**Connected Sites**" - better reflects what's in that page (On "Discover" there are websites as well, etc. so it was a bit confusing).
2. Introducing new icon for Connected Sites and Help, Feedback uses "magic wand" icon from bitcoin icons set, and Discover uses "rocket" previously used in Feedback.
3. Hamburger menu in extended view shows only items which are not in the navigation bar (so does not show Discover and Connected Sites),

New icons:
![Connected](https://user-images.githubusercontent.com/68239231/225908654-6a7bfc36-203c-4cfa-902b-d1bbd4b820d8.svg)
![Help](https://user-images.githubusercontent.com/68239231/225908659-0f8f4279-4beb-47c8-92d2-2347131fb61c.svg)
![Magic wand](https://user-images.githubusercontent.com/68239231/225909044-05ac51e5-0b17-451d-ae7b-4accdad9dcab.svg)

**Comment by kamalchakma1** [comment]
Hi, I would like to work on this issue. Thank you

**Comment by stackingsaunter** [comment]
@kamalchakma1 sure, go for it!

**Comment by kamalchakma1** [comment]
@stackingsaunter Thanks

**Comment by kamalchakma1** [comment]
@stackingsaunter Hello Sir,I'm trying to run it into local machine but I am not able to run. And this is first time I'm using yarn. So can you guide me on this please.

**Comment by stackingsaunter** [comment]
I am not technical enough perhaps @escapedcat or @reneaaron can help

**Comment by kamalchakma1** [comment]
@stackingsaunter ok thank you

**Comment by kamalchakma1** [comment]
@escapedcat @reneaaron Hi, I had clone the project into my local machine but I am facing little problem to run the project in my local machine. I have installed yarn but unable to run and need help from you. Thank you

**Comment by reneaaron** [comment]
@kamalchakma1 Could you fix your problem in the meantime? Do you mind to share some details (error messages, etc) so we can point you into the right direction?

**Comment by kamalchakma1** [comment]
@reneaaron The issue I'm facing is that I'm not able to run in local machine. And I'm new to yarn. If you help me with this then it will be very helpful.  Thanks

**Comment by escapedcat** [comment]
> The issue I'm facing is that I'm not able to run in local machine. And I'm new to yarn. If you help me with this then it will be very helpful. Thanks

Maybe as in [the slack channel](https://github.com/getAlby/lightning-browser-extension#join-the-conversation) and see if someone can help you to get running.

**Comment by reneaaron** [comment]
@kamalchakma1 If you don't provide any more details I can't help you, sorry. Feel free to reach out on Slack.

**Comment by kamalchakma1** [comment]
Hi, Here is the screenshot. Please check it.
![error](https://user-images.githubusercontent.com/53227040/227445892-26f1f559-420a-4de7-8d28-f2ca43fde268.PNG)

**Comment by kamalchakma1** [comment]
Ok thanks

**Comment by ankitzm** [comment]
I would like to work on it, can you assign me the same.

**Comment by ankitzm** [comment]
hey @stackingsaunter, just saw that it uses [@bitcoin-design/bitcoin-icons-react](https://www.npmjs.com/package/@bitcoin-design/bitcoin-icons-react) for icons. Can you specify the icons listed from the list here - https://bitcoinicons.com/

**Comment by stackingsaunter** [comment]
Only magic wand is from bitcoin icons, help and connected sites are not and listed in the first post^
