### ISSUE TITLE
[BUG] If I click to login with Alby on Snort.oficial, then I click on Alby cancel button and click to login again, the Alby popup do not appear

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[BUG] If I click to login with Alby on Snort.oficial, then I click on Alby cancel button and click to login again, the Alby popup do not appear, but it should.

### Screenshots [optional]

See the video:

https://user-images.githubusercontent.com/1178856/226109952-c4dc9eca-5199-4dd2-b6b2-b9b8cb085af3.mp4

### Steps To Reproduce

1. Go to snort.oficial
2. Click to login with extension nip 07
3. Will show the Alby popup, close it, then click again on button Login with extension nip 07

### Expected behavior

The Alby popup show again.

### Alby information

Alby: 1.28.1

### Are you working on this?

No

**Comment by reneaaron** [comment]
Cancelling on the connect screen blocks subsequent requests from this site to prevent websites from spam-opening popups. You can reload the site to reset and will see the connect window again.

**Comment by haarts** [comment]
Reloading stacker.news after dismissing the pop-up doesn't make it reappear.

**Comment by reneaaron** [comment]
With dismissing you mean "blocking" it? Or simply closing it? Where do you exactly see this behavior?

 I just tested it by
 - going to the login page
 - clicking the QR
 - dismissing the alby popup
 - reloading the site
 - clicking the QR code triggers the popup again

**Comment by haarts** [comment]
No, not blocking it. 

With the Alby extension installed, I went to the home page. At that point Alby opened up asking if I wanted to connect (I _believe_ that's the word used). Then I clicked 'cancel'. After that I was unable to make that popup reappear.

Eventually, I was able to login by:
- clicking "login" on the home page
- clicking "login with lightning"
- copying the LNURL just below the QR code
- opening Alby
- clicking 'send'
- pasting the copied LNURL
- clicking 'continue' (at this point sometimes I got a very brief flicker showing the authentication screen but then a solid grey screen)
- clicking 'login' after being prompted if I wanted to login (this request sometimes times out)

I didn't know you could click the QR code! I tried that just now (N=1) and that popup up the the elusive pop-up!
