### ISSUE TITLE
Implement balance box on home popup screen 

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2236]
Currently, the only place we show user balance is account dropdown. As user balance is central and essential, we'd like to move it out from the dropdown ([which will be revamped as well](https://github.com/getAlby/lightning-browser-extension/pull/2195)) and place it on the home screen.

Proposed design:
<img width="828" alt="Screenshot 2023-03-18 at 19 04 29" src="https://user-images.githubusercontent.com/68239231/226125932-74e25099-b5d1-4d8a-a111-60bbbeb9719f.png">

Handoff ([Figma file here](https://www.figma.com/file/AMzMvcwrr2IdunqMakaB8r/navigation%2C-dropdown%2C-receive-onchain-work%2C-connectors%2C-nostr-events?node-id=126-22571)): 
<img width="730" alt="Screenshot 2023-03-18 at 19 05 53" src="https://user-images.githubusercontent.com/68239231/226125979-524341b1-cf57-45a2-a9a9-4395d3ec71f1.png">

Note: this issue relates to balance box only, not to the dropdowns on the screenshots (this is another issue: https://github.com/getAlby/lightning-browser-extension/pull/2195#issuecomment-1474933581)

Related issue: https://github.com/getAlby/lightning-browser-extension/issues/1490

**Comment by Tejasp2003** [comment]
i would like to work on this issue

**Comment by stackingsaunter** [comment]
@Tejasp2003 go ahead!

**Comment by lujakob** [comment]
@Tejasp2003 I have your issue as a dependency for the #2243 - so I will reuse the component you are creating. Would be good if you can keep in mind it will be reused in the bigger options screen. You can see the designs attached in my issue.

**Comment by 11WALTER11** [comment]
@stackingsaunter can i work on this issue?

**Comment by stackingsaunter** [comment]
@11WALTER11 sure, seems like @Tejasp2003 is not responding so go ahead!

**Comment by stackingsaunter** [comment]
> @stackingsaunter can i get access to the figma file ?

Granted

**Comment by lujakob** [comment]
@11WALTER11 please keep in mind this component will be reused on a normal page for #2243 when coding the HTML and CSS and ideally it would already behave responsive.

**Comment by ritikraj26** [comment]
I am willing to work on this issue. Is it still open?

**Comment by stackingsaunter** [comment]
@ritikraj26 there's already a PR, so I'm closing the issue

**Comment by reneaaron** [comment]
@ritikraj26 We assign issues as someone starts to work on them, so you could look for issues that haven't been assigned yet to find new tasks to work on.

**Comment by reneaaron** [comment]
We now have the balance in the popup's wallet screen! :partying_face:
