### ISSUE TITLE
Implement balance info into transacting inputs

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2237]
Because we're going to move balance from the [account dropdown to the home screen](https://github.com/getAlby/lightning-browser-extension/issues/2236), that will remove user's visibility of their balance while transacting.

I propose showing user balance under the input, whenever they need to pay. Then fiat value of sats can be moved inside the input, to the right side:

<img width="692" alt="Screenshot 2023-03-18 at 19 34 23" src="https://user-images.githubusercontent.com/68239231/226129277-0d59136c-851a-458c-b2dd-dad581b653bd.png">

Receive or setting allowence doesn't need to show balance:

<img width="723" alt="Screenshot 2023-03-18 at 19 36 47" src="https://user-images.githubusercontent.com/68239231/226129395-5b05e710-ffcc-4367-b939-6aa89cac5b9b.png">

Handoff (Figma file):

<img width="838" alt="Screenshot 2023-03-18 at 19 46 30" src="https://user-images.githubusercontent.com/68239231/226129914-15fcb09b-0bd3-44cc-b184-a797fa7d3fad.png">

**Comment by AdarshRawat1** [comment]
Requesting permission to contribute to this feature.

**Comment by reneaaron** [comment]
@AdarshRawat1 I just assigned you 🙌

**Comment by AdarshRawat1** [comment]
I have set up the extension locally on my system.Please, guide me on which files to change.
![image](https://user-images.githubusercontent.com/100958893/227840235-0bce702b-701d-4684-b0ee-55786098b866.png)

**Comment by reneaaron** [comment]
@AdarshRawat1 I think the file you want to edit is this one here: 

https://github.com/reneaaron/lightning-browser-extension/blob/master/src/app/screens/LNURLPay/index.tsx#L412-L421

The DualCurrencyField component has a `hint` prop that would probably allow you to add the balance in there.

**Comment by reneaaron** [comment]
@AdarshRawat1 I think the file you want to edit is this one here: 

https://github.com/reneaaron/lightning-browser-extension/blob/master/src/app/screens/LNURLPay/index.tsx#L412-L421

The DualCurrencyField component has a `hint` prop that would probably allow you to add the balance in there.

**Comment by reneaaron** [comment]
@AdarshRawat1 I think the file you want to edit is this one here: 

https://github.com/reneaaron/lightning-browser-extension/blob/master/src/app/screens/LNURLPay/index.tsx#L412-L421

The DualCurrencyField component has a `hint` prop that would probably allow you to add the balance in there.

**Comment by HARI-124** [comment]
Is this issue resolved?

**Comment by HARI-124** [comment]
Can I work on this issue?

**Comment by AdarshRawat1** [comment]
@HARI-124 thank you for your interest in solving this issue. But, I'm working on it . Please find something else that peeks your interest

**Comment by reneaaron** [comment]
@AdarshRawat1 When do you think will this be finished? Can you please submit a PR? 

We have recently merged the new account menu which makes this change a requirement for the next release. Please provide a timeline or allow others to work on this issue if you don't find the time.

**Comment by AdarshRawat1** [comment]
@reneaaron I'll submit a PR today itself .

**Comment by reneaaron** [comment]
@AdarshRawat1 Sure, no worries. 🙏  You want to pick this up from here, @HARI-124?

**Comment by HARI-124** [comment]
> @AdarshRawat1 Sure, no worries. 🙏 You want to pick this up from here, @HARI-124?

Yeah sure
