### ISSUE TITLE
Add "on-chain" tab to Receive screens when users use Alby Accounts

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2240]
Many users now [are seeking on-chain topup in the extension, not realising they can log in on getalby.com](https://github.com/getAlby/lightning-browser-extension/issues/2186) (If they're using Alby Account) and top up it there.

We should give some guidance to users that they can do that and the best place is Receive tab, where divide it into 2 tabs, one for Lightning (what we already have) and other screen which will just link to https://getalby.com/node/receive :

<img width="1098" alt="Screenshot 2023-03-20 at 12 03 40" src="https://user-images.githubusercontent.com/68239231/226321375-c5219192-e750-4a85-bb64-7a66f56a1dc0.png">

However, since we only offer onchain topup for Alby Account, this should be only displayed when users are using Alby Account (with @getalby.com). For all other connectors, nothing should change in Receive tag compared to what we have now.

"Go Alby Account on getalby.com ->" button should lead to https://getalby.com/node/receive

Handoff ([Figma file](https://www.figma.com/file/AMzMvcwrr2IdunqMakaB8r/navigation%2C-dropdown%2C-receive-onchain-work%2C-connectors%2C-nostr-events?node-id=74-8425))
<img width="1769" alt="Screenshot 2023-03-20 at 12 04 01" src="https://user-images.githubusercontent.com/68239231/226321449-f1b2434e-54c6-4049-a95d-7227b463ec39.png">

Icons used:
![Block](https://user-images.githubusercontent.com/68239231/226214373-2afd7405-0454-45f4-80cf-494757d4f4e6.svg)
![Lightning](https://user-images.githubusercontent.com/68239231/226214376-59aac946-bf1c-4961-90d3-de643e452654.svg)

**Comment by iampaandey** [comment]
Can you please assign this task to me ?  I can solve this issue.

**Comment by HARI-124** [comment]
Can I work on it?

**Comment by stackingsaunter** [comment]
yes, thanks @HARI-124 !

**Comment by HARI-124** [comment]
@stackingsaunter  Created PR for this issue
