### ISSUE TITLE
Add getBalance() to WebLN

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#2242]
### Feature description

`webln.getBalance()` should return the current balance in sats. 

### Describe the solution

**Extension**
- [ ] Add to `webln`
- [ ] Create a new permission to read the account balance

**Others**
 - [ ] Add docs to webln.guide
 - [ ] Create typings in webln typescript package

### Are you working on this?

None

**Comment by qqqzhch** [comment]
WebLN when there is a function to read the balance? Or is there a function to read the balance but the units are not what people want?
Is this method in the webln standard?
@reneaaron

**Comment by reneaaron** [comment]
> WebLN when there is a function to read the balance? Or is there a function to read the balance but the units are not what people want?

The format needs to be decided on. I currently think a response like this would make sense: 

```json
{
  balance: 123
}
```

Where the balance is returned in sats. 

>  Is this method in the webln standard?

Not yet.
