### ISSUE TITLE
Merge Send, Receive and Transactions pages into "Wallet"

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2243]
Currently, in extended view of the extension we have 3 seperate pages for functionalities that are accessible from the main popup screen:
<img width="630" alt="Screenshot 2023-03-20 at 13 32 01" src="https://user-images.githubusercontent.com/68239231/226339735-d5bbd267-b6e0-467b-871e-b16ce4fa75ea.png">

We'd like to merge them into one Wallet page:
<img width="1430" alt="Screenshot 2023-03-20 at 13 33 55" src="https://user-images.githubusercontent.com/68239231/226340046-cea2aea1-df4d-4f1e-ac01-b31c060d3228.png">

"Receive" and "Send" pages would be accesible from respectively  Receive & Send buttons from this Wallet page. "See all transactions" should open to the page that is currently under "Transactions".

This page includes new balance box that has to be implemented first: https://github.com/getAlby/lightning-browser-extension/issues/2236

Handoff ([Figma file](https://www.figma.com/file/AMzMvcwrr2IdunqMakaB8r/navigation%2C-dropdown%2C-receive-onchain-work%2C-connectors%2C-nostr-events?node-id=162-26570)):
<img width="1414" alt="Screenshot 2023-03-20 at 13 45 39" src="https://user-images.githubusercontent.com/68239231/226342668-7b8a246d-9b74-4f17-932c-97af2dc5ebf7.png">

**Comment by lujakob** [comment]
@stackingsaunter I could work on it, I already worked on transactions. I am in discussion in the ticket about pagination and unifying of "transactions", but I think this is not easily possible, due the fact how invoices are fetched and connector invoices limitations. This is sort of on hold currently.

**Comment by reneaaron** [comment]
@lujakob Yeah, that needs some more thought, I'll have to dig a bit deeper there. Sorry for the delay.

If you want to continue with this one in the meantime I'd be more than happy to get your help. 🙏

**Comment by lujakob** [comment]
@reneaaron from my current point of view unifying incoming and outgoing with pagination is not possible. First of all the connector API's don't support delivering the "total" of invoices. Second, most of the connectors don't support paginated data yet and third, the problem of not being able to predict the ratios of incoming/outgoing list items in each page. So I think it makes sense to keep the lists separated for now and continue with the approach of this issue.

**Comment by reneaaron** [comment]
@lujakob Let's continue our discussion in the original issue. I didn't give up on it, yet. 😄 

For this issue this is irrelevant I think, so 👍 for continuing with the approach of this issue.

**Comment by lujakob** [comment]
> I didn't give up on it, yet. 😄

Oh yesss. I was testing your attitude ;-)

**Comment by HARI-124** [comment]
Is this issue still open?

**Comment by stackingsaunter** [comment]
I think @lujakob is tackling this alongside other issues

**Comment by lujakob** [comment]
@stackingsaunter which icon should I use for the "Wallet" menu item in the popup dropdown menu? Could you recommend or provide one please?

<img width="252" alt="Bildschirmfoto 2023-04-09 um 12 47 52" src="https://user-images.githubusercontent.com/886152/230788420-0d8b357e-30ff-4e5e-bb9e-2c0f55dfac43.png">

**Comment by stackingsaunter** [comment]
@lukeojones Websites is changing name and there's a new icon for it and Help, Feedback and Discover, see: https://github.com/getAlby/lightning-browser-extension/pull/2289

In that PR, we are also not showing items in the hamburger menu that are available in the top navigaton (when user is in extended view). There's no reason to show twice the same item. So in the case of Wallet page, it shouldn't be in the hamburger menu at all. On extended view it's in top nav and on popup view it's the main view so we don't need it in hambuerger at all :)

**Comment by stackingsaunter** [comment]
@rolznz you're right, it's a bit confusing. We use those boxes on many transactional screens and they look the same as send/receive buttons, see:

<img width="502" alt="Screenshot 2023-04-11 at 13 14 28" src="https://user-images.githubusercontent.com/68239231/231143817-c7d780c5-ba0f-48a2-b6eb-750b49c7aa41.png">

This is probably for separate issue to resolve this and get rid of boxes or make buttons look a bit different. Should we just merge it as it is now and handle this all together with all those conflicts in the app in seperete issue? also cc @reneaaron 

Some potential quick solutions for balance box:

1.
<img width="352" alt="Screenshot 2023-04-11 at 13 16 14" src="https://user-images.githubusercontent.com/68239231/231144360-f7a9d0fd-b413-4b37-b981-d79a8a4d17c2.png">
<img width="935" alt="Screenshot 2023-04-11 at 13 16 26" src="https://user-images.githubusercontent.com/68239231/231144428-8fef3c2d-d163-4f75-ad56-fb521caf32ac.png">

2. 
<img width="249" alt="Screenshot 2023-04-11 at 13 17 41" src="https://user-images.githubusercontent.com/68239231/231144906-9044e08a-1b59-45f3-9aca-38c7e097de6c.png">
<img width="783" alt="Screenshot 2023-04-11 at 13 17 57" src="https://user-images.githubusercontent.com/68239231/231144977-c576771d-2fae-4ede-8277-53352c70f8d7.png">

**Comment by rolznz** [comment]
1. Looks great!

**Comment by lujakob** [comment]
@rolznz @stackingsaunter if the styles conflict of boxes and buttons is affecting components/screens other than wallet, let's do this in a separate issue as a follow up.

**Comment by lujakob** [comment]
> @lujakob Websites is changing name and there's a new icon for it and Help, Feedback and Discover, see: #2289
> 
> In that PR, we are also not showing items in the hamburger menu that are available in the top navigaton (when user is in extended view). There's no reason to show twice the same item. So in the case of Wallet page, it shouldn't be in the hamburger menu at all. On extended view it's in top nav and on popup view it's the main view so we don't need it in hambuerger at all :)

All of the popup dropdown menu items open the "extended view" (options page). So even though the default view of the popup shows the "transactions"/"wallet", I would still keep the "Wallet" menu item in there, to be able to open it in the "extended view". At least to me it would make sense for consistency reasons. And it doesn't hurt.

But I'm open. What do @reneaaron @rolznz think?

**Comment by lujakob** [comment]
Regarding navigation changes, I will wait to finalize until #2289 is merged into master.

**Comment by stackingsaunter** [comment]
> I would still keep the "Wallet" menu item in there, to be able to open it in the "extended view".

Yes, it should be there but only in navigation bar, not in the dropdown
