### ISSUE TITLE
Feature Request: Updating translation file for Hindi language

### ISSUE THREAD

**Issue by SiddheshKukade** [getAlby/lightning-browser-extension#2244]
### Feature description

The existing [translation file for `Hindi` ](https://github.com/getAlby/lightning-browser-extension/blob/master/src/i18n/locales/hi/translation.json) is incomplete (around 50 lines ) and the current [English translation ](https://github.com/getAlby/lightning-browser-extension/blob/master/src/i18n/locales/en/translation.json)is having more than 1000 lines in it. 

### Describe the solution

There should be further translation added in Hindi language to match it with English file ( because it is the most update one).

### Additional context

I have recently worked on the translation for `Marathi` language translation (#2220) and `Hindi` is relatively similar to marathi. I also use this language daily here in India. 
It is the most spoken language in India according to [Wikipedia with over 500 Million ](https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers_in_India#) speakers from a census report of 2011

### Are you working on this?

Yes

**Comment by SiddheshKukade** [comment]
@MoritzKa can I work on this ?

**Comment by Devika0713** [comment]
@escapedcat  as an Indian, I would be really grateful to contribute to something that will make this site more accessible to Indians. So @SiddheshKukade can I work on this with you?

**Comment by SiddheshKukade** [comment]
@Devika0713 the work is already compled.
