### ISSUE TITLE
Revamp forms layout in onboarding screens

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2250]
There's currently a lot of inconsistencies regarding layout on onboarding & connector screens and this is a proposition to improve them a bit, eg:
<img width="723" alt="Screenshot 2023-03-22 at 01 17 38" src="https://user-images.githubusercontent.com/68239231/226770234-8a990874-a241-4d0c-b7d5-4edb0b6b4b75.png">

I propose changes to the design to make it more cohesive, declutter it a bit, make it a bit clearer for users to go through:
- make forms a vertical 600px wide box with 40px margins (if there are any screenshots/videos they can be placed within the layout)
- delete Alby bee from forms
- delete back button from forms (we don't use it anywhere else, users can use their browser back button, we will need another 2 buttons layout in a new onboarding screen which would force us to have 3 buttons there if we'd like to keep back button)
- all buttons under the forms should have fixed 256px size (same size as we use in settings)
- spacing between header and first paragraph should be 16px
- standard spacing between items in form should be 24px (there might be some cases where it's better to have in bigger though)
- connector forms now display a connector logo (64x64px) next to the header

You can see the changes here (or in [Figma file](https://www.figma.com/file/AMzMvcwrr2IdunqMakaB8r/navigation%2C-dropdown%2C-receive-onchain-work%2C-connectors%2C-nostr-events?node-id=38-4400&t=vmLhv4UDl7bFNrWm-0)):

<img width="756" alt="Screenshot 2023-03-22 at 01 33 27" src="https://user-images.githubusercontent.com/68239231/226771994-90fcb521-8964-41a9-9467-2a01afc6d2aa.png">

<img width="1065" alt="Screenshot 2023-03-22 at 01 31 17" src="https://user-images.githubusercontent.com/68239231/226771756-85fbe83e-04f5-4cc8-9e70-ba6862e6a13f.png">

<img width="935" alt="Screenshot 2023-03-22 at 01 31 35" src="https://user-images.githubusercontent.com/68239231/226771783-ec1ac2bd-8703-4818-bdba-91d08ce0de2d.png">

<img width="728" alt="Screenshot 2023-03-22 at 01 31 53" src="https://user-images.githubusercontent.com/68239231/226771813-feb74cf5-038b-4a65-9f8f-3ddc4c8e8056.png">
<img width="782" alt="Screenshot 2023-03-22 at 01 32 14" src="https://user-images.githubusercontent.com/68239231/226771865-db61357a-62a6-47d1-9abf-dd2f584b0ab3.png">

**Comment by fczuardi** [comment]
Hi, I think I can tackle this, do I need to requeest Figma access or the images here plus the issue description are enough?

**Comment by stackingsaunter** [comment]
Hey @fczuardi great! I granted you Figma access. Note that there are some other changes to those screens there as well, but those will land in seperate issues. No new images needed, all is already used in the extension, just in different layout

**Comment by fczuardi** [comment]
ok @taboca (https://github.com/taboca) will be helping me on this one, if you can accept his figma access request as well

**Comment by fczuardi** [comment]
@stackingsaunter what do you mean by:

> delete Alby bee from forms

**Comment by fczuardi** [comment]
also, how do I access the set unlock password screen after I have passed through it the first time (in Firefox)?

**Comment by fczuardi** [comment]
Why some wallets have links in their connector titles while others dont? example: Eclair vs LND:

![image](https://user-images.githubusercontent.com/7760/229664968-809b089c-baf2-40c8-920d-3cdb3dca9928.png)

![image](https://user-images.githubusercontent.com/7760/229665164-fcab0634-f297-4412-b798-89a14fd793aa.png)

Maybe we can handle this inconsistency in another issue...

**Comment by stackingsaunter** [comment]
@reneaaron do you think we need those link at all? Is there a valid case where users need to find out what they are connecting with? :P Perhaps it's a good time to get rid of them if @fczuardi is working on this

**Comment by reneaaron** [comment]
I think the idea was that this page could be used to also discover node distributions. Not sure if that makes sense, feel free to remove it if you don't think so.

**Comment by stackingsaunter** [comment]
@reneaaron you're right, in this case this is probably needed. Although I still find it strange we have a Kollider sign up there

**Comment by fczuardi** [comment]
are thesignup and login buttons on the new Kollider screen actually working?

**Comment by fczuardi** [comment]
this patch fixes the clicks:

```diff
diff --git a/src/app/router/connectorRoutes.tsx b/src/app/router/connectorRoutes.tsx
index 8285dd7b..a625a42f 100644
--- a/src/app/router/connectorRoutes.tsx
+++ b/src/app/router/connectorRoutes.tsx
@@ -69,11 +69,14 @@ function getConnectorRoutes() {
     },
     {
       path: "kollider",
-      element: <ConnectKollider variant="select" />,
       title: i18n.t("translation:choose_connector.kollider.title"),
       description: i18n.t("translation:choose_connector.kollider.description"),
       logo: kolliderLogo,
       children: [
+        {
+          index: true,
+          element: <ConnectKollider variant="select" />,
+        },
         {
           path: "create",
           element: <ConnectKollider variant="create" />,
```

**Comment by ritikraj26** [comment]
Hey, I think I can tackle this issue. Do I need Figma access for this?

**Comment by stackingsaunter** [comment]
@ritikraj26 seems like @fczuardi is working on this. Let's ask him if so and if he needs a hand!

**Comment by fczuardi** [comment]
We are working on this branch https://github.com/getAlby/lightning-browser-extension/pull/2284

**Comment by fczuardi** [comment]
hi @stackingsaunter we believe the PR is good to be reviewed now :)

**Comment by taboca** [comment]
Thanks @stackingsaunter for helping us on https://github.com/getAlby/lightning-browser-extension/pull/2284#issuecomment-1513233092
