### ISSUE TITLE
Add intermediary steps for personal nodes that can run multiple implementations

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2254]
Related to https://github.com/getAlby/lightning-browser-extension/issues/1835 
Dependent on https://github.com/getAlby/lightning-browser-extension/issues/2203

Some nodes can have multiple apps/connectors and currently we assume only one (LND). Good example is Umbrel, which leads straight to LND connector, while Umbrel users run CLN on Umbrel as well, or can connect using LNC.

Those connectors with multiple apps/nodes should have intermediary step when users can choose which implementation they run. That step can utilize cards design from main connectors screen. I also included here minor changes to Umbrel display of LND and LNC. Here are steps for Umbrel, BTCPay, Citadel, RaspiBlitz, myNode and Start9

**Umbrel:**
<img width="869" alt="Screenshot 2023-03-23 at 02 02 46" src="https://user-images.githubusercontent.com/68239231/227072313-84f77652-c007-49c5-8a33-fcba8d2b7488.png">

Changes in connectors:
- **Lightning Node** should lead to what is currently under Umbrel connector 
- **Lightning Terminal**  (LNC) should lead to what is currently "LNC with LND" 

**Citadel:**
<img width="926" alt="Screenshot 2023-03-23 at 02 04 27" src="https://user-images.githubusercontent.com/68239231/227072475-56c59634-dda5-4857-b7bf-524a0ec6aec8.png">
- **Citadel Login** should lead what is currently Citadel
- the rest can lead to standard LNC, CLN and lnbits connectors.

**BTCPay:**
<img width="844" alt="Screenshot 2023-03-23 at 02 05 20" src="https://user-images.githubusercontent.com/68239231/227072561-a6064440-1334-479d-898f-737e1a6bf3f9.png">

- **LND** should lead to what is currently BTCPay
- **Core Lightning** should lead to currently missing https://github.com/getAlby/lightning-browser-extension/issues/2203

**RaspiBlitz, myNode, start9**
<img width="832" alt="Screenshot 2023-03-23 at 02 04 59" src="https://user-images.githubusercontent.com/68239231/227072521-c0b8071e-aa15-401c-bcf5-1f9d159f3e74.png">

- LND on those screens should lead to what is currently under RaspiBlitz, myNode or Start9 connectors
- the rest can lead to standard LNC, CLN, lnbits

New images:
![image](https://user-images.githubusercontent.com/68239231/227066695-efd236ba-f239-4c54-b39c-c245be50d4b5.png)

![image](https://user-images.githubusercontent.com/68239231/227066716-0e207ddd-4628-4958-91ff-a4f423bce653.png)
 
![image](https://user-images.githubusercontent.com/68239231/227066847-1c733bd5-220a-43a0-8116-bb436face960.png)
(Updated Core Lightning logo)

**Comment by lujakob** [comment]
@reneaaron you can assign it to me.

**Comment by lujakob** [comment]
@reneaaron @stackingsaunter my approach would be to create new components `ChooseUmbrelConnector` that display the new intermediary screen. 

Regarding the "Changes in connectors" for Umbrel. 
The first: I would rename the connector `ConnectUmbrel` -> `ConnectUmbrelLndConnect`.
The second: Lightning Terminal  (LNC) should lead to what is currently "LNC with LND" - is there any difference between this one if I come from the Umbrel selection or if I choose it directly?

The last question refers to all connectors that can be choosen from an itermediary step but also directly: is there any display difference, e.g. text?

**Comment by stackingsaunter** [comment]
> Lightning Terminal  (LNC) should lead to what is currently "LNC with LND" - is there any difference between this one if I come from the Umbrel selection or if I choose it directly?

No, they can lead to the same screen. 



> The last question refers to all connectors that can be choosen from an itermediary step but also directly: is there any display difference, e.g. text?

No difference, at least for now. We later may split them and add more details instructions from the interfaces, but for this issue this is out of scope I think

**Comment by reneaaron** [comment]
After trying to debug this issue I found out that BTCPay Server doesn't ship core-lightning plugins (or connection credentials related to them). That means we would have to re-implement a core-lightning connector using the [REST APIs](https://github.com/Ride-The-Lightning/c-lightning-REST) provided through BTCPay Server instead of using the current implementation that is using `commando` to communicate with the node. 

For future reference, the config URL returns this JSON for core-lightning nodes: 

```js
{
    "configurations": [
        {
            "uri": "https://btcpayserver.example.com/clightning-rest/btc",
            "chainType": "Mainnet",
            "type": "clightning-rest",
            "cryptoCode": "BTC",
            "certificationThumbprint": null,
            "macaroon": "0201010b...",
            "adminMacaroon": null,
            "readonlyMacaroon": null,
            "invoiceMacaroon": null,
        }
    ]
}
```

Let's discuss that in tomorrows community call maybe @lujakob.
