### ISSUE TITLE
Update LNC and Umbrel LND connrectors content

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2258]
Umbrel connector content is out of date. Both copy and video there relates to previous Umbrel design:
<img width="1390" alt="Screenshot 2023-03-23 at 11 30 45" src="https://user-images.githubusercontent.com/68239231/227176351-6d79a328-ef61-4284-9e7d-3663cd431db9.png">

Let's update the copy with:

1. In your Lightning Node dashboard go to **Connect wallet**
2. Select **REST (Tor)** or **REST (Local Network)** mode
3. Copy the **lndconnect URL** and paste it below

And change the video to this screenshot:

![image](https://user-images.githubusercontent.com/68239231/227179114-9ccd042a-9996-4298-ac3a-38f64adc4ff3.png)

---

We can update LNC connector as well.

Current version:
<img width="1327" alt="Screenshot 2023-03-23 at 11 40 51" src="https://user-images.githubusercontent.com/68239231/227178619-b1e217f0-1424-449b-a7c6-caf24a4d67dc.png">

Updated copy:
1. On Lightning Terminal sidebar choose **Lightning Node Connect**
2. Click **Create a new session**
3. Label the session, choose desired permissions and submit
4. **Copy pairing phrase** and paste it below

Added screenshot (insead of Alby logo):
![image](https://user-images.githubusercontent.com/68239231/227179356-9100768e-8bcb-4c3c-9701-f746778a87cc.png)

**Comment by AdarshRawat1** [comment]
I can tackle this issue!

**Comment by stackingsaunter** [comment]
@AdarshRawat1 great, go for it

**Comment by mviswanathsai** [comment]
Can I be assigned this issue, if no one else is working on it?

**Comment by AdarshRawat1** [comment]
@mviswanathsai thankyou for your interest in solving this issue.But, I'm working on it . Please look for any other issue that peeks your interest.

**Comment by mviswanathsai** [comment]
@AdarshRawat1 I am sorry but since the issue has been assigned long back I assumed no one is working on it and have created a PR.

**Comment by mviswanathsai** [comment]
@stackingsaunter I have solved this issue, is it ok if I link the PR here? Sorry I just started working on it since it seemed to be inactive.

**Comment by AdarshRawat1** [comment]
@mviswanathsai I apologize for any misunderstanding.

**Comment by mviswanathsai** [comment]
@AdarshRawat1 it's all good, no issues!
