### ISSUE TITLE
[Feature] (UI): Request to add micro-interaction to top nav-bar buttons for better User experience

### ISSUE THREAD

**Issue by thetimileyin** [getAlby/lightning-browser-extension#2259]
### Feature description

Currently, the top nav-bar buttons on Alby has no interaction when users hover on them. This doesn’t seem to be the best user experience for users of Alby.

https://user-images.githubusercontent.com/105345830/227198703-e8814146-120c-4db4-9e04-13ca1399aba7.mov

### Describe the solution

Would love to add a micro-interaction to the buttons when users hover on a particular button.

Like this: 

https://user-images.githubusercontent.com/105345830/227202986-1747c2da-c0f8-461f-b31f-1cfd8c096b69.mov

### Are you working on this?

Yes

**Comment by stackingsaunter** [comment]
This is good point, but I'd make the hover state appear faster, it seems to slow on your video

**Comment by thetimileyin** [comment]
> This is good point, but I'd make the hover state appear faster, it seems to slow on your video

Yeah, It probably slow because of my video recording but I guess it could be faster. Say maybe Instant or smart animate at 100ms

**Comment by reneaaron** [comment]
Good point @thetimileyin! I think we use `duration-200` through our codebase. 

Please also consider doing the same for dark mode. (you can change the theme in your settings)

**Comment by thetimileyin** [comment]
Thank @reneaaron, actually I am a designer and I already added the change to my own Figma duplicate. Here is the link: https://www.figma.com/file/4uOtvSSVIeRrtVE199R9pe/Alby-Extension-Master-Design-(Copy)?node-id=183-15355&t=EZWB2MCdTbbVf04l-0

**Comment by reneaaron** [comment]
Oh, okay. 😅 @stackingsaunter You good with this change? I can implement the changes...
