### ISSUE TITLE
[BUG] I tried to send sats using Alby account but payment didn't go but the balance decreased 

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I tried to send sats using Alby account but payment didn't go but the balance decreased. 

### Steps To Reproduce

1- Try to send a payment that will fail but stay in limbo for a period

### Expected behavior

I expected that Alby extension record the transaction on transaction history as "pending" status and that the funds will return to user balance after a period. And when funds return, Alby could notify the user about it.

### Alby information

Alby: 1.28.1

### Are you working on this?

No

**Comment by reneaaron** [comment]
> 1- Try to send a payment that will fail but stay in limbo for a period

What do you mean with "stay in limbo"? Can you provide steps to reproduce this behavior?

**Comment by bitcoinuser** [comment]
> > 1- Try to send a payment that will fail but stay in limbo for a period
> 
> What do you mean with "stay in limbo"? Can you provide steps to reproduce this behavior? Are we talking about HODL invoices here? (that would perfectly explain this behavior)

I just paid an invoice from Alby account to my own node and I think because the amount was very high, the payment failed, but no instantly, so probably the HTLC thing to wait to return. 

cc @bumi

**Comment by HARI-124** [comment]
Is this issue solved if not can you provide screenshots of that issue?

**Comment by bumi** [comment]
This is solved, when a payment somehow fails on route it will be credited again after a timeout. For security reasons this can take a bit.
