### ISSUE TITLE
Improvement: add current account or account selection in payment popup

### ISSUE THREAD

**Issue by cryptoteun** [getAlby/lightning-browser-extension#228]
I have multiple accounts added to the extension. 
When I have to pay it's not clear in the popup from which account the payment will be done:

![Screenshot from 2021-09-13 20-34-59](https://user-images.githubusercontent.com/73664763/133138363-3dadbf04-06c6-4fc4-ab01-94372ad61ff0.png)

In my opinion two options for improvement:
1. show the current wallet in the pop
2. add a dropdown from were you can select the account to be used

**Comment by cryptoteun** [comment]
Already mentioned this one to @bumi on telegram.

**Comment by bumi** [comment]
this is shipped :shipit: \o/
