### ISSUE TITLE
[BUG] "Copy Invoice" should be made into more intuitive text

### ISSUE THREAD

**Issue by SveeJ** [getAlby/lightning-browser-extension#2290]
### Describe the bug

When the scan QR screen opens for receiving sats, there is a QR that can be used to generate an invoice string that can be pasted in the send section of the extension. I think the 'copy' text should be replaced due to the fact that it's unintuitive to the end-user what it is that is being copied. Changing it to something along the lines of: 

Copy Invoice String or Copy Invoice Code or simply Copy Invoice (looking for community feedback) would be most optimal

<img width="383" alt="unintuitive text" src="https://user-images.githubusercontent.com/62150721/228510797-1c4443a4-0fb2-4c96-8d5c-8745e45763dd.png">

### Steps To Reproduce

1. Click on Receive
2. Generate an Invoice
3. Click on Copy

### Expected behavior

(Copy Invoice String/Code)

### Alby information

Alby 1.28.1

**Comment by escapedcat** [comment]
@stackingsaunter wdyt?

**Comment by stackingsaunter** [comment]
Copy Invoice suits the best. Many people don't know what string is and I don't think "code" describes it well, so just Copy Invoice

**Comment by mohitvdx** [comment]
"Copy address"
being more commonly used. what do you think?

**Comment by stackingsaunter** [comment]
"Address" is incorrect, this is not an address. Let's stay with Copy Invoice

**Comment by SveeJ** [comment]
Alright perfect could I be assigned this issue?
