### ISSUE TITLE
[BUG] Correct upper helper text in inputs coloring

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2291]
Current upper helper text in inputs is black in both light and dark theme (currently used only for range amounts defined by LNURL).

<img width="655" alt="Screenshot 2023-03-29 at 23 53 17" src="https://user-images.githubusercontent.com/68239231/228676170-5a39e11c-08fa-4e48-b6d0-efeb4d8fe3ab.png">

<img width="653" alt="Screenshot 2023-03-29 at 23 47 26" src="https://user-images.githubusercontent.com/68239231/228675162-4591631f-d4c5-4a28-8285-8970d40ab3a4.png">

This element should have different colors:
Light theme: gray-700
Dark theme: neutral-400 

<img width="813" alt="Screenshot 2023-03-29 at 23 56 23" src="https://user-images.githubusercontent.com/68239231/228676689-940259bb-d108-4b61-a93c-9a02355dbd8d.png">

**Comment by PUJAmangale1221** [comment]
Hey Maintainers, I would like to resolve this issue could you please help me to go ahead...!!

**Comment by stackingsaunter** [comment]
@PUJAmangale1221 @devjakubN I think this guide is a good place to start https://github.com/getAlby/lightning-browser-extension/blob/master/doc/CONTRIBUTION.md

**Comment by SveeJ** [comment]
Hi! Could I please be assigned this issue?

**Comment by Pratik-A-N** [comment]
Is this issue under review or I can work on this ??

**Comment by stackingsaunter** [comment]
@SveeJ are you working on this or can @Pratik-A-N take over?

**Comment by stackingsaunter** [comment]
I am assigning you, @Pratik-A-N go ahead

**Comment by SveeJ** [comment]
Hi sorry for the late response. Was not present for health reasons. I'm glad it's taken over.

**Comment by Pratik-A-N** [comment]
![Screenshot from 2023-04-07 02-32-54](https://user-images.githubusercontent.com/91190547/230493494-c32123eb-2695-4dee-9df2-054469ca9c1b.png)
Hi, I'm not able to see the text whose style needs to be fixed. @stackingsaunter can you please tell how do I regenerate this issue in my local setup??

**Comment by stackingsaunter** [comment]
@Pratik-A-N you can see them by pasting those LNURL invoices into Send 

https://github.com/getAlby/lightning-browser-extension/wiki/%F0%9F%A4%A0-Alby-in-the-wild#lnurls

<img width="407" alt="Screenshot 2023-04-07 at 13 38 09" src="https://user-images.githubusercontent.com/68239231/230602676-ec3ad178-ee2c-4014-a45b-015df601c396.png">
