### ISSUE TITLE
Style disabled state of inputs

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2292]
This design is dependent and assumes this update https://github.com/getAlby/lightning-browser-extension/issues/2237 to input will occur (mostly moving fiat amount inside the input) and that those corrections to helper (amount) input will be made https://github.com/getAlby/lightning-browser-extension/issues/2291

Current disabled input state (eg. Nostr public key) look the same as filled state, which may cause bad UX for people in some cases. 

I propose making disabled state visually different, like this (only inside of the input changes the styling):

Light theme: input bg: gray50
Dark theme: input bg: surface16dp
Text inside the input (both themes): gray500

<img width="847" alt="Screenshot 2023-03-29 at 23 58 47" src="https://user-images.githubusercontent.com/68239231/228677085-6d330673-dd0c-4a64-ae7d-f5c3eb32372a.png">

**Comment by stackingsaunter** [comment]
Yes, of course

**Comment by Pratik-A-N** [comment]
Hello, can you please tell me how to start the local development setup I have forked the repository and created my account in the wallet. following [this](https://github.com/getAlby/lightning-browser-extension/blob/master/doc/CONTRIBUTION.md) but not able to get it.

**Comment by Pratik-A-N** [comment]
@stackingsaunter can you please tell me how do I regenerate this issue??

**Comment by Pratik-A-N** [comment]
I have made a PR can you please review it @stackingsaunter ??

**Comment by Pratik-A-N** [comment]
I have now used the prettier format and changed the files accordingly but am not able to get why the E2E test failed?? can you please explain

**Comment by stackingsaunter** [comment]
@Pratik-A-N will test it again when build will be updated by github bot^
