### ISSUE TITLE
Update on QR Scan Page

### ISSUE THREAD

**Issue by maxatic** [getAlby/lightning-browser-extension#2294]
### What I want to implement?
Hello everyone! I want to change the QR scan UI design. The issue is that when we come to the "Scanning QR" page, there is no necessary color palette used by Alby except for white and its shadows. I want to make changes by mainly adjusting four capture elements in the scan camera. Specifically, I want to change the color to "orange" and increase the corner radius to 7 to make it more rounded.

### Why we need to implement it?

There are mainly two reasons for these changes:

1. There are no "Alby" colors used on this page, which makes it look out of design for me.
2. Changing the corner radius is intended to make it more consistent with Alby's design, since we use corner radius values from 5 to 9 in many elements.

### How to implement it?
Simply go to this [figma link](https://www.figma.com/file/09unIvR90lEDYGgHBJWyVL/maxatic_alby-issues?node-id=0%3A1&t=SFgl6QCc5d8768DH-1) I created and see all necessary details.

### Screenshot of what I did

![Scanning_QR](https://user-images.githubusercontent.com/68378768/228795258-9582e05f-a797-4780-89f2-2af762387260.png)

**Comment by Devika0713** [comment]
Hey, this is something I would like to work on.Is it possible to assign this to me?

**Comment by AdarshRawat1** [comment]
@reneaaron please guide on how can I start customizing the QR code scanner? 
 
- Apply custom CSS styles to the scanner container element.
or 
- Design a custom SVG icon using the desired color.

**Comment by reneaaron** [comment]
@AdarshRawat1 I don't think the library in use here has any options to customize the look & feel: (not even hide the existing box)

https://scanapp.org/html5-qrcode-docs/docs/apis/classes/Html5Qrcode

I don't think we would want to overlay the existing box with a custom one, not sure if this "feature" is that important to justify that much of customization.

**Comment by AdarshRawat1** [comment]
> @AdarshRawat1 I don't think the library in use here has any options to customize the look & feel: (not even hide the existing box)
> 
> https://scanapp.org/html5-qrcode-docs/docs/apis/classes/Html5Qrcode
> 
> I don't think we would want to overlay the existing box with a custom one, not sure if this "feature" is that important to justify that much of customization. 

Thank you @reneaaron , noted!
