### ISSUE TITLE
Bug: Settings- bottom div not displaying correctly due to missing margin

### ISSUE THREAD

**Issue by 11WALTER11** [getAlby/lightning-browser-extension#2299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code Ref. :
Inside ```src/app/screens/Settings``` Line no ```398```

``<div  className="shadow bg-white sm:rounded-md sm:overflow-hidden px-6 py-2 divide-y divide-black/10 dark:divide-white/10 dark:bg-surface-02dp">``

### Bug Description

Under Legacy settings we can see ```Legacy LNURL-Auth``` & ``` Legacy signing for LNDhub and LNbits```  toggle button's Parent DIV is touching the bottom leading to bad UX

![UI_bug](https://user-images.githubusercontent.com/81313264/229370424-b9bfda84-d584-4e79-8d24-cb24dd31b6b9.png)

### Steps To Reproduce

1- Visit [chrome-extension://iokeahhehimjnekafflcihljlcjccdbe/options.html#/settings](url)
2- Scroll down to end of the setting page 
3- You can see ```Legacy LNURL-Auth``` & ``` Legacy signing for LNDhub and LNbits```  toggle button's Parent DIV is touching the bottom

### Expected behavior

![bug-fixed](https://user-images.githubusercontent.com/81313264/229349971-be0a384f-f434-4a2f-af45-181f62630552.png)

### Alby information

- Alby Version: [1.28.1]
- Alby installed through : [Chrome web store]
- Wallet connected with Alby : [not connected]

### Device information

- OS:[Windows 11]
- Browser:[ Google Chrome]
- Browser Version : [Version 111.0.5563.147 (Official Build) (64-bit)]

### Are you working on this?

Yes

**Comment by Pratik-A-N** [comment]
Can I work on this issue ??

**Comment by 11WALTER11** [comment]
@stackingsaunter, could you please review this? I have completed the solution and am waiting for the green flag!

**Comment by stackingsaunter** [comment]
thanks @11WALTER11, are you willing to prepare a PR? If yes then I think you can go ahead!

**Comment by 11WALTER11** [comment]
@stackingsaunter Done #2304
