### ISSUE TITLE
[BUG] Flaky E2E tests

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#2321]
### Describe the bug

E2E tests randomly failing most of the time. 

### Steps To Reproduce

See recent E2E builds.

### Expected behavior

Green tests.

**Comment by fczuardi** [comment]
Trying to reproduce the flakiness on my environment, what I did was to insert a `.only` in the [first test of the createWallet spec](https://github.com/getAlby/lightning-browser-extension/blob/master/tests/e2e/001-createWallets.spec.ts#L96) and then on the terminal run:

```
yarn run playwright test tests/e2e/001-createWallets.spec.ts
```

And sometimes the test would pass and some other times it would fail with a Timeout error:

```
yarn run v1.22.19
$ /home/fcz/github/lightning-browser-extension/node_modules/.bin/playwright test tests/e2e/001-createWallets.spec.ts

Running 1 test using 1 worker

  ✘  1 [chromium] › 001-createWallets.spec.ts:96:8 › Create or connect wallets › successfully creates an Alby wallet (30.0s)


  1) [chromium] › 001-createWallets.spec.ts:96:8 › Create or connect wallets › successfully creates an Alby wallet 

    Test timeout of 30000ms exceeded.

  Slow test file: [chromium] › 001-createWallets.spec.ts (30.0s)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    [chromium] › 001-createWallets.spec.ts:96:8 › Create or connect wallets › successfully creates an Alby wallet 
error Command failed with exit code 1.

```

On one instance of this error, I noticed that there were a toaster/popup error message in the browser screen and I was able to screenshot it:

![image](https://user-images.githubusercontent.com/7760/232944781-efa7d7be-6ca9-49be-914a-767991274729.png)
