### ISSUE TITLE
[BUG] Improve UX for the user on the connect your lightning wallet page.

### ISSUE THREAD

**Issue by legendarykamal** [getAlby/lightning-browser-extension#2330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Notice that the UI doesnt intutively tells the user to choose one path which in many cases can make the user think if they are 2 separate steps to be taken inorder to do the setup.

Improve UX for the user on the connect your lightning wallet page.

### Screenshots [optional]

![image](https://user-images.githubusercontent.com/95926324/230785796-4a55417e-0a2c-4cdd-ba37-a2356444fff5.png)

### Steps To Reproduce

1. While setting up your Alby account and  on the connect your lightning wallet page.

2. Notice that the UI doesnt intutively tells the user to choose one path which in many cases can make the user think if they are 2 separate steps to be taken inorder to do the setup.

### Expected behavior

"OR" word should be mentioned in the UI.

### Alby information

Alby version 1.28.1

### Device information

-OS : Windows

### Are you working on this?

Yes

**Comment by legendarykamal** [comment]
@stackingsaunter what are your views on this ?

**Comment by stackingsaunter** [comment]
@legendarykamal it's funny, I actually included "or" in between of those cards in initial design. But we thought it looks a bit strange so decided not to include it. 

Do you think adding "or" in the copy under "Connect" will be a good solution? See screenshot:

<img width="739" alt="Screenshot 2023-04-11 at 00 21 33" src="https://user-images.githubusercontent.com/68239231/231010072-06a418c2-88b0-40c2-be92-2724a94796a7.png">
