### ISSUE TITLE
Add "Pin your Alby Extension" screen as last onboarding step

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2343]
We want to make sure people are pinning the extension in the browser. Currently, we tell nudge them to do this in on of the cards on "Discover" page, but some people still miss it as they are not reading those cards. 

<img width="778" alt="Screenshot 2023-04-12 at 21 56 03" src="https://user-images.githubusercontent.com/68239231/231570227-049ab921-c300-4f1f-9cea-fb62d3417fdd.png">

To improve this, let's add this nudge as the last onboarding step:

**Chrome and all other browsers except Firefox:**
![image](https://user-images.githubusercontent.com/68239231/231570690-0a5db24d-8ab9-4c97-a63f-f240c628a788.png)

**Firefox:**
![image](https://user-images.githubusercontent.com/68239231/231570805-d4a08b51-1255-46f6-9ec7-b11cd88c0c27.png)

Dark version consist different images:
![image](https://user-images.githubusercontent.com/68239231/231571002-35815a47-516a-43f5-9cff-86f2147a5de7.png)

**PR requirements:**
- this needs to show only during onboarding after instal. It shouldn't be shown when users connects another wallets later.
- PR should delete current "pin extension card" from the Discover page

Note: this issue uses new layout that is WIP https://github.com/getAlby/lightning-browser-extension/pull/2284 but can be also applied to current layout with the same copy and images

---

Images to be used:

Chrome and others:
![image](https://user-images.githubusercontent.com/68239231/231571610-0c75e312-b015-43c6-bb11-e2af74cca297.png)
![image](https://user-images.githubusercontent.com/68239231/231571636-cc0887e7-2bc6-4d1f-8c94-e753080317f6.png)

Firefox:
![image](https://user-images.githubusercontent.com/68239231/231571726-a51e0b4d-90c0-495d-b01e-d94866a43dfa.png)
![image](https://user-images.githubusercontent.com/68239231/231571747-ee2edc92-51e8-4728-9220-8eae499e2545.png)

Extensions icon:
![puzzle](https://user-images.githubusercontent.com/68239231/231571893-7c5b2cdb-5a76-46e0-98fc-f33307f7e376.svg)

**Comment by lujakob** [comment]
@stackingsaunter I could work on it. Can you assign me?

**Comment by lujakob** [comment]
@stackingsaunter @reneaaron is it possible for the user at this stage of onboarding to have a black mode screen already? I thought this is set in settings page, being accessible only after completing the onboarding?

**Comment by reneaaron** [comment]
@lujakob I think default is "System", so if your OS / browser supports it and you've selected "dark" theme there, I think that could be the case.

**Comment by lujakob** [comment]
@stackingsaunter "1. Click on in the top right corner of your browser" has this extension icon in it. Do you have the character/charcode for it to be able to use it in the translation file? Same for the "Start buzzin" button. Do you have the character/charcode?

**Comment by reneaaron** [comment]
I don't think it's perfect, but I'd say an icon is more recognizable than a word (even it's not exactly the same icon). 

So I'd say either we go with the emoji 🧩 or the icon we already used in the onboarding cards. (puzzle.svg)

**Comment by lujakob** [comment]
@stackingsaunter @reneaaron I decided to go for the `puzzle.svg` that was already used in the current "pin extension" box. Also I added the "Alby" icon. I thought is is more consistent and even more explanatory. What do you think?

<img width="840" alt="Bildschirmfoto 2023-04-13 um 15 41 46" src="https://user-images.githubusercontent.com/886152/231878562-7ef636ff-52f7-4b0f-bfa0-9eb076abbc88.png">
