### ISSUE TITLE
[BUG] remove deprecated translations for Welcome

### ISSUE THREAD

**Issue by lujakob** [getAlby/lightning-browser-extension#2348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Working on the #2343 onboarding pin extension, I noticed `RouteObject` properties `name` that are neither part of the interface (that was not applied before) and seem to nave no relevance. I suspect this is deprecated code. They might have been used in an old layout displaying a navigation (navigation steps). If this is indeed deprecated I would like to remove the properties from the objects and all translations.

https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/router/Welcome/Welcome.tsx#L29

https://github.com/getAlby/lightning-browser-extension/blob/master/src/i18n/locales/en/translation.json#L5-L9

### Steps To Reproduce

Check code

### Expected behavior

Remove deprecated

### Alby information

latest master

### Are you working on this?

Yes

**Comment by lujakob** [comment]
@reneaaron could you please check and confirm this? By the way, which type of issue would you use for this case? Bug, Feature? None feels right..

**Comment by reneaaron** [comment]
Didn't look into it, but feel free to submit a PR. If it's really not in use we should definitely remove them. :+1: 

I think `chore` should be the right one for that.
