### ISSUE TITLE
Add two websites to "Discover" page

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#2353]
### Feature description

https://musicsideproject.com/ and https://curiocaster.com can be added to the "Discover" pages

### Describe the solution

CurioCaster, Podcast web player
Music Side Project, Music web player

Both websites can be added to the "Entertainment" section. 

At the same time we can correct the typo: Entertai**n**ment

### Are you working on this?

No

**Comment by 11WALTER11** [comment]
Hello, @MoritzKa can i work on this ?

**Comment by AdarshRawat1** [comment]
@MoritzKa I was unable to locate the typo in the word ‘Entertainment’.

**Comment by 11WALTER11** [comment]
Hi @MoritzKa , I just wanted to follow up on my earlier comment about this issue. I've prepared a pull request to address the issue, and I'd be happy to receive your feedback and suggestions.

> Hello @MoritzKa, can i work on this ?

**Comment by MoritzKa** [comment]
There is another PR already: https://github.com/getAlby/lightning-browser-extension/pull/2354

**Comment by 11WALTER11** [comment]
> There is another PR already: #2354

 I was waiting for your approval to start working
