### ISSUE TITLE
[BUG] Onboarding connectors: Kollider wallet Signup and Login buttons dont work

### ISSUE THREAD

**Issue by fczuardi** [getAlby/lightning-browser-extension#2355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

At the Kollider wallet screen where there is 2 buttons, clicking on one of them in the development build changes the location bar, but the screen remains.

[Kollider-routes.webm](https://user-images.githubusercontent.com/7760/230426042-fb9af585-bf32-4e8c-938f-1f21dc98073a.webm)

### Screenshots [optional]

![image](https://user-images.githubusercontent.com/7760/232650460-a89f5713-7a80-43ff-9c72-3dcd3dd46072.png)

### Steps To Reproduce

- clone the repo
- `yarn`
- `yarn dev:chrome`
- load unpacked extension

### Expected behavior

The screens change

### Alby information

- Alby commit b7cfb433b99d51a5e14137c8ed8f7979cfa4d94e

### Device information

I was able to reproduce it on the master branch for both Brave, Chrome and Firefox. With node versions `v16.18.0` and `v18.15.0`

### Additional context

There is a suggestion of fix [here](https://github.com/getAlby/lightning-browser-extension/pull/2309).

### Are you working on this?

No

**Comment by mquasar** [comment]
I was able to reproduce this on Chrome (Version 111.0.5563.149) using node v18.15.0

None of the buttons on the /choose-path/choose-connector/kollider/ works for me.

**Comment by fczuardi** [comment]
OK, I am closing this issue since the mentioned PR now is assigned to @im-adithya and they are working on the proper fix.

Thanks everybody!
