### ISSUE TITLE
[Feature] Improve QR code colors in dark mode

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2366]
### Feature description

QR colors should be inverted in dark mode. They need to be passed to the QRCode component. Since it isn't css, we can't apply the styles using Tailwind. We need a way to get the theme which I think will be available when this commit is merged: https://github.com/getAlby/lightning-browser-extension/pull/2347

![image](https://user-images.githubusercontent.com/33993199/233378054-0491b84f-c983-4dac-b459-325e95d90acd.png)

### Describe the solution

Invert the QR code colors in dark mode so it is easier on the eyes

### Are you working on this?

None

**Comment by 11WALTER11** [comment]
@rolznz  Please assign it to me; I'll work on it.

**Comment by AdarshRawat1** [comment]
> @rolznz Please assign it to me; I'll work on it.

@11WALTER11 lets wait for #2347 to get merged after that we'll be able to use `useTheme` [hook](https://github.com/getAlby/lightning-browser-extension/pull/2347#issuecomment-1507060468).

**Comment by RajGM** [comment]
Looks like a good issue to start.

**Comment by pavanjoshi914** [comment]
maybe @dadofsambonzuki can work on this to get started!

**Comment by dadofsambonzuki** [comment]
I'm mad busy right now I'm afraid. Next time!
