### ISSUE TITLE
Hide optional inputs under "More" button on transacting screens

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2370]
Solves https://github.com/getAlby/lightning-browser-extension/issues/1662

Currently, users when transacting, almost always need to scroll down to see buttons to cancel or send the payment, eg:

<img width="428" alt="Screenshot 2023-04-25 at 00 43 21" src="https://user-images.githubusercontent.com/68239231/234132010-3ce1682d-e1a0-429b-94d4-b37ecaba69eb.png">

Let's hide those under "More" button/link, so action buttons will be seen immediately:

<img width="966" alt="Screenshot 2023-04-25 at 00 44 55" src="https://user-images.githubusercontent.com/68239231/234132219-ed1eca67-7000-4e2c-aa02-412f532e1287.png">

### PR requirements:
- Must involve all transacting screens with optional fields hidden in this way in the popup view
- Does not need to be implemented in extended (desktop) view
- Link default state color is blue600 and blue700 on hover (both light and dark theme)

**Comment by lujakob** [comment]
I'll pick it.
