### ISSUE TITLE
Shrink "receiver" box 

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2375]
We're adding "more" button on transactional screens to hide two of the optional fields. However, users in many cases still need to scroll the extension to confirm a transaction. To solve this, we need to make the "receiver" box smaller:

![image](https://user-images.githubusercontent.com/68239231/234567361-0f7ed4a8-2b20-4a13-bba1-b40228a50720.png)

![image](https://user-images.githubusercontent.com/68239231/234567438-ffed14b9-37dc-451a-a6b4-4ecdd1e38b58.png)

Here's handoff for updated component:

![image](https://user-images.githubusercontent.com/68239231/234568887-b61cb856-2ce3-4657-bba0-8fb8c1e27917.png)

[Link to Figma file](https://www.figma.com/file/MCzf4t1e3pi7Dre6huwq1y/transacting-screens-update?node-id=46%3A7840&t=sEqhZQ9LyemSJD4s-1)

**Comment by lujakob** [comment]
@stackingsaunter I can pick it as well.

**Comment by lujakob** [comment]
@stackingsaunter do you have an lnurlpay getalby address that shows me a profile picture?

**Comment by lujakob** [comment]
> @stackingsaunter do you have an lnurlpay getalby address that shows me a profile picture?

I asked in the Telegram chat and Bumi answered "no, we don’t expose images and I am hesitant to do that. I don’t think images should be embedded in JSON" So I just neglected this case.

But what irritates me now, why do we have the image element implemented in the first case.

@stackingsaunter @reneaaron If you know a use case where this component shows an image please let me know how I can test it.

**Comment by stackingsaunter** [comment]
@lujakob it shows it when battery is activated, eg. on twitter page of hannes https://twitter.com/escapedcat

**Comment by lujakob** [comment]
> https://twitter.com/escapedcat

cool. I updated the PR and added the screenshot to it's description.
