### ISSUE TITLE
Remove/ Add apps from "Discover page"

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#2382]
### Feature description

Some of the apps did not show progress and are not useable anymore. Other apps are improving and can be listed. 

### Describe the solution

Remove:

- [ ] https://hamstr.to/home
- [ ] https://emon.chat/
- [ ] https://yosup.app/

Add:

- [ ] https://habla.news/

### Are you working on this?

No

**Comment by AdarshRawat1** [comment]
I'm on it.

**Comment by bumi** [comment]
@MoritzKa why remove hamstr? it works fine, doesn't it?

**Comment by MoritzKa** [comment]
Main reason for removing was that hamstr did not really improve much compared to Iris, snort or primal why are better clients for first time users. 
But I just tested it and it did not load my data for my pub key.

**Comment by bumi** [comment]
has anyone else problems with hamster?

**Comment by AdarshRawat1** [comment]
Logo For Habla - 
![Habla Logo](https://github.com/getAlby/lightning-browser-extension/assets/100958893/a523ec2c-e9ad-43c9-a547-366e9de6f35b)

**Comment by AdarshRawat1** [comment]
> has anyone else problems with hamstr?

+1

**Comment by reneaaron** [comment]
I am having problems with hamstr.to as well. Also no dev activity for the last 6 months: 

https://github.com/styppo/hamstr

**Comment by AdarshRawat1** [comment]
@reneaaron Should I remove hamstr from #2411

**Comment by reneaaron** [comment]
@AdarshRawat1 Hamstr is already removed in this PR: 

https://github.com/getAlby/lightning-browser-extension/pull/2411/files#diff-7effc0a7cbef9cb2ada7cd0f5c53571fe7ef9f882e094292b93377ac067f4dc2L106-L109

**Comment by AdarshRawat1** [comment]
@reneaaron Oh, my bad. I mistook hamstr for Habla.
