### ISSUE TITLE
[RFC] Citadel connection

### ISSUE THREAD

**Issue by AaronDewes** [getAlby/lightning-browser-extension#239]
These are some things regarding a possible integration with Citadel. Instead of connecting directly to LND, I'd recommend routing all connections to github.com/runcitadel/middleware. (I'd build a connector for this, but I probabl won't be able to build an UI).
This is better than using LND, because

- It allows users to connect using just their Citadel password.
- Citadel will soon allow apps to "reserve" funds, so if an app offers multiple wallets (LNBits, LndHub, ...), these funds can't be spent from the dashboard (only after muultiple warnings). Connecting directly to LND would leave Alby unaware of this.
- It will always work, no matter what Lightning implementation Citadel is using

Here's a suggested way for users to connect:

[OPTIONAL] (Alby could scan if it can find either umbrel.local or citadel.local and check if it's a Citadel node, if it is, automatically ask the user to connect)

- If it's the first connection, ask for the (internal, not LND, but Citadel) pubkey of the node and validate it
- Otherwise, check the pubkey
- If it's the first connection, ask for the password
- Otherwise, send it

You're now connected and can use the node

**Comment by bumi** [comment]
That sounds awesome!

I think the first step is easy and we can take care of the UI - For authenticating the API calls only the Citadel password is needed? 

connectors are a simple class that implement the basic methods to interact with the lightning API. The class is initialized with the config provided by the user (e.g. URL + password).
You can follow the current implementations: https://github.com/getAlby/lightning-browser-extension/tree/master/src/extension/background-script/connectors (we actually should move those to TypeScript and provide type definitions)
I actually also started a [doc listing the methods](https://github.com/getAlby/lightning-browser-extension/wiki/Connector-API). But that's WIP.


Doing the local discovery is a great idea, that makes the setup also so much easier. But we have to think what to do when the user is not in the same network.

**Comment by AaronDewes** [comment]
Yes, there is also a JWT needed internally, but I'm building a library which handles all of that. Currently only authentication methods are implemented, nothing else: runcitadel.github.io/sdk.

**Comment by AaronDewes** [comment]
> Doing the local discovery is a great idea, that makes the setup also so much easier. But we have to think what to do when the user is not in the same network.

Ask the user to setup a Tor proxy on their system, it's possible to route that through that, and with the Citadel SDK, getting the Tor URL of the node will be as easy as `await citadel.manager.system.getHiddenServiceUrl()`.

**Comment by bumi** [comment]
> Ask the user to setup a Tor proxy on their system, it's possible to route that through that, and with the Citadel SDK, getting the Tor URL of the node will be as easy as await citadel.manager.system.getHiddenServiceUrl().

Do you have any recommendations there? I've either used tor (and proxied everything through a tor socks proxy, or no tor at all). I wasn't sure how to best selectively proxy from the browser? is there some kind of HTTP reverse proxy for this?

**Comment by AaronDewes** [comment]
Sorry, doesn't seem like there is. There probably are public reverse proxies for onion URLs, but I'm not sure how secure they are. https://github.com/runcitadel/sdk just launched the first beta though I'll still do some testing, and the upcoming Citadel 0.5.0 will fully work with it.

**Comment by AaronDewes** [comment]
But if you only want to proxy the whole browser (not the whole OS), that's possible.
Or a native companion which includes a Tor daemon and a HTTP reverse proxy would be possible.

**Comment by escapedcat** [comment]
Fixed via #472 I believe
