### ISSUE TITLE
Give Alby users the opportunity to claim a Lightning Address through Alby

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#240]
Alby allows to send tips to Twitter profiles when the profile owner published a Lightning Address in the profile. Currently there is only a very limited amount of services that allow to conveniently generate a LN Address ([some examples](https://lightningaddress.com/#providers))
Alby could integrate such a service to give more user the possibility to receive payments (e.g. tips on Twitter)
There are several options:
1.) Provide a full service consisting of LN address server + custodial node. That would allow Alby to give any user a LN address. 
2.) Provide an own bridge server to an user's existing LN node. 
3.) Integrate a ["community-supported" LN address server](https://lightningaddress.com/#community) to a user's existing LN node

**Comment by secondl1ght** [comment]
This functionality has been added now but maybe we want to use this thread to discuss ways to improve the process and make it more visible to the users?
