### ISSUE TITLE
Improve padding on onboarding screens

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2408]
This is the current onboarding screens padding:

![image](https://user-images.githubusercontent.com/68239231/236947764-da734fc1-fb2b-439c-8aae-326628d10f7c.png)
![image](https://user-images.githubusercontent.com/68239231/236947792-ae24664c-e03d-4868-8f1a-aeec04e76ed6.png)

I'd like to propose some changes to keep design more compact so the button is never below the fold and more consistent with other places in the extension. After discussing it with the team we think we also do not need "Connect / To start using..." copy on the screen where users choose Alby account/connectors since it's a bit redundant and the same content is in the cards. 

Proposed changes to padding an screens:
![image](https://user-images.githubusercontent.com/68239231/236948347-9ecc4422-6239-4eec-a8db-9e71360a16e1.png)
![image](https://user-images.githubusercontent.com/68239231/236948369-d06d0c5d-3366-4ab6-bef3-468515d257f7.png)
![image](https://user-images.githubusercontent.com/68239231/236948392-fcc70cef-c229-4efb-9ad0-e503a1929114.png)

List of all changes:
- card padding is **40px** (both vertical and horizontal)
- padding between header and content is **16px**
- "Welcome to Alby" is 40px below and top of the page and above the form
- No "Connect / To start using the Alby Extension..." header/copy
- 40px between cards on that screen (and 16px between headers inside and the content)

**Comment by mquasar** [comment]
Could you please assign this to me?

**Comment by mquasar** [comment]
changes committed and waiting for review
