### ISSUE TITLE
[BUG] Should show a message when inserting a value that is higher than the available balance

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

Should show a message when inserting a value that is higher than the available balance. And disable confirm button.

https://github.com/getAlby/lightning-browser-extension/assets/1178856/bfb08505-8e9c-453f-b364-9f140a033c92

### Steps To Reproduce

1- Paste a lightning address 
2- Insert a value higher than your available balance

### Expected behavior

Show a message telling that the value is higher than the available balance and disable confirm button

### Alby information

Alby version: 2.01

### Are you working on this?

No

**Comment by lujakob** [comment]
I can pick it.

**Comment by im-adithya** [comment]
Sure, thanks @lujakob! But this would require some input from @stackingsaunter first

**Comment by stackingsaunter** [comment]
If the validation can be done "live" without clicking the button, then I propose disableing the button and an input error state like this:

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/bca9bd84-6d08-4731-950d-9222aade6909)

Also cc @reneaaron to make sure it's fine

**Comment by lujakob** [comment]
@stackingsaunter contrary to your design I noticed a range field located above right of the field. Should I color this text all or parts of it in red as well?

<img width="385" alt="Bildschirmfoto 2023-05-23 um 16 34 23" src="https://github.com/getAlby/lightning-browser-extension/assets/886152/be2a1bf0-adc7-466e-86fc-f51c715d863f">

**Comment by lujakob** [comment]
@reneaaron I noticed the max value of the range mentioned and shown in the screenshot above is fixed. I'll adapt it to be either the current fixed or `auth.account.balance`, because it doesn't it is contrarian to display a range higher than the max, agree?

`  const amountMax = Math.min(Math.floor(+details.maxSendable / 1000), auth?.account?.balance || 0);
`

**Comment by lujakob** [comment]
@reneaaron I only made changes in the LNURLPay page. Does it make sense to add it to the Keysend page as well? Any more I am missing?

**Comment by stackingsaunter** [comment]
@lujakob can it be done like this?

- If amount is above user's balance, color red Balance
- If amount is outside of range, color the text above (range)
- If both, color red both

**Comment by lujakob** [comment]
> @lujakob can it be done like this?
> 
> * If amount is above user's balance, color red Balance
> * If amount is outside of range, color the text above (range)
> * If both, color red both

Good idea. I updated the PR accordingly.
