### ISSUE TITLE
[Feature] Add https://vida.live/ 

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2416]
### Feature description

Hi,

Add https://vida.live/ 

### Describe the solution

Add https://vida.live/ 

### Are you working on this?

No

**Comment by lujakob** [comment]
I'll pick it..

**Comment by lujakob** [comment]
The logo needs to be uploaded to the CDN under `https://cdn.getalby-assets.com/alby-extension-website-screen/vida.png`

![vida](https://github.com/getAlby/lightning-browser-extension/assets/886152/eca46736-09c7-4512-8e73-1f319afd6466)
