### ISSUE TITLE
[BUG] I can't switch from non custodial wallet to Alby custodial wallet if this message appear: Failed to connect the WASM

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I can't switch from non custodial wallet to Alby custodial wallet if this message appear: Failed to connect the WASM

https://github.com/getAlby/lightning-browser-extension/assets/1178856/06980a11-c657-430e-b2a4-8e28c5f12b84

### Steps To Reproduce

1- Have two wallets on Alby. A non custodial wallet LNC and Alby custodial wallet.
2- If the error message Failed to connect the WASM appear, try to switch to Alby custodial wallet

### Expected behavior

Be able to switch to Alby custodial wallet.

### Alby information

Alby version: 2.01

### Are you working on this?

No

**Comment by bitcoinuser** [comment]
Logs


background.bundle.js:2 Loading background script
background.bundle.js:2 State loaded
background.bundle.js:2 Using indexedDB
background.bundle.js:2 Current DB version: 5
background.bundle.js:2 Loading DB data from storage
background.bundle.js:2 Found 147 allowances already in the DB
background.bundle.js:2 Found 2127 payments already in the DB
background.bundle.js:2 Found 1 blocklist already in the DB
background.bundle.js:2 Found 178 permissions already in the DB
background.bundle.js:2 DB opened
background.bundle.js:2 Event subscriptions registered
background.bundle.js:2 Events subscribed
background.bundle.js:2 Loading completed
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
3background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
2background.bundle.js:2 Routing call: getBlocklist
2background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
3background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
3background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
2background.bundle.js:2 Routing call: getBlocklist
3background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
2background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    at p (background.bundle.js:2:732910)
background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
2background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
Unchecked runtime.lastError: No tab with id: 2054339261.
background.bundle.js:2 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    at p (background.bundle.js:2:732910)
3background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
2background.bundle.js:2 Routing call: getBlocklist
4background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: status
4background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: status
3background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: unlock
background.bundle.js:2 init LNC
background.bundle.js:2 2023-06-06 19:59:11.067 [DBG] WASM: WASM client ready for connecting
background.bundle.js:2 2023-06-06 19:59:11.735 [DBG] GRPC: [core] parsed scheme: ""
background.bundle.js:2 2023-06-06 19:59:11.744 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
background.bundle.js:2 2023-06-06 19:59:11.751 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{[mailbox.terminal.lightning.today:443](https://mailbox.terminal.lightning.today/)  <nil> 0 <nil>}] <nil> <nil>}
background.bundle.js:2 2023-06-06 19:59:11.756 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
background.bundle.js:2 2023-06-06 19:59:11.768 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
background.bundle.js:2 2023-06-06 19:59:11.781 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
background.bundle.js:2 2023-06-06 19:59:11.805 [DBG] GRPC: [core] Subchannel picks a new address "[mailbox.terminal.lightning.today:443](https://mailbox.terminal.lightning.today/)" to connect
background.bundle.js:2 2023-06-06 19:59:11.822 [DBG] MBOX: Client: Dialing...
background.bundle.js:2 2023-06-06 19:59:11.813 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x1f74910, {CONNECTING <nil>}
background.bundle.js:2 2023-06-06 19:59:11.835 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
background.bundle.js:2 2023-06-06 19:59:11.833 [DBG] MBOX: New client conn,
read_stream=595d57a448d63f93b52f80cc99b8a2ddacf5a8f8ea30f84aceee79e941c66ce7bcd32400b3cceccf22ef7c43e1f266f666e27cc6674f019d529d684d0be3d995, write_stream=595d57a448d63f93b52f80cc99b8a2ddacf5a8f8ea30f84aceee79e941c66ce7bcd32400b3cceccf22ef7c43e1f266f666e27cc6674f019d529d684d0be3d994
background.bundle.js:2 2023-06-06 19:59:11.838 [DBG] MBOX: Client: Attempting to create send socket/stream
background.bundle.js:2 2023-06-06 19:59:17.821 [DBG] MBOX: Client: Connected to send socket/stream
background.bundle.js:2 2023-06-06 19:59:19.838 [DBG] MBOX: Client: receive mailbox initialized
background.bundle.js:2 Error: Failed to connect the WASM client to the proxy server
    at background.bundle.js:2:158738
Dd @ background.bundle.js:2
background.bundle.js:2 2023-06-06 19:59:22.868 [DBG] MBOX: Starting client handshake
background.bundle.js:2 2023-06-06 19:59:22.878 [DBG] MBOX: Kicking off client handshake with client_key=022f09dd62e37639a9e98da753ea15c8fd367d3faa43cddaf9397b393bc9385b0f
background.bundle.js:2 2023-06-06 19:59:23.903 [DBG] MBOX: Completed client handshake with with server_key=02ebc3b7a12b97b1dac5efe7ceb6a77c5f6c4d63aff473133518abfc42d2e8d597
background.bundle.js:2 2023-06-06 19:59:23.903 [TRC] MBOX: Client handshake completed
background.bundle.js:2 2023-06-06 19:59:23.944 [DBG] GRPC: [core] Subchannel Connectivity change to READY
background.bundle.js:2 2023-06-06 19:59:23.946 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x1f74910, {READY <nil>}
background.bundle.js:2 2023-06-06 19:59:23.946 [DBG] GRPC: [core] Channel Connectivity change to READY
background.bundle.js:2 2023-06-06 19:59:23.947 [DBG] WASM: WASM client connected to RPC
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
2background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: status
3background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: accountInfo
background.bundle.js:2 Routing call: getAccounts
background.bundle.js:2 Routing call: getCurrencyRate
background.bundle.js:2 Routing call: getAllowance
background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getPayments
background.bundle.js:2 Routing call: getInvoices
background.bundle.js:2 Routing call: getCurrencyRate
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
3background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
2background.bundle.js:2 Routing call: getBlocklist
3background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
3background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getAccount
2background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: status
3background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: accountInfo
background.bundle.js:2 Routing call: getAccounts
background.bundle.js:2 Routing call: getCurrencyRate
background.bundle.js:2 Routing call: getAllowance
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getPayments
background.bundle.js:2 Routing call: getInvoices
background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: status
3background.bundle.js:2 Routing call: getSettings
background.bundle.js:2 Routing call: accountInfo
background.bundle.js:2 Routing call: getAccounts
background.bundle.js:2 Routing call: getCurrencyRate
background.bundle.js:2 Routing call: getAllowance
background.bundle.js:2 Routing call: getBlocklist
background.bundle.js:2 Routing call: getPayments
background.bundle.js:2 Routing call: getInvoices

**Comment by rolznz** [comment]
I believe this happens whenever you are currently connected (or try to connect) to an LNC account that is unreachable. From then on the app gets stuck and you can't switch accounts.
