### ISSUE TITLE
[Feature] For custodial Alby wallets that have a lightning address, should show the lightning address on main Alby window

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2429]
### Feature description

Hi,

For custodial Alby wallets that have a lightning address, should show the lightning address on main Alby window. Something like this:

![Captura de tela de 2023-05-13 14-58-29](https://github.com/getAlby/lightning-browser-extension/assets/1178856/87a8bb16-5c7a-496b-a3c0-ae43c2df5569)

### Describe the solution

For custodial Alby wallets that have a lightning address, should show the lightning address on main Alby window. 

### Are you working on this?

No

**Comment by rolznz** [comment]
@bitcoinuser I agree. We need to wait for https://github.com/getAlby/lightning-browser-extension/issues/1956 in order to implement it.
