### ISSUE TITLE
[BUG] Extension stopped working: "API Error: Request Failed with status code 503"

### ISSUE THREAD

**Issue by yarub123** [getAlby/lightning-browser-extension#2431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Clicking upon the extension I get the error above. Trying to switch between accounts in the drop down menu, gives the same error. 

### Screenshots [optional]

![Screenshot 2023-05-14 at 5 57 31 PM](https://github.com/getAlby/lightning-browser-extension/assets/84487964/d2cb661f-5cec-4d14-b31f-a7aa07d00d2c)

### Steps To Reproduce

1. visit any site
2. click the extension icon
3. error comes up
4. cannot even switch accounts. 

### Expected behavior

For it to work like usual and switch btw accounts as normal. 

### Alby information

Alby v 2.0.1

### Device information

-OS MacOS
-Firefox v 113

### Are you working on this?

None

**Comment by reneaaron** [comment]
@yarub123 I assume you are using an Alby Account here? That might have been a temporary problem on our end, sorry for any inconvenience caused! :neutral_face:  Does it work again for you? 

> cannot even switch accounts.

Do you mean switching between between 2 different Alby accounts?

**Comment by yarub123** [comment]
@reneaaron Hey thanks for the response. Yeah I'm using an Alby account. 

And for switching between 2 accounts I mean this from the extension drop down menu when you can select which (Alby) account to view: 
<img width="365" alt="image" src="https://github.com/getAlby/lightning-browser-extension/assets/84487964/cd439a7a-75e8-445b-8b48-ab53d57a156d">

<img width="137" alt="image" src="https://github.com/getAlby/lightning-browser-extension/assets/84487964/e9b24600-40e0-411e-a112-1d65ec6cb0a8">

I left the names of accounts out of the pic 🙃

**Comment by reneaaron** [comment]
Alright, thanks for clarifying. But now it works again for you? 

FYI: We're about to improve error handling during account loading in #2377.

**Comment by marcinx** [comment]
Somewhat related I guess. Started getting these:

<img width="383" alt="Screenshot 2023-05-18 at 4 11 07 PM" src="https://github.com/getAlby/lightning-browser-extension/assets/4034123/761337e0-7fde-4291-bf66-4d16675c2c8e">

I can ping ln.getalby.com. It pulls the account balance but cannot send or receive. Tons of the above errors.

<img width="379" alt="Screenshot 2023-05-18 at 4 17 17 PM" src="https://github.com/getAlby/lightning-browser-extension/assets/4034123/61d370c6-2619-4e82-a781-cae21f382135">

When trying to connect to the lndub address in another wallet the request just times out.

Thoughts?

**Comment by yarub123** [comment]
@marcinx I fixed it btw. I believe the issue arises when you add more than one account. In order to allow multiple accounts to work you have to add them through the settings (which I'm sure you did) then completely log out of Alby. 

At the original sign in page of the extension use the password you used the FIRST time you logged in to Alby. 

It should then work and you will see all accounts.

**Comment by reneaaron** [comment]
This will hopefully soon be improved, closing in favor of #2468.
