### ISSUE TITLE
[Feature] Allow password fill using a password manager

### ISSUE THREAD

**Issue by verityj** [getAlby/lightning-browser-extension#2471]
### Feature description

Currently https://getalby.com/login can be filled from a password manager (Bitwarden, for example).

Extension drop down and pop up windows must be using different URLs so the password manager does not recognize it and can't offer to fill anything. Workaround: separately open the password manager extension, find Alby, copy password (which I keep long and complex), then look again for the Alby pop up (which is now behind the browser window) and paste.

### Describe the solution

https://bitwarden.com/help/uri-match-detection/ What is the Alby _**extension**_ base domain that would enable recognition by the password manager for a login match?

I can add it manually to my password manager so it starts offering the option of a password fill into the Alby extension.

### Describe alternatives

Keep the Alby password simple to remember and type in manually every single time. I don't like this option.

### Additional context

I checked https://github.com/getAlby/lightning-browser-extension/blob/master/static/views/popup.html but didn't understand most of it. I'm not that good :)

### Are you working on this?

None

**Comment by verityj** [comment]
Thank you. I looked through "page source" and the location bar shows `chrome-extension://iokeahhehimjnekafflcihljlcjccdbe/prompt.css?b64e8ea5cdb46ab290a2` but unfortunately no part of it as a bitwarden URI works to recognize the popup for auto fill.

Also inspected the popup element and the address was `chrome-extension://iokeahhehimjnekafflcihljlcjccdbe/popup.html` but still didn't work as a URI.

Based on your screenshots, did it work for you? I still get `no matching logins`.

**Comment by reneaaron** [comment]
Awesome, glad I could help! (auto-fill doesn't work by design as extensions can't inject scripts into other extensions)
