### ISSUE TITLE
[BUG] Unlock dialog launched multiple times

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A second dialog can launch while the first is open, when the extension is locked.

### Screenshots [optional]

https://github.com/getAlby/lightning-browser-extension/assets/33993199/4cc15d6e-9088-48ab-86de-e1e57edf783c

### Steps To Reproduce

1. Launch a new browser with extension locked
2. Open snort.social (Note: Maybe you need snort premium for it to launch 2 modals like this)

### Expected behavior

Only one modal is opened

### Alby information

2.1.1

### Device information

Chrome Windows

### Are you working on this?

None

**Comment by reneaaron** [comment]
User feedback: 

https://feedback.getalby.com/-feature-request/posts/browser-extension-popup-windows

**Comment by bumi** [comment]
sounds like it's a premium feature: "you need snort premium for it to launch 2 modals like this" 
you pay and you get two prompts. you get what you pay for :)

**Comment by pavanjoshi914** [comment]
unable to reproduce this on my side!

**Comment by reneaaron** [comment]
I could just reproduce it on snort.social: 

They are using `window.webln` and `window.nostr` at the same time. Calling `webln.enable()` and `nostr.getPublicKey()` simultaneously will lead to this behavior but I think the problem really is that `webln.enable()` should only be called on user interaction (and not on page load), I don't think there is much we could do to prevent this from our side. (unless we want to have one promiseQueue for all providers?) cc @bumi

**Comment by rolznz** [comment]
Hmm. I think nostr and webln are becoming more and more closely integrated and this could happen on many apps. I think we should actually consider fixing this on our side.

@pavanjoshi914 @reneaaron

**Comment by reneaaron** [comment]
@rolznz After thinking about it I have to admit, you are completely right. We should definitely have a maximum of *1* enable popup per website (no matter which APIs are being used). cc @pavanjoshi914
