### ISSUE TITLE
[Feature] Send a message to the website when user switches account

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2503]
### Feature description

Websites that use window.webln or window.nostr currently do not know when a user switches to a different account inside the extension, and show information from the previous account. It would be useful if a website could listen to a message so it can stay in sync.

### Describe the solution

Post a message to the window when the Alby account changes

### Are you working on this?

None

**Comment by pavanjoshi914** [comment]
closed in favour of #2504
