### ISSUE TITLE
[BUG] Invalid manifest on Brave browser

### ISSUE THREAD

**Issue by kuba-04** [getAlby/lightning-browser-extension#2517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Unable to install extension to brave browser, I looked for the issue but couldn't find

### Screenshots [optional]

![image](https://github.com/getAlby/lightning-browser-extension/assets/30311112/65c6a20c-5f65-4ab8-8d8e-02a8657b21dc)

### Steps To Reproduce

1. Open Brave browser
2. Manage extensions
3. search Alby
4. try adding it

### Expected behavior

Alby is added to browser extensions

### Alby information

not installed

### Device information

Ubuntu 22.04.2 LTS
Brave [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)](https://brave.com/latest/)

### Are you working on this?

None

**Comment by reneaaron** [comment]
Thanks for your report! 

You seem to be having a very outdated version of Brave, could that maybe be the issue here?  I just installed Alby in Brave and it seemed to work fine: 

![image](https://github.com/getAlby/lightning-browser-extension/assets/100827540/9c51c984-4571-4913-8c27-3eaf1ddd308b)

**Comment by kuba-04** [comment]
alright, if that works for you then sorry for bothering, I should have checked! Thank you, closing it

**Comment by reneaaron** [comment]
Please let us know if updating your Brave browser fixed the problem for you, happy to take another look otherwise :+1:

**Comment by kuba-04** [comment]
I confirm after upgrade it works, thx

**Comment by reneaaron** [comment]
Awesome, thanks for reporting back!
