### ISSUE TITLE
[Feature] Display profile header for account related pages

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2521]
### Feature description

Currently you can have one account selected and edit another one, but in account subpages it is not obvious which account you are editing.

### Describe the solution

- Display the profile header on subpages of the account. (currently I think only the secret key related things are "below" the account).

### Are you working on this?

None

**Comment by lujakob** [comment]
I could pick it, if no one is on it.

Should the accounts list page be removed as well, right?

**Comment by rolznz** [comment]
@lujakob thanks. This issue needs to be reviewed first. Also, it would be good for [this PR](https://github.com/getAlby/lightning-browser-extension/pull/2338) to be merged first

**Comment by bumi** [comment]
can't we just keep this account header on the new edit pages
<img width="1039" alt="image" src="https://github.com/getAlby/lightning-browser-extension/assets/318/29d6851d-1528-4435-bc72-b21a49439fb0">

we had especially added this feature before.

**Comment by reneaaron** [comment]
I also don't think we should remove the functionality to edit other accounts than the currently used one. 

+1 for displaying the profile header on subpages of the account. (currently I think only the secret key related things are "below" the account).

**Comment by lujakob** [comment]
@reneaaron is the issue description still accurate? I'm kind of confused with Bumis comment.

**Comment by rolznz** [comment]
I updated the description. I believe we should follow Bumi's comment (add a header to new pages). @lujakob please note for now this is just: import/generate/backup secret key, and nostr settings pages (all added in the mnemonic PR which was just merged)

**Comment by reneaaron** [comment]
@lujakob Sorry I didn't clarify that enough. We should try to add the profile header as kind of a Layout for account related subpages so it's clear which account you are currently editing your keys of. 

@rolznz Thanks for updating the description.
