### ISSUE TITLE
[BUG] Add validation for account names

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#2528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Do not allow empty account names

![image](https://github.com/getAlby/lightning-browser-extension/assets/100827540/a5d8f88a-9afd-45bd-a261-f680bf3c99c9)

### Steps To Reproduce

1. Go to your account
2. Delete your account name
3. Click save

### Expected behavior

Do not allow to save empty account names.

### Alby information

-

### Are you working on this?

None

**Comment by akshatb22me007** [comment]
Hey @reneaaron  I want to work on this issue.

**Comment by reneaaron** [comment]
Awesome, I assiged it to you. :ok_hand:

**Comment by akshatb22me007** [comment]
> Awesome, I assiged it to you. :ok_hand: 

Thanks @reneaaron  for assigning this issue to me.

**Comment by Rithvik-padma** [comment]
@reneaaron @roland I would like to work on this issue can you assign it to me. 
We can even add a validation for the Alby page display name too if that sounds necessary.
