### ISSUE TITLE
why does webln.enable() return an object?

### ISSUE THREAD

**Issue by otech47** [getAlby/lightning-browser-extension#2596]
According to [this spec](https://www.webln.guide/building-lightning-apps/webln-reference/webln.enable) the enable function has a void return type

However the webln object injected by Alby has an enable function that does not adhere to this spec so it seems some app devs have assumed that enable may return an object with `enabled: true` or `isEnabled: true` 

Seems this creates confusion for WebLN providers since `enable()` could be implemented in inconsistent ways

Cross-posting this in more than one place (https://github.com/BoltzExchange/boltz-web-app/issues/229) since I'm not sure what the best approach to fix this is... implementations are either building on an outdated spec or they are not compliant with a spec that cannot be enforced 🤔 

any suggestions on what to do here?

**Comment by reneaaron** [comment]
Thanks for bringing this up. Since `enable()` throws an exception when a user declines the prompt (like any other method in WebLN) I think we should change our implementation here to not return anything. I've prepared a PR for that. 

However that might break some existing applications out there :thinking: Did you notice any other services that use those parameters?

**Comment by otech47** [comment]
going through bolt.fun for LN enabled apps and compiling a list of patches for any apps that would break

## May need patch
- https://github.com/lightsats/lightsats/pull/174
- bitrefill.com (https://twitter.com/oz_21m/status/1685362091589242880?s=20)

## Does not use webln.enable()
- https://lnvpn.net/
- https://lightning.gifts/

## Uses webln.enable() properly
- https://lncal.com/ ✅ 
- https://www.lnflip.com/ ✅

**Comment by otech47** [comment]
cant find source code for Kollider browser extension... I checked kollider-lite-app and it seems unaffected by this

tagging a few contributors maybe we can find out if @kolliderhq should patch too at least on the browser extension side... 

@fl-y @the-kollider @mk-kollider

**Comment by bumi** [comment]
thank you @otech47. This is some old old thing (it got falsely added in the first commit even)
