### ISSUE TITLE
Swap Inter font for OpenRunde

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2612]
OpenRunde is a a variation of Inter but with rounded corners. It feels Alby brand with it's a bit more pleasant appeal while preserving great characteristics of Inter. Font is on the same license as Inter. There are currently 4 weights of Open Runde and those are exactly what we use. Creator of Open Runde also added [slashed zeros](https://github.com/lauridskern/open-runde/issues/2) for us to display numbers as we do now.

[OpenRunde repo](https://github.com/lauridskern/open-runde?ref=designerdailyreport.com)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/47c4fa87-28f5-48d3-9044-a64542b2f592)

**Comment by stackingsaunter** [comment]
Go ahead @AdarshRawat1

**Comment by reneaaron** [comment]
Only saw your comment as I already implemented it :see_no_evil: Sorry @AdarshRawat1, maybe you want to take a look at the PR and review it?

**Comment by AdarshRawat1** [comment]
Appreciate the PR, @reneaaron ! I'll definitely take a look and provide my feedback.
