### ISSUE TITLE
[BUG] When clicking on close button, should close Alby instead of go to previous window

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

When clicking on close button, should close Alby instead of go to previous window.

https://github.com/getAlby/lightning-browser-extension/assets/1178856/7071343d-bfe6-4dc9-a115-e89ea1988495

### Steps To Reproduce

1- Visit https://geyser.fund/
2- Send Sats
3- Click on Close button

### Expected behavior

When clicking on close button, should close Alby instead of go to previous window

### Alby information

Alby version: 3.0

### Are you working on this?

No

**Comment by stackingsaunter** [comment]
When popup is triggered by webln it autocloses as it should be, but If users triggers manually the popup I don't think it should autoclose the popup. To do this, you can click Alby icon.
