### ISSUE TITLE
[Feature] Add https://stemstr.app/ to nostr section

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2623]
### Feature description

[Feature] Add https://stemstr.app/ to nostr section

### Describe the solution

[Feature] Add https://stemstr.app/ to nostr section

### Are you working on this?

No

**Comment by reneaaron** [comment]
We are in the process of migrating this discover page to our website here:

https://getalby.com/discover

You can find a form to submit other apps that you think should be included at the end of this page, I've already submitted the one you suggested here. 👍️
