### ISSUE TITLE
[BUG] There is no active Tab

### ISSUE THREAD

**Issue by biplavmz** [getAlby/lightning-browser-extension#2624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no active Tab

### Screenshots [optional]

<img width="523" alt="image" src="https://github.com/getAlby/lightning-browser-extension/assets/68702055/9eb544c0-5df8-4f2b-ae5b-c1f9222eb24a">

### Steps To Reproduce

go to website click on menu.

### Expected behavior

background color in active Tab

### Alby information

<img width="523" alt="image" src="https://github.com/getAlby/lightning-browser-extension/assets/68702055/bdb33859-fd37-4038-ae58-a7d637f8550c">

### Are you working on this?

None

**Comment by brihuang99** [comment]
This issue is posted on the wrong repo; you need to post this on the getalby.com website repo [here.](https://github.com/getAlby/website)
