### ISSUE TITLE
[BUG] Cannot export old login credentials to a new browser

### ISSUE THREAD

**Issue by mariaa144** [getAlby/lightning-browser-extension#2637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I signed up for localsats.org using the login feature on the Alby extension. I can still login to the site using the Alby extension on that computer. However, I want to export the login credentials to a new computer but I cannot because the export isn't showing up on the extension. Instead I see "Generate new Master Key" and "Import your Master Key" on the extension.

What I think happened is logged into localsats.org using an old version of Alby which had login keys by default. Now Alby has changed and a login key needs to be generated. Now I need the old login keys for my new computer but I cannot get to them. Does that sound right? Is this possible?

At this point all I can think to do is delete my account on localsats.org and start over with a generated master key which I can export, backup and import.

### Steps To Reproduce

1. Login to localsats.org with an old version of Alby which didn't have master key generation.
2. Try to export those login keys on a new version of Alby
3. Notice it isn't possible to export the old login keys

### Expected behavior

The old login keys generated by an old Alby will also be available to be exported and imported.

### Alby information

- 3.0.0 alby

I don't know the version of the old version of Alby I used when first signing into localsats.org

### Are you working on this?

No

**Comment by rolznz** [comment]
Hi @mariaa144 

That's right, but you don't need to delete your localsats account! Please use the Lndhub connector instead of the Alby one to recover LNURL auth.

Please see this guide for more information: https://guides.getalby.com/overall-guide/alby-browser-extension/faqs/how-to-access-my-old-account-in-apps-with-the-alby-extension

**Comment by mariaa144** [comment]
I was able to connect using Lndhub connector but for some reason when I logged into localsats.org I didn't log into the same account. I'm not sure why that would be. I don't know if it is something different with Alby or a bug with localsats.org.

**Comment by bumi** [comment]
Can you check in the in the Extension Settings at the very bottom if you have to enable "legacy mode".
If you had an old installation this might be the reason. 

Sorry for that experience. It's a bit the tricky part when keys are used and keys can not be updated. 
<img width="1053" alt="CleanShot 2023-08-08 at 23 38 50@2x" src="https://github.com/getAlby/lightning-browser-extension/assets/318/e6d5d5fa-03e6-4b9f-a99c-8f0ac24b6a22">

**Comment by reneaaron** [comment]
@mariaa144 Did you manage to recover your accounts?

**Comment by mariaa144** [comment]
I don't recall for sure but I think I was able to login as my old account when I set Legacy LNURL-Auth. Thanks for asking.
