### ISSUE TITLE
[BUG] Checkbox should be disabled during payment

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Checkbox should be disabled during payment

https://github.com/getAlby/lightning-browser-extension/assets/1178856/1828c23f-2dc7-44da-afd6-d515504a8308

### Steps To Reproduce

See the video

### Expected behavior

Checkbox should be disabled during the payment.

### Alby information

Alby: 3.0

### Are you working on this?

No

**Comment by Rithvik-padma** [comment]
@reneaaron I want to work on this issue, can you assign it to me?

**Comment by reneaaron** [comment]
@Rithvik-padma Sure, I just assigned you. Looking forward to your PR, let me know if you have any questions!

**Comment by pavanjoshi914** [comment]
closed in favor off #2731
