### ISSUE TITLE
[Feature] Add https://nostree.me/ on Nostr section

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2646]
### Feature description

Add https://nostree.me/ on Nostr section

### Describe the solution

Add https://nostree.me/ on Nostr section

### Are you working on this?

No

**Comment by AdarshRawat1** [comment]
![transparent-svgviewer-png-output](https://github.com/getAlby/lightning-browser-extension/assets/100958893/56c52b53-fd48-4b5c-8212-688b65646c55)

**Comment by reneaaron** [comment]
We are in the process of migrating this discover page to our website here:

https://getalby.com/discover

You can find a form to submit other apps that you think should be included at the end of this page, I've already submitted the one you suggested here. 👍️
