### ISSUE TITLE
Revamp Receive screen

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2659]
Proposition to revamp "Receive" screen.

[Figma link with a user flow and handoff](https://www.figma.com/file/MCzf4t1e3pi7Dre6huwq1y/Receive-%2F-Send-revamp?type=design&node-id=251-23749&mode=design&t=H0l2ZM0Vq4IPEY20-0)

## Changes:
- displaying user's lightning address
- displaying QR code with user's lightning address + user avatar inside
- "list item" buttons with icons and better explained ways of receiving bitcoin

# Alby Accounts:
![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/670236ee-a1e4-4a4e-9d51-55c4e0fc87bc)

# Non-Alby Accounts:
![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/ed44bfd9-9854-4799-9f2e-54ce4f83e9f2)
Alternatively, this way could be implemented: 
![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/47aac099-3eb9-4ab3-8138-ae907355790e)

# New icons used:
![Bitcoin circle](https://github.com/getAlby/lightning-browser-extension/assets/68239231/7c1d1090-0a6c-491c-bb0d-b3e74022fcdd)

Note:

In "dev mode" you can see the color tokens that are not yet used in the extension
<img width="403" alt="image" src="https://github.com/getAlby/lightning-browser-extension/assets/68239231/94b16ada-e538-4831-b955-c297f3871e2f">

Here's the equivalent of those from tailscale:

<img width="751" alt="image" src="https://github.com/getAlby/lightning-browser-extension/assets/68239231/285e4142-ab0b-4f42-bb77-381590ded4b6">
<img width="743" alt="image" src="https://github.com/getAlby/lightning-browser-extension/assets/68239231/418a6eb4-d65f-40d5-a5a9-1ec4d08e5caf">
<img width="753" alt="image" src="https://github.com/getAlby/lightning-browser-extension/assets/68239231/ceec4ab9-4daa-4559-8682-8af3a6a4ee12">

**Comment by bitcoinuser** [comment]
Is it not possible display qrcode for Non-Alby Accounts? I think it's possible show a qrcode with no amount, right?

**Comment by stackingsaunter** [comment]
> Is it not possible display qrcode for Non-Alby Accounts? I think it's possible show a qrcode with no amount, right?

It is possible, but AFAIK 0 amount invoices are not safe thus not recommneded

**Comment by bitcoinuser** [comment]
> > Is it not possible display qrcode for Non-Alby Accounts? I think it's possible show a qrcode with no amount, right?
> 
> It is possible, but AFAIK 0 amount invoices are not safe thus not recommneded

Hum, I thought that this 0 amount invoices not safe was something already fixed. And to be honest, even if not safe, people will probably use the qrcode to send fund to themselves, so what is the worry?

**Comment by fiatjaf** [comment]
0-amount invoices are safe since 2019 I think. They were fixed by the introduction of the invoice "secret" that prevents nodes in the middle of a route to hijack the payment like they could before.

**Comment by stackingsaunter** [comment]
There were slight changes to the designs (colors, some padding, borders), it's [updated in Figma file](https://www.figma.com/file/MCzf4t1e3pi7Dre6huwq1y/Receive-%2F-Send-revamp?type=design&node-id=251-23749&mode=design&t=yTPX1kVnSI0cJj0z-0)
I also included desktop views.
