### ISSUE TITLE
[Feature] Add https://swarmstr.com/ in Nostr section

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2660]
### Feature description

Add https://swarmstr.com/ in Nostr section

### Describe the solution

Add https://swarmstr.com/ in Nostr section

### Are you working on this?

No

**Comment by reneaaron** [comment]
We are in the process of migrating this discover page to our website here: 

https://getalby.com/discover

You can find a form to submit other apps that you think should be included at the end of this page, I've already submitted the one you suggested here. 👍️
