### ISSUE TITLE
[BUG] Confirm and cancel buttons should be on bottom

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[BUG] Confirm and cancel buttons should be on bottom.

![photo_5098406371589729167_x](https://github.com/getAlby/lightning-browser-extension/assets/1178856/327e7d22-f991-4e69-90de-5e793d49ea71)

### Steps To Reproduce

1- Go to https://www.stacksats.how/podcast and click on Alby extension button

### Expected behavior

Confirm and cancel buttons on bottom

### Alby information

Alby: 3.0.0

### Are you working on this?

No

**Comment by reneaaron** [comment]
Can be fixed in here:

https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/LNURLPay/index.tsx

**Comment by tiwariParth** [comment]
heyy! I would love to solve this issue

**Comment by Rithvik-padma** [comment]
@tiwariParth Are u still working on this?
If not I am ready to work on this.
@rolznz @reneaaron

**Comment by tiwariParth** [comment]
> @tiwariParth Are u still working on this?
> If not I am ready to work on this.
> @rolznz @reneaaron 
> I have fixed it locally.

Ohh Sure you can work on it
