### ISSUE TITLE
Invalid lnurl-auth signature on some domains

### ISSUE THREAD

**Issue by edcolmar** [getAlby/lightning-browser-extension#2667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am implementing lnurl-auth across multiple domains and projects, using the same code.  My second domain:  https://unlockd.gg is always reporting an "invalid signature" error.  

My backend code is based on: https://github.com/ko-redtruck/ln-auth-python

With viewable source here:  https://github.com/unlockd-gg/backend/blob/4eede70c2f837417846d3bb532aaa6ec8d903fd6/backend/app/views.py#L85

### Screenshots [optional]

![alby_error](https://github.com/getAlby/lightning-browser-extension/assets/840851/504e29ba-fed7-4ebe-a281-29bf92887598)

### Steps To Reproduce

Visit:  https://unlockd.gg
Click Login
Click Connect to browser
Perform getalby login steps
Observe "invalid signature" error

### Expected behavior

Expect to get a valid signature.

### Alby information

3.0.0

### Device information

windows, chrome

### Additional context

René Aaron has been super nice and helpful.  He suggested that I open this ticket as he believed it was an internal issue.

### Are you working on this?

None

**Comment by rolznz** [comment]
Hi, what connector are you using? are you using the new secret key LNURL auth, or legacy LNURL auth?

**Comment by edcolmar** [comment]
> Hi, what connector are you using? are you using the new secret key LNURL auth, or legacy LNURL auth?

How can I tell?  Source link is above.

**Comment by ko-redtruck** [comment]
Hello, I wrote this: https://github.com/ko-redtruck/ln-auth-python. It was never meant to be used in production and is probably out of date with the current spec.

**Comment by edcolmar** [comment]
Ditched ko-redtruck.  Everything seems to be working fine using the lapp-template backend instead
