### ISSUE TITLE
[Feature] Should be possible to add accounts using Nostr Wallet Connect of Umbrel

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2687]
### Feature description

Should be possible to add accounts using Nostr Wallet Connect of Umbrel

I have Nostr Wallet Connect on Umbrel and I would  like to add an account with Alby using it.
For now I use LNC with tailscale but sometimes the connection is lost for some unknown reasons. So I think Nostr Wallet Connect could fix it.

### Describe the solution

I have Nostr Wallet Connect on Umbrel and I would  like to add an account with Alby using it.
For now I use LNC with tailscale but sometimes the connection is lost for some unknown reasons. So I think Nostr Wallet Connect could fix it.

### Are you working on this?

No

**Comment by rolznz** [comment]
@bitcoinuser what functionality would you need?

Currently NWC only supports paying invoices and getting balance. Making and checking invoices will be coming soon.

Getting a list of incoming or outgoing transactions may not be supported for a long time.

**Comment by bitcoinuser** [comment]
Completed

**Comment by bumi** [comment]
@bitcoinuser did you use it? how does it work for you?

**Comment by bitcoinuser** [comment]
> @bitcoinuser did you use it? how does it work for you?

Sorry, I didn't test because I stopped my Umbrel Node.
