### ISSUE TITLE
[Feature] Grant Nostr permissions to website

### ISSUE THREAD

**Issue by alexgleason** [getAlby/lightning-browser-extension#2698]
### Feature description

Currently Alby will prompt the user to sign Nostr events with a pop-up. The user can check "Remember my choice and don't ask again" for the entire website.

![image](https://github.com/getAlby/lightning-browser-extension/assets/3639540/07ff9e43-e302-44eb-88b1-46d24d6ebb25)

However, as a website developer, I want the ability to request **specific permissions from Alby**, for example:

```js
[{
  scope: 'nostr.nip04.decrypt',
  filters: [{ kinds: [24133] }],
}, {
  scope: 'nostr.signEvent',
  filters: [{ kinds: [6, 7, 10002] }],
}, {
  scope: 'nostr.getPublicKey',
  filters: [] // ??? not sure about this
}]
```

### Describe the solution

When I call the function from my website, Alby should prompt the user to accept the permissions. The user would have the ability the modify or disable any permissions before confirming.

For permissions that aren't granted, Alby would prompt with a pop-up as normal.

### Are you working on this?

None

**Comment by alexgleason** [comment]
The thing I dislike most is that checking "Remember my choice" allows all permissions. Am I wrong? It's a binary choice between prompt everything and full permissions. I want to grant some permissions all the time, and I want it to always prompt for others.

**Comment by reneaaron** [comment]
This is great feedback, thanks @alexgleason! I agree that it would make sense to have more granular control over which permissions you want to grant to websites. 

Currently there are only permissions for the individual functions (e.g. getPublicKey, signEvent, encrypt, decrypt) but there is currently no way for a user to scope permissions to certain kinds. You can test it yourself over in this demo page: 

https://codepen.io/reneaaron/pen/BavLBMe

> However, as a website developer, I want the ability to request specific permissions from Alby, for example:

Currently you don't request any permissions beforehand (there is no spec for that, yet. I kind of like the idea though as it minimizes the number of permission requests users have to confirm). So whenever a website calls a certain `window.nostr` function, Alby would prompt you for this particular call.

What would you think about adding an option for users to restrict those permissions on a kind basis for a first step? (see screenshot) 

![image](https://github.com/getAlby/lightning-browser-extension/assets/100827540/e7fc3d47-2eb5-4613-9b65-816ba033391c)

cc @stackingsaunter

**Comment by stackingsaunter** [comment]
@reneaaron maybe share with @alexgleason the dropdown you did?

**Comment by badonyx** [comment]
At the very least would be nice to have client auth as a separate event type to help address https://github.com/nostr-protocol/nips/issues/818

**Comment by stackingsaunter** [comment]
Solved with [the newest release ](https://github.com/getAlby/lightning-browser-extension/releases/tag/v3.7.0)
