### ISSUE TITLE
Unlock screen design

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#272]
<img width="465" alt="CleanShot 2021-10-12 at 13 00 04@2x" src="https://user-images.githubusercontent.com/318/136943871-95d5b2d3-e769-4921-b778-245ec62307f0.png">

**Comment by bumi** [comment]
Update proposal: https://www.figma.com/file/xEPJFGFdc3HD0JS1ax2IpH/Extension-(MVP)?node-id=2480%3A15920

**Comment by bumi** [comment]
@umarrg did you already look into this. if not @secondl1ght that would be great if you can look into this!

**Comment by umarrg** [comment]
Yes I've started working on it
