### ISSUE TITLE
[BUG] Zeus URL is incorrect

### ISSUE THREAD

**Issue by dadofsambonzuki** [getAlby/lightning-browser-extension#2723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Zeus link on the accounts page links to `bluewallet.io`.

### Screenshots [optional]

![Screenshot 2023-09-05 at 19 11 53](https://github.com/getAlby/lightning-browser-extension/assets/87125117/08632e8a-eedc-48a4-9212-22dff1d2fa12)

### Steps To Reproduce

Click on Zeus link on Accounts page.

### Expected behavior

Link to https://zeusln.app

### Alby information

Running extension 3.1.1 in Brave.

Looked in the [Accounts Detail](https://github.com/getAlby/lightning-browser-extension/blob/51430e7d6b6076f6f336269acb1dc3928c4ced0f/src/app/screens/Accounts/Detail/index.tsx#L232) code, but couldn't see anything.

Perhaps it's in the [translation JSON](https://github.com/search?q=repo%3AgetAlby%2Flightning-browser-extension+%3C0%3EZeus%3C%2F0%3E&type=code) as the elements don't look to be incrementing? If so I'm happy to submit a PR.

### Are you working on this?

None

**Comment by reneaaron** [comment]
Thanks for reporting this error! :raised_hands: 

I just pushed a fix, should be included in the next release. :crossed_fingers:

**Comment by dadofsambonzuki** [comment]
Damn, I was looking for my first PR! 🤣

**Comment by reneaaron** [comment]
Damn, I didn't know that, sorry. :cry: 

Next time please please let us know about your plans and we can help you with questions, etc. You might also take a look at the good-for-starter issues on our repository:

https://github.com/getAlby/lightning-browser-extension/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee

**Comment by dadofsambonzuki** [comment]
No worries - next time!
