### ISSUE TITLE
Persist lndhub back key for the current session if someone has entered the "Create new wallet" flow

### ISSUE THREAD

**Issue by johnsBeharry** [getAlby/lightning-browser-extension#273]
### Expected Behaviour
```gherkin
  Scenario: See the same key after I exit and return to "Create new wallet"
    Given I am on onboarding
     When I click "Create new wallet"
      And I see the lndhub key i "lndhub://a:a@http://..."
      And I click "Back"
      And I click "Create new wallet"
     Then I see the lndhub key is "lndhub://a:a@http://..."
  ```

### Actual Behaviour
```gherkin
  Scenario: See the same key after I exit and return to "Create new wallet"
    Given I am on onboarding
     When I click "Create new wallet"
      And I see the lndhub key i "lndhub://a:a@http://..."
      And I click "Back"
      And I click "Create new wallet"
     Then I see the lndhub key is "lndhub://b:b@http://..."
```

### Rationale
- Given I backup the lndhub key, but accidently click back (I'm a clicky person) a new key is generated which I may not be aware has to be backed up. Since there is 1. no friction when going back 2. no indication that it's a new key that I'm seeing. It's a bunch of bitvomit so we have to be obvious.
- The may back up the wrong key, which could result in a loss of funds if there is storage or device failiure.

**Comment by bumi** [comment]
we do this now with email/password login
