### ISSUE TITLE
[Feature] Add logo to the QR codes for invoices

### ISSUE THREAD

**Issue by Rithvik-padma** [getAlby/lightning-browser-extension#2757]
### Feature description

Adding the Alby logo to the QR code used for invoices

### Describe the solution

Currently we are using the `react-qr-code` package for creating QR code with invoice instead we can use the `react-qrcode-logo` package to add a logo to the QR codes.

### Additional context

![image](https://github.com/getAlby/lightning-browser-extension/assets/99183441/b7a57e14-54a1-4ba8-8495-507eb114971a)

### Are you working on this?

Yes

**Comment by Rithvik-padma** [comment]
@reneaaron @bumi any thoughts on this?

**Comment by rolznz** [comment]
@Rithvik-padma I am not sure this is necessary now. We just merged a PR to add the user's account avatar to the QR code. Can you please checkout master and try it?

**Comment by Rithvik-padma** [comment]
> @Rithvik-padma I am not sure this is necessary now. We just merged a PR to add the user's account avatar to the QR code. Can you please checkout master and try it?

Ohh I was using a LND test account so I couldn't find that, but we can add the alby logo for non-alby users instead of the avatar (better than a plain QR code), only if it sounds necessary.

**Comment by stackingsaunter** [comment]
I think this can be nice-have if it won't affect scanning. I would use Alby head with white stroke here though so it's visable, or in a white circle. It would be great If you could match the design style here

![CleanShot 2023-09-19 at 03 22 11@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/ffc2151c-6334-419e-a281-5aec23b5bc03)

![Head](https://github.com/getAlby/lightning-browser-extension/assets/68239231/27c41edb-1587-4518-8316-39671411422d)

**Comment by Rithvik-padma** [comment]
Yeah, sure I will see that the design style matches.

**Comment by AnamuddinAhmad** [comment]
@rolznz  Can you assing me please ?

**Comment by rolznz** [comment]
@Rithvik-padma did you work on this one?

**Comment by AnamuddinAhmad** [comment]
Yes, I am working on it.

**Comment by Rithvik-padma** [comment]
> @Rithvik-padma did you work on this one?

Yes I have made the changes locally, will make a PR soon.
Thanks!

**Comment by Rithvik-padma** [comment]
@stackingsaunter I feel the image you provided is too small considering the QR code size

![RLpIMRg2iS](https://github.com/getAlby/lightning-browser-extension/assets/99183441/c3acb53b-55f6-41d2-94dd-fd9829429824)
this is icon you have provided but this is small and of size 32x32 ig.


![Tk60gUEYmV](https://github.com/getAlby/lightning-browser-extension/assets/99183441/382b805f-eea5-4eac-bfeb-95928211afda)
this is of size 64x64 (expanded version)

should I use the icon you have provided or if not can you provide the icon I should use here.
Thanks!

**Comment by rolznz** [comment]
@Rithvik-padma can you use an svg version of the icon?

**Comment by Rithvik-padma** [comment]
> @Rithvik-padma can you use an svg version of the icon?

Yes, I am using a svg version only.
