### ISSUE TITLE
[Feature] Automatically generate a master key for new accounts

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2759]
### Feature description

The onboarding can be simplified if we generate the master key automatically - no need for onboarding prompts and websites just work without having to refresh the page after setting up a master key. LNURL auth onboarding is simplified and backwards compatible (solving https://github.com/getAlby/lightning-browser-extension/issues/2713).

There are many implications here that need to be considered (how to get the user to backup their master key now? where do we show reminders and the master key onboarding? are there any side effects here for existing accounts/existing users?)

### Describe the solution

TBC

### Are you working on this?

None

**Comment by bitcoinuser** [comment]
I agree with this. About backups, maybe could be interesting backup master key to nostr relays, encrypted with lock password?

**Comment by stackingsaunter** [comment]
Epic prepared here: https://github.com/getAlby/lightning-browser-extension/issues/2917
