### ISSUE TITLE
Password invalid when it isn't

### ISSUE THREAD

**Issue by Bosch-0** [getAlby/lightning-browser-extension#276]
Generated and set a new password via my password manager. When entering Alby and locking the app and entering the same password I get an error saying incorrect password - not sure why.

It is quite a large password

&DMwUkC@Cx%YQgsE#4fJ#7K$xY7Dm$uqdRBB%2@G3$JgA3e43d

**Comment by dylancom** [comment]
Just tested this password with the Chrome extension, works fine for me though.

**Comment by bumi** [comment]
did you get an alert message `Passwords don't match.`? or some other error?

**Comment by bumi** [comment]
can you test this again? is this still a problem?

**Comment by bumi** [comment]
we got a few new versions out. 
closing for now, please open it again if the issue still persists.
