### ISSUE TITLE
[BUG] Not nice experience manually entering nostr private key

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

private key is validated on each keypress rather than on form submission.

### Screenshots [optional]

![image](https://github.com/getAlby/lightning-browser-extension/assets/33993199/848f842b-01c6-4051-b686-f94acf978b40)

### Steps To Reproduce

1. Go to nostr private key settings
2. Clear the form and start typing

### Expected behavior

Key is only validated on save

### Alby information

3.1.1

### Are you working on this?

None

**Comment by Rithvik-padma** [comment]
@rolnz I would like to work on this issue, can you assign it to me?
