### ISSUE TITLE
[BUG] QR code is not scannable

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

QR code is not scannable for "leo@getalby.com". I wonder if the short LN address makes the QR less detailed, and therefore the icon hides too much of the QR.

### Screenshots [optional]

![image](https://github.com/getAlby/lightning-browser-extension/assets/33993199/ca841d20-ecc3-4d76-ac3c-6028dbaa55ec)

### Steps To Reproduce

Try scan the above screenshot, or hardcode the app to use leo's LN address.

### Expected behavior

QR should be scannable.

### Alby information

3.2.1

### Are you working on this?

None

**Comment by Rithvik-padma** [comment]
@rolnz I would like to work on this issue, can you assign this to me.
Some ways to overcome this issue are - Bigger qr size, smaller icon or higher error correction level.
I feel using higher error correction level would be a best way, currently we are using `medium` level but using `quartile` level will fix this issue (works fine for 1 character lightning address names too)

**Comment by bumi** [comment]
sounds good @Rithvik-padma

**Comment by AnamuddinAhmad** [comment]
@rolznz I'M INTRESTED WORK ON THIS TECHNOLOGY CAN YOU ASSING ME PLEASE ?
