### ISSUE TITLE
[Feature] Show details of Nostr user you are paying rather than the website

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2777]
### Feature description

When zapping a nostr user on Nostr sites, it doesn't make sense that we are paying the website (we aren't). It is especially confusing when doing split payments.

![image](https://github.com/getAlby/lightning-browser-extension/assets/33993199/6b4a4a67-e518-4d33-a719-e2888e960bf2)

### Describe the solution

Show the name or profile of the person who we are zapping

### Are you working on this?

None

**Comment by reneaaron** [comment]
Since there is just an invoice being passed to `webln.sendPayment()` I wonder where you would get this information from?

**Comment by rolznz** [comment]
@reneaaron hmm, yes I guess this is not possible, not without storing some reference inside the invoice, which we currently do not do, and all zap providers would need to do it too.

**Comment by reneaaron** [comment]
I don't think there is currently a way to achieve this. Feel free to re-open this issue if you ever have a genius idea.
