### ISSUE TITLE
[BUG] Buttons not aligned at the bottom for creating lightning invoice.

### ISSUE THREAD

**Issue by Rithvik-padma** [getAlby/lightning-browser-extension#2786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Create invoice button is not aligned to the bottom of the receive screen  

### Screenshots [optional]

![tUpYYpiFvt](https://github.com/getAlby/lightning-browser-extension/assets/99183441/64c57ff8-86f4-4b22-81ba-c19d6de8f371)

### Steps To Reproduce

1. Go to your Alby extension
2. Click on the "Receive" button
3. Click on the "Lightning Invoice" button
4. You can find the "Create Invoice" button not aligned to the bottom of the screen.

### Expected behavior

The button should be at the bottom of the screen

### Alby information

- Alby version : 3.2.1

### Device information

- OS: Windows
- Browser: Chrome

### Are you working on this?

Yes

**Comment by Rithvik-padma** [comment]
@rolznz I would like to work on this small fix for hacktoberfest only if it sounds valid.
Can you please assign me this issue.
Thanks!

**Comment by reneaaron** [comment]
I am not a 100% sure this will be better (since you have to move your mouse more than before), but it's definitely more consistent. 

Feel free to submit a PR and let's see how it feels. :+1:
