### ISSUE TITLE
[BUG] Small padding issue for the confirm/cancel buttons in the LNURL pay send screen

### ISSUE THREAD

**Issue by Rithvik-padma** [getAlby/lightning-browser-extension#2788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The buttons are breaking a little (padding issue) when more options are open, this hinders the uniformity of padding.

### Screenshots [optional]

![mzBlJky1Mv](https://github.com/getAlby/lightning-browser-extension/assets/99183441/b5d286d9-d082-433f-92dc-089b41abfab2)

### Steps To Reproduce

1. Visit the Alby extension
2. Click on the `Send` button
3. Populate the `Recipient` field and click on `Continue` button.
4. Click on the `More` button at the bottom and you will observe that the padding is not uniform and there is a little bit of breaking issue.

### Expected behavior

The padding issue to be fixed to make the alignment of buttons uniform

### Alby information

Alby Version - 3.2.1

### Device information

- OS - Windows
- Browser - Chrome

### Are you working on this?

Yes

**Comment by weex** [comment]
Are you talking about the space above Name or at the very bottom below the Cancel and Confirm buttons?

**Comment by Rithvik-padma** [comment]
> Are you talking about the space above Name or at the very bottom below the Cancel and Confirm buttons?

the later
