### ISSUE TITLE
[BUG] When adding a new Alby account, shouldn't be able to add an account with same name of an existing account

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

When adding a new Alby account, shouldn't be able to add an account with same name of an existing account. Should ask to add a new name if already one with same name exists.

### Steps To Reproduce

1- Add a new Alby custodial wallet

### Expected behavior

Ask to rename the new account if a existing one exist with the same name.
Why? It's very confusing have two accounts with the same name. 

### Alby information

Alby: 3.2.1

### Are you working on this?

No

**Comment by lujakob** [comment]
I like this issue request, because I usually test two LNBits and have to do the longway of editing the name after creating it. 

But I would suggest adding a distinct "name" field at the beginning of each connector that is prefilled with the value we currently have. In case a connector with this name already exists I would add a suffix (like "(copy)" or "(new)".

@stackingsaunter @reneaaron what do you think of the proposal?

I could work on this.

**Comment by reneaaron** [comment]
I agree this isn't optimal currently, however I don't think we can prefill this field at this stage as the name is only available after the connector was initialized. :thinking: 

I think we have 2 options here: 

1) Offer a link to edit after the account was connected

How about offering a link to edit the account after the connector has been setup? 

https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Options/TestConnection/index.tsx#L123

2) Adding some logic to have distinguishable names automatically 

Suppose we already have a `LNBits` account, the next account could be named `LNBits (2)`

I tend to lean towards 2). What do you think?

**Comment by bitcoinuser** [comment]
> I tend to lean towards 2). What do you think?

I agree.

**Comment by reneaaron** [comment]
Great, let's do it! I assigned @lujakob, let me know if you have any questions regarding implementation.

**Comment by lujakob** [comment]
@reneaaron I created a PR. Please have a look.
