### ISSUE TITLE
Regression: Budget and Login not green color on connected sites

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Budget and Login not green color on connected sites

![Captura de tela de 2023-10-12 10-15-11](https://github.com/getAlby/lightning-browser-extension/assets/1178856/a3da4242-1905-42d4-ad8d-66e4c38b7c15)

### Steps To Reproduce

Visit connected sites and see Login and budget

### Expected behavior

See Login and Budget in green color

### Alby information

Alby: 3.3

### Are you working on this?

No

**Comment by Hemant2335** [comment]
Yaa that's not a big deal I can fix it please assign this issue to me

**Comment by bitcoinuser** [comment]
> Yaa that's not a big deal I can fix it please assign this issue to me

I think this was fixed by @reneaaron here, no?: https://github.com/getAlby/lightning-browser-extension/pull/2814

**Comment by reneaaron** [comment]
@bitcoinuser Very right, I wasn't aware there is an issue for that. Thanks for creating it, I now linked the PR to your issue. :+1:
