### ISSUE TITLE
[Feature] When connecting Alby wallet, should always show Alby popup on right side of the window

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2815]
### Feature description

Hi, I was testing unisat wallet and they always open the popup on the right side of the window. But Alby always open in center.
I think is better open in the right side of the window.

https://github.com/getAlby/lightning-browser-extension/assets/1178856/91481af3-5db9-439a-8a76-86dd5348dbe9

### Describe the solution

Hi, I was testing unisat wallet and they always open the popup on the right side of the window. But Alby always open in center.
I think is better open in the right side of the window.

### Are you working on this?

No

**Comment by reneaaron** [comment]
Interesting, yeah. I always thought having it centered would be good because it immediately draws your attention to it. Since I also noticed quite a lot of people moving the popup around during demoing Alby I wonder whether positioning at the right (also matching the display location of the popup) would overall be better. :thinking: 

@stackingsaunter Any thoughts on that? Feel free to test the build of the linked PR to check out how it feels to you.

**Comment by stackingsaunter** [comment]
I have mixed feelings about this. Normally I'd prefer the right side, same as @bitcoinuser but in my browser (Arc) extension now are on the left side of the browser... so if it would appear on the opposite site of my click, it would be quite frustrating. This is probably one of the few browsers who has it not on the top right side, so I am not sure if we should optimize for it. However, having it at the center at least is universal for all browsers.

We could potentially let user change it in settings?

**Comment by reneaaron** [comment]
I don't know Arc, but the popup window (the one appearing when you click the extension window)  isn't positioned in a special way (the position of those popups is determined by the browser).

This is about the prompt windows that are triggered when you e.g. do a payment via WebLN, sign an event on nostr, etc. 

Not sure if that changes anything for you, but I am against providing a user setting for that.

**Comment by bitcoinuser** [comment]
> Thanks for clarifying.
> 
> I think center is good for this and would keep it. You're performing an action on the website and it appears in front of you (almost like modal), so you continue in the prompt window naturally and don't need to move your mouse away.
> 
> I don't see any benefit in moving it to the right, honestly

I don't agree. Sometimes I'm using a Nostr client like Primal, and click to zap someone and popup a window in front hiding the information you were reading.
