### ISSUE TITLE
[BUG] Button to receive a new payment should be on bottom part as in other windows 

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[BUG] Button to receive a new payment should be on bottom part as in other windows 

![Captura de tela de 2023-10-12 12-41-04](https://github.com/getAlby/lightning-browser-extension/assets/1178856/3d6cfa16-980e-433d-9d8d-d44467cf3651)

### Steps To Reproduce

Receive a ln payment and see the button to receive a new payment

### Expected behavior

Receive new payment button should be at the bottom part of the window.

### Alby information

Alby: 3.3

### Are you working on this?

No

**Comment by lujakob** [comment]
It's a small fix, I can do it.
