### ISSUE TITLE
[BUG] Alby connector does not work on ungoogled chromium and other browsers with different identity redirect URLs

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It's impossible to connect using the Alby connector with browsers that do not support identity, or use a custom redirect URL, because there are only OAuth clients setup for standard Chrome and Firefox redirect URLs.

### Steps To Reproduce

1. Try to login with Alby on the ungoogled chromium browser

### Expected behavior

User can login with whatever browser they choose

### Alby information

- 3.3.0
- ungoogled chromium

### Additional context

Please contact support@getalby.com Error: Wrong Redirect URI. Provided: [ Scheme: https, Host: iokeahhehimjnekafflcihljlcjccdbe.ch40m1umapp.qjz9zk ], Expected: [ Scheme: https, Host: iokeahhehimjnekafflcihljlcjccdbe.chromiumapp.org ]

### Are you working on this?

None

**Comment by rolznz** [comment]
Temporary workaround with Lndhub connector:

1. go to https://getalby.com/node and copy your wallet connection credentials
2. in the Alby extension add a new account -> other wallets -> Lndhub and paste the credentials you copied above.

**Comment by maxvdmerwe** [comment]
Hello Roland,

The workaround works perfectly.

Thank you
Max

**Comment by pavanjoshi914** [comment]
#2869 might resolve this issue

**Comment by reneaaron** [comment]
This should be solved with the newly implemented oAuth connector flow :+1:
