### ISSUE TITLE
Convert connectors to TypeScript

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#283]
The connector classes should be the first parts of the app that we should fully convert to TypeScript and create type definitions.
This makes sure that the functions are called with the correct parameters and makes it easier for connector developers to create new connectors. 
Also we need to write specs for those that can be used to test new connectors.

**Comment by secondl1ght** [comment]
Could you point me to where the connector classes are?

**Comment by bumi** [comment]
https://github.com/getAlby/lightning-browser-extension/tree/master/src/extension/background-script/connectors
