### ISSUE TITLE
Use Alby head as extension icon and change graphic depending on wallet or current website state

### ISSUE THREAD

**Issue by johnsBeharry** [getAlby/lightning-browser-extension#287]
<img width="1196" alt="Screenshot 2021-10-18 at 09 07 07" src="https://user-images.githubusercontent.com/183140/137684311-e8fb6222-383f-45e4-bdc0-46a9da8b41dd.png">

@gbks worked on a set of Alby bot heads which are great for showing the various statuses of the extension.

Would love to see these expanded so we can get it implemented in replacement of the existing extension icon which currently is using a variation of black or orange Sats icon.

From what I gather here are the different things that would affect which icon is currently being shown.

### States
Orange when
- detects WebLN
- detects a twitter profile with a lightning address
- detects a youtube video with a lightning address in description
- a podcast2.0 feed (not sure if this is implemented as yet)

Black when
- Did not detect webln in the page

---

Additional state ideas
- active allowance
- budget low
- tipping enabled

---

1. Have I missed any?
2. Do we want to have more icons to represent other states?
  a. e.g. connection to the users node, or internet connectivity

Here are some other examples.

<img width="914" alt="Screenshot 2021-10-18 at 09 04 39" src="https://user-images.githubusercontent.com/183140/137684011-ae86f6a3-9607-4a62-8d2f-87ef9b3f7549.png">

**Comment by bumi** [comment]
Icon sizes: 
16x16
32x32
48x48
128x128

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons

**Comment by MoritzKa** [comment]
we merged a PR with the new icon. Shall we close this (#287) one.
