### ISSUE TITLE
[EPIC] Improvements resolving "accounts" / "wallets" copy and extension settings problems

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2871]
Identified problems this epic tries to improve:

1. Uses confuse Alby Accounts (alby-hosted wallets) with extension accounts (wallet connections with Alby Extension - custodial or self-custodial)  
2. Users are lost in trying to find settings for one or another (eg. NIP-05)

Based on user research and a lot of brainstorming within Alby team we came up with following solutions:

1. Change (extension) “accounts” to “wallets”
2. Better communicate difference between extension settings / wallet settings
3. Show and link all to important settings regarding Alby Accounts in the wallet settings

You can view Figma filem with some schemas showing current state, proposed change and designs [here](https://www.figma.com/file/w3ZLyJ2ScwPfGKNuzcaNhx/Extension-accounts-%26-settings-problem?type=design&node-id=54%3A10065&mode=design&t=ML7bvnXqIyn1Ntit-1)

## Tasks:

1. - [x] #2872
2. - [x] #2873
3. - [x] #2874

**Comment by Rithvik-padma** [comment]
@stackingsaunter I see that this a very big issue I would like to work on this, can u assign me this issue?
