### ISSUE TITLE
 Swap "accounts" for "wallets" copy

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2872]
Part of #2871 epic, which full desired effect [can be viewed in this Figma](https://www.figma.com/file/w3ZLyJ2ScwPfGKNuzcaNhx/Extension-accounts-%26-settings-problem?type=design&node-id=54-10065&mode=design&t=ML7bvnXqIyn1Ntit-0)

Goal is to change copy related to "extension accounts" that from now on will be called "wallets". 

List of changes:

### Dropdowns
- "Settings" --> "Extension Settings"
- "Account settings" --> "Wallet Settings"
- "Add an account" --> "Connect a Wallet"
- "Manage accounts" --> "Manage Wallets
- "Switch account" --> "Switch Wallet"

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/ada2f5ae-4d90-464b-9f5c-6e0c1bb6e56a)

### "Settings" page
- Page title changes to "Extensions Settings" 

### "Account settings" page
- Page title changes to "Wallet Settings" 

### "Accounts" (Manage accounts)
- Title changes to "Wallets"
- Button copy changes to "Connect a Wallet"
- 
![CleanShot 2023-11-16 at 21 18 42@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/ef91b945-34a3-439c-bfc3-e27ec09150c4)

**Comment by ayushdhiman-py** [comment]
@stackingsaunter Could you please provide details of the files that need to be changed? It would be really helpful.

**Comment by rolznz** [comment]
@ayushdhiman-py this is part of the task to figure that out and make the changes.

**Comment by Harshit-Prasad** [comment]
@stackingsaunter can you assign me this #2872 issue.
I went through the figma files and went through all the required changes I will get back to you once i finish setting up the project.

**Comment by Harshit-Prasad** [comment]
@stackingsaunter sorry but i won't be continuing the issue, thank you as I got to learn about react-i18n. Also this was my first time working on an extension.

**Comment by rolznz** [comment]
@Harshit-Prasad thanks for you work. I don't think the translations are an issue here and we can remove the outdated keys of the other languages by running a script.

**Comment by stackingsaunter** [comment]
@AdarshRawat1 forgot to mention this in initial post

On Wallet Settings page in "Danger" zone copy also must be updated to wallets:

![CleanShot 2023-12-01 at 12 07 49@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/6e48b3a0-15dc-4d17-9b7c-3c83af0a82d7)

**Comment by amitamrutiya2210** [comment]
@stackingsaunter, if this issue is still valid, I would like to work on it.

I noticed that in the wallet setting screen, we still use the account name in some places, such as:
- "Danger Zone"
- "Back up your master key description"

**Comment by reneaaron** [comment]
@amitamrutiya2210 Good point, I just revisited the translations file and found 50 mentions of `account`. Feel free to revisit those occurrences and update them. (please don't just search & replace but go trough them as the context matters quite a bit)
