### ISSUE TITLE
 Updates to Wallet Settings layout

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2873]
Part of #2871 epic, which full desired effect [can be viewed in this Figma](https://www.figma.com/file/w3ZLyJ2ScwPfGKNuzcaNhx/Extension-accounts-%26-settings-problem?type=design&node-id=54-10065&mode=design&t=ML7bvnXqIyn1Ntit-0)

### Main Wallet Settings page

![CleanShot 2023-11-16 at 22 18 54@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/bc7cf758-0a4f-4d16-aafd-6477c1c9b8ff)

- Page title "Wallet Settings" is text-2xl/bold and has an explainer text "Settings related to this particular instance of the connected wallet. If you reconnect, settings related to keys or display name will have to be set again."
- Each section title should be text-xl/bold
- First section title is "General"
- All buttons and a dropdown should be 256px
- Updated capitalization of items (all words capitalized except "of, with, the, on" etc)

#### General section
- New item (only for Alby Accounts): displaying user Lightning Address and CTA to: https://getalby.com/lightning_addresses/{{ALBY ACCOUNT USERNAME}}/edit
- New item (only for Alby Accounts): Connect to mobile wallet and CTA to: https://getalby.com/node   and links to [Zeus](https://zeusln.app/) and [Blue Wallet ](https://bluewallet.io/)

#### Key Management section
- Delete emoji from Key Management title
- Nostr Public Key should not be a disabled input anymore, but just displayed npub. If it's imported, "Imported" tag can be next to the title.
![CleanShot 2023-11-16 at 22 12 23@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/349292cb-6067-4ceb-ae81-29ca0c3c451a)

#### Danger Zone
- "Danger Zone" has the same formatting like previous other sections
- "accounts" copy changed to "wallets"
- Danger buttons should have different visual style as they are irreversible actions
![CleanShot 2023-11-16 at 22 17 26@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/67889d2d-3caf-4ad6-8e39-8f50c0c47f70)

### Nostr Settings

- Layout follows the pattern list from main settings page
- New section added (for Alby Accounts only): "Nostr Address" - displays information if user set or not set their LN address as an identifier, and has a CTA to: https://getalby.com/lightning_addresses/{{ALBY ACCOUNT USERNAME}}/edit

![CleanShot 2023-11-16 at 22 35 10@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/5ad547c4-c0ee-4576-b4b9-7ea43ab4992b)

![CleanShot 2023-11-16 at 22 35 44@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/41da480a-3519-4297-9bb6-e63a8af812dc)

**Comment by Rithvik-padma** [comment]
@saunter Can u assign me this issue. I would like to work on it.

**Comment by stackingsaunter** [comment]
@Rithvik-padma assigned for this issue, good luck!

**Comment by stackingsaunter** [comment]
@Rithvik-padma hey are you still working on this? any progress?

**Comment by Rithvik-padma** [comment]
> @Rithvik-padma hey are you still working on this? any progress?

I was accompanied by some college work so I will start working on it right now.

**Comment by stackingsaunter** [comment]
Hey, still planning to work on this @Rithvik-padma?
