### ISSUE TITLE
Updates to Extension Settings layout

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2874]
Part of #2871 epic, which full desired effect [can be viewed in this Figma](https://www.figma.com/file/w3ZLyJ2ScwPfGKNuzcaNhx/Extension-accounts-%26-settings-problem?type=design&node-id=54-10065&mode=design&t=ML7bvnXqIyn1Ntit-0)

![CleanShot 2023-11-16 at 22 50 44@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/de8f5f6d-50d1-4fd2-ab18-d240c293e9d0)

Changes:

- Page tile contains a description "Global settings that affect your experience on all connected wallets in - Alby Extension.". Space between title and descriptions should be 4px.

- Section headers are text-xl/bold

- All buttons and dropdowns should have fixed 256px width

- Use Title case in all list item labels and buttons 

- Delete Nostr section 

- Delete legacy section

**Comment by AdarshRawat1** [comment]
@stackingsaunter I got it.

> * Delete Nostr section
> * Delete legacy section

Are we removing the whole section?( settings part )

**Comment by stackingsaunter** [comment]
@AdarshRawat1 yes, whole UI parts of the section.

**Comment by amitamrutiya2210** [comment]
Hey @AdarshRawat1, are you still working on this issue? If not, then @stackingsaunter, I would like to try tackling this good first issue.

**Comment by AdarshRawat1** [comment]
This one totally slipped my mind. 🤧

@amitamrutiya2210 if you wish to start contributing to Alby, you can start with this good first issue.

**Comment by amitamrutiya2210** [comment]
Thanks @AdarshRawat1, for replying. I will work on this issue then.

**Comment by amitamrutiya2210** [comment]
Hey @stackingsaunter,

I think some of your suggested changes have already been addressed or removed in the current codebase, such as:

- The subtitle "Global settings that affect your experience on all connected wallets in - Alby Extension" is not present.
- The heading for the General section is missing.
- All buttons and dropdowns have a fixed width of 256px.
- There is no "Nostr" section.

Here are the things I need to do:
- Ensure section header only `Personal Data` is text-xl/bold.
- Delete the legacy section.
- Use Title Case in all list item labels and buttons as suggested in figma file.

Is there anything you want to suggest?

**Comment by AdarshRawat1** [comment]
I think there is some confusion.

> - The subtitle "Global settings that affect your experience on all connected wallets in - Alby Extension" is not present.

> Is there anything you want to suggest?

You have to add the subtitle as it is not present currently.

**Comment by amitamrutiya2210** [comment]
Okay, I overthought this issue. Now I understand it.
