### ISSUE TITLE
Add window.alby.nostr support

### ISSUE THREAD

**Issue by lukegao209** [getAlby/lightning-browser-extension#2886]
### Feature description

window.alby.nostr  is the same with window.nostr(NIP07).

### Describe the solution

After adding this, users will be able to select their own extension when using the plugin. This also avoids the difficulty users face due to the order of window.nostr variable injection caused by different nostr plugins

### Are you working on this?

None

**Comment by reneaaron** [comment]
@lukegao209 This has been recently been implemented with #2907 and has been included within the last release.
