### ISSUE TITLE
Improve NIP07 encrypt prompt

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#2889]
### Feature description

The current encrypt prompt only asks you to allow the client to encrypt things, but it doesn't show any details:

![image](https://github.com/getAlby/lightning-browser-extension/assets/100827540/1958b919-f835-4679-a405-7b29617361d8)

### Describe the solution

There are 2 things that could be added here: 
 - The message that is being encrypted
 - Which public key this will be encrypted for

**Comment by itstomekk** [comment]
Have in mind that it might be a bit confusing, whether you 'remember choice' to encrypt any messages or just this message, like here

![image](https://github.com/getAlby/lightning-browser-extension/assets/16482809/926da224-d2eb-41eb-8384-d9e6a4cfc8af)

**Comment by reneaaron** [comment]
@itstomekk "Remember" is currently per API-call, so you can allow certain actions (signEvent, encrypt, decrypt) to be performed automatically, without prompting you every time.
