### ISSUE TITLE
[BUG] CLN Connection with Rune Shows Balances as `NaN`

### ISSUE THREAD

**Issue by kn0wmad** [getAlby/lightning-browser-extension#2910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Balance and historical incoming tx amounts all show as `NaN`

### Screenshots [optional]

![image](https://github.com/getAlby/lightning-browser-extension/assets/39687477/ea37a55f-cf6f-4356-bd22-d0d9b8e352ba)

### Steps To Reproduce

1. Connect via CLN with a Rune (in this case from StartOS)
2. Connection completes successfully
3. Balance and historical incoming tx amounts all show as `NaN`
    - Historical outbound tx amounts display properly

### Expected behavior

Correct balances and payment history display in sats

### Alby information

Alby 3.4.1 Firefox extension

### Device information

Linux 6.1, Firefox 120

### Are you working on this?

None

**Comment by kn0wmad** [comment]
The balance issue has been fixed, however the NaN bug still remains for the tx history.  Suggest re-open

![image](https://github.com/getAlby/lightning-browser-extension/assets/39687477/cbc43682-792e-48cb-9e5a-a1dc6740c1c8)

**Comment by pavanjoshi914** [comment]
![image](https://github.com/getAlby/lightning-browser-extension/assets/55848322/18decd86-143f-444a-8af6-b50bfd9e707e)


just had a quick test on cln. was unable to reproduce. what kind of transactions those are someone paying you rom specific website or something else?

**Comment by kn0wmad** [comment]
Good thought - I rolled down and realized this is only happening on spam txs of 1sat, of which I've received a ton for some reason.  These are all keysends.  Legitimate txs (all > 1sat) are shown accurately.  Hopefully this is helpful.

**Comment by pavanjoshi914** [comment]
> Good thought - I rolled down and realized this is only happening on spam txs of 1sat, of which I've received a ton for some reason. These are all keysends. Legitimate txs (all > 1sat) are shown accurately. Hopefully this is helpful.

thanks for helping us @kn0wmad! issue should be resolved in next release
