### ISSUE TITLE
[EPIC] New onboarding with Master Key autogenerated with the wallet connection

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2917]
### Overall goal

This epic aims to adjust onboarding experience that accommodates Master Key creation with every wallet connection, thus requiring us to more eagerly encourage users to back up the Master Key. It also introduces a bunch of other UX and UI improvements to the overall onboarding experience.

### Issues

1. https://github.com/getAlby/lightning-browser-extension/issues/2918
2. https://github.com/getAlby/lightning-browser-extension/issues/2919
3. https://github.com/getAlby/lightning-browser-extension/issues/2921
4. https://github.com/getAlby/lightning-browser-extension/issues/2932
5. https://github.com/getAlby/lightning-browser-extension/issues/2922
6. https://github.com/getAlby/lightning-browser-extension/issues/2923
7. https://github.com/getAlby/lightning-browser-extension/issues/2924

### Related issues

- https://github.com/getAlby/lightning-browser-extension/issues/2920#issue-2036660877
- https://github.com/getAlby/lightning-browser-extension/issues/2925

**Comment by ayushanand308** [comment]
@stackingsaunter  I can work on this as well.

**Comment by pavanjoshi914** [comment]
closing as done
