### ISSUE TITLE
Add language picker to the onboarding

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2918]
Part of https://github.com/getAlby/lightning-browser-extension/issues/2917 epic

User cannot currently set their preferred language before they actually onboard to the extension
We can add small language selector in the top left corner of the screen. It would be good if it could be fixed in the corner of the screen

See [Figma designs here](https://www.figma.com/file/IvlUHnC3vkIWnQ14FppZqT/%F0%9F%8E%A8-Extension-UI-revamp?type=design&node-id=844-14307&mode=design&t=WBy4yi31pW9Wm4mb-4)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/5502cd75-6189-40c0-a193-4624b6afbc87)
![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/417b7bcc-9f09-4abd-b762-892a581253a3)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/78744b83-2369-4bb4-82a7-ae378af8b33c)
![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/22e2285a-8d87-497d-970a-66ed17ab358e)
![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/9c7ad191-a558-4a05-91bc-b9f3f5faab1e)

**Comment by Nkiriobasi** [comment]
I'll take this up.
