### ISSUE TITLE
Onboarding screens UI and copy improvements and fixes

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2919]
Part of #2917 epic

## Improvements across all screens

- Button color in these designs are different, you can ignore that
- For detailed views and more handoff files/screenshots that will felp you work on it, see [Figma file here](https://www.figma.com/file/IvlUHnC3vkIWnQ14FppZqT/%F0%9F%8E%A8-Extension-UI-revamp?type=design&node-id=847-14350&mode=design&t=Ny2zb50J17F9Ewmk-4), also check out dev mode to inspect better

### 1. Delete "Welcome to Alby" from the top

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/3d12ea49-2f01-40d6-aee8-27e2cb1af496)

Right now cards are centred and "Welcome to the Alby" can stick to the card in a buggy way. Let's delete this at all so it does not take space and force user to scroll and not see buttons on smaller screens.

### 2. Cards styling
- [x] Delete card shadows
- [x] Add border 1px inner gray200 / dark: neutral700
- [x] Change corner radius to rounded-2xl
- [x] Put buttons inside the card, center and fix 256px (w-64)
- [x] all cards should have p-10 padding (40px)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/afdd2d55-9817-44fd-8f4b-8f29f39e8410)

### 3. Use icons from Popicons 

See https://github.com/getAlby/lightning-browser-extension/issues/2920#issue-2036660877

There are also some custom icons that are not available in this set, which I provide seperately

Icons color (except color ones): gray600 / dark: neutral400

### 1. Create Unlock Passcode

- [ ] center content
- [ ] delete copy from the above of the image
- [ ] add two points with icons from Popicons

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/9948c22b-510f-44ea-a706-b0b7df43c662)

### 2. Choose Your Wallet

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/4a14578c-71a5-4984-ad46-8125990a7628)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/80915110-5ac3-45e4-b157-c1198fcd950d)

- [ ] changes to copy all over
- [ ] make both cards width w-96 (384px)
- [ ] spacing between them p-6
- [x] use Popicons for listed points
- [x] buttons 100% width inside cards (only here)

Needed icon for "bring your own wallet":
![connectors](https://github.com/getAlby/lightning-browser-extension/assets/68239231/d6113ed2-ae97-48cf-a936-99c0ae4f0f23)
 
### 3. Wallet connector screens

- [x] delete shadow on connector selection cards
- [ ] add 1px border gray 200 dark:neutral700]
- [ ] make sure individual connector flow cards are max-w-xl (576px) and have p-10 padding (40px)
- [ ] buttons 256px inside the cards (w-64)
- [ ] If you see any differences from how it's implemented now and how it looks in Figma, I appreciate If you change it as well 🙏

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/24fc3320-18c9-422d-88e4-cd557481b071)
![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/5e1d2e31-d0ea-4a70-8e55-64a6146b48ff)

### 4. Pin extension screen

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/b3f7f2fb-2782-43f4-b792-93d3ed3c7d84)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/b728e479-25f5-49e9-bcb0-c6105cbf9a6e)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/1ea88428-1dfc-4ef1-beba-26f968c0bc32)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/cdca5e29-4535-442f-9009-8aeb39b81f0f)

- [ ] General overhaul of this page, new copy
- [ ] "Pin me here!" pointer in the top-right place of the screen. Make sure Alby bee head in dark-mode has white stroke
- [ ] Shortcut buttons that are highlighted when user types those keys (the middle should reflect user system: mac keyboard "⌥" or and Windows "Alt"

Content of what's in the popup is a separate issue, here only for reference to show popup is triggered

Alby bee and head and in case it's not in the extension files already
(light mode and dark mode):

![Full](https://github.com/getAlby/lightning-browser-extension/assets/68239231/8521caad-33f8-4adf-a228-0def2755ff32)
![White](https://github.com/getAlby/lightning-browser-extension/assets/68239231/8dae888c-d861-494b-9cac-112ca274b75b)

![Expression=Default](https://github.com/getAlby/lightning-browser-extension/assets/68239231/4e079b7b-4102-4c2c-8825-fb9d81574c63)
![Expression=White Stroke](https://github.com/getAlby/lightning-browser-extension/assets/68239231/23bffadf-33e7-41b4-8bb1-4ec48f38129c)

Puzzle icon:
![puzzle](https://github.com/getAlby/lightning-browser-extension/assets/68239231/c8dfdfbe-d7ea-423e-bb75-f78f3166617e)

**Comment by Nkiriobasi** [comment]
And also take this up

**Comment by stackingsaunter** [comment]
@Nkiriobasi I just finished writing this issue, please double check If you want to work on this!

**Comment by Nkiriobasi** [comment]
I'll focus on the first one.

**Comment by stackingsaunter** [comment]
Choose your wallet screens are addressed here https://github.com/getAlby/lightning-browser-extension/pull/2952 so no need to work on those

**Comment by pavanjoshi914** [comment]
welcome to alby heading is fixed recently. maybe no need to delete it now

**Comment by Dunsin-cyber** [comment]
Hi @stackingsaunter , I want to update the "Pin extension screen" with the new shortcut to open the extension:  "ALT + A" and also the design generally.

But I'm confused; which design should I go with? This one here referenced in the issue or the one in Figma?


this is the one in Figma ⬇
<img width="1358" height="639" alt="Image" src="https://github.com/user-attachments/assets/c816d148-1057-4732-8c74-2f74cff12f7e" />

This is what we have published presently

<img width="1329" height="635" alt="Image" src="https://github.com/user-attachments/assets/8f131be4-27fe-4ea8-b112-d2fa6ab400e1" />

**Comment by Dunsin-cyber** [comment]
> Hi [@stackingsaunter](https://github.com/stackingsaunter) , I want to update the "Pin extension screen" with the new shortcut to open the extension: "ALT + A" and also the design generally.
> 
> But I'm confused; which design should I go with? This one here referenced in the issue or the one in Figma?
> 
> this is the one in Figma ⬇ <img alt="Image" width="1358" height="639" src="https://private-user-images.githubusercontent.com/85681801/462619527-c816d148-1057-4732-8c74-2f74cff12f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIxNjg0NjMsIm5iZiI6MTc1MjE2ODE2MywicGF0aCI6Ii84NTY4MTgwMS80NjI2MTk1MjctYzgxNmQxNDgtMTA1Ny00NzMyLThjNzQtMmY3NGNmZjEyZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzEwVDE3MjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3N2Y4MjRlZWE3NDNkNmUzNTFiYzdhMGZmMWNlYzQ0NDQ5N2U5MjM2ZWEyYmQwNWIxOWJkNzgxYmFiMDYwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UUIuqV6TXoXfvxynS3os3VIAAly4E8ghCsS7MqeVMtU">
> 
> This is what we have published presently
> 
> <img alt="Image" width="1329" height="635" src="https://private-user-images.githubusercontent.com/85681801/462620371-8f131be4-27fe-4ea8-b112-d2fa6ab400e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIxNjg0NjMsIm5iZiI6MTc1MjE2ODE2MywicGF0aCI6Ii84NTY4MTgwMS80NjI2MjAzNzEtOGYxMzFiZTQtMjdmZS00ZWE4LWIxMTItZDJmYTZhYjQwMGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzEwVDE3MjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNWY4YmU2NmYyN2QwNTQ1OWQ2Nzc2YTIyMDlmYjU3M2M2MTdmNWFlYmQ2YTNiNjk0ZTBlN2NlYTc0NTQxMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FeBqilmJjhXLciCUuPbsYEXlT9BRfMtzMEGLbkWf0uQ">

any update on this @stackingsaunter ?
