### ISSUE TITLE
Change iconset to Popicons

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2920]
Swap all existing icons in the extension to ones from open source iconset Popicons.
There is possible a react import, see here:
https://github.com/uxthings/popicons

Current designs with new icons can be [viewed here](https://www.figma.com/file/LP96uJXiN2ULQuHyfKaklF/%F0%9F%90%9D--Alby-Browser-Extension?type=design&node-id=1440-1857&mode=design) (currently file is a bit messy, but that shouldn't affect this issue)

**Note:** In the designs I use a default viewbox 24x24 for icons, and if they are rescaled, they are rescaled from that viewbox

There a few custom icons that are not in the set, and are included here:
- ![puzzle](https://github.com/getAlby/lightning-browser-extension/assets/68239231/ad5c64a5-70f5-47c2-ae2f-b0b52257a222)
- ![face-surprise](https://github.com/getAlby/lightning-browser-extension/assets/68239231/f74e09b4-6cc1-40ea-a700-bd97ef5cc811)
- ![arrow-up-right](https://github.com/getAlby/lightning-browser-extension/assets/68239231/33313623-2903-4e85-a223-de07b5396d65)

These are some icons currently implemented that can stay (because there's no popicons version):
- chevrons
- "Connnected Sites" (alby with checkmark)

**Comment by stackingsaunter** [comment]
@MayaSatishRao go ahead

**Comment by MayaSatishRao** [comment]
@stackingsaunter i ran the project successfully. And I don't know how to proceed further? 
![Screenshot 2024-01-06 134429](https://github.com/getAlby/lightning-browser-extension/assets/67920373/a224f54a-771d-4859-bc74-957c7667be7d)
Also, which package is currently used for icons?

**Comment by MayaSatishRao** [comment]
@stackingsaunter which wallet should I connect?

**Comment by stackingsaunter** [comment]
@MayaSatishRao hey, I don't know what you mean exactly. You can connect any way you want. It shouldn't matter in relation to the issue.

Currently we're using https://bitcoinicons.com/

**Comment by amitamrutiya2210** [comment]
Hey @MayaSatishRao , are you still working on this issue? If not, then @stackingsaunter, I would like to try tackling this good first issue.

**Comment by reneaaron** [comment]
@amitamrutiya2210 Feel free to submit a PR!
