### ISSUE TITLE
New onboarding/notifications popup item buttons

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2922]
Part of #2917 epic

Component used in the current "Receive" screens, after some updates will be reused instead of current "onboarding cards".

See [Figma file](https://www.figma.com/file/IvlUHnC3vkIWnQ14FppZqT/%F0%9F%8E%A8-Extension-UI-revamp?type=design&node-id=847-14354&mode=design&t=Ny2zb50J17F9Ewmk-4) for detailed design inspect

## Styling

![CleanShot 2024-01-12 at 11 16 37@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/583346a8-e86a-4eb0-88c4-979ffb919287)

![CleanShot 2023-12-13 at 02 20 26@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/b55ab3ee-d88d-4a69-af40-d2fdc39a944f)

### To do

- [x] corner radius to **rounded-xl** (12px)
- [ ] use Popicons icons and update "Receive" icons too https://github.com/getAlby/lightning-browser-extension/issues/2920#issue-2036660877 (excep Chevrons, as there's no one in Popicons atm)
- [ ] copy colors
- [ ] chevron color change to gray400 / dark: neutral500
- [ ] spacing between cards sm (8px)
- [ ] make sure Receive screen uses the same component

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/400c2a24-4549-412b-b894-6bad8229ded5)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/c172a7ff-9510-482d-9279-228b19bdc84b)

## Behaviour

1. **Whenever connected wallet has no transactions, 4 cards should be visible** (3 + 1 after scroll)
(We can skip "Buy bitcoin" card for now since onramps are turned off for the moment)

![CleanShot 2023-12-13 at 02 41 20@2x](https://github.com/getAlby/lightning-browser-extension/assets/68239231/4056510f-fdc2-4d15-8ec8-727522d6488b)

2. **When transaction list is loaded, then:**
a) If user with this connected wallet went through Master Key backup or import flow, we don't show any cards
b) If user hasn't finished either import or backup flow, we always show "backup" and "import" cards

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/fd7664a2-6300-4b67-8d6a-97a99f93022a)

**Comment by MayaSatishRao** [comment]
@stackingsaunter i want to contribute to this issue? Can i work on this?
