### ISSUE TITLE
Update menu dropdown and navigation

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2924]
Part of #2917 epic

### Popup dropdown
- [x] update dropdown item layout
- [x] update items copy (Wallet -> Full Screen)
- [x] delete dividers
- [x] delete "Discover" button from the dropdown
- [x] update icons to [Popicons](https://github.com/getalby/lightning-browser-extension/issues/2920)
- [x] add border to the dropdown, 1px inner gray200 / dark: neutral700
- [x] change dropdown corner radius to rounded-xl
- [x] update copy colors if are mismatched to one in Figma

### Full screen view, dropdown and navigation
- [x] update copy colors of the navigation to those in Figma
- [x] change Discover copy to Discover Apps, add icon arrow up right icon and it should lead to https://getalby.com/discover
- [x] at the same time, all Discover page can be deleted from the extension

#### Arrow up right icon:
![arrow-up-right](https://github.com/getAlby/lightning-browser-extension/assets/68239231/62830459-5d4d-4aca-91aa-ce6966917cf7)

### Screenshots 

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/d21937f2-c6c0-4c0b-a691-6f0684fd97a7)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/13182dec-fea5-4647-8efe-f9e80da9b4e3)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/35c65c81-b887-4b12-9612-8b532a5b54d6)

**Comment by bitcoinuser** [comment]
I have a suggestion here. I think in the bottom of the menu, should have icons of Alby social networks, like Nostr, X, Telegram, Github. For now is not easy to people find where follow Alby. 
Something like this:

![Captura de tela de 2024-01-14 17-53-09](https://github.com/getAlby/lightning-browser-extension/assets/1178856/75d32474-c97a-410c-becd-b8188784b1f2)

**Comment by pavanjoshi914** [comment]
what we do about the tip cards here?

**Comment by stackingsaunter** [comment]
@pavanjoshi914 no tip cards anymore, those buttons kinda take their place https://github.com/getAlby/lightning-browser-extension/issues/2922

**Comment by reneaaron** [comment]
@bitcoinuser We might consider that adding at one point, but that's probably a separate PR. Thanks for the feedback!
