### ISSUE TITLE
[BUG] non-LNURL link with "lnurl" in it incorrectly opens Alby extension

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<a href="https://files.ekzyis.com/public/sn/lnurlpay_comments.mp4">lnurlpay_comments.mp4</a> opens the extension when it should not.

### Steps To Reproduce

1. Click the link lnurlpay_comments link in https://files.ekzyis.com/public/sn/

### Expected behavior

Alby does not intercept links that are not actually LNURLs

### Alby information

3.4.1

### Are you working on this?

None

**Comment by ekzyis** [comment]
> [lnurlpay_comments.mp4](https://files.ekzyis.com/public/sn/lnurlpay_comments.mp4) opens the extension when it should not.

interestingly, the extension does not open when clicking on the link in Github :thinking: 

Proof of bug:


https://github.com/getAlby/lightning-browser-extension/assets/27162016/a0a86907-fc14-4e89-a3dd-821333c74afa

**Comment by pavanjoshi914** [comment]
unable to reproduce this in pure html. need more information about the same!

**Comment by ekzyis** [comment]
> unable to reproduce this in pure html. need more information about the same!

Steps to reproduce with minimal HTML:

1. Save following file:

```html
<html>

<body>
    <a href="lnurlpay_comments.mp4">lnurlpay_comments.mp4</a>
</body>

</html>
```

2. Host file with a webserver. Example: `python -m http.server 8000`
3. Go to http://localhost:8000
4. Click on link

<details>

<summary>video</summary>


https://github.com/getAlby/lightning-browser-extension/assets/27162016/f08fe806-cf94-4e34-8eb2-e22e82daf7d0

</details>

**Comment by pavanjoshi914** [comment]
thanks for providing the additional information. yup! this can be a problem when a site has such relative URLs
