### ISSUE TITLE
Update Master Key back up and import flows

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2932]
Part of #2917 epic

For detailed inspect of designs, [see this Figma file](https://www.figma.com/file/IvlUHnC3vkIWnQ14FppZqT/%F0%9F%8E%A8-Extension-UI-revamp?type=design&node-id=877-18928&mode=design&t=7prPviaZBt6uBX6l-4)

### To do

- [ ] Update copy on both screens with new [Popicons](https://github.com/getAlby/lightning-browser-extension/issues/2920)
- [ ] Illustration update (light and dark mode) and it goes below copy
- [ ] Add border 1px inner gray200 / dark: neutral700
- [ ] Change corner radius to rounded-2xl
- [ ] Put buttons inside the card, center and fix 256px (w-64)
- [ ] Cards should have p-10 padding (40px)
- [ ] Ideally, recovery phrase box with 12 words is narrowed and layout follows the one in Figma (doesn't have to be ideally the same though)

### New illustrations:
![Type=Dark](https://github.com/getAlby/lightning-browser-extension/assets/68239231/531c8ea5-6553-45df-b66e-6cc50270373a)
![Type=Light](https://github.com/getAlby/lightning-browser-extension/assets/68239231/e2888af1-3632-4602-856c-7769ef13a34b)

Custom icon (not available in Popicons):
![face-surprise](https://github.com/getAlby/lightning-browser-extension/assets/68239231/475164dd-34f3-4352-a308-950231487ce1)

### Screenshots

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/25a921bf-7110-4372-97d4-af645dcc2597)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/c255fb1d-43d6-4c12-98d4-b69af21438df)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/654d5dac-5001-4679-a9ee-a4ffcd8574e3)

**Comment by ayushanand308** [comment]
@stackingsaunter I can take up this issue and start working on this ASAP.
