### ISSUE TITLE
[BUG] List of transaction order on LNC connector is not correct

### ISSUE THREAD

**Issue by frnandu** [getAlby/lightning-browser-extension#2937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When connecting my LN node using the LNC connector, I get the following behaviour on my list of transactions:
First there are listed my invoices, and only in the end the payments but showing -NaN sats

### Screenshots [optional]

![Screenshot from 2023-12-16 17-06-32](https://github.com/getAlby/lightning-browser-extension/assets/1931672/8c350e1f-f268-4341-bb90-a0a77cd82e46)

### Steps To Reproduce

connect with LNC

### Expected behavior

transactions should be sorted chronologically and correct amound on the payments

### Alby information

3.4.1

### Device information

Ubuntu, Firefox

### Are you working on this?

None

**Comment by reneaaron** [comment]
This has been fixed recently, just tested and works correctly now.
