### ISSUE TITLE
[BUG] CORS issue

### ISSUE THREAD

**Issue by ChristianChiarulli** [getAlby/lightning-browser-extension#3000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm having a CORS issue

### Screenshots [optional]

![image](https://github.com/getAlby/lightning-browser-extension/assets/29136904/0a787ce9-e58c-4015-b7f5-566a42b01470)

### Steps To Reproduce

```
export async function getZapEndpoint(profileEvent: Event) {

  try {
    let lnurl = "";
    const { lud16 } = JSON.parse(profileEvent.content) as Profile;
    if (lud16) {
      const [name, domain] = lud16.split("@");
      lnurl = `https://${domain}/.well-known/lnurlp/${name}`;
    } else {
      return undefined;
    }

    const res = await fetch(lnurl);
    const body = (await res.json()) as ZapResponseBody;

    if (body.allowsNostr && body.nostrPubkey) {
      return body.callback;
    }
  } catch (err) {
    console.error(err);
  }

  return undefined;
}
```

### Expected behavior

no CORS issue

### Alby information

Installed on firefox through extension store

### Device information

tested on linux and macOS

### Are you working on this?

None

**Comment by bumi** [comment]
I think this might be an issue because getalby.com currently has some downtime and networking issue

**Comment by ChristianChiarulli** [comment]
yea I think so too, thanks for confirming.
