### ISSUE TITLE
Wallet connected through NWC shows wrong dates in transaction list

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#3006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I connected a NWC app with the Breez SDK and a Greenlight node to Alby. The dates of the transactions are off.

### Screenshots [optional]

![image](https://github.com/getAlby/lightning-browser-extension/assets/13707997/df799f65-d0cf-4ec9-9d99-f6bf89fb51a6)

### Steps To Reproduce

connect a NWC app with the Breez SDK and a Greenlight node to Alby

### Expected behavior

correct dates

### Alby information

the latest version of the Alby extension

### Are you working on this?

None

**Comment by reneaaron** [comment]
This has already been fixed in master. cc @rolznz
