### ISSUE TITLE
Update Import flow with a link to import only Nostr key

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#3037]
A lot of users might want to import just nostr key, without being interested in master key. Currently they don't have any good flow for this and would have to find Nostr settings and import it by themself

Let's add a simple change to latest improvements to Master Key related changes

## 1. Change copy of "Import" card to include Nostr key there:

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/c2c8a723-9d32-4cf0-bb20-ee09f0974df2)

Title: Import Master Key or Nostr key
Description: Use existing Master Key or Nostr private key to use them with this wallet

## 2. Add a screen to choose which key user wants to import

It uses the cards we used in a wizzard some time ago (now they are not in the extension). I just changed corner radius of them to 12px (and layout inside the card a bit)

Master Key path leads to Import Master Key screen.
Nostr key path leads to Nostr settings screen.

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/eb3547ba-946d-446a-900e-77f3f3d236a7)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/41d477a4-f5b1-4a61-bda9-37224c859ffb)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/09ba4181-2318-4919-9b15-e4740e69a70f)

**Comment by stackingsaunter** [comment]
@pavanjoshi914 please hold, I will update this issue later today

**Comment by pavanjoshi914** [comment]
@stackingsaunter do ping me when changes are finalised

**Comment by stackingsaunter** [comment]
@pavanjoshi914 changes finalised! Quite a bit of them though:

## 1. There's only one button for both backup/import:

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/dcc1d9e5-49d2-4a22-a6a1-c61a56ecfb6b)


## 2. Clicking on it opens this screen with Master Key onboarding and a choice to back up / import
There is a small link at the top to Nostr settings to import just nostr keys

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/27f3d11a-2666-4f2b-8762-a5781df675af)
![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/352f9d88-c8e7-4579-beb8-d5f9843744c5)

## 3. Back up is the same

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/d66df27a-8fa1-4f3d-82e7-a45c7eb13a24)


## 4. Import should be the same

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/4afab11e-5fab-4bfc-b834-aa0387716fd9)

--- 

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/ab7b05d7-e47c-454c-80d6-3e9a83d2d24b)
