### ISSUE TITLE
Store full location and LNURL description for tipping payments  

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#304]
Currently we only save the host. We should also store the full location and the LNURL description in the tipping payment.

we probably need to pass in more information here: https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/LNURLPay.tsx#L67-L70

all payment attributes: https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/db.js#L11

**Comment by escapedcat** [comment]
`db.js` was moved to TypeScript:  
https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/db.ts#L11

**Comment by escapedcat** [comment]
Can this be closed?  
We do this i.e. here, yes?: https://github.com/getAlby/lightning-browser-extension/blob/fix/currency-conversion-rate/src/extension/background-script/actions/ln/sendPayment.ts#L48

**Comment by bumi** [comment]
do we store the full location? your link goes to a notification.
