### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#305]
I heard people like dark modes
Can we use the system's dark/light mode?

**Comment by secondl1ght** [comment]
Do you know how you want this implemented? If so I could do some research and start working on it.

**Comment by secondl1ght** [comment]
I did some research on this and it looks like Tailwinds makes this fairly easy. I'll look into implementing it.

**Comment by secondl1ght** [comment]
Question: I am starting to implement this on this screen first ```src/app/screens/Onboard/ChooseConnector/index.tsx``` but I dont see in this file where the styling for the main page comes from. I see styling for some elements on the page and I know I need to go to component files for other elements but where is the styling for the main page coming from. For example the background color of the entire page for this screen?

**Comment by bumi** [comment]
I think @dylancom can help here.
but I think if it is too much changes or too complicated we should do that later.

**Comment by secondl1ght** [comment]
Shouldn't be too complicated, I just need to add a dark mode styling for each element. Because I am new to the project I just don't know where to find all the elements that's all.

But if it is decided to be lower priority I can work on something else too. I did start making some changes though and the dark mode does look pretty good.

**Comment by bumi** [comment]
up to you. :) I just don't think we should too many potential breaking changes at this moment. 
but a (WIP) PR would be awesome then we can discuss there.

**Comment by secondl1ght** [comment]
Ok I started an initial draft here #360.
