### ISSUE TITLE
[Feature] Creation of LNURL-w vouchers

### ISSUE THREAD

**Issue by itstomekk** [getAlby/lightning-browser-extension#3052]
### Feature description

Some users requested it, but it's not often raised.

Alby users can redeem LNURL vouchers, but not create. Would be nice to have this feature, though not super important.

### Describe the solution

![image](https://github.com/getAlby/getalby.com/assets/16482809/a61d6cf7-56bc-48d1-b07b-40a96e6472f2)

### Additional context

I'm not sure if this is correct repo for this

### Are you working on this?

None

**Comment by reneaaron** [comment]
This would first and foremost need to be supported by the wallet backend. (not the extension)

**Comment by itstomekk** [comment]
Exactly...then which repo?

pon., 19 lut 2024, 14:20 użytkownik René Aaron ***@***.***>
napisał:
