### ISSUE TITLE
Unify "sats" wording

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#308]
Currently we use "Sats" "Sat" "sats". 

what is it? seems most apps use "sat"

**Comment by secondl1ght** [comment]
If we decide on a standard I could update all instances of the word.

**Comment by bumi** [comment]
I think `sat` it is.

**Comment by secondl1ght** [comment]
Do you also want instances of 'Satoshi' changed to sat?

**Comment by secondl1ght** [comment]
PR #364
