### ISSUE TITLE
[BUG] Error: 400: Internal keysend payments require the custom record 696969 to be present.

### ISSUE THREAD

**Issue by amcquade** [getAlby/lightning-browser-extension#3088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to get boosts working for a Podcast 2.0 app. I have been following [webln documentation](https://www.webln.guide/building-lightning-apps/webln-reference/webln.keysend) and using [existing applications implementation as a reference](https://github.com/Podcastindex-org/helipad/blob/main/webroot/script/helipad.js#L666). Nothing works seems to work. Going forward I will be testing previous version of the extension to find the stable version. We have used this same implementation in other services, now nothing works. 

### Steps To Reproduce

1. Visit https://widgets.blubrry.com/162/boost
2. Click boost button
3. Fill in boost information
4. Click boost
5. Confirm boost
6. Internal error appears

### Expected behavior

The extensions should let me pay since that custom value is already set in the boost object.

### Alby information

- Alby version: 3.6.0
- Extension installed through browser
- Alby wallet connected

### Device information

- OS: windows
- Browser: Firefox developer, chrome developer, standard chrome

### Are you working on this?

None

**Comment by reneaaron** [comment]
@amcquade Thanks for the report, I could reproduce it. We're currently looking into this issue.

**Comment by amcquade** [comment]
@reneaaron thank you so much ! i was starting to go a bit crazy 😅

**Comment by bumi** [comment]
@reneaaron @amcquade can you try again? it should work now.

**Comment by amcquade** [comment]
@bumi @reneaaron boost worked ! thank you guys so much !!
