### ISSUE TITLE
Limit amount of transactions show in the popup

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#310]
Currently we just list all transactions. Probably we should only list the last n transactions.

**Comment by bumi** [comment]
@secondl1ght do you maybe want to look into this? 
I feel like as more people start using Alby this becomes more important. otherwise the list becomes super long and useless.

**Comment by secondl1ght** [comment]
I can look into this for sure, I am a bit busy over the next few days so if it needs to be done right away then maybe someone else should do it otherwise i'd be happy to give it a try!

**Comment by secondl1ght** [comment]
PR #461 in
