### ISSUE TITLE
[Feature] Add support for denying a sign request and remember

### ISSUE THREAD

**Issue by vicariousdrama** [getAlby/lightning-browser-extension#3110]
### Feature description

When visiting some web applications, I am confronted with requests to sign events that I don't want to, and never want to.  For example, 

- Coracle wants me to repeatedly sign kind 15 events for notifications
- Primal wants me to sign kind 30078 for app settings

The browser extension has an option to remember my choice and don't ask again, but this only applies when continuing with the signing event.

![image](https://github.com/getAlby/lightning-browser-extension/assets/88121568/03784dd6-180f-48f4-8d27-1803773b0b38)

### Describe the solution

Add another button next to Cancel, or a Drop Down from Cancel to "Deny". If a signing event is denied, and not simply cancelled, then take into account whether the checkbox to remember my choice is checked and apply to future requests of the same kind.

### Are you working on this?

No

**Comment by reneaaron** [comment]
@vicariousdrama Thanks for your feedback, I totally understand that this a pain currently. 

We already have plans to improve on that, hopefully we'll be able to include it in the next release coming up in the next month.

**Comment by reneaaron** [comment]
This has been included in the latest release. Feel free to check it out!
