### ISSUE TITLE
Export transactions with metadata

### ISSUE THREAD

**Issue by badonyx** [getAlby/lightning-browser-extension#3118]
### Feature description

Alby as a Lightning wallet needs a way to export transactions since there is no other way to track transactions e.g. for personal accounting. It should include metadata like amounts sent/received, fees, addresses/hashes, description where available, etc.

### Describe the solution

An export function could be added to download transaction history to CSV. An example for comparison is Wallet of Satoshi which exports a CSV like this
```
utcDate,type,currency,amount,fees,address,description,pointOfSale
2023-01-01T12:00:00.000Z,CREDIT,LIGHTNING,0.00000420,0,lnbc1abc123,"Thanks, sats received! Note: Sats for xyz",false
2023-01-01T13:00:00.000Z,DEBIT,LIGHTNING,0.00000069,0,lnbc1def456,"Sent zap!",false
2023-01-01T14:00:00.000Z,CREDIT,LIGHTNING,0.00000069,0,lnbc1ghi789,"{""nostr_key"":""nostr_value"",...}",false
```

### Additional context

Overlaps with #1527 but with a very limited scope.

### Are you working on this?

None

**Comment by reneaaron** [comment]
For your Alby account there is an CSV export over here: 

https://csv.albylabs.com

However, we don't have that for the extension yet. Does that help?

**Comment by badonyx** [comment]
This looks like an elaborate scam. I've never seen this `albylabs.com` domain before.

**Comment by reneaaron** [comment]
It's not. We have several (experimental) apps running on this domain: 
 - pos.albylabs.com
 - csv.albylabs.com
 - zapplanner.albylabs.com

You can see the code over here: 

https://github.com/getAlby/csv-export

Also, the app just requests reading your transaction history and will not be able to spend any funds. 

![image](https://github.com/getAlby/lightning-browser-extension/assets/100827540/2c9c7164-94f7-4142-8694-344abfa0af36)
