### ISSUE TITLE
[Feature] Support Mutinynet

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#3123]
### Feature description

Trying to pay a mutinynet invoice fails due to unable to parse the invoice

### Describe the solution

Support parsing and paying Mutinynet invoices

### Additional context

Voltage will support Mutinynet and allow developers to use it for free in a few weeks

### Are you working on this?

No

**Comment by thebrandonlucas** [comment]
I've started working on a PR that supports this (and signet in general) but could use some help from people more familiar with the codebase: https://github.com/getAlby/lightning-browser-extension/pull/3128
