### ISSUE TITLE
unable to receive keysend payments on my getAlby extension wallet

### ISSUE THREAD

**Issue by Jared-Dahlke** [getAlby/lightning-browser-extension#3131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a getAlby wallet. I connect to it using nwc in my app. I read the pub key off it: "03708f209ace8ab645923a8d4280cc7cf4305282dcffc96b677bd2656a9da945". 
Then I connect a different wallet and try to send a keysend to it using that pubkey.
I receive "Error: invalid destination pubkey (Request failed with status code 400)" error

Is my getAlby extension wallet not able to receive via keysend?

### Steps To Reproduce

 try to send sendkey to my getAlby wallet  public key: "03708f209ace8ab645923a8d4280cc7cf4305282dcffc96b677bd2656a9da945". 

Receive "Error: invalid destination pubkey (Request failed with status code 400)" error

### Expected behavior

able to send sendkey

### Alby information

chrome extension. latest

### Device information

macos macbook pro

### Are you working on this?

None

**Comment by rolznz** [comment]
Hi @Jared-Dahlke 

How do you get this pubkey?

Please note most Alby accounts currently use a shared node (https://ln.getalby.com/) and therefore to send a keysend message you also need the user's custom key and value to send to the correct Alby user. These can be retrieved from the user's lightning address. You can use https://guides.getalby.com/developer-guide/v/alby-wallet-api/lightning-address-details-proxy or https://github.com/getAlby/js-sdk to get this info.

**Comment by Jared-Dahlke** [comment]
thank you @rolznz. This was def a noob question. Once I realized i could just use LN Address I prefer to use that over keysend.

Thanks for the response.
