### ISSUE TITLE
Redesign add new account screen

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#315]
* work with wallet/node logos?

<img width="1084" alt="CleanShot 2021-10-23 at 16 46 34@2x" src="https://user-images.githubusercontent.com/318/138561166-bcd0992e-8981-42a4-880b-175462e10451.png">

**Comment by secondl1ght** [comment]
I can add the logos to this screen if this is needed?

**Comment by secondl1ght** [comment]
Created PR #349 for this
