### ISSUE TITLE
when using my own instance on lnme tip page/lightning address server alby web ln does not work.

### ISSUE THREAD

**Issue by Funman2** [getAlby/lightning-browser-extension#3151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when opening  https://lnme.alex71btc.com/ the web ln by alby extension does not get triggered , whereas ZBD app extension works and can open the invoice and pay, with Alby nothing happens.

### Steps To Reproduce

open https://lnme.alex71btc.com/ attempt a payment.

### Expected behavior

alby should create an invoice.

### Alby information

linux browser firefox extension

### Are you working on this?

None

**Comment by reneaaron** [comment]
Thanks for reporting! :raised_hands: 

There is a bug in the upstream code you seem to be using. The provider first needs to be enabled before executing sendPayment according to the WebLN spec: 

![image](https://github.com/getAlby/lightning-browser-extension/assets/100827540/a3308bd1-18b4-4f08-a39e-291ef6988a6c)

I've prepared an upstream fix here: 
https://github.com/bumi/lnme/pull/60
