### ISSUE TITLE
Stylized scrollbar [minor fix]

### ISSUE THREAD

**Issue by itstomekk** [getAlby/lightning-browser-extension#3200]
### Feature description

When i see the scrollbar on our extension it makes you feel it's a bit old or not properly sized.

![image](https://github.com/user-attachments/assets/533576db-9a96-4235-847a-515898d557e9)

### Describe the solution

Can we gat something in style, like:

![image](https://github.com/user-attachments/assets/1f1288b0-0679-4785-9d00-24e553d20182)

### Are you working on this?

None

**Comment by Tripathiaman2511** [comment]
Is it open for contribution?

**Comment by pavanjoshi914** [comment]
we hide scrollbar for now. there will be no scrollbars shown in popup's
