### ISSUE TITLE
Connect wallet screen could be higher placed

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#3204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Connect wallet screen could be higher placed or relatively higher for bigger screensizes. 

### Screenshots [optional]

![chrome_F4O73DnZww](https://github.com/user-attachments/assets/9a8f7f79-95d5-49e2-9b9d-f736c6923d1e)

### Steps To Reproduce

Navigate to the connect new wallet screen

### Expected behavior

Closer to the top menu bar

### Alby information

latest Alby release on a 26 inch screen

### Are you working on this?

None

**Comment by reneaaron** [comment]
@pavanjoshi914 They should always be vertically centered on the screen. (that's what I see on the latest version, I can't seem to reproduce this behavior)

@MoritzKa Which browser are you using? Can you share a full-screen screenshot covering the whole screen? (so we can see the resolution)

**Comment by MoritzKa** [comment]
it is vertically centered. I was just surprised that there was such a distance between the menu bar and the graphic. 
![chrome_Aip7LO2jVz](https://github.com/user-attachments/assets/37891fda-d561-4c5c-a320-93b06a953e2a)

**Comment by pavanjoshi914** [comment]
I will close this. as i don't think we will be doing any changes here.
