### ISSUE TITLE
[BUG] Keysend no longer works

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#3216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Keysend to a node ID shows an error

### Screenshots [optional]

![image](https://github.com/user-attachments/assets/1aae6870-b82f-4a15-ba61-1fb0472b61a9)

### Steps To Reproduce

1. Go to wallet -> send
2. Enter a node ID

### Expected behavior

Keysend is sent successfully

### Alby information

Latest

### Device information

Windows, Chrome

### Are you working on this?

None

**Comment by pavanjoshi914** [comment]
fixed in #3218
