### ISSUE TITLE
[BUG] German translations are wrong

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#3234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![chrome_n1O7PFN7HR](https://github.com/user-attachments/assets/6dc8edb0-191e-4c81-b103-2d485eba8992)
![chrome_0ymqcdpoIU](https://github.com/user-attachments/assets/bf1c968b-6c0b-45e7-ae66-ca8e24744ab4)

### Steps To Reproduce

Select German as language in the extension

### Expected behavior

correct translation

### Alby information

most recent version. 

### Are you working on this?

None

**Comment by bumi** [comment]
the whole sentence is strange. can you edit it in weblate?
