### ISSUE TITLE
Add Alby logo to the extension window

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#329]
As as user I would like to see the awesome Alby bee when I use the extension.

The picture is only a suggestion. I am not sure yet where to place the display of the wallet amount

![2021-10-25_21h01_50](https://user-images.githubusercontent.com/13707997/138756512-68dd016d-a4c4-4bbc-93ec-94ea869c172a.png)
.

**Comment by Plvtinum-1** [comment]
Okay, I'll search for something there, thanks

**Comment by secondl1ght** [comment]
Is this something we still want to do?

**Comment by bumi** [comment]
I think we should first really think about some design concept before we do this.

**Comment by escapedcat** [comment]
@dvoroneca can this be closed?
