### ISSUE TITLE
LNURL response notification is not shown in chrome

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#342]
In Firefox the LNURL response message (e.g. thanks for the payment) is shown as notification.
In chrome I only see the payment success notification with the pre-image. 

Maybe this is a bug, maybe this is only how my chrome notifications are configured?

**Comment by bumi** [comment]
maybe we simply do a `setTimeout` and wait 500ms ? :)

**Comment by MoritzKa** [comment]
There also doesn't seem to be a notification after tipping on Firefox. 
For Chrome I did not encounter this issue described above.

**Comment by dylancom** [comment]
I tried to work with a timeout but that will make the first notification disappear directly when the new one appears (they don't stack). I guess the best solution is to show successAction message within the screen and not closing the window.
