### ISSUE TITLE
Tipping a LN address on twitter

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#353]
I am using Google Chrome browser. I could tip Twitter profiles with an address like this ⚡moritz@getalby.com in the profile. 
Now I cannot send tips anymore. I restarted Chrome already. Alby detects Twitter (orange icon; Twitter logo in the extension screen), but it does not show the tipping screen anymore (it sometimes shows the tipping screen for a millisecond). 

![image](https://user-images.githubusercontent.com/13707997/140185247-d2a2c8ed-e400-4483-84cc-1f9c8a2534c6.png)

**Comment by bumi** [comment]
how does the Alby popup look like? 
and can you test the build from this branch: https://github.com/getAlby/lightning-browser-extension/pull/354
