### ISSUE TITLE
Show account loading skeleton while switching accounts

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#356]
We show a loading skeleton when we initially load the account information. 
Switching accounts can take a bit and while the information is loaded we should show the skeleton again to give the user some feedback.

**Comment by secondl1ght** [comment]
I think I know how to do the HTML/CSS for this and I have an idea about the JS/React but i'm not sure. Maybe you could show me how you would implement this sometime?

**Comment by johnsBeharry** [comment]
Are there any other areas in the application that may be impacted by this latency? For instance the list of publishers, or their details?
