### ISSUE TITLE
Scrollbars on prompt window

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#362]
Using Google Chrome I have scroll bars on the prompt window. I think it would look nice if we remove them 
![image](https://user-images.githubusercontent.com/13707997/140643356-79460f94-9f7d-4753-9b81-f8670beb8633.png)

Maybe we can make the window even responsive. e.g. the yellow bar does not go over the whole window size.
![image](https://user-images.githubusercontent.com/13707997/140643392-32482cb3-f670-4f6f-afb6-787949fb8427.png)

**Comment by bumi** [comment]
@dylancom do you have an idea here? I would not make it responsive for now but maybe we fix the width of the window?

**Comment by dylancom** [comment]
@bumi I remove the fixed width from the template, which makes it responsive. Besides that I increased the height from 580 to 600 (upon window creation). If we also don't want scrollbars while setting a budget, we should increase the height even more. (This will result in more bottom white space though...)
