### ISSUE TITLE
Fixed popup height

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#374]
Currently the popup has no fixed height and some things from the menu can run below the fold and are not visible. 
I think we could have a fixed height OR this problem solves itself when we have a nicer designed blank screen (when there are no transactions visible)

<img width="421" alt="image" src="https://user-images.githubusercontent.com/318/141477587-d92d6813-b5b7-4e8c-8421-a4c07b226b20.png">

**Comment by dylancom** [comment]
I'm for the problem fixing itself as I'm sure the nicer designed blank screen will require more height.
