### ISSUE TITLE
Check if the setup of a new account by an user is finished properly, and provide a way to go through the onboarding again.

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#375]
It might happen that a user does not or cannot finish the account setup properly (= a password is set). 
Then the user still should have the chance to set up an account
- Alby checks if account setup is finished and opens a new onboarding screen if it was not
- provide a link on the password screen of the pop up window: "set up your account" that opens the onboarding screen

**Comment by bumi** [comment]
@secondl1ght do you want to look into that? I think also it is a good one to see some of the inner details of the extension.

**Comment by bumi** [comment]
related: https://github.com/getAlby/lightning-browser-extension/issues/180

**Comment by bumi** [comment]
actually I think we already open the welcome page if Alby is not fully configured: https://github.com/getAlby/lightning-browser-extension/blob/00c03bf895a295b90813de1b68d73f05959ea4f0/src/app/context/AuthContext.tsx#L31-L42

@MoritzKa can you elaborate what is missing?

**Comment by bumi** [comment]
can you review this? is this still a problem?

**Comment by MoritzKa** [comment]
I have not encountered that issue again. 
I will close it.
