### ISSUE TITLE
Remove "User canceled" notification

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#377]
If I as a user cancel a prompt, an alert pops up (see below). Does a user really need to see this notification? 

Chrome:
![image](https://user-images.githubusercontent.com/13707997/141507974-b43465cb-a0c0-4a1e-8d44-1f179cc34a20.png)

Firefox:
![image](https://user-images.githubusercontent.com/13707997/141508108-4502752d-4dc9-4509-9cb5-18847e5893d1.png)

What do you think?

**Comment by bumi** [comment]
this is this alert: https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/inpage-script/index.js#L70
