### ISSUE TITLE
Problems with the extension in Librewolf

### ISSUE THREAD

**Issue by altoidkind** [getAlby/lightning-browser-extension#378]
I am experiencing some problems with the Alby Wallet in the Librewolf browser, there are errors when working with payments.

When I try to create an invoice, I get a error: `can't access property "length", this.data is undefined`:

![Screenshot_4](https://user-images.githubusercontent.com/90278419/141507384-758ce890-0d0c-4270-a7c0-330840b2c803.png)

When I try to pay a payment invoice, I get an error: `Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`:

![Screenshot_6](https://user-images.githubusercontent.com/90278419/141508376-02ff14f8-f164-44d9-91cb-012296dbe42f.png)

The same problems are completely absent in Chrome on my device

**Comment by bumi** [comment]
thanks for reporting this! 
what connection (LND, Bluewallet, etc.) do you use? 
who are you trying to pay? could also be that it is an invalid LNURL server response. we do not validate those responses very will so far.

**Comment by altoidkind** [comment]
I use LNBits to connect to a wallet. I tried to pay several invoices created in SimpleBitcoinWallet, BlueWallet and another LNBits account, but there is an error everywhere.

**Comment by bumi** [comment]
OK, I think I was able to debug this, sorry for the delay. 

What Lnbits host do you use? Are you running your own LNbits or do you use the public one? They changed the domain and this is a problem for the API (the responses are no longer the same using the old domain). 
I think the new domain is: https://legend.lnbits.com

can this be the reason?

**Comment by altoidkind** [comment]
I use public lnbits with the domain legend.lnbits.com, I think this can't be the reason

**Comment by bumi** [comment]
We have a new release out. Can you check it with that version again. 
The new version includes some lnbits API updates.

**Comment by altoidkind** [comment]
The problems remain

**Comment by bumi** [comment]
ok, thanks for the report. sadly I can not reproduce it... :( 
Could it be that you used the INVOICE/READ key not the ADMIN key to connect Alby? The admin key is needed to be able to send payments. Sadly LNBits seems to not return a proper error but just fails when a wrong key is used, so we do not get a proper error message there.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/318/144969331-103b52df-d308-4e21-badd-694c0d97fd52.png">

**Comment by altoidkind** [comment]
Yes, this method really works and the errors disappear in this case

**Comment by bumi** [comment]
oh nice. great. thanks.
