### ISSUE TITLE
Should we match 'Websites' and 'Allowances' naming

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#381]
Currently there is the 'Websites' button on the NavBar and on the dropdown menu there is 'Allowances'. Both buttons take you to the same page so I think they should be named the same. Do people agree with this?

**Comment by bumi** [comment]
@johnsBeharry is this part of some copy writing brainstorming? :)

@MoritzKa ack for using "Websites" there, too?

**Comment by MoritzKa** [comment]
I slightly prefer the "Allowances" in the nav bar more. For me as a user "websites" could be anything. And the main use case for clicking on it (in the pop up) would be to change or check my existing allowances. 
On the other side a user doesn't have an allowance for every website. Also, if I am on the Alby fullscreen then the use case might be different. I would rather like to have an overview of websites that I visited. Therefore "websites" would fit better. 
Maybe in the future we have two pages: active allowances and just websites (or a filter).

**Comment by secondl1ght** [comment]
These are good points @MoritzKa, I thought it would be easy to pick one or the other but you make a good case for both here haha.

Could even use something like 'Connections' or 'Permissions' as well...but I do think Websites is the most obvious for now.

**Comment by secondl1ght** [comment]
PR #397 if we agree on the naming for this.

**Comment by secondl1ght** [comment]
Closed with #397
