### ISSUE TITLE
Show "receive transactions" in the transaction list of the popup and the "website" menu

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#389]
Currently Alby does not show WebLN receive transactions in the transaction lists (of the pop up and the "⚡️ Websites")

We only show sending transactions made from Alby because of the metadata that we add.

To be considered here:
- ~show an entry when a website requests an invoice (same as when the website sends a payment) (webln.makeInvoice vs. webln.sendPayment)~
- ~sync the data with the transactions from the node (did we actually receive the payment?)~
- get (latest n) incoming transactions from the node via API call

**Comment by bumi** [comment]
I think somehow this should be the full audit system that logs every action a user made on Alby.

**Comment by MoritzKa** [comment]
confirmed.

**Comment by dvoroneca** [comment]
Hi Guys, here is my take on how the transactions list, including the incoming transactions. 
Feel free to leave comments in [figma](https://www.figma.com/file/kdkEo1fpGvaiMifkfZQQjN/Recent-Transactions?node-id=0%3A1). 

There are versions that need feedback. 

1. Updated open transaction view V1 and V2.
2. Incoming, Outgoing, and Invoice expended views.

**Comment by MoritzKa** [comment]
According to #https://github.com/getAlby/meta/issues/15

tasks:
- API call to get incoming transactions
- design tab for incoming transaction

**Comment by dvoroneca** [comment]
As an outcome of the refinement meeting, here are the mockups for the tabs in the recent transactions lists on the "Transactions list" and transaction history on the "Contextual Screen"

![transactions](https://user-images.githubusercontent.com/35034985/174791888-e552b97c-fd95-4133-a2aa-0fb6a21a079e.png)

-----------

## Transaction History:

![List-1](https://user-images.githubusercontent.com/35034985/174792207-94466786-cace-46c5-87f0-bd113a9cf1e3.png)
![List](https://user-images.githubusercontent.com/35034985/174792215-6a65d213-5ca7-43b8-b0d5-2d574195ffde.png)

-------------------

## Opened view:
![open V3](https://user-images.githubusercontent.com/35034985/174792307-34c34b1a-a02f-4ab9-92bf-2febaef68956.png)

-------------------

## Contextual Screen:
![Extension Recent Transactions-1](https://user-images.githubusercontent.com/35034985/174792408-fbf85110-6474-4f20-a733-86fbbc970f46.png)
![Extension Recent Transactions](https://user-images.githubusercontent.com/35034985/174792416-73c40071-781d-422e-a5fe-0e3cf360beb4.png)

------------------

## [Figma link](https://www.figma.com/file/kdkEo1fpGvaiMifkfZQQjN/Recent-Transactions?node-id=248%3A2910)
