### ISSUE TITLE
Firefox/LNBits: creating an invoice results in an error: Amount must be of number type

### ISSUE THREAD

**Issue by cryptoteun** [getAlby/lightning-browser-extension#390]
When creating a new invoice (Receive) I get the following error:
<img width="570" alt="Screenshot 2021-11-17 at 20 05 20" src="https://user-images.githubusercontent.com/73664763/142266219-93438915-cfd3-4e40-b4d6-662658572fdd.png">

I use:

- Firefox addon via the Extensions (no clue of the version)
- LNBits as funding source
- Data: 
  - Description: Test
  - Amount: 10

**Comment by bumi** [comment]
hmm, interesting. thanks for reporting. What LNBits instance are you using?

**Comment by cryptoteun** [comment]
You mean like, the funding source? It's LND. Or do you mean version?
