### ISSUE TITLE
Add ability to delete account

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#404]
I think it would be useful to be able to delete an account after you have added it. Also I think it would be useful to be able to name your account anything you'd like. Currently if you have 2 LNDHub accounts there is no way to tell the difference, they are both displayed in the dropdown as 'LNDHub'. So you could name one 'Home node' and another one 'Alby custodial' or something like this. Just thought i'd make an issue to see if other people think this is a good feature.

**Comment by bumi** [comment]
👍 ❗️
related: #80 

we need a full page to list, edit and delete accounts in the options page.

**Comment by secondl1ght** [comment]
Sounds good! If we get a design done up I could give the front-end coding a try.

**Comment by raucao** [comment]
Naming accounts would be very useful indeed!

![Screenshot from 2022-01-11 07-24-54](https://user-images.githubusercontent.com/842/148952306-1b6d6723-4c99-455b-9751-ff1708b8c6a6.png)

**Comment by MoritzKa** [comment]
One observation: The balance shows the name of my LND-Raspiblitz but the account list does not. The account list only shows LND (nativelnd)

**Comment by escapedcat** [comment]
> One observation: The balance shows the name of my LND-Raspiblitz but the account list does not. The account list only shows LND (nativelnd)

Should this be actionable? Is this a new issue?

**Status of this issue (correct if wrong):**
- [x] delete account
- [ ] rename account

**Comment by bumi** [comment]
yes I think splitting up this issue with more details for each is a good idea.

**Comment by escapedcat** [comment]
This can be renamed to "Add ability to delete account" and closed

**Comment by secondl1ght** [comment]
Ok which PR closed this issue?

**Comment by escapedcat** [comment]
> Ok which PR closed this issue?

Looks like functionality was added/touched here: https://github.com/getAlby/lightning-browser-extension/pull/626/files#diff-ecfb4b028d45afcf61dba185fe5ab45d0d24e443fb91d6da02840986834f5e4aR97-R99  

Is that correct?

**Comment by dylancom** [comment]
> > Ok which PR closed this issue?
> 
> 
> 
> Looks like functionality was added/touched here: https://github.com/getAlby/lightning-browser-extension/pull/626/files#diff-ecfb4b028d45afcf61dba185fe5ab45d0d24e443fb91d6da02840986834f5e4aR97-R99  
> 
> 
> 
> Is that correct?

#599 added it.

**Comment by secondl1ght** [comment]
Awesome nice work!

**Comment by dylancom** [comment]
Thanks!
