### ISSUE TITLE
Show wallet balance of a user

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#408]
Lightning web apps (e.g. trading) want to be able to show the user's wallet balance to the user in the Lightning web app. This information improves the user experience, as users don't have to go back to check their wallet but can stay within the Lightning app. 

Can we extend WebLN to request the wallet balance?

**Comment by bumi** [comment]
this should go here: https://github.com/joule-labs/webln/issues/39

**Comment by reneaaron** [comment]
Fixed for now with #2242
