### ISSUE TITLE
Run getalby.com accounting system (LNDHub) for custodial accounts)

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#409]
We are currently using BlueWallets LNDhub to provide a wallet to new Alby users. 

Users report occasionally LNDHub shows 503: Connection Error

How can we improve the Alby wallet by providing a reliable service.

**Comment by bumi** [comment]
I have no idea what causes that problem. 
I have setup our own LNDHub instance but we still need some better node management there to use it.
