### ISSUE TITLE
Live update of wallet balance after transactions

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#410]
After creating an invoice, received amount is shown only after closing and opening the extension. 
Users expect to see the new wallet balance immediately. Otherwise they wonder if they actually received the amount. 

Can we update the balance of the wallet ("top left" in the pop up window) without reopening the extension. 
E.g. if automated updates are tricky we could work with a refresh button next to the balance. (just an idea)

**Comment by bumi** [comment]
related: https://github.com/getAlby/lightning-browser-extension/issues/289

**Comment by bumi** [comment]
we do this now. can you test it and confirm?

**Comment by MoritzKa** [comment]
yes. confirmed. Will close it.
