### ISSUE TITLE
Hide blank preimages 

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#411]
![image](https://user-images.githubusercontent.com/13707997/143032722-9ea6be47-3ab9-4434-800c-97ddce1d277f.png)

**Comment by MoritzKa** [comment]
is this a bug or not possible to show due to the payment recipient?

**Comment by bumi** [comment]
what connector was used there? 
I think the lnbits API currently does not return a preimage. (they have to fix that) 

but we should remove the `Preimage:` if we do not have one.

**Comment by MoritzKa** [comment]
Alby was linked to BlueWallet i.e. LNDHub
