### ISSUE TITLE
Payment errors when LNBits is the funding source

### ISSUE THREAD

**Issue by supertestnet** [getAlby/lightning-browser-extension#431]
When I try to pay an invoice with an lnbits account as my funding source I get two error messages:

![Screenshot 2021-11-29 11 59 54 AM](https://user-images.githubusercontent.com/58400631/143919336-c4c36040-0544-44e2-9ef7-adcbe9a9b4e4.png)
![Screenshot 2021-11-29 11 59 45 AM](https://user-images.githubusercontent.com/58400631/143919347-578b0577-a81a-4c09-b241-4d3f7f71f53f.png)
![Screenshot 2021-11-29 12 00 07 PM](https://user-images.githubusercontent.com/58400631/143919355-bff61382-bcbc-419f-bf64-a329944f4b6b.png)

I believe alby expects json and receives either an html file or an xml from lnbits. Perhaps it is doing the api call incorrectly.

**Comment by bumi** [comment]
thanks a lot for reporting this! 
Which LNBits version are you running? is it the public instance or your own? 

I think there have been some changes in LNBits for which we got some updates in the next release. 
Do you feel comfortable with running Alby from master and helping to debug this?

**Comment by bumi** [comment]
Could it be that you used the INVOICE/READ key not the ADMIN key to connect Alby? The admin key is needed to be able to send payments. Sadly LNBits seems to not return a proper error but just fails when a wrong key is used, so we do not get a proper error message there.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/318/144969331-103b52df-d308-4e21-badd-694c0d97fd52.png">

**Comment by supertestnet** [comment]
> Could it be that you used the INVOICE/READ key not the ADMIN key to connect Alby?

Yes that's probably it. Sorry for the false alarm.

**Comment by bumi** [comment]
goood. thanks! sorry that it took a while to figure this out. have to think how we better can catch that error.
