### ISSUE TITLE
Add feedback forms to Alby

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#432]
Add a submission form to Alby to collect feature requests and bugs.

**Comment by MoritzKa** [comment]
I registered an Alby account for the "Fly High" tier from https://hellonext.co/

**Comment by bumi** [comment]
hellonext looks good! and with that plan we can run it on our domain, nice!
and does also support posting without signup?

**Comment by MoritzKa** [comment]
Yes I made an email optional
![image](https://user-images.githubusercontent.com/13707997/144011678-a73d2f41-eddc-4324-a73c-993fc7ff6694.png)

**Comment by secondl1ght** [comment]
Is this something we would want to have a design done first, or could we just start coding this?

**Comment by MoritzKa** [comment]
Hellonext requires users to leave an email for posting and voting. That would be acceptable as users still can remain anonymous. But commenting requires login. 
With these requirements I only found https://getalby.noorahq.com/ . Roadmap and Changelog are currently switched on but can be disabled if we want. The account includes custom domain & SSL and no limitations in terms of members, boards and contacts. What do you think?
@secondl1ght I prepared some ideas how we can add it to Alby. We can discuss them together and start coding :D

**Comment by secondl1ght** [comment]
I think https://getalby.noorahq.com/ looks good and pretty easy to use, maybe we wouldn't need a feedback form in Alby but just a button that takes you to this form?

**Comment by secondl1ght** [comment]
Linked PR #450
