### ISSUE TITLE
Change "are you sure you want to delete this publisher?"

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#441]
In Alby I can remove websites that I "connected" to. When I remove a website I see a prompt "are you sure you want to delete this publisher?". let's change it to "Are you sure you want to delete this website?" So that it is in line with the "Website" section.

**Comment by secondl1ght** [comment]
PR submitted #443

**Comment by secondl1ght** [comment]
PR merged will close now
