### ISSUE TITLE
Review text/explanation of what people have to enter to connect wallets

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#451]
we have to do a better job to explain exactly what people have to enter to connect a node and where they find that information.

**Comment by gabbyprecious** [comment]
Hello @bumi can I work on this?

**Comment by escapedcat** [comment]
If there's no linked PR, no assignee and no other comment here I would assume nobody is working on it.  
Maybe start with a draft-PR if you want to tackle this.

**Comment by bumi** [comment]
sure, though this is not a good/specific issue. if you have good ideas, then PRs are for sure welcome!

**Comment by gabbyprecious** [comment]
Hi @bumi, You're referring to subsection here right? I have an idea on making developers know how to set up or get these details and what they mean, either by providing it on a screen or doing both, would like to confirm if that is the idea and get started
<img width="1157" alt="Screenshot 2022-03-12 at 12 43 17" src="https://user-images.githubusercontent.com/47405251/158016651-a400700b-1866-42aa-bb45-2a466a360e1b.png">

**Comment by bumi** [comment]
I think with the new connectors we already have made good progress on this.
