### ISSUE TITLE
Add a list of places using Alby to the read me/website.

### ISSUE THREAD

**Issue by frazras** [getAlby/lightning-browser-extension#456]
Just installed Alby a minute ago, I've been hearing about it since Adopting Bitcoin conference.
However, I installed it and want to play around with it but I don't know what sites currently use it if any at all.

Are there any projects/websites supporting Alby and can we make a list?

**Comment by bumi** [comment]
YES! this is so much needed. and there are still not many websites implementing webln. 
We want to have a whole directory that we can show to the user after installation. Which should also be an inspiration for other makers.
@johnsBeharry do you maybe have a link on where to see the status of that? and maybe we should just start collecting some great sites here? (what do you think @MoritzKa?)

**Comment by MoritzKa** [comment]
We can start with this list and adjust it with new submissions from the community:
**Shopping:**
https://www.bitrefill.com/

**Trading:**
https://kollider.xyz/
https://loft.trade/
https://lnmarkets.com/

**Social**
https://stacker.news/

**Gaming:**
https://www.lnblackjack.com/
https://lightning-poker.com/
https://lightning-roulette.com/
https://lngames.net/

**Miscellaneous**
https://lightningnetworkstores.com/
https://lnshort.it
https://kriptode.com/satsforlikes/index.html
https://sparkshot.io/

**Comment by dylancom** [comment]
I recently got this list:

**Games**
⚡ https://bc.game/
⚡ https://mintgox.com/
⚡ https://lightnite.io/
⚡ https://thndr.games/games
⚡ https://satoshis.games/
⚡ https://lngames.net/
⚡ https://microbet.fun/
⚡ https://launcher.elixir.app/
⚡ https://rollercoin.com/
⚡ https://zebedee.itch.io/bitcoin-rally
⚡ https://www.hangarsixgaming.com/
⚡ https://escapeqr.com/
⚡ https://lightning-roulette.com/
⚡ https://lightningpuzzle.com/
⚡ https://lightning-poker.com

**Comment by secondl1ght** [comment]
What's the status of this issue, anything needed to be done or helped with?

**Comment by Kodylow** [comment]
I think a really nice solution to this might be to split the "websites" page into 2: "My Websites" and "Other Websites supporting Lightning"

1. My Websites: Keep it exactly as is, a list of sites you've set up allowances for
2. Other Websites Supporting Lightning: A bunch of small cards with sites that work well with alby: clicking through the card might bring me to the website and prompt me to open a small allowance for them, and once I open the allowance the card would move from "Other Sites" to "My Websites"


![image](https://user-images.githubusercontent.com/74332828/152358887-e47361bf-5ec4-46e0-be10-65d898d2ec53.png)

**Comment by bumi** [comment]
we got this in now, and will also extend this in the future.
