### ISSUE TITLE
Notification text confusing when sending to another wallet

### ISSUE THREAD

**Issue by RicardoCapricciosa** [getAlby/lightning-browser-extension#473]
As described and shown in a screenshot here:
https://github.com/getAlby/lightning-browser-extension/pull/465#issuecomment-995118018

reproduce:

1. send some funds FROM Alby to some non-Alby wallet
2. notice the notification (tested with Firefox), it says "Sent 500 sats to Alby", but the 500 sats weren't sent TO Alby, but sent FROM Alby to somewhere else ![image](https://user-images.githubusercontent.com/11453387/146690252-925fec69-1a6d-4f14-84d7-dfaa52103fa1.png)

**Comment by bumi** [comment]
I think this is (party?) solved - at least for lightning addresses.

**Comment by bumi** [comment]
closing this. this is partly solved and we have some other related issues that are currently worked on

**Comment by escapedcat** [comment]
Related to #770
