### ISSUE TITLE
Alby state should be stored between closing and opening Alby

### ISSUE THREAD

**Issue by RicardoCapricciosa** [getAlby/lightning-browser-extension#474]
The state of the Alby pop-up is not saved when it is closed for some reason. Which might lead to confusion. Here'e an example.

reproduce:

1. Open Alby click on **Receive** and enter some amount and description
2. Click **create invoice**, the invoice is displayed
3. Now switch the browser tab ore to another window, etc., i.e. to open another wallet in order to pay the invoice

When going back to Alby the invoice is gone, if you did not copy it immediatley you have to create a new one.

Imo this is not a good solution because everytime I do anything in alby I have to finish it otherwise it'll be gone as soon as I click somewhere else.

**Comment by reneaaron** [comment]
There is no easy way to achieve this behavior other than storing the state of the application in some storage and restoring application state from there (which is a very hard thing to do and has a lot of potential side effects, e.g. having two windows opened at the same time, etc). 

If you need to switch contexts when doing tasks I suggest you open Alby in a separate window than using the extension popup (you can just click on the "wallet" button in the dropdown menu top open Alby in a new tab): 

![image](https://github.com/getAlby/lightning-browser-extension/assets/100827540/83012572-4879-4896-894b-5dc764d61fd1)

Closing as I don't see us implementing this over the next months.
