### ISSUE TITLE
Bug: New onboarding screen top nav is not working

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#479]
The 'Welcome', 'Your Password' etc. top navbar does not seem to be working on the latest master branch. As you can see in the screenshot below, I am on the 'Connect To Lightning' page but the top navbar still displays the 'Welcome' tab.

![image](https://user-images.githubusercontent.com/85003930/147194471-e9e7089a-ecf9-42a3-8872-ff9a4d287b07.png)

**Comment by dylancom** [comment]
Thanks for reporting this!
