### ISSUE TITLE
Better error handling for LNURL pay responses

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#489]
Currently we do not verify the responses for the LNURL pay flow and we do not handle invalid responses (e.g. when the server is down or responds with some error).
We should fix this and show a proper error message to the user.

ToDo: here we get the lnurl details: https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/LNURLPay.tsx#L73

we should check the response for an `error` (`{"status": "ERROR", "reason": "error details..."}`) 
as described in the LNURL specs, e.g.: https://github.com/fiatjaf/lnurl-rfc/blob/luds/06.md

**Comment by hsjoberg** [comment]
Indeed, LNURL-pay servers may return an error telling them what's wrong.
For example on my https://chat.blixtwallet.com site, it will inform the user if they did not provide a chat message:

![image](https://user-images.githubusercontent.com/3824379/152078573-b3d2d749-c9e9-4264-83d5-af565518108e.png)

**Comment by im-adithya** [comment]
Isn't this solved in #852? The above error is now shown in a toast with the reason:
![Screenshot from 2022-06-08 11-15-06](https://user-images.githubusercontent.com/64399555/172540870-f9f1c58f-2036-41e7-8a47-9b95c90bb62e.png)

**Comment by bumi** [comment]
I think that is good enough: 
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/LNURLPay.tsx#L144-L152
