### ISSUE TITLE
Update to Tailwind 3

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#491]
There has been a major release of Tailwind. 
We need to update to the latest version - see the [upgrade guide](https://tailwindcss.com/docs/upgrade-guide)

depfu PR: https://github.com/getAlby/lightning-browser-extension/pull/484

**Comment by bumi** [comment]
@secondl1ght do you want to look into that?

**Comment by secondl1ght** [comment]
Sure I can do this

**Comment by secondl1ght** [comment]
Ok this is complete, I tested it out locally and from first test it looks like everything is still working as before. I went through the entire upgrade guide to make sure we are all good, I'll be putting in a PR for this with the details!
