### ISSUE TITLE
Allow connectors to cache responses

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#492]
Currently we always do a "getinfo" call when the popup is opened. This takes some time and results in a loading state on the page. 

We should allow the connector to cache that response and update the information in the background to prevent the loading state and too many requests.

**Comment by bumi** [comment]
@dylancom do you think a memoization library is the way to go here? (e.g. https://www.npmjs.com/package/moize or https://github.com/medikoo/memoizee ?)

**Comment by dylancom** [comment]
@bumi as far as I'm aware when using memoizee, the data is lost upon restarting the popup?
We can use: browser.storage.local

**Comment by bumi** [comment]
the data would be stored on the connector in the background script. so the actual getInfo call would be cached for a short period of time. 
But I think the main problem I had was that I would love to update that cache in the background. 
e.g. respond with cached data but update it in the background - and this was with one of them not easily possible I think?

**Comment by bumi** [comment]
related: https://github.com/getAlby/lightning-browser-extension/issues/333

**Comment by dylancom** [comment]
Proposal in #519

**Comment by dylancom** [comment]
@bumi do we need to keep this issue open for the "amount" of requests?
