### ISSUE TITLE
Add support for LUD-18 email payer data 

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#514]
We introduced [LUD-18](https://github.com/fiatjaf/lnurl-rfc/blob/luds/18.md) support and currently support providing the name.
Similar to the name we should also add support for users to provide an email address.

**Comment by AustinKelsay** [comment]
Hey @bumi I've been working on this today and think I have a solution, is there a good way to test this locally and confirm the username/email payer data is getting passed correctly?

**Comment by AustinKelsay** [comment]
#541

**Comment by bumi** [comment]
Hey @AustinKelsay super cool!! thanks (sorry for the late reply).

I think you can test this using the lnurl playground: https://lnurl.fiatjaf.com/
This should support username/email payerdata.

Let me know if you need help. I will also test this asap!

**Comment by AustinKelsay** [comment]
Hey no problem @bumi I actually found this playground after searching around a bit and everything seems to work as expected with the payer data

**Comment by bumi** [comment]
ah, awesome, that's great to hear. so we should get your PR in soon. :shipit:

**Comment by bumi** [comment]
Yay, this is shipped!
