### ISSUE TITLE
Re-think or replace slider

### ISSUE THREAD

**Issue by kiwiidb** [getAlby/lightning-browser-extension#529]
I don’t find the slider for choosing the amount very useful. It's not a great tool for numerical input and it's wildly inaccurate.
For example, in an LN address payload there is a minimum and a maximum field, but these can differ greatly. If I touch the slider on my own twitter profile even slightly, the amount jumps from 10 sats to >10000 sats immediately, which is not something most people would want. What I would find more useful is some buttons with sane pre-filled amounts.

**Comment by secondl1ght** [comment]
Do we have an idea on what we would like the pre-filled amounts to be for the buttons?

**Comment by secondl1ght** [comment]
Making a note that in the future we want to add click and hold functionality to add the amounts for the buttons, for now we will just have a single click function to set the input.

**Comment by secondl1ght** [comment]
Should I close this now that the PR is merged and open a new issue to add the click and hold function?

**Comment by dylancom** [comment]
Yes, this can be closed. We can add that as a "nice-to-have" or something I think, so we can currently play with this and get some ideas to improve on it.

**Comment by secondl1ght** [comment]
Closed by #539
