### ISSUE TITLE
Feedback for new send sat amount buttons

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#554]
Creating this to get feedback on improvements, if any, for the new sat amount buttons when sending (#539). One suggestion so far is that when you click and hold it should add more sats to the input.

**Comment by secondl1ght** [comment]
https://github.com/getAlby/lightning-browser-extension/pull/539#issuecomment-1021142858

**Comment by bumi** [comment]
I really like the new send sat buttons!
