### ISSUE TITLE
Setup UI tests for the extension

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#556]
We should be able to use Playwright, Puppeteer etc. and also hosted services to test UI flows.
I am opening this issue to collect some links for this. 

https://www.cypress.io/
https://github.com/microsoft/playwright
https://www.lambdatest.com/online-browser-testing
https://www.browserstack.com

### Cypress
+ https://www.cypress.io/
+ https://medium.com/@knoldus/how-to-load-chrome-extension-in-cypress-io-e313d3c68988

### Pupeteer

+ https://pptr.dev/
+ https://puppetry.app/
+ https://github.com/checkly/headless-recorder

### LambdaTest:
Support says they support extensions
"you can test through automation testing by uploading a file to browser> extenstion> unpacked or packed extension"
* https://www.lambdatest.com/support/api-doc/#/extensions/UploadExtensions

**Comment by escapedcat** [comment]
Heard good stuff about playwright. We're mostly (still) cypress and are happy with it.
