### ISSUE TITLE
ConnectNative not available after requesting native_messaging permissions

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#562]
It seems on Chrome the `connectNative` API (used [here](https://github.com/getAlby/lightning-browser-extension/blob/8ee270b2ecca8656bac6296e60fd92d806c22bbb/src/extension/background-script/connectors/Native.ts#L23) is not available after the user has requested the native messaging permission. It only becomes available after a reload. 

The reload can be done with the [runtime.reload()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/reload) call but that closes all extension windows (welcome, options, popup) and thus would throw the user out of the onboarding process. 

This is only the case in Chrome but not in Firefox

**Comment by dylancom** [comment]
https://stackoverflow.com/questions/66925508/optional-permissions-are-not-being-applied-after-being-added

**Comment by bumi** [comment]
`chrome.runtime.reload();` would close the onboarding page.

**Comment by bumi** [comment]
we now require the native messaging permission by default
