### ISSUE TITLE
Dark mode updates

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#569]
Collecting some dark mode todos here
<img width="366" alt="image" src="https://user-images.githubusercontent.com/318/151663275-a1c0a358-8073-454c-8835-8b8524905d9c.png">

**Comment by secondl1ght** [comment]
Fixed with #571, let me know if you find any more!

![image](https://user-images.githubusercontent.com/85003930/151718776-19d1ce5d-4588-4348-bd5e-2e3ecf669bc5.png)

**Comment by escapedcat** [comment]
Fixed according to comment
