### ISSUE TITLE
Detecting the Alby extension on the user

### ISSUE THREAD

**Issue by altoidkind** [getAlby/lightning-browser-extension#570]
I propose to implement a specific module Alby, so that using JavaScript functions it would be possible to check whether this particular purse of the user is installed. **This can be used for faster authorization**. 

The whole scheme should be similar to MetaMask (see. https://ethereum.stackexchange.com/a/51356 or https://stackoverflow.com/a/14399123/16782022).

**Comment by bumi** [comment]
We have optimized this. webln is now faster available and you should be able to check for `if (window.webln)`

The webln guide was also extended and there is now a suggestion on how the check if webln is available: https://www.webln.guide/building-lightning-apps/getting-started

Does this help and solve your problem?
