### ISSUE TITLE
Improve Information Available in Recent Transactions List

### ISSUE THREAD

**Issue by Kodylow** [getAlby/lightning-browser-extension#577]
I would like to be able to see additional information from the paid invoices stored in my recent transactions list. 

Currently each paid invoice is displayed in a collapsed and expanded view.

Collapsed: I see 1. a circle with a minus sign in it (which makes me think I didn't pay the invoice or it failed or something), 2. "Alby" and the amount sent in bold on the top, and 3. "Sent" and time since payment sent

Expanded: I see 1. The preimage of the invoice, and 2. A raw "chrome-extension" link which on clickthrough opens alby's chrome extension as a new tab with the invoice data prompting me to pay the invoice (even if it's already paid) or pay to the LNURL if it's an LNURL.

Thoughts:
1. The white circle with the minus sign in it makes me think that I didn't pay the invoice, and when I click on the invoice it pops up as a standard invoice screen allowing me to pay it again. This is confusing: If the bolt11 invoice is in the recent transactions list it has already been paid, so clicking through it should give me additional information about the invoice like description, recipient, maybe some of the routing info, not prompting to pay it again.
2. In the expanded view I see a raw link and the preimage. I can't think of a situation where the preimage would be all that useful to see without the larger context of the rest of the invoice, so I think that should be swapped out with the invoice's description section. Clicking through the link should bring me to a page with additional information about the invoice (because it's already been paid) instead of to a page prompting me to try paying the invoice again.

![image](https://user-images.githubusercontent.com/74332828/152355501-748cec24-0a31-4538-9e7a-cafc3ea55796.png)

**Comment by bitcoinuser** [comment]
I think the transaction list was improved a lot since this issue was opened. Maybe this issue can be closed? Thanks.

**Comment by reneaaron** [comment]
@bitcoinuser Thanks, yeah I think those things have drastically improved with the recent releases and Kody's points have been addressed.
