### ISSUE TITLE
Flexing LNURL Picture to inline

### ISSUE THREAD

**Issue by Kodylow** [getAlby/lightning-browser-extension#580]
I think the giant LNURL picture is unnecessary, and it makes the view longer than the default extension size so you have to scroll down to pay. I'd like to move the picture to inline with the "Send payment to" and "Description" section (see pictures below)

![image](https://user-images.githubusercontent.com/74332828/152413872-1cfee48d-9f5a-4cc5-bd0e-a243bcbe894b.png)

![image](https://user-images.githubusercontent.com/74332828/152414536-65a8d813-0b29-40c4-96a0-49926a4864b1.png)

**Comment by bumi** [comment]
@dylancom what do you think?  it is kinda related to #581 

so far I mostly found the image not very useful actually.

**Comment by dylancom** [comment]
I agree that the giant picture is unnecessary.
The suggested change looks a bit cluttered to me as we also have the PublisherCard.
Can we just omit the image?

**Comment by Kodylow** [comment]
If we drop the image, can we keep some reference to LNURL vs Bolt11 invoice

**Comment by bumi** [comment]
yes, I think the reference is untouched we would just not show the lnurl embedded image here. 

+1 for removing it
