### ISSUE TITLE
Pasting LnURL-Auth

### ISSUE THREAD

**Issue by decentropy** [getAlby/lightning-browser-extension#593]
Alby works great detecting site logins o my PC with Chrome plugin... but I would like to login from other devices (e.g. Android), by scanning/pasting an LNURL-Auth in "Send".

Is this supposed to work with LnURL-Auth? I am trying with lnmarkets.com or lite.kollider.xyz, and after I paste in, it just fills in fields with "loading..." but does not let me click "Confirm"

I'm connected to Umbrel, but also created an Alby wallet... and that doesn't work either (so I think the issue is on Alby's side)

**Comment by kirkawolff** [comment]
https://feedback.getalby.com/feature-requests-/posts/lnauth-cannot-be-used-with-other-devices

**Comment by kirkawolff** [comment]
There is a way to install Alby on android by using the [Kiwi browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser) chrome-clone. Alby appears to run well on it, but the lnauth feature does not work. It will hook into the alby extension, but the "grant access" alby popup does not work.

**Comment by bumi** [comment]
I didn't know about Kiwi browser. thanks for sharing. 
can you explain what you do? which website do you try to login? do you click on some "login link"? when should the popup open?

**Comment by kirkawolff** [comment]
Im trying to login to stacker.news with the lnauth button via android kiwi browser with alby installed as an extension

**Comment by bumi** [comment]
we now support copy-pasting the lnurl-auth string in the new release (v1.14.2)
