### ISSUE TITLE
Make fiat currency configurable and display amounts additionally in fiat

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#597]
Additionally to the satoshi amounts we should show fiat amounts for the not-yet hyper-bitcoinized users.

The favorit currency should be configurable and additional to the satoshi amounts we should convert the amount to fiat.

**Comment by mmalisani** [comment]
how about something like this? https://www.figma.com/file/fFj8yLtRu8VMp8RUsW03Dy/Alby-Suggestions--By-Mariano-Malisani?node-id=200%3A41

**Comment by escapedcat** [comment]
> how about something like this?

You think people will switch this a lot or could it be under settings?

**Comment by bumi** [comment]
@mmalisani thanks for the proposal. we fist should add this to the extension before we add it to the getalby.com webapp. 
And @escapedcat I agree, having a setting for this is good - will not often change.

**Comment by lightningxbtc** [comment]
I'd like to take this ticket and bounty on. Is the thinking something like this? A select option next to the input that allows the user to toggle the value display and then on creation of the invoice the value gets converted back to sats?

<img width="461" alt="Screen Shot 2022-05-08 at 13 41 04" src="https://user-images.githubusercontent.com/104893211/167283516-461a4a00-e375-44b8-bc51-5e7e37a32f77.png">

Or is the thinking more of a global toggle thats changes all values in the alby app? @bumi @escapedcat

**Comment by escapedcat** [comment]
> I'd like to take this ticket and bounty on. 

Awesome!

> Is the thinking something like this? A select option next to the input that allows the user to toggle the value display and then on creation of the invoice the value gets converted back to sats?
> Or is the thinking more of a global toggle thats changes all values in the alby app?

I think it's the second option. That's how I understood bumi:

>>  I agree, having a setting for this is good - will not often change.

**Comment by lightningxbtc** [comment]
Thanks!

How many currencies should it support? Just the "main" ones, or as many as possible? And any preferences on where I acquire currency exchange info from?

**Comment by bitcoinuser** [comment]
> Thanks!
> 
> How many currencies should it support? Just the "main" ones, or as many as possible? And any preferences on where I acquire currency exchange info from?

I think should support as many as possible. Breez app use https://yadio.io/ and is great.

**Comment by bitcoinuser** [comment]
See Breez:

![Screenshot_2022-05-08-08-00-44-182_com breez client](https://user-images.githubusercontent.com/1178856/167293185-179aa6f9-a0cf-498b-9c3c-6b6df2055a33.jpg)

![Screenshot_2022-05-08-08-00-27-648_com breez client](https://user-images.githubusercontent.com/1178856/167293196-2253b74a-6b0c-496a-961f-f396f54a918d.jpg)

**Comment by bumi** [comment]
yeah! super cool @lightningxbtc 🚀 

as the preferred fiat currency will not change much I thought it's best to save it in the settings. 
maybe we can also keep the source for the exchange rates rather flexible that we in the future can even allow the user to choose their source? 

When displaying the amounts I think only one other currency is enough, meaning we show sats and the selected fiat currency. 

besides the UI topics I think it's important to check how we handle the currency data. Right now our amounts are often represented as strings (we also don't do any calculations with it). Is there something like the Ruby [money gem](https://github.com/RubyMoney/money) in JS? Which allows us to have some "object" that knows about the amount and currency and has functionality to convert to other currencies? 
What's the best way to handle this in the most universal way? 

looking forward to get this is, as this is a highly requested feature

**Comment by escapedcat** [comment]
So far we only use simple native selects I believe.   
![image](https://user-images.githubusercontent.com/1016218/167979426-0248715e-0f12-476e-bd08-713cfd0ec2fe.png)  
No need to style it in this way.

**Comment by lightningxbtc** [comment]
> Is there something like the Ruby [money gem](https://github.com/RubyMoney/money) in JS? Which allows us to have some "object" that knows about the amount and currency and has functionality to convert to other currencies?

there is https://openexchangerates.github.io/money.js/

**Comment by bumi** [comment]
maybe we can start with a native dropdown? (should be much easier to develop) 

@lightningxbtc what do you think about money.js?

**Comment by dylancom** [comment]
https://github.com/dinerojs/dinero.js might be interesting.

**Comment by escapedcat** [comment]
- [moneyjs seems unmaintained (last release 7 years ago?)](https://github.com/openexchangerates/money.js)
- [dineros last release was an alpha sometime last year](https://github.com/dinerojs/dinero.js/releases/tag/v2.0.0-alpha.8)
- [currency.js](https://www.npmjs.com/package/currency.js) seems maintained but is not yet full TS

I guess we should have a closer look at dinero and currency? What else is out there?

**Comment by dvoroneca** [comment]
> native selects

No need for the custom design dropdown. 😅
I've edited the [design file](https://www.figma.com/file/kfSSGaZqbT65SyKbJ8qQz8/Fiat-values?node-id=29%3A2994) to reflect the native dropdown.

**Comment by dvoroneca** [comment]
In terms of function, I've made 2 versions.
 **Version 1** - Only reflects Fiat value
**Version 2** - The switcher between SATS and FIAT values in inputs (like in Phantom). 

The ticker requested "to display amounts". I've added a switcher between values as an option 2. 
 Do you think adding the switcher will be an easy update or we should keep it till further updates?

<img width="602" alt="Screenshot 2022-05-12 at 10 14 34" src="https://user-images.githubusercontent.com/35034985/168024256-224c6997-2331-4f78-80f3-e7ee86754578.png">

**Comment by dvoroneca** [comment]
> 

Good point, I've [updated values](https://www.figma.com/file/kfSSGaZqbT65SyKbJ8qQz8/Fiat-values?node-id=29%3A1696) to reflect SATS.

**Comment by lightningxbtc** [comment]
I think the native drop downs (Selects) should be fine, are are styled components already in the setting that use them like the theme picker. Only thing with using native select is lack of search so might be a bit of scrolling to find your currency.

**Comment by escapedcat** [comment]
> Only thing with using native select is lack of search so might be a bit of scrolling to find your currency.

Good point. Let's keep this in mind for i.e. a second iteration.
Could be an autocomplete or something similar depending on how this feature will be accepted/used by the users.

**Comment by dylancom** [comment]
I prefer to keep the currency next to the entered amount (v1), where in v2 I think SATS looks out of placement.
From v2 I like it though that the USD amount is directly placed below the sats amount. (instead of left - right).

The USD amount could potentially be also placed directly into the input like for e.g. in MetaMask:
<img width="351" alt="Schermafbeelding 2022-05-13 om 12 51 42" src="https://user-images.githubusercontent.com/12894112/168268926-0a23e5df-bc90-421e-98ce-4b3dce30c98d.png">

**Comment by dvoroneca** [comment]
> The USD amount could potentially be also placed directly into the input like for e.g. in MetaMask: <img alt="Schermafbeelding 2022-05-13 om 12 51 42" width="351" src="https://user-images.githubusercontent.com/12894112/168268926-0a23e5df-bc90-421e-98ce-4b3dce30c98d.png">

I tried the MetaMask field, and it does seem very intuitive and takes up less space. I think it's the best choice at this point.

If everyone agrees, here's a link to a file that has all the amendments discussed earlier. 

------------------

[Figma link](https://www.figma.com/file/kfSSGaZqbT65SyKbJ8qQz8/Fiat-values?node-id=113%3A4518)
[Switch icon.zip](https://github.com/getAlby/lightning-browser-extension/files/8707988/Switch.icon.zip)


https://user-images.githubusercontent.com/35034985/168803724-75a721ff-50c9-472e-8f16-3691afde49ae.mov


https://user-images.githubusercontent.com/35034985/168803733-578652a5-d36e-4ca7-ab7c-413efa8032ee.mov


https://user-images.githubusercontent.com/35034985/168803738-db5fb85e-8b49-4d19-a47a-1f0aa7bf75da.mov

**Comment by bumi** [comment]
looks good to me. great. 
can this be a universal react component that then takes care of everything?

**Comment by dvoroneca** [comment]
> looks good to me. great. can this be a universal react component that then takes care of everything?

This is definitely possible and desirable. Is there a repository of our components somewhere in react?

**Comment by escapedcat** [comment]
> Is there a repository of our components somewhere in react?

atm we have the Storybook setup: https://lbe-stories.netlify.app  
This might not cover all existing components though

**Comment by bumi** [comment]
thanks to everyone who worked on this!! 🎉
