### ISSUE TITLE
Make dark/light mode configurable

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#598]
Currently we use the system's dark/light settings. Can this also be a custom Alby setting? (mode: light/dark/system?) 

https://feedback.getalby.com/feature-requests-/posts/i-would-like-no-dark-mode-option-on-alby

**Comment by bumi** [comment]
@secondl1ght you want to check this out?

**Comment by secondl1ght** [comment]
Sure I can check this out

**Comment by secondl1ght** [comment]
Just wanted to give an update on this, I have it setup on the front-end and have starting working on hooking it up. Just need to figure out how to get it working but I should have time soon to look into this. Here is how the settings look, there are 3 options: Light, Dark and System for the theme.

![image](https://user-images.githubusercontent.com/85003930/154831615-8be1d6fe-54eb-468a-8095-179a4ca25c77.png)

**Comment by bumi** [comment]
Super cool. Feel free to open a draft PR then people already can follow the development and maybe can help with hints maybe.

**Comment by secondl1ght** [comment]
That would be great! I'll do that now.
