### ISSUE TITLE
Alby prompt keeps popping up on boltz.exchange

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#601]
If a user wants to do the off- to onchain swap on boltz.exchange/reverse, the user is asked to pay a lightning invoice. But the Alby prompt keeps popping up. As a result several (>20) Alby windows are open what makes the website not useable anymore. 
I noticed the there are only 4 Joule windows open. Zebedee, Strike or tippin.me did not react at all. 
![image](https://user-images.githubusercontent.com/13707997/153657525-97c6e7d7-70b4-4687-a1c9-9cf8a0266763.png)

**Comment by dylancom** [comment]
There seems to be some re-rendering bug on their end.
Exactly on every second (when you see the expiration time updating) it calls `webln.enable()` & `webln.sendPayment()`

**Comment by MoritzKa** [comment]
so only webln provider extensions are affected then?

**Comment by dylancom** [comment]
Yes, I think somehow Joule prevents spawning prompts somehow. To me it stops after 2 prompts show up.

**Comment by MoritzKa** [comment]
Yes it does. Maybe we can do that, too. But I will also contact boltz.exchange. Thanks for letting me know the cause.

**Comment by dni** [comment]
is this completely resolved?

**Comment by bumi** [comment]
It should be resolved, yes. Did you notice an issue? 
boltz still calls the webln functions too often (periodically), but Alby blocks those calls then

**Comment by dni** [comment]
i'm just thinking about improving boltz in that direction and stumbled upon this issue and was wondering if it is fixed now. 
polling to webln seems not ideal. i noticed i could not cancel the alby popup because it was constantly popping up again, which is kind of annoying.

**Comment by bumi** [comment]
yes, but why would one poll to webln? 
any webln resolves a promise or fails. 
for example: 

```js

webln.enable().then(() => {
  webln.makeInvoice(args).then((response) => {
    console.log(response.paymentRequest);
  });
});
```
no need to call makeInvoice multiple times.

See also: https://www.webln.guide/

With the change in this issue we try to prevent websites from calling multiple webln calls the same time.

**Comment by dni** [comment]
i have no clue, but thanks for that snippet, i see what i can do on that one
