### ISSUE TITLE
Show tipping options even if the publisher card is shown

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#607]
When a website is connected (a publisher/allowance is stored) we currently show only the publisher card and do not show the lightning tipping options. Ideally we mage to show both.

This can be reproduced on getalby.com (login with Alby on [getalby.com/login](https://getalby.com/login) and go to the [homepage](https://getalby.com) which contains lightning details.
 
https://feedback.getalby.com/feature-requests-/posts/the-https-getalby-com-site-has-no-option-to-donate-via-ln-

**Comment by secondl1ght** [comment]
I'm not able to reproduce this - when I login to the Alby site and then go back to the homepage and open the extension, there is a 'Send Satoshis' button that I can click to send tips.

**Comment by bumi** [comment]
Is getalby.com on the websites list / do you have an allowance saved?

**Comment by secondl1ght** [comment]
Oh no it isn't, I wasn't prompted to add as a publisher, how can I do this?

**Comment by bumi** [comment]
so I guess you did not login with Alby on getalby.com
You have to play around and dig into that yourself. Try to understand what is happening. That is the most work when debugging and fixing bugs. But it's easy just click around a bit. This also helps you to understand how things work in Alby.

**Comment by secondl1ght** [comment]
That's weird because I was taken to the logged in screen to I assumed that meant I was logged in.. :\

![image](https://user-images.githubusercontent.com/85003930/154852577-bd339eca-97e7-4734-bb4e-19c3d4631a90.png)

**Comment by secondl1ght** [comment]
Ok I put in PR #619 to resolve this!

**Comment by bumi** [comment]
@secondl1ght good find! great!! I left a comment there...we should try to not copy&paste the code...somehow we need to refactor this to keep it DRY.
