### ISSUE TITLE
Enhancement: Adding Alby installation link in the about section of the repository

### ISSUE THREAD

**Issue by pavanjoshi914** [getAlby/lightning-browser-extension#609]
Its good practice to have a website link or installation link of the product in the about section of the repository. 
This provides a handy way for users visiting this repository, to look over the product and get their installation done.

We can add chrome web store link , or website link in the about section of the repository.

**Comment by pavanjoshi914** [comment]
yeah! I would love to do that. But I think this can be changed by only authorities. I can't see any cog to edit this.
![image](https://user-images.githubusercontent.com/55848322/154786401-55ca124e-d01a-4f43-b6c2-8d5f0df32fd7.png)

If there is any way to edit, About the description of the repository. I would like to do this

**Comment by escapedcat** [comment]
True, can only be updated but people belonging to the org I think.  
Wanna propose a text that could be copy & pasted by them?

**Comment by pavanjoshi914** [comment]
we can keep this simple, 
we can put a link directly in the about section after the existing description. or 
we can give a shoutout first and then the respective links

eg.
a. 
```
Try Alby!

Chrome: https://chrome.google.com/webstore/detail/alby-bitcoin-lightning-wa/iokeahhehimjnekafflcihljlcjccdbe
Firefox: https://addons.mozilla.org/en-US/firefox/addon/alby/
```
b. 
```
Try Alby! or Give it a try! or Install Alby Now!
https://getalby.com/
```

c. simply after the already existing description, we can directly put a link.

**Comment by bumi** [comment]
ah I see you mean in the repo description. I've added the link to the getalby.com website. 

should we add more information also here: https://github.com/getAlby/lightning-browser-extension#browser-support ?

**Comment by pavanjoshi914** [comment]
Yeah, I think we can add a separate section for installation. links in the browser-support section don't reflect the context of installing the extensions.

**Comment by pavanjoshi914** [comment]
@escapedcat  links specified in the browser support section are stable releases or alpha releases!

**Comment by pavanjoshi914** [comment]
What do you think @escapedcat ?

## Browser Support

Alby supports

- All [Chromium based browsers](https://en.wikipedia.org/wiki/Chromium_(web_browser)#Browsers_based_on_Chromium) - Chrome Opera, Brave etc.
- Firefox
- more coming soon...

## Installation

Add Alby to your Browser

- [Add To Chrome, Opera, Brave, and all Chromium based browsers](https://chrome.google.com/webstore/detail/alby/iokeahhehimjnekafflcihljlcjccdbe)
- [Add to Firefox](https://addons.mozilla.org/en-US/firefox/addon/alby/)

**Comment by escapedcat** [comment]
tbh I think the [current browser support section](https://github.com/getAlby/lightning-browser-extension#browser-support) looks sufficient to me. What do you think we gain from separating this? Maybe I'm missing something

**Comment by pavanjoshi914** [comment]
> Yeah, I think we can add a separate section for installation. links in the browser-support section don't reflect the context of installing the extensions to user

I'm supposed to think this. installation section will be more transparent to the user
