### ISSUE TITLE
Enhancement: Setup template for creating issues for the repository

### ISSUE THREAD

**Issue by pavanjoshi914** [getAlby/lightning-browser-extension#610]
I think having a different organisational template for creating issues, features requests etc is a good practice.

```Proposed Bug report template```

**Describe the bug**

**Steps To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
A clear and concise description of what you expect to happen.

**Screenshots (If Any)**
 add screenshots to help explain your problem.

**Device Information [optional]:**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, safari, firefox]
 - Browser Version [e.g. 22]

**Additional comments**

**Are you working on this issue? (Yes/No)**

```Proposed Feature Request Template```

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Additional context**
Add any other context about the feature request here.

**Are you working on this? (Yes/No)**

**Comment by ankur12-1610** [comment]
@pavanjoshi914 I would like to work on it:sweat_smile:

**Comment by pavanjoshi914** [comment]
I have to see if manual changes of.github folder through PR effect or not. generally, this is done by authors themselves.
