### ISSUE TITLE
Enhancement: Integrate commitlint with proper commit conventions 

### ISSUE THREAD

**Issue by pavanjoshi914** [getAlby/lightning-browser-extension#612]
Alby doesn't have any proper commit conventions that everyone should follow

we can integrate any available linter so that everyone follows the same commit conventions, this will help in
a.  keeping commit history clean for the codebase, 
b. do regressions and analysis of previous commits easy in future. or while using git bisect
c. Commit messages could also be used to determine the next version number according to [semver](https://semver.org/). 

Proposed plugins:
1. https://github.com/conventional-changelog/commitlint 
2.  https://github.com/conventional-commits/conventionalcommits.org (personally I love this)

coding conventions of conventional commits

https://www.conventionalcommits.org/en/v1.0.0/

Once mentors decide which would be best for us, I can start working on it

**Comment by pavanjoshi914** [comment]
@escapedcat

**Comment by escapedcat** [comment]
Some background info: https://slides.com/marionebl/the-perks-of-committing-with-conventions

**Comment by dylancom** [comment]
Let's add in the industry standard: https://github.com/conventional-changelog/commitlint
