### ISSUE TITLE
Inconsistent lightning meta tag content description

### ISSUE THREAD

**Issue by schneimi** [getAlby/lightning-browser-extension#614]
**Works**
https://getalby.com/value4value
`content="lnurlp:you@lightning.address"`

**Doesn't work**
https://github.com/getAlby/lightning-browser-extension/wiki/Lightning-Monetization-meta-tag
`content="lnurlp=your@lightning.address"`

**Comment by bumi** [comment]
briefly I thought `=` is better thatn `:` but I kept `:` 
the document to follow is this one: https://github.com/BitcoinAndLightningLayerSpecs/rfc/issues/1
