### ISSUE TITLE
Make lnurl-auth with Lnbits compatible the their implementation

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#631]
Currently we create a custom key used for lnurl-auth with lnbits. 
Since lnbits supports lnurl-auth we should make sure to be comptabile. This then results in the same accounts when the user logs in with Alby or with Lnbits.

code in lnbits:
https://github.com/lnbits/lnbits-legend/blob/dbab18175935a65fa3a41a4869257953f5ec38cb/lnbits/core/models.py#L41

**Comment by kirkawolff** [comment]
No matter how hard I try, I can't figure out what lnbits is putting in for Wallet.id and how that's defined. I believe this compatibility would only be important for lnd, eclair and lnbits wallets, and not for lndhub wallets.

**Comment by bumi** [comment]
I think this can only be compatible if the user connect Alby to lnbits - lnbits connected to LND or something else is unrelated there. 
The wallet ID must be something lnbits specific. 
If you create a lnbits wallet (e.g. on https://legend.lnbits.com/) you see in "API Info" on the right a "Wallet ID" entry. isn't that what is used there?

**Comment by kiwiidb** [comment]
What should be the signing key then exactly?

**Comment by bumi** [comment]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/318/160807668-f1f7fd95-64af-4b32-92b3-8cf16240d591.png">

Turns out I am wrong. the code I linked in this issue is only a place holder so far. They don't have full lnurl-auth support. 

So I think we should use a similar schema as lndhub (`lnbits://${this.config.adminkey}`) to create the key used for signing.
