### ISSUE TITLE
Deleting the last account in the accounts list causes Alby to think no account is configured 

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#633]
**Describe the bug**

**To Reproduce**

Make sure to have 2 or more accounts configured

1. Visit the accounts page
2. Delete the last account in the list
3. Reload the page or open the extension popup => it seems Alby thinks no account is setup and opens the welcome page

**Expected behavior**

A different account should be selected.

**Information About Alby**
- Alby Version: latest master

**Comment by escapedcat** [comment]
Happy to give this a try

**Comment by bumi** [comment]
maybe this is a strange case that I got my storage in... and it has nothing to do with the last one. From quickly looking at the code I don't think the "last" account has an issue. 

BUT: we have an issue with the account IDs (which currently are just numbers. For that we use the accounts.length +1 - which now is not good enough anymore. We need to switch to UUIDs for that.

**Comment by bumi** [comment]
@escapedcat you can check this one if you want: https://github.com/getAlby/lightning-browser-extension/issues/635
maybe this solves this.
