### ISSUE TITLE
Switch account Ids to UUIDs

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#635]
**Describe the bug**
Currently we use numbers as account IDs. Those are currently simply generated by counting the accounts and +1. 
Before being able to delete an account this was fine. Now since we can delete accounts this is a problem because it can cause "duplicates"

**To Reproduce**
1. Make sure to have two accounts: (ID 1 and ID 2)
2. Delete the first account (ID 1) (ID 2 is still there)
3. Try to add a new account

Error: This will try to create a new account with ID accounts.lenght+1 == 2 - and thus overwrite the existing account

**Idea**

We should switch to UUIDs when creating new accounts. 
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/actions/accounts/add.js#L14

**Comment by dylancom** [comment]
This has been integrated.
