### ISSUE TITLE
feat: proper error handling in Alby extension

### ISSUE THREAD

**Issue by pavanjoshi914** [getAlby/lightning-browser-extension#650]
**Is your feature request related to a problem? Please describe.**
Most of the error messages displayed in alert doesn't provide user friendly description about the error and are limited to representing error status code

**Describe the solution you'd like**
Proper error handling so that user and developers can understand whats going on

**Additional context**
Some examples 
When we use an existing email address which is already registered. the error message should be "email has already taken"
![image](https://user-images.githubusercontent.com/55848322/156498782-b616b72c-3f8f-4552-ab43-bb0ba50111e3.png)

![image](https://user-images.githubusercontent.com/55848322/156499131-29b95b5f-e135-43e8-bc80-17efd3467fbc.png)

**Are you working on this? (Yes/No)**

**Comment by escapedcat** [comment]
Closing this in favour of #703 even though this is the original :P
