### ISSUE TITLE
docs refactor existing readme and add new documentation

### ISSUE THREAD

**Issue by pavanjoshi914** [getAlby/lightning-browser-extension#651]
**Is your feature request related to a problem? Please describe.**
currently, we specify everything in one readme file
I especially consider it to show meaningful things on main read me refactor other documents and share links in the main readme.
this also provides the opportunity to give more information and motivation about the organization in the main readme

eg. 
https://github.com/wikimedia/mediawiki
eg. 

https://github.com/CircuitVerse/CircuitVerse

**Describe the solution you'd like**
1. refactoring readme and creating new documentation
```setup.md```represents how to run Alby in the local development environment.
```contribution.md``` contribution guide for new developers.
```code_of_conduct.md``` giving more information about code of conduct.

2. In README.md
a. Alby horizontal banner at the start of the readme 
b. More about organization
c. Section motivating to join the community
d. links to the specific markdown files

**Are you working on this? (Yes/No)**
After finishing already pending work

**Comment by escapedcat** [comment]
Good point. Moving things into `docs` can also work. Filenames should be uppercase (as Github suggests).  
Recently liked this: https://github.com/LN-Zap/zap-desktop/tree/master/docs

**Comment by qqqzhch** [comment]
represents how to run Alby in the local development environment.
I just need to build a local development and testing environment, so I will sort out the information on how to build a development environment
