### ISSUE TITLE
UI - dark mode: Accounts context menu (3 dots) are not visible on hover

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#655]
**Describe the bug**
Problem:
Non-hover  
<img width="432" alt="image" src="https://user-images.githubusercontent.com/1016218/156914792-535a1d2d-aeb8-4ea2-8655-9e2948413600.png">
Hover  
<img width="426" alt="image" src="https://user-images.githubusercontent.com/1016218/156914805-0ed8dea1-c833-45db-91c6-1ac76f318aad.png">

**To Reproduce**
1. Use dark-mode
1. Visit Accounts
1. Hover over "3 dots context menu" right of an account entry

**Expected behavior**
Menu-icon still visible on hover

**Device Information [optional]:**
 - OS: OSX
 - Browser: Chrome Canary
 - Browser Version: 101.x.x.x

**Are you working on this issue?**
No

**Comment by secondl1ght** [comment]
Thanks for reporting - it looks like this entire section actually needs dark mode updates because it is new. Will add now.

**Comment by secondl1ght** [comment]
PR is in #659
