### ISSUE TITLE
UI - dark mode: Websites settings menu focus colors/text not enough contrast

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#656]
**Describe the bug**
Problem:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/1016218/156917403-f482190d-36f7-4e0c-ac8c-76af3bd07ce1.png">

**To Reproduce**
1. Visit Websites
1. Click on Alby
1. Use tab to focus on settings icon & press enter (all with keyboard)
1. "Edit" is higlighted in menu but it's white text on light-grey background 

**Expected behavior**
Good contrast

**Device Information [optional]:**
 - OS: OSX
 - Browser: Chrome Canary
 - Browser Version: 101.x.x.x

**Are you working on this issue?**
No

**Related issues**  
#655

**Comment by bumi** [comment]
thanks, @secondl1ght (head of dark-mode :D) can you look into this?

**Comment by secondl1ght** [comment]
Thanks for reporting, will put in a fix for this soon!

**Comment by secondl1ght** [comment]
I just checked it out with the latest version and I cannot reproduce, are you on the latest version?

![image](https://user-images.githubusercontent.com/85003930/156933888-3c0fd812-98c3-40b2-a1cb-fb4c7a8d3ffd.png)

**Comment by escapedcat** [comment]
Using the keyboard navigation I can still reproduce this issue.  

See: 
![keyboard-issue](https://user-images.githubusercontent.com/1016218/156967036-e577466e-2e00-4d87-8d5e-702268f41a03.gif)

Do you see this as well?

**Comment by secondl1ght** [comment]
Hmm ok yeah now I see it.. that is a weird edge case. I dont think many people use their keyboard to navigate the app, I looked into it and it seems like the `hover:` class does not work for keyboards. Some people recommended substituting `focus:` for this to work similar on keyboards but it only works on some elements. Maybe @dylancom you have another idea on how to solve for this? Or maybe it is so rare that we don't need to, @bumi what do you think?

**Comment by escapedcat** [comment]
> Hmm ok yeah now I see it.. that is a weird edge case. I dont think many people use their keyboard to navigate the app, 
Yeah, it's not a high prio.  
But apart from people relying on keyboard-navigation there are tons of people out there who prefer keyboard navigaiton. Bitcoin might be their bubble.

> I looked into it and it seems like the `hover:` class does not work for keyboards. Some people recommended substituting `focus:` for this to work similar on keyboards but it only works on some elements. 

You have links to these findings? If this is i.e. a Tailwind issue they might already have an issue for this we could link.

**Comment by dylancom** [comment]
Here you can find how to style the active (focussed) item of a Menu. https://headlessui.dev/react/menu#styling-the-active-item

**Comment by secondl1ght** [comment]
Nice @dylancom, @escapedcat do you want to do the fix for this? - just checking since you put in the issue.

**Comment by escapedcat** [comment]
> you want to do the fix for this? - just checking since you put in the issue

Just wanted to document it first really.  Go ahead if you are interested. Otherwise it could be a "good first issue" as well maybe.

**Comment by bumi** [comment]
I think this is fixed?

**Comment by escapedcat** [comment]
Yup!
