### ISSUE TITLE
Add tipping support for Medium profiles and articles

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#663]
"[Medium](https://medium.com/) is a place to write, read, and connect". Similar to the [tipping feature on Twitter or Vimeo](https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/content-script/batteries/VimeoVideo.ts) Alby should support tipping of articles and profiles on [Medium.com](https://medium.com/). Alby can extract lightning address details from the article and author profile

**Additional information**
Medium also offers the possibility to add custom domains which would need Alby to search for Lightning Addresses, LNURL, etc on every website. As discussed in the community call today we limit support to blogs on medium.com and will tackle custom domains in a separate issue. 

I am going to work on this issue. 🙌

**Comment by reneaaron** [comment]
## Analysis

### Potential sources of information

I could find 3 potential places where you an author could potentially add some⚡ info:

#### Short bio (max. 160 characters)
![image](https://user-images.githubusercontent.com/100827540/157306545-6abc532b-8f1f-4b5d-ad3e-2b44823e7b3d.png)

This info is displayed along with your name on your profile as well as at the end of every article. (see screenshot) As the short bio is very limited in length (160 chars max) it is probably only viable for Lightning Addresses. 

#### About page

This is a separate page available at medium.com/[username]/about where you can describe yourself.  However, the information from the about page would have to be fetched with a separate request. 

#### The article content

You'd need to add your ⚡ info into every article. From the maintenance perspective this could be quite a hassle. (imagine your lightning address ever changes 😅)

### Parsing data

Medium's CSS class names are automatically generated and change very frequently so there is no point in relying on them. I needed to come up with quite some DOM queries to actually find the relevant information (author name, image, etc). Also I don't know how reliable this parsing will be over time. 

## Current status

I have a working prototype for each of the sources running now, please let me know which sources you would want to see supported by Alby so I can prepare a PR. 🙌

**Comment by bumi** [comment]
oh ja, I see... that seems quite tricky with their HTML. wasn't aware that they make it that hard. 

I think the "Short bio" would be the best. Because as you say then no additional request is required and there is one place that works for all medium.com pages. 

Do you think that's possible? How do you feel with you PR? can we reliably extract this information?

**Comment by reneaaron** [comment]
Thanks for your feedback, that makes sense to me. 👍

The queries seem to be quite reliable, yeah. I'll prepare a MR so you can see for yourself.
