### ISSUE TITLE
Add info on the `Websites` tab about what it is

### ISSUE THREAD

**Issue by Bosch-0** [getAlby/lightning-browser-extension#666]
Just created a new Alby hosted wallet. When clicking on the websites tab the page is just blank, it would be handy if there was a tool tip or something explaining what this page is  - maybe even link to an example site that people can test it with.

Page in question:

![image](https://user-images.githubusercontent.com/55287964/157162400-d71b1c52-3ccf-4b05-8e52-ac76f6f8525e.png)

**Comment by escapedcat** [comment]
Does this duplicate #88 ?

**Comment by bumi** [comment]
yes, and we need to get #490 done. 
quite important as it's confusing for people like this.

**Comment by Bosch-0** [comment]
Sorry missed #88, will close and follow discussions there

**Comment by escapedcat** [comment]
Lovely issue number btw 😈 🇨🇳 💰
