### ISSUE TITLE
Export wallets after creation

### ISSUE THREAD

**Issue by kiwiidb** [getAlby/lightning-browser-extension#669]
**Is your feature request related to a problem? Please describe.**
There is no way to export a wallet after it’s created. So if you forget to backup for some reason, you can’t do it later. Or if you first install in Chrome, but then want it in Firefox as well, you can’t easily get the LNDhub connection string.

**Describe the solution you'd like**
At least for LNDhub wallets, we could have the option to export the connection string at any time (password protected). This way, your computer and mobile version of the wallet act like backups of eachother.

I don't think we need this for other connectors, but we could consider it.

**Describe alternatives you've considered**
- Inspect `/auth` network requests to extract the connection string.
- Look in the storage to extract the connection string.

**Are you working on this? (No)**

**Comment by MoritzKa** [comment]
Feedback from another user: 

- A botton to export this URL / download QR Code image
- A warning on not sharing this

**Comment by bumi** [comment]
We now got an accounts list. We can have an account detail page that shows the credentials and related information

**Comment by bumi** [comment]
I think the easiest to do this is to add an "export" menu item and then show the lndhub connection details in a modal. 
As we show the details after the account is added: https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/connectors/NewWallet/index.tsx#L127-L141

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/318/172261321-8b10017e-90a1-4622-ac69-a67e9a86b95b.png">

**Comment by im-adithya** [comment]
Any changes? @bumi 
![Screenshot from 2022-06-07 19-31-14](https://user-images.githubusercontent.com/64399555/172399763-c5967753-0482-436b-90f6-750329111cfa.png)
![Screenshot from 2022-06-07 19-30-15](https://user-images.githubusercontent.com/64399555/172399641-69a8382b-22cd-4001-b7a3-4e1a801c9636.png)

**Comment by bumi** [comment]
I don't think we have the data for the lightning address there. so that would be just the export QR code AND we should add it as a string in an input field. - that allows users to copy it.

**Comment by escapedcat** [comment]
At a later stage we could think about adding a "copy to clipboard" button to an input. Not sure if we already have this somewhere. I.e. https://bionicjulia.com/blog/creating-copy-to-clipboard-button-in-react  
Should not be done in this issue.
