### ISSUE TITLE
Simplify tor integration

### ISSUE THREAD

**Issue by supertestnet** [getAlby/lightning-browser-extension#670]
Recently alby added support for connecting to a node over tor. To use this, users have to download a companion app which opens up a connection to tor, and alby proxies all queries to .onion endpoints through that companion app. This is unnecessary if you have tor already set up on your computer and already configured your browser to forward .onion requests to the tor port you use.

However, alby doesn't allow this because it now automatically detects if you try to query a .onion endpoint, intercepts those requests, and tries to send them to the companion app, even if you don't have the companion app running because you already have tor and a properly configured browser.

Perhaps a more ideal scenario would be one where alby autodetects if you can visit tor sites by doing an http request from a tor site. If it gets back the expected value then it can pass queries directly to tor sites without passing them through the companion app. Otherwise it can prompt the user to install the companion app.

**Comment by decentralizedb** [comment]
I tried it with the current build file to test (I took the Firefox zip file, maybe it might be a good idea to have a Tor zip file?). 
I can see the message that says you have the option not to install the companion app and continue using Tor Browser, but I get a network error message.
The console shows a network error message but doesn't give much detail. See attached images.

Using Tor Browser over Linux (Ubuntu)
Tried to connect LND node using onion address and admin macarron

![image](https://user-images.githubusercontent.com/58108487/188832779-1dd18cf3-22c9-4837-ad35-7b12decd848d.png)
![image](https://user-images.githubusercontent.com/58108487/188832887-8edb807a-73e5-4f77-90e4-22d6b2a59e31.png)
![image](https://user-images.githubusercontent.com/58108487/188833039-48ee3ccb-2092-4503-a681-a4f1f895fa0f.png)

**Comment by bumi** [comment]
thanks for testing it! 
I've made some update that maybe explain the problem and solution here.

**Comment by decentralizedb** [comment]
> 

Ok, I tried again with the latest update, and it failed the first time, but as you said, it shows more help.

I clicked on the onion address (to validate the https), and once I accepted the risk message, I tried again, and the second time it worked and connected. Also I open an order in Robosats and pay the order using Alby, works fine!.

I'm left wondering if, with a final version, once I close Tor, will the https validation be permanent, or will it have to do the workaround anytime you open the Tor browser?

**Comment by bumi** [comment]
from my experience so far the browser (also the Tor Browser) remembers this decision... but it can be that this exception has to be added again after a Browser update or similar (it basically depends on the browser)

Alternatively the certificate can be added globally to the system - but this becomes complicated I think. 
(I've also seen some good posts about this in the [Umbrel forum](https://community.getumbrel.com/)

**Comment by bumi** [comment]
thanks for testing it! very helpful...we keep working on making the setup easier. (and I think LND will also provide more options to avoid the self-signed cert issue in the future)

**Comment by decentralizedb** [comment]
> thanks for testing it! very helpful...we keep working on making the setup easier. (and I think LND will also provide more options to avoid the self-signed cert issue in the future)

Ok, I'll look at the Umbrel forums.
I forgot to say that I'm not using Umbrel, I'm testing this outside of Umbrel, but I think it's useful for Umbrel users as well.
Anytime, I'm happy to help. 💪🏼😃

**Comment by bumi** [comment]
this should be shipped now.
