### ISSUE TITLE
Add RaspiBlitz connector

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#673]
**Describe the solution you'd like**
In order to make it easier for RaspiBlitz user we want to show them within Alby how to connect their node and where they find the connection settings. 
This could be done in a special RaspiBlitz connector UI with special instructions that then adds a LND connection.

**Comment by secondl1ght** [comment]
Does anyone have a Raspiblitzl that can write out the instructions we want to display on this connector?

**Comment by escapedcat** [comment]
Somewhat related to https://github.com/cstenglein/raspiblitz-web/issues/207

**Comment by secondl1ght** [comment]
This has been merged
