### ISSUE TITLE
Add Umbrel connector

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#674]
Describe the solution you'd like
In order to make it easier for Umbrel user we want to show them within Alby how to connect their node and where they find the connection settings.
This could be done in a special Umbrel connector UI with special instructions that then adds a LND connection.

Pretty much the same as #673

**Comment by secondl1ght** [comment]
Does anyone have an Umbrel that can write out the instructions we want to display on this connector? 

Also there are many other plug and play nodes like myNode, Start9, Citadel etc. do we want to let users know that Alby is compatible with any of them? If we only have an Umbrel and Raspiblitz connectors then some users might think they can't use a different node implementation even though they can.

**Comment by bumi** [comment]
For Cidadel we got already a special connector in a PR. needs to be merged. and it for sure would be good to add others, too. myNode, Start9, etc. maybe they can help us? I've never used them so we would need to find out how they work and where users find the LND credentials.

**Comment by secondl1ght** [comment]
PR in #682 just need the Umbrel steps from somebody with an Umbrel and I can add those in.
