### ISSUE TITLE
People are unsure which account is used to login

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#675]
**Describe the bug**
In the login (or payment) prompt it is currently not clear which account is used. This can be confusing when users have two or more accounts.

**Expected behavior**
Maybe we can name the current selected account in the prompts. And/or allow changing the account from within the prompt.

**Screenshots (If Any)**
<img width="403" alt="image" src="https://user-images.githubusercontent.com/318/157488758-06d15325-ad49-4c6c-bff8-0b6f3644c744.png">

**Comment by im-adithya** [comment]
We can also think of providing the feature to name different accounts (user-defined) as all of them show the same name (Alby) like this:
![Screenshot from 2022-03-19 19-38-34](https://user-images.githubusercontent.com/64399555/159124392-c14f60c2-224f-42d0-b69e-494fa21f6d79.png)

**Comment by escapedcat** [comment]
> We can also think of providing the feature to name different accounts (user-defined) as all of them show the same name 

This has been done here: #647
