### ISSUE TITLE
Add Start9 (EmbassyOS) connector

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#677]
They have both a LND and c-lightning option.

**Comment by escapedcat** [comment]
Would be great to always link mentioned services so people who don't know these can follow easier.  
In this case I assume: https://github.com/Start9Labs/embassy-os

**Comment by secondl1ght** [comment]
Yes sorry about that, I was busy when I wrote this so I just put a short description in.

**Comment by escapedcat** [comment]
No worries
