### ISSUE TITLE
Password setup discussion

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#679]
@Bosch-0 mentioned in the Slack that it would be good to provide more user feedback when you incorrectly confirm your password on the initial sign up screen (right now the button is just disabled until you enter it correctly but no other feedback). I also thought it might be good to add a toggle so users can view/hide the password they entered to verify it is correct. What does everyone think of these 2 improvements?

**Comment by Bosch-0** [comment]
All good suggestions to me :)

**Comment by escapedcat** [comment]
Sounds good! Is it too early to introduce a form-validation-lib? 😊

**Comment by secondl1ght** [comment]
I was just going to use pure javascript for it.. 😛

**Comment by escapedcat** [comment]
> I was just going to use pure javascript for it.. 😛

I thought so :D  
I think that's ok for now. I expect mid-term we'll end up with more validations on different form fields and then a lib will make sense.

**Comment by secondl1ght** [comment]
@dylancom @bumi I think I see now why it is currently this way, because if the button is disabled until the passwords match, then you will have to trigger the error `onChange` which will result in errors displaying while the user types their password which isn't a good UX either. Can you guys confirm you want to leave it the way it is?

**Comment by bumi** [comment]
not sure about the details there right now. you can decide based on complexity for the improvement or of other things bring more value.

**Comment by secondl1ght** [comment]
Ok maybe we will skip the error feedback for now but could still add the show/hide password toggle.

**Comment by im-adithya** [comment]
Can I work on the toggle feature?

**Comment by secondl1ght** [comment]
Sure sounds good @im-adithya thanks!

**Comment by escapedcat** [comment]
PR was merged
