### ISSUE TITLE
webln.addAccount() call to automatically prefill account addition

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#680]
Opening this issue to document my experiments. 

To make the onboarding easy from node management UIs we can implement an `webln.addAccount` function. This function can be called from websites (similar to other webln functions) and opens the connector form prefilled with node data. 

I tried to add an `addAccount` action which opens the connector form options page. 
To avoid that sensitive node data is persisted in the browser history I do not want to pass data to the page in query params. 
As alternative I tried to directly execute JS in the opened page. 

From background scripts we can only open pages using: `browser.tabs.create()`
And we can only execute JS in the opened page using [executeScript](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript). 

To pass in data we would need to interpolate the code that is passed to `executeScript` (code is passed in as string). 
Because we can not trust the data this is a problem and I am not sure right now how to avoid this.

**Comment by reneaaron** [comment]
Done with #1916
