### ISSUE TITLE
"https://" autofill or error message when connecting to LND

### ISSUE THREAD

**Issue by Kodylow** [getAlby/lightning-browser-extension#693]
**Describe the bug**
I tried connecting to LND over Voltage today and it took me a couple tries to realize that the "https://" was required on the Alby side, but in voltage's "connect" tab for REST it doesn't include the https:// , just the url. 

The https:// is in the placeholder text for Alby, but I think there should be a more clear error notification when the user tries to connect. Making the https:// required in the form would probably be the most useful, or specifying in the error message that it's a url format issue instead of "Are your LND credentials correct?"

Will work a quick PR for this tonight.
<img width="462" alt="Screen Shot 2022-03-14 at 8 54 45 AM" src="https://user-images.githubusercontent.com/74332828/158212055-7c5dc989-a4a7-4689-9bc1-754f01a9b5f4.png">
<img width="501" alt="Screen Shot 2022-03-14 at 8 57 16 AM" src="https://user-images.githubusercontent.com/74332828/158212064-e5ff216f-a2c6-4e60-964e-3901cf46db7e.png">

**Comment by bumi** [comment]
oh nice. great idea! 
do you want to make a PR? (should be used on all URL inputs)

**Comment by Kodylow** [comment]
yup I'll make it tonight, working on a branch now. Going to see if it's an issue with the other connectors too

**Comment by Kodylow** [comment]
the other connectors have better error checks or autofill with the correct URL (citadel.local, etc) , just made the changes for lndhub and lnd
