### ISSUE TITLE
Lists appearing as tasks in pull request templates

### ISSUE THREAD

**Issue by pavanjoshi914** [getAlby/lightning-browser-extension#702]
**Is your feature request related to a problem? Please describe.**
list items present in pull request templates appearing as tasks in pull request overview

**Describe the solution you'd like**
1. Use  double space in ```-[  ]``` brackets so that only checked items appear as a task in the PR overview, and unchecked items remain still without appearing in the PR overview

2. if we don't want checked items not appearing in pr overview as well,  Instead of using lists which can be checked, use numbered list and contributors can decide what to keep and what not to keep depending on the pr created.

**Additional context**
before 
![image](https://user-images.githubusercontent.com/55848322/158817369-5e34ae7a-44ee-4ef3-bb4d-0f90a497eb3b.png)

after :
only checked items appear in the PR overview
![image](https://user-images.githubusercontent.com/55848322/158819021-6450c07a-e6cf-4f23-b02a-47d3ac46ca25.png)

for second  solution, no task status will appear in pr overview

**Are you working on this? (Yes/No)**

**Comment by pavanjoshi914** [comment]
@bumi  @escapedcat

**Comment by escapedcat** [comment]
Sounds good.  
Also would be nice to [replace this](https://github.com/getAlby/lightning-browser-extension/blob/master/.github/pull_request_template.md?plain=1#L2) with i.e. `#[ISSUE_NUMBER]`.  
At the moment some PRs already are linked to 147 because people didn't modify or remove the number.

**Comment by pavanjoshi914** [comment]
what we shall go with then, solution 1 or 2

**Comment by escapedcat** [comment]
Ah sorry 🤦   

Suggestion:  
- "Type of change" - Can be switched to a normal list with a note that says i.e. "Please remove not matching type"
- "How Has This Been Tested? - List can be removed but the headline stays. People can fill this out when needed.
- "Checklist" - Could stay I think. We can use this to enforce certain tasks.
