### ISSUE TITLE
Idea: notifications for your ln address 

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#704]
I have an idea - since users can now associate their e-mail with their lightning address in Alby, could we have the option for users to enable notifications? So they would get an automated e-mail each time they receive sats to their ln address?

**Comment by bumi** [comment]
can you open that issue in the getalby.com repo?

**Comment by secondl1ght** [comment]
Closed in favor of: https://github.com/getAlby/getalby.com/issues/91
