### ISSUE TITLE
Display "no websites" message

### ISSUE THREAD

**Issue by im-adithya** [getAlby/lightning-browser-extension#713]
**Describe the bug**
The websites section should show a filler when there are none

**To Reproduce**
1. Open the Wallet
2. Click on Websites
3. Remove all (if any)
4. You'll see an empty screen

**Expected behavior**
There should be some gray icon saying `no websites`

**Information About Alby**
- Alby Version: Latest
- Alby installed through: Dev version
- Wallet connected with Alby: BlueWallet LNDhub

**Screenshots (If Any)**
![Screenshot from 2022-03-19 19-11-11](https://user-images.githubusercontent.com/64399555/159123556-debfaa4e-f68a-4708-9a3b-cc343b04485a.png)

**Are you working on this issue? (Yes/No)**
Will work on this after discussing with the design team.

**Comment by escapedcat** [comment]
Duplicates #88

**Comment by im-adithya** [comment]
Oops! Closing this!
