### ISSUE TITLE
Re-design connectors screen

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#720]
Creating this issue to track the discussion about re-designing the connectors screen. We mentioned in the call today that we might want to look into this now that we have 3 rows of connectors. I searched the issues and couldn't find anything open about this.

**Comment by BhuvanAde** [comment]
Can you please assign me this issue. I'm interested to work on this.

**Comment by stackingsaunter** [comment]
@BhuvanAde I actually started the redesign so I will probably finish it, but I will appreciate your feedback on this! 
Not a big change for now so it can be easily implemented without a lot of code work.

It consists mostly of:
1. Adding a intermediary step if user chooses a node implementation that can have multiple node/wallet apps, like this for Umbrel:

<img width="1367" alt="Screenshot 2023-03-17 at 12 14 06" src="https://user-images.githubusercontent.com/68239231/225889503-82159b3e-2fa8-4fd2-9f31-758fc951785f.png">


2. Decluttering the form by getting rid of Alby bee on the right side, placing all elements vertically. Also minor changes like buttons having the same size for better balance or adding connector logo in the header. 

<img width="1140" alt="Screenshot 2023-03-17 at 12 14 22" src="https://user-images.githubusercontent.com/68239231/225889555-eb31a223-2f45-4ee7-a80e-61170526dc5e.png">

There's prototype [here you can play](https://www.figma.com/proto/AMzMvcwrr2IdunqMakaB8r/navigation%2C-dropdown%2C-receive-onchain-work%2C-connectors%2C-nostr-events?page-id=38%3A4400&node-id=62-7316&scaling=min-zoom&starting-point-node-id=62%3A7316) and [Figma file to see ](https://www.figma.com/file/AMzMvcwrr2IdunqMakaB8r/navigation%2C-dropdown%2C-receive-onchain-work%2C-connectors%2C-nostr-events?node-id=38-4400)

What do you think?

**Comment by BhuvanAde** [comment]
@stackingsaunter I appreciate the design you created, and I think everything you did was excellent. I just want to draw attention to the back and continue buttons on the second screen. Continue should, in my opinion, be given equal or greater importance than it currently is. This is just a suggestion, so please let us know if there is a specific justification for it. I greatly appreciate your efforts, maintaining the design's hierarchy and consistency.

**Comment by BhuvanAde** [comment]
@stackingsaunter Please let me know if there are any other issues that might require my assistance. I will be overjoyed to do so!

**Comment by stackingsaunter** [comment]
@BhuvanAde Thanks for feedback! Continue on the second screen is disabled, because form are empty. Filled looks like this:

<img width="562" alt="Screenshot 2023-03-17 at 12 46 43" src="https://user-images.githubusercontent.com/68239231/225895891-d3002018-4312-4b49-a430-931d4f1cd15e.png">

**Comment by BhuvanAde** [comment]
Alright! @stackingsaunter
