### ISSUE TITLE
Replace sha.js library with crypto-js SHA265 library

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#721]
**Describe the solution you'd like**
Currently we use sha.js and crypto-js/SHA265 for hashing. We should replace all sha.js usages with the crypto-js hashing lib.

**Comment by escapedcat** [comment]
Can do

**Comment by escapedcat** [comment]
Found [sha-js being used in `getHash()`](https://github.com/escapedcat/lightning-browser-extension/blob/master/src/common/lib/utils.ts#L40-L42  )

But I can't find `getHash` is being used in the codebase anywhere? Am I missing something or can this just be removed?

**Comment by bumi** [comment]
remove it. :) 
I remember that in the beginning I struggled with the SHA thing, so maybe that's a leftover...
