### ISSUE TITLE
Add support for value4value tipping on podcastindex.org

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#722]
**Is your feature request related to a problem? Please describe.**
Currently we do not support tipping on podcastindex.org. Tipping recipients are shown on the page.

Ideally this support is directly added to podcastindex.org ([code](https://github.com/Podcastindex-org/web-ui/blob/36e4113db2d7c151663d05f6f7ad63c4e9eed275/ui/src/components/Value/index.tsx#L38))
but maybe we can support it also directly like other platforms.

Example podcast: https://podcastindex.org/podcast/185230

**Additional context**
We now support keysend payments but we currently do NOT have an UI to support payments to multiple value4value recipients.

**Are you working on this? (Yes/No)**
no

**Comment by MoritzKa** [comment]
can be closed, right?
