### ISSUE TITLE
The pre-defined amounts have a line break on windows

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#727]
**Describe the bug**
A minor UI bug: The pre-defined amounts have a line break on windows.

**To Reproduce**
1. Visit to https://twitter.com/dergigi
2. Open Alby
3. Click "send satoshis" 

**Information About Alby**
- Alby Version:  1.7.0
- Alby installed through the Firefox browser store
- Wallet connected with Alby 

**Screenshots (If Any)**
<img width="267" alt="image" src="https://user-images.githubusercontent.com/318/159516678-30b0fc19-067d-4db7-a7de-c11d2734ac5d.png">

**Device Information [optional]:**
 - OS: Windows
 - Browser Firefox

**Comment by bitcoinuser** [comment]
Still on version 1.9.1

![photo_2022-04-03_10-15-11](https://user-images.githubusercontent.com/1178856/161429964-a95f0465-40e4-4d82-b13c-90eec046260b.jpg)

**Comment by escapedcat** [comment]
Master and freshly installed 1.9.1 seems fine on Firefox (98.0.2):  
<img width="408" alt="image" src="https://user-images.githubusercontent.com/1016218/161431013-549c71b6-f51b-4625-8498-25f8e9e9e17f.png">

Would you mind double check? I had the master dev version installed before, which also looked fine. Not sure if deletign that and installing from the Add-ons is clean/reset enough.

**Comment by bitcoinuser** [comment]
> Master and freshly installed 1.9.1 seems fine on Firefox (98.0.2): <img alt="image" width="408" src="https://user-images.githubusercontent.com/1016218/161431013-549c71b6-f51b-4625-8498-25f8e9e9e17f.png">
> 
> Would you mind double check? I had the master dev version installed before, which also looked fine. Not sure if deletign that and installing from the Add-ons is clean/reset enough.

I'm using Alby 1.9.1 on Brave and Ubuntu.

**Comment by escapedcat** [comment]
> I'm using Alby 1.9.1 on Brave and Ubuntu.

So, then it's fixed. yes?

**Comment by bitcoinuser** [comment]
> > I'm using Alby 1.9.1 on Brave and Ubuntu.
> 
> So, then it's fixed. yes?

No, NOT fixed.

**Comment by escapedcat** [comment]
> I'm using Alby 1.9.1 on Brave and Ubuntu.

Ah, got it. Confused cause this issue was about Firefox. Will have a look into Brave. Thanks!

**Comment by escapedcat** [comment]
@bitcoinuser wanna open up a new issue specifically for Ubuntu (which version) and Brave (which version)?
