### ISSUE TITLE
LNURL-channel support

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#738]
[LNURL-channel](https://github.com/fiatjaf/lnurl-rfc/blob/luds/02.md) describes a way of how wallets and services communicate to request a new channel.

A service like [blocktank](https://blocktank.synonym.to/) uses LNURL. Can we somehow handle those channel requests in Alby and make it easier for those services to open channels to the user's node.

**Comment by bumi** [comment]
This wouldn't be supported by all connectors (which is fine). We can start with LND.

We need a new prompt: https://github.com/getAlby/lightning-browser-extension/blob/39ac28cfe3f2691ee487dfed8da151d6e681e076/src/extension/background-script/actions/lnurl/index.ts#L21-L32
and then add an ln action for channels: https://github.com/getAlby/lightning-browser-extension/tree/39ac28cfe3f2691ee487dfed8da151d6e681e076/src/extension/background-script/actions/ln

**Comment by escapedcat** [comment]
- connectPeer method in connector
- https://api.lightning.community/?javascript#v1-peers
  - `perm: true`
- lnuri response need to be split (`node_key@ip_address:port_number`)
- wait for response and call the `callback`
- who else implemented this already? zeus?
- how can we tests this, which service implemented lnchannels already?
- https://requestbin.net/

**Comment by MoritzKa** [comment]
[these apps](https://github.com/fiatjaf/lnurl-rfc#:~:text=ones%20listed%20below-,02,clich%C3%A9%2C%20SimpleBitcoinWallet%2C%20Zap%20Android%2C%20Zap%20Desktop%2C%20Zeus,-03) implemented it.
