### ISSUE TITLE
Add option to change password to unlock

### ISSUE THREAD

**Issue by pretyflaco** [getAlby/lightning-browser-extension#740]
**Is your feature request related to a problem? Please describe.**
I want to change my Alby password, but there is no option to do so.

**Describe the solution you'd like**
Change password under settings. After login. Prompt for current password, then enter new password.

**Are you working on this? (Yes/No)**
No

**Comment by im-adithya** [comment]
Thanks for the suggestion @pretyflaco! Working on this!

@escapedcat, Just wanted to know your thoughts on this (is it okay to use flex-row or should I use column instead?):
![Screenshot from 2022-03-29 17-41-55](https://user-images.githubusercontent.com/64399555/160608522-31bdec72-75f5-49c4-851a-1cbfe7129175.png)

Wouldn't it be better if we can place a Save button on top and enable it when changes are made? This can also help us with the username part as right now it is a bit confusing (reg, whether the username typed, is saved or not as the only way to confirm is to refresh)

**Comment by bumi** [comment]
honestly, no idea :) 
but probably changing the password does not fit in the current settings which are auto-saved. 
Maybe we do this in a modal with a save button. Changing the password will also use a different, special action.

but @im-adithya be carful: when changing the password all account details have to be decrypted first and then encrypted with the new password. (that's the tricky part here probably)
