### ISSUE TITLE
Improve "selected account" icon

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#746]
*Via telegram*
![image](https://user-images.githubusercontent.com/1016218/159828180-1576a33f-52f1-476b-80bd-08a219c7d461.png)

- Replace "wallet"-icon with connector-logo

**Are you working on this?**
no

Relates to #732 

### ToDo: 

- [ ] gather logos that fit there? - guess they should still be such icons and not logos? who can create those?

**Comment by secondl1ght** [comment]
Here are some options, maybe we can get some votes on each one? Feel free to add more suggestions as well.

![image](https://user-images.githubusercontent.com/85003930/163315133-fb6290d0-1b62-45ce-b3b6-a8bfc674baed.png)
![image](https://user-images.githubusercontent.com/85003930/163315190-908dbd3d-0729-4aba-b367-ae68fc7a74f2.png)
![image](https://user-images.githubusercontent.com/85003930/163315219-8a4cc8b5-b964-4568-a8d6-924a7179523d.png)
![image](https://user-images.githubusercontent.com/85003930/163315279-0c30c7f3-5bc7-433c-8e3c-8463b7e142ba.png)
![image](https://user-images.githubusercontent.com/85003930/163315424-94b9ca02-e9ba-42de-996b-f8d92e083940.png)

Just curious did this come from user feedback? They didn't like the current icon?

**Comment by bumi** [comment]
I though we use an icon for the different connectors. e.g. `lnd` or `eclair` etc. 

even though this is maybe problematic because we don't store the info that it's a raspiblitz/citadel/etc. - there we only store that it connects through "lnd".

**Comment by escapedcat** [comment]
> Just curious did this come from user feedback? 

Came via telegram

> I though we use an icon for the different connectors. e.g. lnd or eclair etc.

This! ;)

**Comment by secondl1ght** [comment]
Should we use the same images that we use for the connectors for this icon then? Because I don't think there will be similar style SVG icons as what we already have here for each connector. Just want to check that you are OK with using the same colored images as the connectors? Otherwise we may need to get a designer to create 'icons' for each connector to use if we want them all to have similar style.

**Comment by escapedcat** [comment]
Sounds like a good idea to reuse the ones we have. At least as a first step. If they look ugly or are not easy be rcognized because they are too small we can adapt.

**Comment by secondl1ght** [comment]
Ok I think they will probably be too small to recognize but I'll post a screenshot so you can see and then decide from there.

**Comment by secondl1ght** [comment]
Here's an example of how one icon looks:

![image](https://user-images.githubusercontent.com/85003930/166125914-1d0e98ba-db88-41c3-beb1-b3b7517ef6c6.png)

**Comment by escapedcat** [comment]
Ugh, not too nice, right? Hm, can we reuese their favicons if all projects have one? I.e.   
https://bluewallet.io/uploads/favicon.png

**Comment by secondl1ght** [comment]
Here's how that one looks:

![image](https://user-images.githubusercontent.com/85003930/166131797-9d82d137-7fc6-49d1-a2fd-641a1ac8e03d.png)

**Comment by escapedcat** [comment]
Looks a bit nicer. What do you think?

**Comment by secondl1ght** [comment]
It does look a bit nicer, not sure that every connector has a favicon though. Like there is no website for LND is there? But if people like this then I could start hunting down all the favicons.

**Comment by secondl1ght** [comment]
I guess I could use the Lightning Labs favicon for LND?

**Comment by bitcoinuser** [comment]
How looks like on NOT dark mode?

**Comment by escapedcat** [comment]
We decided not to continue with this. It's not crucial issue and to finish this in a complete way will take more time off from more important issues.

In the near future new designs will roll in step by step and that might be a good time to tackle this.
