### ISSUE TITLE
Rename message `type` to `action`

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#759]
We had started this before. I think `action` is a better name and matches that we have an `actions` folder in the background script

The `type` or `action` in the content-script message to the background script defines which "action" function should be executed. The core of this is [here](https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/index.js#L86-L89) 

I think `action` is more descriptive than `type`. But we have to be careful to find all places where the message is used or where a message is published.

**Comment by escapedcat** [comment]
```ts
export interface Message {
  args: Record<string, unknown>;
  origin: OriginData;
  application?: string;
  prompt?: boolean;
  type?: string;  // <<< this
}
```
https://github.com/getAlby/lightning-browser-extension/blob/master/src/types.ts#L65
