### ISSUE TITLE
If I have two wallets, one non-custodial the other custodial and something happens on non-custodial one, the other is affected

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#760]
Hi,
Looks like If I have two wallets, one non-custodial the other custodial and something happens on non-custodial one (like the node is synchronizing), the other custodial wallet is affected, but shouldn't. The custodial wallet should work ok.

Obs. After some minutes the custodial wallet started to work again.
Obs1. Maybe to reproduce the problem, you need to start Alby on the non-custodial wallet (with problem) and then switch to the custodial one. So you have to have two wallets.

See what happens on the custodial wallets on Alby:

![photo_2022-03-30_18-39-21](https://user-images.githubusercontent.com/1178856/160935448-bbcd770d-6b13-4c6d-996e-a7d2401ab4da.jpg)

**Comment by bumi** [comment]
I think the problem here is that we disable the account selection while one account is loading/initializing. If initializing fails then the account menu stays disabled. we might need to check how to better catch errors
