### ISSUE TITLE
Account menu shows "Alby - Alby" for Alby accounts

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#774]
**Describe the bug**
This is only a small glitch - but still: In my opinion it should show Alby only once.

**To Reproduce**
1. Visit to '...'

**Expected behavior**

**Screenshots**
<img width="361" alt="image" src="https://user-images.githubusercontent.com/1016218/161737053-46997c89-0a9b-4672-b335-4a1d5714c4ad.png">

**Device Information [optional]:**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, safari, firefox]
 - Browser Version [e.g. 22]

**Additional context**
Add any other additional context about the problem here.

**Are you working on this issue?**
No

**Comment by bumi** [comment]
this is `${ account name } - ${ node alias }` - maybe we just set a different node alias? ideas?

**Comment by reneaaron** [comment]
How about something like `🐝 getalby.com`? That would also help others recognize this is the public Alby node (like on node explorers) and would create a direct link to visit Alby without first having to search for the website.

**Comment by bumi** [comment]
//cc @kiwiidb

**Comment by bumi** [comment]
then no bee - the sting is universal for all connectors. 
(even though kraken uses emojis: https://amboss.space/node/02f1a8c87607f415c8f22c00593002775941dea48869ce23096af27b0cfdcc0b69 - 1ml can not display it: https://1ml.com/node/02f1a8c87607f415c8f22c00593002775941dea48869ce23096af27b0cfdcc0b69)

**Comment by kiwiidb** [comment]
Oh like that, I think that's possible: `Alby - 🐝 getalby.com` I just thought that the first `Alby` needed to be replaced by the emoji. I will update the alias in lndhub.

**Comment by kiwiidb** [comment]
I've added it but the problem is that for people that have imported this as an LNDhub account (myself), it looks like this:
![Schermafbeelding 2022-04-15 om 10 15 27](https://user-images.githubusercontent.com/33457577/163546527-5019246c-a96d-4bc6-baa4-dae01ce258d7.png)

**Comment by bumi** [comment]
what is the problem with this?  how should it look like?

**Comment by reneaaron** [comment]
I guess we could improve this a bit by adding `text-overflow: ellipsis` so the text does not just get cut off. 

Other than that I also think it's fine the way it is right now 👍
