### ISSUE TITLE
Add standard-version for automatic changelog and version bump

### ISSUE THREAD

**Issue by chris-aeviator** [getAlby/lightning-browser-extension#79]
I find https://github.com/conventional-changelog/standard-version to be an amazing tool to create releases. This adds a `yarn release` command which automatically bumps your version (can be displayed inside the plugin), adds a git tag, creates/ appends a changelog.md .

All you need to do is to add `feat: my awesome feature` or `fix: fixes the world` or `breaking: integrated non-backward compatibe feature` as your commit message (only the ones that are supposed to show up inside the changelog) and upon `yarn release` you get the complete changelog

Example:
![grafik](https://user-images.githubusercontent.com/11522213/123157216-8a7cf900-d46a-11eb-9fb8-67d3d6aab7b5.png)

**Comment by bumi** [comment]
I have setup the release-drafter and create proper GH releases. do you think that is enough, or should we additionally have a changelog.md ? 
we probably can use the same content.

**Comment by chris-aeviator** [comment]
release drafter looks to do the same as `standard-version` so it's rather a preference of what you prefer on a workflow level
