### ISSUE TITLE
Make it more recognizable that sites are offering tipping support

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#793]
I just noticed that there is a different Alby icon showing up in the browser whenever a website supports tipping. (metatag, but also on GitHub, Youtube, etc)

Inactive
![image](https://user-images.githubusercontent.com/100827540/163378598-4c832a38-32c9-48c3-83ec-b45ad8f5a53b.png)

Active
![image](https://user-images.githubusercontent.com/100827540/163378659-b7ea5116-5564-485e-adff-f932cfab0fdd.png)

I think it would be great if the active icon would indicate tipping support a bit more obvious. (by having a different color maybe?)

**Are you working on this?**
If you agree I'll prepare some suggestions and make a PR.

**Comment by bitcoinuser** [comment]
Agree

**Comment by bumi** [comment]
maybe @johnsBeharry or @GBKS have some ideas? 
There is also the possibility to add a colored badge to the icon (like those unread messages badges)

**Comment by GBKS** [comment]
I think the problem really is the dark background. On a light background, the difference between the two icons is more obvious. Can we show different icons for dark backgrounds?

For reference, here is the [source](https://www.figma.com/file/YVMGfhSHNkK7IWWkCeGUvp/Alby?node-id=47%3A227) for the different Alby head states.

**Comment by bumi** [comment]
@secondl1ght can you check if we can customize the browser action icon based on the theme?
I think there is something like `theme_icons`

**Comment by bumi** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action

**Comment by reneaaron** [comment]
Here is the difference on light themes:

✅ Active
![image](https://user-images.githubusercontent.com/100827540/163562368-87ffed03-0c21-4363-bb5f-a1ff19829afa.png)

❌ Inactive
![image](https://user-images.githubusercontent.com/100827540/163562394-a9ee3537-748b-4673-9ee8-220d35173d66.png)

To me the the 2 icons are too similar for users to recognize their function, also considering the size they are displayed. I used Alby for multiple weeks when I found out about different icons while browsing the source code 😅

**Comment by blastshielddown** [comment]
Another way to approach this might be to use a standard icon/indicator on the service/site itself to show that Alby (or another WebLN wallet) is supported. Even something as simple as a chip that says "WebLN" with a checkmark or green dot. Would be curious to hear what better UX experts think of this.

Rough example:
<img width="91" alt="chip" src="https://user-images.githubusercontent.com/77257032/163906708-0457df77-ca40-43d9-83bf-6d085a17b696.png">

**Comment by GBKS** [comment]
I think we had some discussion early on whether to make the icon grey when the current website does not support webLN. Problem was that this gave the impression that the extension was disabled altogether. And since 99.99% of websites don't support webLN, the icon would be grey all the time.

An alternative would be to add a small circle to the icon - a status indicator:
- No circle - site does not support webLN
- Grey circle - site does support webLN, but is not connected
- Green circle - connected
- Blue circle - new activity, or activity ongoing

This relieves the small icon from having to represent the character as well as the connection state.

Chrome extension icons can have [badges](https://developer.chrome.com/docs/extensions/reference/browserAction/#badge), but I don't think those would work well since they are text-based.

As for that @blastshielddown noted, I'd distinguish between sites that natively implement webLN, and sites that Alby "enhances with webLN". The former should have a "Connect wallet" button (or "Log in with bitcoin" or something along those lines). For the latter, users are dependent on Alby to inform them when a site is supported. In that case, the extension icon is a good indicator.

**Comment by reneaaron** [comment]
Technically there is no way to know if a site supports WebLN natively before the user initiates a WebLN action and grants permission. This is only possible for sites that Alby provides tipping support (Youtube, GitHub, websites with lightning metatag, etc). 

  -  ~~No circle - site does not support webLN~~ Cannot be known beforehand
  -  ~~Grey circle~~ - site does support webLN, but is not connected ➡️ Only possible for website enhancements
  -  Green circle - connected ➡️ User granted permission for this website
  -  Blue circle - new activity, or activity ongoing 

It would make sense to me to structure them like that:

 - Default icon, no circle (user did not grant WebLN permissions before and site does not offer tipping)
 - Green circle (user granted WebLN permission before or site does offer tipping) 
 - Blue circle - new activity, or activity ongoing
 
The green circle has a duplicate meaning (it's not clear if the user granted permission or the site is offering tipping). If we want to distinguish that too, we need a second dimension to communicate the current state:

 - Main Icon (Default: yellow, green if the user granted permissions before)
 - Indicator (Default: hidden, i.e. green / red notification bubble if site offers tipping)
 
![image](https://user-images.githubusercontent.com/100827540/164203016-c1fafe19-ce4b-4c62-8ebf-b77732f44e80.png)

What do you think?

**Comment by GBKS** [comment]
I think it's fine if the green circle would have two meanings. Could be grey for tipping support, which gets overridden with green when the user has granted permissions.

**Comment by reneaaron** [comment]
Alright. So that would leave us with something like that where we have 2 states: 

 - Alby icon with grey dot (default)
 - Alby icon with green dot (permission granted before or site offers tipping support)

![image](https://user-images.githubusercontent.com/100827540/165275871-9e1cba06-245f-40e4-83b5-25ff0041b87b.png)

@GBKS I've created this draft in a [copy of the Figma file](https://www.figma.com/file/7veeVSRGbgHu3nwpJx3gWi/Alby-(Copy)) as I had no editing rights. Are you okay with the sizing / placement / coloring of the notification icon? Do you want to add them to the original file's header states? 



If everybody is okay with this proposal I'd prepare a MR for the new icons. 🙌

/cc @bumi

**Comment by reneaaron** [comment]
Thanks for your proposal, I really like the states having a bigger visual difference to each other. 

The only thing that bugs me a bit is that the Alby icon will be grey on like 99.99% of all websites and will only be shown in it's "original color" when a site offers tipping (but you never tipped before, then it will turn green). But maybe we should just focus on getting more websites to support ⚡Lightning. 😅

**Comment by escapedcat** [comment]
> The only thing that bugs me a bit is that the Alby icon will be grey on like 99.99% of all websites and will only be shown in it's "original color" when a site offers tipping 

Good point. In that case the grey/green dot would be nice.  
A grey Alby logo looks just kinda disabled. But that's not true because I can still open the extension through that, no?

**Comment by GBKS** [comment]
> A grey Alby logo looks just kinda disabled.

Correct. And that's why the Alby logo this far was not grey by default, to prevent the disabled look. Downside was just that the unavailable and available states then had less contrast.

An alternative would be to keep the default Alby yellow (as it is now) and make it blue to indicate Lightning availability, and green for the connected state. Very simple to understand, just means Alby changes color frequently (which is fine, it's a magic internet bee after all).

<img width="700" alt="Alby browser icons 220428" src="https://user-images.githubusercontent.com/695901/165683163-350e63e2-676c-48fa-96cc-e6c6839b4ca7.png">

**Comment by kiwiidb** [comment]
I would suggest a browser notification in addition to the different icon. We can make it opt-out.

**Comment by reneaaron** [comment]
@GBKS I like the colorful magic internet bees, the states are clear and have distinct icons which makes it easy for users to recognize. 👍

@kiwiidb Sending out browser notifications for tipping support seems a little bit intruding to me, no? 🤔 I think tipping support should be more obvious but I'd argue it should still be some kind of a passive indicator. It feels kind of strange to me to instantly get a notification when I open a website.

**Comment by kiwiidb** [comment]
I agree that it can be perceived as intruding. But I think that we should not be afraid to experiment with this. Maybe people like it, who knows? You could always opt-out of the notifications.

**Comment by GBKS** [comment]
Notifications seem like a different issue from this one. I don't remember off the top of my head, does the onboarding flow show a list of supported sites for tipping? If so, that screen could include a toggle for notifications? That way it's opt-in. Personally, I loathe it when websites and services show notifications by default.

**Comment by kiwiidb** [comment]
Opt-in means almost nobody will use it. I can certainly understand that you loathe it. However, we have already received this feature request from real users, so it seems not everyone thinks about it that way.

**Comment by MoritzKa** [comment]
Users today want more obvious notifications about if this website is Lightning enabled. Hence, we should make it much, much more obvious. 

re icon: I would keep the default icon yellow. That is the Alby brand and we should make it recognizable as good as possible even though there are not yet many Lightning websites out there. A green and a blue icon seem to be more visible than before. That's already a great improvement.

re notifications: That's a different issue, yes, but supports the purpose of this discussion. I agree we should experiment with that (e.g. show it only for the meta tag use case and YouTube, where people might not expect Lightning. There it might not be so annoying and users can opt-out).

**Comment by bumi** [comment]
how do we get this in? we are so far with this? 
The new icons are already a great improvement, aren't they?

we then optionally can still optionally inject HTML to show a bigger notification arrow pointing to Alby or something similar.

**Comment by bitcoinuser** [comment]
This is fixed on version 1.12.0. Please close.

**Comment by bumi** [comment]
interesting feedback for the green icon: https://github.com/getAlby/lightning-browser-extension/issues/1142#issuecomment-1185955128

**Comment by bitcoinuser** [comment]
> interesting feedback for the green icon: [#1142 (comment)](https://github.com/getAlby/lightning-browser-extension/issues/1142#issuecomment-1185955128)

Maybe this can be solved with the idea of the sites that support lightning login, show on the page that the user is logged using a specific wallet and node info, something like what ethereum dapps does.
