### ISSUE TITLE
Replace npm package to parse lightning invoices

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#809]
**Is your feature request related to a problem? Please describe.**
Seems the [invoices package](https://www.npmjs.com/package/invoices) keeps having breaking changes in patch releases: 
https://github.com/getAlby/lightning-browser-extension/pull/808
It also comes with heavy dependencies. 

We should replace the package with a different more lightweight bolt11 parser. 

https://www.npmjs.com/search?q=bolt11
https://www.npmjs.com/package/light-bolt11-decoder
https://www.npmjs.com/package/bolt11

**Comment by escapedcat** [comment]
Only checking at the repo [bolt11](https://github.com/bitcoinjs/bolt11) looks pretty good.  
It's JS but comes with TS-types, looks maintained and contributers are well known ;)
