### ISSUE TITLE
Scan the location field in Twitter for a Lightning Address

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#814]
**Is your feature request related to a problem? Please describe.**
Sometimes profiles have not enough space for a Lightning Address, because of other information. So we could use other fields to allow the publication of a Lightning Address

**Describe the solution you'd like**
Scan and detect the location field in Twitter for a Lightning Address

**Describe alternatives you've considered**
n.a.

**Additional context**
![image](https://user-images.githubusercontent.com/13707997/164723423-1996e19b-d686-4f6c-a48d-401df315d1d5.png)

**Are you working on this? (Yes/No)**
No

**Comment by stefanwuest** [comment]
I can have a go at this.
