### ISSUE TITLE
Get balance of allowance

### ISSUE THREAD

**Issue by blastshielddown** [getAlby/lightning-browser-extension#831]
Similar to #408 but narrower, for allowance balances only.

The idea is to enable a LN service to get the balance of an Alby user's allowance for that particular service. For example, on a site like [Wavlake](https://wavlake.com), the service would be able to display the user's remaining allowance for the site. When the user performed a payable action like tipping or listening to a track, the user's displayed balance for the service would decrement automatically. More broadly speaking, I think this would allow for LN services to behave more like easy-to-use custodial applications (which have a clear view of, and access to, a user's available funds) but in an explicitly permissioned and non-custodial way.

AFAIK, allowances are not defined in the WebLN standard at all, so my bias would be to add this as a feature in Alby as opposed to proposing a change to WebLN. There is also the challenge of defining what a wallet's general balance actually means in Lightning, as raised [here](https://github.com/joule-labs/webln/issues/39). Another advantage I think this approach has to a more general wallet balance-type of approach is better privacy. The service only can see what it needs to see in order to make the user's experience better.

**Comment by reneaaron** [comment]
Fixed for now with #2242
