### ISSUE TITLE
Added email for LNURL on Alby settings, did a payment with email field, but on transaction details do not show it

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#841]
1. I added my email on Alby settings for Lnurl.
1. Did a payment to leonardo18@lntxbot.com (lightning address) and appear the field email pre filled on preview payment window. 
1. Confirmed the payment.

On transaction list detail of the transaction, I think should show the information of the field email. For now do not appear this information.

![Captura de tela de 2022-05-02 17-04-51](https://user-images.githubusercontent.com/1178856/166318534-b953d0d0-60bd-49a9-88a4-bf750a85b432.png)

**Comment by stackingsaunter** [comment]
Same as https://github.com/getAlby/lightning-browser-extension/issues/1401, closing this one
