### ISSUE TITLE
Improve description for additional userdata being sent via LNURL

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#844]
![image](https://user-images.githubusercontent.com/100827540/166434824-8f9e029b-3683-4bad-908b-1d4c2d86010a.png)

I just stumbled upon some new settings and was surprised Alby asks me to fill in personal data like name & email to be sent along with LNURL payments. 👀 

 - Why would you send an name / email along with a payment? 
 - Is this info attached to every payment? 

After learning about [LUD-18](https://github.com/fiatjaf/lnurl-rfc/blob/luds/18.md) I understand the use-case, but I think we should let users know that this information is not shared without the explicit consent for every payment and that they are in control of who they share this data with.

**Comment by bumi** [comment]
+1 do you have an idea what we should call it/describe it? 

some related issues/prs:
#541 #514 #508 #515

**Comment by reneaaron** [comment]
I just played around with the settings page and came up with this proposal: 

![image](https://user-images.githubusercontent.com/100827540/166469035-86aa93e9-487d-483f-b53d-ae2097674655.png)

What do you think?

**Comment by bitcoinuser** [comment]
> I just played around with the settings page and came up with this proposal:
> 
> ![image](https://user-images.githubusercontent.com/100827540/166469035-86aa93e9-487d-483f-b53d-ae2097674655.png)
> 
> What do you think?

I like it. I just think is not necessary to mention LNURL. My suggestion: For sending along with payments when requested, instead of: For sending along with payments when supported. So change word supported for requested and remove LNURL. Thanks

**Comment by bumi** [comment]
looks good. 

maybe we can that this is used for lightning addresses ? 

"...sent along with payments to supported lightning address (LNURL)?"

**Comment by bitcoinuser** [comment]
> looks good.
> 
> maybe we can that this is used for lightning addresses ?
> 
> "...sent along with payments to supported lightning address (LNURL)?"

Not all lightning address (LNURL) request this data. It's an option of the service request some or none data. So for me make more sense even to people not familiar with these terms like lightning address (LNURL) a phrase like: For sending along with payments when requested. 

It's more generic and simple.

**Comment by bumi** [comment]
so +1 for what @reneaaron wrote

**Comment by reneaaron** [comment]
For me it would make sense if we try to hide technical terms (LNURL) from users where possible since the average user probably doesn't know about those protocols anyway. Also I don't think it's very important for the user to know which protocols support this.

I tried to rephrase the use-case ("Payees can request for additional data to be sent with a payment") and moved this description to the subtitle of the section to avoid repeating it on a settings-level. Also I removed "user" from the settings titles as this is somewhat obvious. 

![image](https://user-images.githubusercontent.com/100827540/166482895-a9ef315f-f29d-4497-8f4d-4e468a8d2423.png)

**Comment by bitcoinuser** [comment]
> For me it would make sense if we try to hide technical terms (LNURL) from users where possible since the average user probably doesn't know about those protocols anyway. Also I don't think it's very important for the user to know which protocols support this.
> 
> I tried to rephrase the use-case ("Payees can request for additional data to be sent with a payment") and moved this description to the subtitle of the section to avoid repeating it on a settings-level. Also I removed "user" from the settings titles as this is somewhat obvious.
> 
> ![image](https://user-images.githubusercontent.com/100827540/166482895-a9ef315f-f29d-4497-8f4d-4e468a8d2423.png)

I agree and I liked it.
