### ISSUE TITLE
Add videos to RaspiBlitz and MyNode connectors

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#847]
**Is your feature request related to a problem? Please describe.**
Users have a hard time to find the credentials to connect their remote nodes

**Describe the solution you'd like**
add a video to the connector page
MyNode video: https://fra1.digitaloceanspaces.com/alby-storage/connector-guides/in_extension_guide_mynode.mp4
RaspiBlitz video: https://fra1.digitaloceanspaces.com/alby-storage/connector-guides/in_extension_guide_raspiblitz.mp4

**Describe alternatives you've considered**
-
**Additional context**
check-out the integration of the Umbrel video: https://github.com/getAlby/lightning-browser-extension/pull/827

**Are you working on this? (Yes/No)**
No

**Comment by bumi** [comment]
Use the https://cdn.getalby-assets.com domain for the video. 
https://cdn.getalby-assets.com/connector-guides/in_extension_guide_mynode.mp4
https://cdn.getalby-assets.com/connector-guides/in_extension_guide_raspiblitz.mp4

**Comment by secondl1ght** [comment]
PR #870 in
