### ISSUE TITLE
Alby payment sent window shouldn't appear because Brave already notify about payment sent

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#858]
Hi,

I did a payment on https://chat.blixtwallet.com/ and after click Confirm, Alby show a payment sent window. 
I think when the user click confirm and the transaction is confirmed, Alby window should automatically close, because Brave already show a notification of transaction paid.

![Captura de tela de 2022-05-04 18-38-47](https://user-images.githubusercontent.com/1178856/166830189-49a17419-adcf-4a38-8da1-70b3fd9e81f4.png)

**Comment by bumi** [comment]
thanks :) good timing... this is changed in #773 (which hopefully is part of the release this week) 
Can you test that PR, does that work for you?

**Comment by bitcoinuser** [comment]
Great, will wait for the next release so.

**Comment by bitcoinuser** [comment]
Fixed. Thanks

**Comment by bumi** [comment]
👍 https://chat.blixtwallet.com/  is a pretty good showcase.
