### ISSUE TITLE
Lnd, Lndhub...shouldn't appear on accounts menu

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#859]
I don't think Lnd, lndhub... should appear on Accounts menu. I don't se a reason to show this info to users, and I think more confuse than help.

![photo_2022-05-04_19-04-17](https://user-images.githubusercontent.com/1178856/166833442-8bf535e3-9385-4566-a967-6e9ab0b1a54c.jpg)

**Comment by bumi** [comment]
+1 @johnsBeharry any idea what else we thought of with those badges?

**Comment by escapedcat** [comment]
> maybe we just remove the badge and see how it is?

Let's try. As long as it's still visible in the account-overview we're good I think.

**Comment by secondl1ght** [comment]
I put a PR in for this: #916
