### ISSUE TITLE
Failed payment when I top up sats4likes Balance

### ISSUE THREAD

**Issue by dvoroneca** [getAlby/lightning-browser-extension#872]
**Describe the bug**
Fail to top up sats4likes Balance when using Alby extension. 

**To Reproduce**
1. Visit [Sats 4 Likes](https://kriptode.com/satsforlikes/index.html)
2. Click on **"Balance: 0 Sats"**
3. Enter the amount
4. Press confirm on extension
5. Press request in popup
7. See the error! 

*8. Also, the **Dismiss** text in error is green. Not the best colour to be used in the error pop up.

**Expected behavior**
Funds top-up should be reflected in the [Sats 4 Likes](https://kriptode.com/satsforlikes/index.html) interface

**Information About Alby**
- Alby Version: [e.g. 1.10.0]
- Alby installed through [e.g. installed through the browser stores]
- Wallet connected with Alby [Alby]

**Screenshots (If Any)**
Add screenshots to help explain your problem.

![Group 5](https://user-images.githubusercontent.com/35034985/167454230-e1f82719-589e-4ba1-a0ed-24d5c1728154.png)
![Screenshot 2022-05-09 at 18 17 1](https://user-images.githubusercontent.com/35034985/167454251-1f74b47e-4b58-43b7-814d-e769be1d41e7.png)
![Screenshot 2022-05-09 at 18 19 1](https://user-images.githubusercontent.com/35034985/167454260-567ab282-1845-4f0f-8ff1-6dc41dfed691.png)

**Device Information [optional]:**
 - OS: [e.g. MACOS 12.2.1]
 - Browser [chrome]
 - Browser Version [Version 101.0.4951.54 (Official Build) (x86_64)]

**Are you working on this issue? (No)**

**Comment by dylancom** [comment]
The website says:
<img width="891" alt="Schermafbeelding 2022-05-09 om 18 52 32" src="https://user-images.githubusercontent.com/12894112/167459136-7b27da54-c09a-4ae8-ba1c-7cc5b2339726.png">

**Comment by dylancom** [comment]
I updated the link inside the extension with: #873
