### ISSUE TITLE
refresh during onboarding causes crash

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#874]
**Describe the bug**
When you refresh the browser during the initial onboarding it causes a crash where the screens starts to flicker/re-render in a loop.

**To Reproduce**
1. Load Alby for the first time
2. Refresh the browser

**Expected behavior**
A refresh does not cause the app to crash.

**Information About Alby**
- Alby Version: latest master
- Alby installed through master branch
- Wallet connected with Alby n/a

**Screenshots (If Any)**

**Device Information [optional]:**
 - OS: Linux (PopOS)
 - Browser Brave
 - Browser Version latest

**Additional context**

**Are you working on this issue? (Yes/No)**
No

**Comment by dylancom** [comment]
Great catch!
This bug seems to have been introduced by: https://github.com/getAlby/lightning-browser-extension/commit/7d17db559c2a85b943d4554ff161adb815fba606

**Comment by bumi** [comment]
ohoh! :high5: for the quick fix @dylancom
