### ISSUE TITLE
Alby window should disappear when payment is confirmed

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#879]
Hi,

Similar to this: https://github.com/getAlby/lightning-browser-extension/issues/858

But here: 
![Captura de tela de 2022-05-10 09-22-13](https://user-images.githubusercontent.com/1178856/167628111-4db67a70-f0c4-413f-a639-c48d41049b89.png)

Obs. As you can see when a payment is confirmed, we receive the message:  Thanks, sats received. 
I think this message should appear on Brave popup.

**Comment by bumi** [comment]
Interesting. What do you think the behaviour should be if something else is shown? E.g. a longer message or even a link?

**Comment by escapedcat** [comment]
@bitcoinuser you have some feedback here?

**Comment by bitcoinuser** [comment]
Closing. I agree with Bumi.
