### ISSUE TITLE
Publishers blank state

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#88]
What do we show on the publishers page when a user does not yet has configured any allowances?
Maybe: an explanation what an allowance is and a link to a demo publisher (as after the onboarding screen)

**Comment by MoritzKa** [comment]
so this is not the website screen, but this one: 
![image](https://user-images.githubusercontent.com/13707997/154831855-16dab73f-91cc-4cee-8aae-2b6a8cdfbcca.png)

**Comment by bumi** [comment]
I think the website screen. (your screenshot shows the details page of a publisher/website)

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/318/154846518-af0cce9c-65ac-4325-b195-1f9c0cb53c88.png">

**Comment by MoritzKa** [comment]
If you mean the "Websites" screen then we can link: https://github.com/getAlby/lightning-browser-extension/pull/490
but also single publisher/websites pages still look quite empty (s. screenshot in my previous comment)

**Comment by secondl1ght** [comment]
Is there a design for this screen?

**Comment by bumi** [comment]
I think there are screens somewhere (in Figma?) but the screens in the PR are fine. we just should make sure it's simple code. in the end we just want to show some boxes listed :)

**Comment by secondl1ght** [comment]
Ok maybe I can rewrite it from scratch then? Is there a list of websites we want to show here?

**Comment by MoritzKa** [comment]
https://www.figma.com/file/xEPJFGFdc3HD0JS1ax2IpH/Extension-(MVP)?node-id=2711%3A16621
![image](https://user-images.githubusercontent.com/13707997/158430059-3d69d9e1-d6f8-4aa8-b9f9-d890bed54f3b.png)

**Comment by MoritzKa** [comment]
I would prefer to have these websites directly in Alby
1.) We can test "marketplace" functionalities with users
2.) We are independent from directories

regarding code, maybe @dylancom can give some advise.

**Comment by bitcoinuser** [comment]
I would like to see something like this too: https://feedback.getalby.com/feature-requests-/posts/store-sites-that-alby-users-used-to-make-payments

**Comment by im-adithya** [comment]
Can I work on this?

**Comment by escapedcat** [comment]
> Can I work on this?

I think this is (mostly?) covered by #490 but got stuck. Further above @secondl1ght already mentioned to work on it.

**Comment by secondl1ght** [comment]
If you want to give this a try you can go ahead @im-adithya, it was in my backlog of things to do.
