### ISSUE TITLE
update sat unit to sats in UI

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#917]
Recently in PR #867 it came up that a Twitter poll for Alby users determined they prefer the unit 'sats' instead of 'sat'. We chose to use sat previously in #308. I am creating this issue to track this task, it seems like it is decided that we will update the units to sats. But if anyone has any further feedback please post it here.

**Comment by im-adithya** [comment]
So is `sats` final? Should I send in a PR to update it?

**Comment by bumi** [comment]
👍 thanks!
