### ISSUE TITLE
500 error when logging into Alby Wallet

### ISSUE THREAD

**Issue by thebrandonlucas** [getAlby/lightning-browser-extension#918]
**Describe the bug**
When logging into my Alby wallet, I receive the following alert: 
"Failed to create a new wallet. {"status":500,"error":"Internal Server Error"}"

I'm unable to login to Alby this way

**To Reproduce**
1. Start Alby from current master branch [commit 49ebeca](https://github.com/getAlby/lightning-browser-extension/commit/49ebecabdb5ddc03a865e0be53c7f431b35ecf6d) using `yarn run dev:chrome` and load extension into Chrome.
2. Select "Alby Wallet" on "Connect to lightning" screen.
3. Enter your email address and password for an existing Alby Wallet.

**Expected behavior**
My Alby wallet should login correctly and send me to the "Done" navigation screen

**Information About Alby**
- Alby installed manually from current master branch

**Screenshots (If Any)**
<img width="1240" alt="Screen Shot 2022-05-20 at 10 15 31 PM" src="https://user-images.githubusercontent.com/38222767/169630663-c2d04b13-7f4d-4d94-a31c-36a0173d0595.png">

**Device Information [optional]:**
 - OS: MacOS
 - Browser Chrome

**Additional context**
The error appears to only occur with the commit [commit 49ebeca](https://github.com/getAlby/lightning-browser-extension/commit/49ebecabdb5ddc03a865e0be53c7f431b35ecf6d). I believe [this url change on NewWallet screen](https://github.com/getAlby/lightning-browser-extension/commit/49ebecabdb5ddc03a865e0be53c7f431b35ecf6d#diff-070b2745eed6a27072e7e29f4fd76b750052f35bb9a3764a80b5d0bbf6b78586L11) may have caused the issue. The commit immediately before this does not appear to have the issue, so I think it was introduced here.

**Are you working on this issue? (Yes/No)**
No

**Comment by escapedcat** [comment]
Recently [the default ENV was changed to testnet](https://github.com/getAlby/lightning-browser-extension/pull/627/files#r869811467) for all things development. Currently there's an issue with DNS within DigitalOcean. This is being checked at the moment. Once this is fixed this should work again.
Is this blocking you?
Thanks for the heads up and making this transparent!

**Comment by thebrandonlucas** [comment]
Not blocking me at the moment! Thanks for the info, just wanted to make sure it was on the radar since I didn't find any discussions on it yet :)

**Comment by bumi** [comment]
This should be fixed now. 

please note: in development we now default to the simulation/regtest network. 

If you want to use the production Alby accounts you have to set the environment variable: `WALLET_CREATE_URL="https://getalby.com/api/users"`

**Comment by thebrandonlucas** [comment]
Thanks @bumi! Dumb question, where are env vars getting set? I see `NODE_ENV` being set to development in `package.json` but not where vars like `WALLET_CREATE_URL` get set.

**Comment by escapedcat** [comment]
Weill be fixed via #925

**Comment by kiwiidb** [comment]
> Thanks @bumi! Dumb question, where are env vars getting set? I see `NODE_ENV` being set to development in `package.json` but not where vars like `WALLET_CREATE_URL` get set.

Build and uploading to the stores is done manually for now, and these env variables are also set manually while doing that.

**Comment by bumi** [comment]
if you want to run the latest master branch but use the production/real getalby.com accounts API use the following: 

```
WALLET_CREATE_URL="https://getalby.com/api/users" yarn run dev:firefox
```

this sets the `WALLET_CREATE_URL` env variable for the executed command `yarn ...`

**Comment by bumi** [comment]
when it works for you, can you close this issue?

**Comment by thebrandonlucas** [comment]
Thanks all for your help!
