### ISSUE TITLE
Evaluate Strike API to build a connector between Alby and Strike accounts

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#936]
**Is your feature request related to a problem? Please describe.**
Strike is a mobile Bitcoin Lightning app and provides an API. Can we use that API to allow Strike users connect their Strike account to the Alby wallet?

**Describe the solution you'd like**
Strike users can connect their Strike account to Alby and use their sats on websites through Alby

**Describe alternatives you've considered**
none

**Additional context**
Can we use the Strike API to build a connector?
- Strike API: https://developer.strike.me/; 
- Strike API documentation: https://docs.strike.me/api/
- sample interface for a connection to Alby: https://github.com/getAlby/lightning-browser-extension/wiki/Connector-API
- Example 1: [LND connector](https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/connectors/lnd.ts)
- Example 2: [Galoy connector](https://github.com/getAlby/lightning-browser-extension/blob/70147b68f52670cddc4579b842426f00fc122fc3/src/app/screens/connectors/ConnectGaloy/index.tsx)

**Are you working on this? (Yes/No)**
No

**Comment by john-zaprite** [comment]
The API is currently very limited and only allows you to generate invoices on a user's behalf.
It's not possible to spend from a user's account.

**Comment by MoritzKa** [comment]
I will close that issue for now. Let's reevaluate it again.
