### ISSUE TITLE
Cannot create invoices with Alby for my RaspiBlitz

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#941]
**Describe the bug**
I cannot generate invoices repeatedly with Alby for my RaspiBlitz (tor activated). Error message: (Cannot read properties of undefined (reading "error")

**To Reproduce**
If I restart my browser and I generate an invoice over Alby from my RaspiBlitz it works. Then I pay it by switching accounts in Alby. If I try it again: Switch back to my RaspiBlitz in Alby, I cannot generate another invoice. Error message: (Cannot read properties of undefined (reading "error")

**Expected behavior**
If I click on "Receive" in Alby I generate an invoice that is shown as a QR code and I can copy it.

**Information About Alby**
- Alby Version: 1.10
- Alby installed through the browser stores
- Wallet connected with Alby: RaspiBlitz on LND

**Are you working on this issue? (Yes/No)**
No

**Comment by bumi** [comment]
can you post the logs? (from the background script)

**Comment by bumi** [comment]
is this still open?

**Comment by MoritzKa** [comment]
I can't reproduce the error anymore. It is working now. Let's hope my RaspiBlitz just had a bad day. 
I will close this issue now.
