### ISSUE TITLE
LNURL withdraw link uses msat amount as default instead of dividing by 1000

### ISSUE THREAD

**Issue by Semisol** [getAlby/lightning-browser-extension#954]
**Describe the bug**
LNURL withdraw link uses msat amount as default instead of dividing by 1000.

**To Reproduce**
Try using an LNURLw link

**Expected behavior**
Default is sats

**Information About Alby**
- Alby Version: 1.10.0
- Alby installed through browser store
- Wallet connected with LNbits

**Screenshots (If Any)**
Add screenshots to help explain your problem.

**Device Information [optional]:**
*left blank*

**Additional context**
This was an attempted withdrawal on stacker.news

**Are you working on this issue? (Yes/No)**
No

**Comment by dylancom** [comment]
Could you provide a screenshot? I can't reproduce the problem.
