### ISSUE TITLE
Replace "Delete" account with "Unlink"  account

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#955]
**Is your feature request related to a problem? Please describe.**
User can remove accounts in Alby when they click on "Delete". However, they might think that they really delete an account and not just unlink it what they actually do. 

**Describe the solution you'd like**
Replace "Delete" account with "Unlink"  account

**Describe alternatives you've considered**
"Remove" Account

**Additional context**
![image](https://user-images.githubusercontent.com/13707997/170655725-83257eec-ee96-4e47-8fcf-ad8758378d56.png)

**Are you working on this? (Yes/No)**
No

**Comment by MoritzKa** [comment]
@dvoroneca what do you think about that?

**Comment by bumi** [comment]
I actually like "remove" more. we use "add account" -> thus "remove" sounds matching to me. 
We don't use "link" an account. 

In the alert we can warn the user: 

"This will remove the account. This can not be undone. If you used this account to login to websites and you might loose access to those."

**Comment by im-adithya** [comment]
Will work on this after #993 is merged!

**Comment by bitcoinuser** [comment]
> "This will remove the account. This can not be undone. If you used this account to login to websites and you might loose access to those."

I think Alby could list the websites that the user logged in the past using the account that is being removed. 

So maybe a message like: 

This will remove the account. This can not be undone. You used this account to log in to the following sites.... If you remove this account, you might loose access to those.

**Comment by theewiz** [comment]
Hi everyone, I have just conducted the replacement of the "Delete" with a "Remove"; You can see the replacement in the [working file](https://www.figma.com/file/HXIxAFG9OUCcr2EJMJ6JMm/Budgetting?node-id=141%3A1853) under '@wiz! workspace'

**Comment by bitcoinuser** [comment]
I like the idea that I see on some wallets that when removing something critical, the wallet ask the user to type a sentence to be sure that the user know what is doing, like:

I confirm this action

**Comment by bitcoinuser** [comment]
> Hi everyone, I have just conducted the replacement of the "Delete" with a "Remove"; You can see the replacement in the [working file](https://www.figma.com/file/HXIxAFG9OUCcr2EJMJ6JMm/Budgetting?node-id=141%3A1853) under '@wiz! workspace'. I added the copy for the alert @bumi shared
> 
> Please share your thoughts.

I think the dialog should mention that wallet that is being removed.

**Comment by theewiz** [comment]
@bitcoinuser it actually does, go through the link. I designed that in
![wallet](https://user-images.githubusercontent.com/81051645/173236238-1474db09-71f4-4abe-938e-e2c69e638468.png)

**Comment by theewiz** [comment]
What do you think about this @bitcoinuser 👇

![wall](https://user-images.githubusercontent.com/81051645/173236811-13bd6dbc-b27c-4270-9ad7-6e3d99848e6f.png)

**Comment by escapedcat** [comment]
> I think that the request to enter "I confirm this action", although sometimes used, would be overkill in this case.

Agreed. I also think removing an account is nothing severe because it can re-added all the time again, right @bumi ?

> How about, like @bitcoinuser suggested, we list services that this account was associated with in the popup and ask him to confirm the remove.

👍 Good improvement. Would be good to handle that in a separate follow up issue. This issue doesn't need to be blocked by that.

**Comment by escapedcat** [comment]
Alby decision is:
- go with a simple native alert for now
- Text: "This will remove the account. This can not be undone. If you used this account to login to websites and you might loose access to those."

**Comment by bumi** [comment]
the problem currently is that we do not know for what and on which pages the account has been used. 

we'll optimize this in the future once we have all that data available. until then, I like the proposals, @dvoroneca and @theewiz do we keep those in figma?
