### ISSUE TITLE
Strings doesn't change to new language which are translated using I18n.t()

### ISSUE THREAD

**Issue by pavanjoshi914** [getAlby/lightning-browser-extension#964]
**Describe the bug**

Currently, strings that are translated using the I18n.t() method don't get translated to a new language set using a language switcher.

Reason::
https://github.com/getAlby/lightning-browser-extension/pull/883/files/503db64662e9aae93eb40515e6c87ebf576f8e27#
This will create a different instance of i18n as compared to the instance used by the locale switcher from react-i18next.
now if you change the language using the language switcher translated version of strings will not get reflected which are solved using i18n.t().

**To Reproduce**
Steps to reproduce the behaviour:
1.  use an alternate language translation for the string which is translated using I18n.t'
2. change language using the language switcher
3. See no change in the translation of string

**Expected behaviour**
The string must get translated after the language is changed via the language switcher

**Comment by escapedcat** [comment]
Thanks! Pinged thebrandonlucas. Maybe he finds time to have a look otherwise we'll have a look.

**Comment by thebrandonlucas** [comment]
Thanks for pointing this out @pavanjoshi914! Looking into this

**Comment by thebrandonlucas** [comment]
This should be fixed now! #969 @pavanjoshi914 @escapedcat let me know if it works for you :)

**Comment by escapedcat** [comment]
Closing this :)  
Thanks @thebrandonlucas !
