### ISSUE TITLE
Enhancement: Include id and balance for each account in Accounts page

### ISSUE THREAD

**Issue by thebrandonlucas** [getAlby/lightning-browser-extension#970]
### Is your feature request related to a problem? Please describe
On the Account page, it may be helpful to show the unique id & balance of an account rather than just the default, since names are sometimes defaulted and can be duplicated, such as below. This makes it difficult to know which account you are editing or deleting.

<img width="1281" alt="Screen Shot 2022-05-30 at 12 25 03 AM" src="https://user-images.githubusercontent.com/38222767/170916939-b50ec566-e201-4594-98bd-d28991bba65b.png">

### Describe the solution you'd like
Display showing the (editable) `name`, `node_id`, and `amount`, such as is given for the currently selected node in the account menu:
<img width="230" alt="Screen Shot 2022-05-30 at 12 18 24 AM" src="https://user-images.githubusercontent.com/38222767/170916298-3f3cbaff-1c27-47c7-bad9-01ff4bf9c7a5.png">

This is closely related to #966.

### Are you working on this?

Not currently, but happy to give this a shot if we decide to pursue it!

**Comment by theewiz** [comment]
@thebrandonlucas what do you think about this? 👇


![wr](https://user-images.githubusercontent.com/81051645/173245352-09ca7e32-7b04-4612-b8cc-355d82c68e3a.png)

**Comment by thebrandonlucas** [comment]
@theewiz It looks good to me! In this design we'd be able to tell the difference between four accounts even if they were all Alby/lndhub accounts.

**Comment by escapedcat** [comment]
@bumi you think it would be helpful to display the node id?

**Comment by thebrandonlucas** [comment]
@bumi @escapedcat Personally, I don't think the balances of each are absolutely crucial on this page as long as we have some way to distinguish the different accounts (i.e. for editing/deletion purposes)

**Comment by qqqzhch** [comment]
It is more practical to display a node ID in the account list and switching account

**Comment by escapedcat** [comment]
> It is more practical to display a Account alias in the account list and switching account I found that the two imported account aliases are different ${authAccount?.alias}

Not exactly sure what you mean, can you link to code or explain in detail?

**Comment by qqqzhch** [comment]
![sss](https://qqqzhch.github.io/Albyimage/WX20221203-110312.png)
When switching accounts, I think it's OK to remind that this account is different from other accounts
in components/AccountMenu/index.tsx
authAccount  data
{
	"alias": "alby-testnet-lnd2",
	"balance": 3316718,
	"id": "3a6a8a14-129f-4151-aa3d-e3476e97c496",
	"name": "LND"
}
accounts  data
[{
	"config": "U2Fs*******AET/o",
	"connector": "lnd",
	"id": "3a6a8a14-129f-4151-aa3d-e3476e97c496",
	"name": "LND"
}]
I think we can add alias attribute to the accounts data,different accounts may have different aliases

#### Here's what I'm curious about

Those who are used to using the btc eth wallet will generally look at their wallet address
And these are account information, but there is no lightning network address(public key of the destination node),
If there is a public key, the public key can also be used to distinguish different accounts



public key can be used in webln.keysend

await webln.enable();
const result = await webln.keysend({
    destination: "03006fcf3312dae8d068ea297f58e2bd00ec1ffe214b793eda46966b6294a53ce6", 
    amount: "1", 
    customRecords: {
        "34349334": "HELLO AMBOSS"
    }
});

**Comment by qqqzhch** [comment]
![sss](https://qqqzhch.github.io/Albyimage/WX20221203-131445.png)

In metamask, each account is given an added ID. I think it is easy to partition different accounts in this way. 
In alby the current account names are the same, which is easy to mistake for a bug

**Comment by bumi** [comment]
Adding the alias or balance or similar is problematic right now because that requires a call to the node. This is only possible with the current active account (because credentials are encrypted and some connections require some time to initialize (e.g. Tor))

Adding a number is a very good idea and I think this should be possible. We probably could count the existing accounts in here and add the number to the name? 
https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/actions/accounts/add.ts

**Comment by qqqzhch** [comment]
I'll try to modify this

**Comment by qqqzhch** [comment]
@bumi @escapedcat  
This adds the number, do you need to implement it to see the effect?

**Comment by escapedcat** [comment]
> This adds the number

What's "this"?

**Comment by qqqzhch** [comment]
Adding a number is a very good idea and I think this should be possible. We probably could count the existing accounts in here and add the number to the name?
https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/actions/accounts/add.ts

@escapedcat 
The advantage of this method is that it works for newly registered accounts
But it doesn't work for 2 cases
1 old account
2 Register a new account, the account number is 1, then delete the account, and register a new account, the account number is still 1
![WX20230114-113257](https://user-images.githubusercontent.com/3917994/212448883-997f5f20-4815-4ddd-9cf2-1e9cbf9cb5f2.png)
Other methods can also be used, such as processing account information to generate a corresponding small picture. Different pictures corresponding to user accounts can also easily distinguish account information with exactly the same name, and this is work for all accounts.
![WX20230114-113556](https://user-images.githubusercontent.com/3917994/212448986-3c0a4ddf-7296-4eeb-bba9-8785f53172e3.png)

**Comment by bumi** [comment]
cc @reneaaron what do you think about identicons?

**Comment by rolznz** [comment]
Can't we cache the alias and color inside the account and update it the next time they load that account (in the rare? case it does change later)?
 
This probably wouldn't work for the balance since it can be easily changed outside of the extension, but I think the more static data is OK?

**Comment by bumi** [comment]
The alias does not work for all the connectors (basically only LND+CLN).
look how the data is loaded. (frontend => background script => connector => node) We don't have any caching there. 
Try it out, but I dont' think all the complexity (as I see it) is worth it.

if we really want a different name there, then maybe we set the name in the connect screen when adding the account:
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/connectors/ConnectLnd/index.tsx#L63

The validation (which we can not always call (because Tor)) we have the info and the alias.

This is the default name filed: https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/connectors/ConnectLnd/index.tsx#L49 - to be changed here.

**Comment by reneaaron** [comment]
I personally like the identicon idea as they might give you some additional thing that can easily be scanned in a longer list. (without having to read all the different account names)

**Comment by rolznz** [comment]
@bumi thanks for a pointer where to look. I guess there is a workaround by manually editing the account name but I still feel like this would be a nice improvement for the text-part (I am not sure identicons solve the whole issue)

**Comment by bumi** [comment]
if we want the alias in there we can add the alias when adding the account. (- I did not mean to do this manually)

**Comment by qqqzhch** [comment]
```
{
"alias": "alby-testnet-lnd2",
"balance": 3316718,
"id": "3a6a8a14-129f-4151-aa3d-e3476e97c496",
"name": "LND"
}
```
Is the id in this json now unique or not?  @reneaaron

**Comment by escapedcat** [comment]
@qqqzhch not sure if we still need this. Avatars have just been merged with #1992

**Comment by qqqzhch** [comment]
Maybe it's not needed anymore, I think I need to look at more issues and pr instead of just focusing on a few issues
@escapedcat

**Comment by rolznz** [comment]
@escapedcat I think now they can be visually identified by different icons, but my connections will all still say "LND". I think it would be still good to add the alias when adding the account. Sorry, I haven't got around to making a PR for this yet.

**Comment by qqqzhch** [comment]
![WX20230131-104958](https://user-images.githubusercontent.com/3917994/215650362-dcc09f56-44a4-4889-ab10-cd0104ad4e86.png)
Different accounts of the same type, the difference is not very obvious
[Polkadot-js](https://polkadot.js.org/extension/) has similar implementations, but they are all based on different addresses and display different icons
[https://polkadot.js.org/docs/ui-identicon/react](https://polkadot.js.org/docs/ui-identicon/react)
![WX20230131-105325](https://user-images.githubusercontent.com/3917994/215650867-a1737590-7013-41bb-bc2f-fd160acdffeb.png)

**Comment by reneaaron** [comment]
With the alias added to the name of the account also the avatars will be different. 

For now you can just manually rename them. 

Thanks for tackling this @rolznz!

**Comment by rolznz** [comment]
Update: I believe it would be good to keep the alias constant ("LND" or "CLN" etc), but set the account name directly from the node name.

From https://github.com/getAlby/lightning-browser-extension/pull/2032 (closed due to not being the correct solution for this problem)
