### ISSUE TITLE
Design Onboarding flow

### ISSUE THREAD

**Issue by dvoroneca** [getAlby/lightning-browser-extension#981]
## Design Issue: Onboarding flow

Redesign the onboarding flow for the extension. We received feedback that the UI design can be more on brand, and that users should have more guidance on getting their firsts SATS to their wallets.

--------

## [Working file](https://www.figma.com/file/vYlItb04IbZHq92AoGBm19/Onboarding?node-id=0%3A1)

**Comment by dvoroneca** [comment]
We've analysed the onboarding flow with @AnastasiaVolk and created this flowchart that showed the current flow. 

Based on this flow, now we've identified issues with the password for the wallet and passcode for the extension, as well as the issue that at the end of this flow user is asked to test the flow without the balance on the wallet. 

We've now reworked the flow and introduced the wireframes that would give the user to the point where he can acquire Bitcoin to his wallet.

The next steps are to design the flow with existing components and test it. 

You can find the wireframes [here](https://www.figma.com/file/xwGXHxW4FWpV03Tt37atZv/Extension-1.10.0?node-id=466%3A3712)

**Comment by dvoroneca** [comment]
## Onboarding UX Review

1. In the chrome extension first point of contact can be improved...
- image can be improved. should include a name, our logo and words: Bitcoin Lightning and Payments
- Text should end at the first full stop. Without doubling on the Bitcoin Lightning text
![Screenshot 2022-10-20 at 17 34 23](https://user-images.githubusercontent.com/35034985/196993420-eba5ab0c-c23b-4298-8700-9b4074734ea1.png)

2. Chrome extension cover images

- Alby shouldn't have distorted outlines and should include our logo and words: Bitcoin Lightning and Payments for the web.
- Second, if not the first image should communicate that you can log in with a list of other bitcoin wallets.
- Fast payments
- Logins
- Allowances
- Payment tracking also can be improved visually

![image](https://user-images.githubusercontent.com/35034985/196994405-7b483b92-f4f8-4081-b465-53178b41b31f.png)

-------------------

3. Registration first screen.
When the user is at the point where he hits "install" in the chrome store, he either already knows the benefits or he is looking forward to seeing ht interface. So this is a redundant page that gives no value to the user at this step.

![Screenshot 2022-10-20 at 17 10 59](https://user-images.githubusercontent.com/35034985/196993095-791c6367-a110-47f6-bab4-530596b92923.png)

4. Your Alby Lightning wallet page

User feedback:
- For the returning user, it is unclear whether this is a login page as well as a registration page. The assumption is that users will create a new account when going forward.
- For new lightning users the Lightning address that looks like an email is confusing.

![image](https://user-images.githubusercontent.com/35034985/196996820-50a56df6-86ff-42ea-9a81-950242758140.png)

5. Asking users to send sats to try out the extension is a bad UX. The flow for the user is ending in him failing to try the extension!
![Screenshot 2022-10-20 at 17 11 55](https://user-images.githubusercontent.com/35034985/196997475-6ff354d6-6045-4380-a886-5c9bce121022.png)

![Screenshot 2022-10-20 at 17 53 42](https://user-images.githubusercontent.com/35034985/196998054-1afca104-ed3f-4f92-a0f2-a627ca5d5286.png)

![Screenshot 2022-10-20 at 17 54 50](https://user-images.githubusercontent.com/35034985/196998324-2548c6b3-b054-41e4-b62a-fc42cf841af6.png)

**Comment by dvoroneca** [comment]
### Designs for the new onboarding flow:

As our users are facing difficulties in understanding and following the registration flow I propose the following updates

1. Divide the registration into two actions with 2 success screens. 1. Setup password for the chrome extension 2. Add alby or not alby wallets.

2. Take users to Chrome extension web view with a welcome banner.


All the designs with all the cases (forgetting login details, connecting other wallets and more you can find in the [Figma](https://www.figma.com/file/vYlItb04IbZHq92AoGBm19/Onboarding?node-id=407%3A2272) file.
_____________

![Welcome](https://user-images.githubusercontent.com/35034985/197017177-ce8cc505-76f3-453c-8afe-1d6fab217b06.png)
![Welcome-3](https://user-images.githubusercontent.com/35034985/197017407-12d3097c-86cd-4cb5-9c7d-8a1d39984cb7.png)
![Create new Alby Account](https://user-images.githubusercontent.com/35034985/197017424-4187af2a-4c72-4857-9473-d7897afe6ed7.png)
![Create new Alby wallet](https://user-images.githubusercontent.com/35034985/197017436-593c5e36-4a7d-463e-8b4d-8e758f520e07.png)

![Welcome for all users](https://user-images.githubusercontent.com/35034985/197018446-05c38fa9-701d-4ed2-93ec-1ded8a807117.png)

**Comment by dvoroneca** [comment]
I have made UI designs that I think **looks cool** and can be further developed into our brand identity.

![Welcome](https://user-images.githubusercontent.com/35034985/197019325-25a49f22-5f5e-443d-8379-f34709281ca8.png)
![Welcome-1](https://user-images.githubusercontent.com/35034985/197019346-dc62b0ea-1560-484c-959b-d859f0668aef.png)

![Welcome-2](https://user-images.githubusercontent.com/35034985/197019392-b3ad09fb-fdfe-41db-82f6-b6718e6238a7.png)
![Welcome-3](https://user-images.githubusercontent.com/35034985/197019424-3e1465ea-da9b-4bd6-949d-b74324643ea5.png)
![Welcome](https://user-images.githubusercontent.com/35034985/197019563-890d0e08-0aa3-4d98-8484-e220bbda4324.png)

**Comment by MoritzKa** [comment]
Some feedback to the latest comment:
- the graphics in the screens are cool but somehow different. Using variations of the bee as suggested in the comment before is more consistent to what we currently have
- why do we explain the user why the password is needed (screen 2) after he creates the password (screen 1)? 
- how does this flow address the problem that users often set long passwords that make the usage of the extension cumbersome? 
- We talk about passcode and password.
- the last screen shows the lightning address, but there is no way to create a lightning address before.

**Comment by jakubszwedo** [comment]
Here's a link to alby onboarding experience map based on crypto/bitcoin user novice: [Figma](https://www.figma.com/file/z3uJ9ukGm6RIuTVKvKMYNw/Alby-onboarding-evaluation?node-id=0%3A1&t=YRhP9oXbaYFhDzWR-0)

A lot of the same problems as identified before

**Comment by stackingsaunter** [comment]
Closing as it's outdated and onboarding gets ongoing improvements
